/* -*- Mode: C -*- */
/* Author: Henrik Theiling
 * Description:
 *       The Erwin library for standard data structures and algorithms.
 *       This include file includes all instantiated data structure
 *       definitions.
 *
 * @@Begin: Licencing and Copying@@
 * 
 * Copyright (c) Henrik Theiling
 * Licence Version 2, Special Version for Erwin.
 * 
 * The term 'this software' used in the following, additional to its
 * usual usage, also includes the instantiated source files generated by
 * tools of this package.
 * 
 * This software is provided 'as-is', without warranty of any kind,
 * express or implied.  In no event will the authors or copyright holders
 * be held liable for any damages arising from the use of this software.
 * 
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 * 
 * 1. The origin of this software must not be misrepresented; you must
 * not claim that you wrote the original software. If you use this
 * software in a product, an acknowledgment in the product documentation
 * would be appreciated.
 * 
 * 2. Altered source versions must be plainly marked as such, and must
 * not be misrepresented as being the original software.
 * 
 * 3. You must not use any of the names of the authors or copyright
 * holders of the original software for advertising or publicity
 * pertaining to distribution without specific, written prior permission.
 * 
 * 4. If you change this software and redistribute parts or all of it in
 * any form, you must make the source code of the altered version of this
 * software available.  As an exception, files that were generated by
 * tools of this package may be used freely, including modification.
 * 
 * 5. This notice must not be removed or altered from any source
 * distribution.
 * 
 * This licence is governed by the Laws of Germany.  Disputes shall be
 * settled by Saarbruecken City Court.
 * 
 * @@End: Licencing and Copying@@
 *
 */

#ifdef ERWIN_DEBUG_INCLUDE
#warning "Including erwin.h."
#endif

#ifndef ERR_ERWIN_ERWINALL_H
#define ERR_ERWIN_ERWINALL_H

#ifdef ERWIN_DEBUG_INCLUDE
#warning "First inclusion of erwin.h."
#endif

#ifdef ERR_ERWIN_COMPILING
#  include "error/erwin/base.h"
#  include "error/erwin/forwards.h"
#else
#  include <error/erwin/base.h>
#  include <error/erwin/forwards.h>
#  include <error/erwin/defaults.h>
#endif

/* @@Begin: #include@@ */
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_int_callback.h"
#else
#include <error/err_map_int_callback.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_int_v_callback.h"
#else
#include <error/err_map_int_v_callback.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_symbol_int.h"
#else
#include <error/err_map_symbol_int.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_v_callback.h"
#else
#include <error/err_v_callback.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_symbol_stream.h"
#else
#include <error/err_map_symbol_stream.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_v_stream.h"
#else
#include <error/err_v_stream.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_symbol_string.h"
#else
#include <error/err_map_symbol_string.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_v_char.h"
#else
#include <error/err_v_char.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_int_map_int_v_callback.h"
#else
#include <error/err_map_int_map_int_v_callback.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_int_char_p.h"
#else
#include <error/err_map_int_char_p.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_v_buffer.h"
#else
#include <error/err_v_buffer.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_v_int.h"
#else
#include <error/err_v_int.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_v_char_const_p.h"
#else
#include <error/err_v_char_const_p.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_int_v_stream.h"
#else
#include <error/err_map_int_v_stream.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_int_symbol.h"
#else
#include <error/err_map_int_symbol.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_file_stream.h"
#else
#include <error/err_map_file_stream.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_char_p_char_p.h"
#else
#include <error/err_map_char_p_char_p.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_symtab.h"
#else
#include <error/err_symtab.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_v_message.h"
#else
#include <error/err_v_message.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_int_bool.h"
#else
#include <error/err_map_int_bool.h>
#endif
#ifdef ERR_ERWIN_COMPILING
#include "error/err_map_int_int.h"
#else
#include <error/err_map_int_int.h>
#endif
#ifdef __cplusplus
struct ErrErwin: public ErrErwinBase {
    typedef unsigned                 uint;
    typedef unsigned short           ushort;
    typedef unsigned long            ulong;
    typedef unsigned char            uchar;
    typedef signed char              schar;
    typedef err_hashval_t       hashval_t; /*kind=normal*/
    typedef err_v_int_feature_t v_int_feature_t; /*kind=normal*/
    typedef err_map_symbol_string_pair_t map_symbol_string_pair_t; /*kind=aggregate*/
    typedef err_map_symbol_string_index_t map_symbol_string_index_t; /*kind=normal*/
    typedef err_map_file_stream_pair_ptr_cmp_t map_file_stream_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_map_int_int_void_pair_cmp_t map_int_int_void_pair_cmp_t; /*kind=normal*/
    typedef err_v_message_cpp_feature_t v_message_cpp_feature_t; /*kind=normal*/
    typedef err_v_char_const_p_cpp_feature_t v_char_const_p_cpp_feature_t; /*kind=normal*/
    typedef err_map_int_int_value_t map_int_int_value_t; /*kind=normal*/
    typedef err_map_int_map_int_v_callback_void_pair_cmp_t map_int_map_int_v_callback_void_pair_cmp_t; /*kind=normal*/
    typedef err_map_int_int_index_t map_int_int_index_t; /*kind=normal*/
    typedef err_map_int_bool_pair_cmp_t map_int_bool_pair_cmp_t; /*kind=normal*/
    typedef err_map_symbol_string_feature_t map_symbol_string_feature_t; /*kind=normal*/
    typedef err_v_int_element_ref_t v_int_element_ref_t; /*kind=normal*/
    typedef err_v_int_cmp_t v_int_cmp_t; /*kind=normal*/
    typedef err_map_char_p_char_p_feature_t map_char_p_char_p_feature_t; /*kind=normal*/
    typedef err_map_int_map_int_v_callback_pair_cmp_t map_int_map_int_v_callback_pair_cmp_t; /*kind=normal*/
    typedef err_map_int_v_callback_void_pair_cmp_t map_int_v_callback_void_pair_cmp_t; /*kind=normal*/
    typedef err_map_char_p_char_p_pair_cmp_t map_char_p_char_p_pair_cmp_t; /*kind=normal*/
    typedef err_map_int_v_stream_void_pair_cmp_t map_int_v_stream_void_pair_cmp_t; /*kind=normal*/
    typedef err_v_char_quotation_method_t v_char_quotation_method_t; /*kind=aggregate*/
    typedef err_v_message_cnt_t v_message_cnt_t; /*kind=normal*/
    typedef err_map_symbol_string_void_pair_cmp_t map_symbol_string_void_pair_cmp_t; /*kind=normal*/
    typedef err_map_int_map_int_v_callback_value_t map_int_map_int_v_callback_value_t; /*kind=normal*/
    typedef err_map_symbol_stream_key_result_t map_symbol_stream_key_result_t; /*kind=normal*/
    typedef err_map_int_symbol_index_t map_int_symbol_index_t; /*kind=normal*/
    typedef err_map_int_int_pair_t map_int_int_pair_t; /*kind=aggregate*/
    typedef err_v_message_map_t v_message_map_t; /*kind=normal*/
    typedef err_v_char_cmp_t v_char_cmp_t; /*kind=normal*/
    typedef err_map_int_v_callback_pair_t map_int_v_callback_pair_t; /*kind=aggregate*/
    typedef err_map_int_callback_index_t map_int_callback_index_t; /*kind=normal*/
    typedef err_map_int_map_int_v_callback_index_t map_int_map_int_v_callback_index_t; /*kind=normal*/
    typedef err_map_int_symbol_feature_t map_int_symbol_feature_t; /*kind=normal*/
    typedef err_symtab_pair_t symtab_pair_t; /*kind=aggregate*/
    typedef err_map_int_int_key_result_t map_int_int_key_result_t; /*kind=normal*/
    typedef err_map_symbol_int_key_result_t map_symbol_int_key_result_t; /*kind=normal*/
    typedef err_map_int_char_p_value_t map_int_char_p_value_t; /*kind=normal*/
    typedef err_map_int_char_p_void_pair_cmp_t map_int_char_p_void_pair_cmp_t; /*kind=normal*/
    typedef err_v_stream_map_t v_stream_map_t; /*kind=normal*/
    typedef err_symtab_feature_t symtab_feature_t; /*kind=normal*/
    typedef err_map_int_bool_pair_ptr_cmp_t map_int_bool_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_map_int_v_stream_feature_t map_int_v_stream_feature_t; /*kind=normal*/
    typedef err_v_message_cmp_t v_message_cmp_t; /*kind=normal*/
    typedef err_map_int_int_element_ptr_t map_int_int_element_ptr_t; /*kind=normal*/
    typedef err_map_int_v_stream_index_t map_int_v_stream_index_t; /*kind=normal*/
    typedef err_map_int_map_int_v_callback_feature_t map_int_map_int_v_callback_feature_t; /*kind=normal*/
    typedef err_map_char_p_char_p_pair_ptr_cmp_t map_char_p_char_p_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_map_int_char_p_pair_ptr_t map_int_char_p_pair_ptr_t; /*kind=aggregate*/
    typedef err_v_char_const_p_feature_t v_char_const_p_feature_t; /*kind=normal*/
    typedef err_map_symbol_int_pair_cmp_t map_symbol_int_pair_cmp_t; /*kind=normal*/
    typedef err_v_callback_size_t v_callback_size_t; /*kind=normal*/
    typedef err_map_file_stream_value_t map_file_stream_value_t; /*kind=normal*/
    typedef err_map_int_char_p_index_t map_int_char_p_index_t; /*kind=normal*/
    typedef err_map_char_p_char_p_index_t map_char_p_char_p_index_t; /*kind=normal*/
    typedef err_symtab_index_t symtab_index_t; /*kind=normal*/
    typedef err_v_message_index_t v_message_index_t; /*kind=normal*/
    typedef err_map_int_v_callback_key_result_t map_int_v_callback_key_result_t; /*kind=normal*/
    typedef err_map_int_bool_pair_t map_int_bool_pair_t; /*kind=aggregate*/
    typedef err_v_callback_map_t v_callback_map_t; /*kind=normal*/
    typedef err_map_symbol_string_pair_ptr_t map_symbol_string_pair_ptr_t; /*kind=aggregate*/
    typedef err_map_symbol_int_pair_t map_symbol_int_pair_t; /*kind=aggregate*/
    typedef err_map_int_map_int_v_callback_element_ptr_t map_int_map_int_v_callback_element_ptr_t; /*kind=normal*/
    typedef err_map_symbol_stream_pair_ptr_t map_symbol_stream_pair_ptr_t; /*kind=aggregate*/
    typedef err_map_int_bool_key_result_t map_int_bool_key_result_t; /*kind=normal*/
    typedef err_v_char_const_p_combine_t v_char_const_p_combine_t; /*kind=normal*/
    typedef err_v_char_cpp_feature_t v_char_cpp_feature_t; /*kind=normal*/
    typedef err_map_int_int_pair_ptr_t map_int_int_pair_ptr_t; /*kind=aggregate*/
    typedef err_map_int_callback_element_ptr_t map_int_callback_element_ptr_t; /*kind=normal*/
    typedef err_map_symbol_stream_void_pair_cmp_t map_symbol_stream_void_pair_cmp_t; /*kind=normal*/
    typedef err_v_callback_cpp_feature_t v_callback_cpp_feature_t; /*kind=normal*/
    typedef err_map_symbol_stream_feature_t map_symbol_stream_feature_t; /*kind=normal*/
    typedef err_v_message_combine_t v_message_combine_t; /*kind=normal*/
    typedef err_v_char_format_info_t v_char_format_info_t; /*kind=aggregate*/
    typedef err_v_stream_feature_t v_stream_feature_t; /*kind=normal*/
    typedef err_map_symbol_int_void_pair_cmp_t map_symbol_int_void_pair_cmp_t; /*kind=normal*/
    typedef err_map_int_v_stream_pair_ptr_cmp_t map_int_v_stream_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_v_char_const_p_cmp_t v_char_const_p_cmp_t; /*kind=normal*/
    typedef err_map_int_char_p_pair_cmp_t map_int_char_p_pair_cmp_t; /*kind=normal*/
    typedef err_v_message_size_t v_message_size_t; /*kind=normal*/
    typedef err_v_message_element_ref_t v_message_element_ref_t; /*kind=normal*/
    typedef err_v_buffer_value_t v_buffer_value_t; /*kind=normal*/
    typedef err_map_int_map_int_v_callback_key_result_t map_int_map_int_v_callback_key_result_t; /*kind=normal*/
    typedef err_map_symbol_string_element_ptr_t map_symbol_string_element_ptr_t; /*kind=normal*/
    typedef err_symtab_pair_ptr_cmp_t symtab_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_v_char_size_t v_char_size_t; /*kind=normal*/
    typedef err_v_char_combine_t v_char_combine_t; /*kind=normal*/
    typedef err_map_int_v_callback_pair_cmp_t map_int_v_callback_pair_cmp_t; /*kind=normal*/
    typedef err_map_int_callback_pair_ptr_cmp_t map_int_callback_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_v_buffer_cmp_t v_buffer_cmp_t; /*kind=normal*/
    typedef err_map_int_symbol_key_result_t map_int_symbol_key_result_t; /*kind=normal*/
    typedef err_map_int_int_pair_cmp_t map_int_int_pair_cmp_t; /*kind=normal*/
    typedef err_map_symbol_string_key_result_t map_symbol_string_key_result_t; /*kind=normal*/
    typedef err_v_callback_value_t v_callback_value_t; /*kind=normal*/
    typedef err_map_symbol_int_pair_ptr_t map_symbol_int_pair_ptr_t; /*kind=aggregate*/
    typedef err_map_symbol_stream_pair_t map_symbol_stream_pair_t; /*kind=aggregate*/
    typedef err_v_int_size_t v_int_size_t; /*kind=normal*/
    typedef err_v_char_index_t v_char_index_t; /*kind=normal*/
    typedef err_v_char_const_p_map_t v_char_const_p_map_t; /*kind=normal*/
    typedef err_map_int_char_p_feature_t map_int_char_p_feature_t; /*kind=normal*/
    typedef err_v_char_element_ptr_t v_char_element_ptr_t; /*kind=normal*/
    typedef err_map_int_v_stream_pair_cmp_t map_int_v_stream_pair_cmp_t; /*kind=normal*/
    typedef err_v_callback_element_ptr_t v_callback_element_ptr_t; /*kind=normal*/
    typedef err_v_int_combine_t v_int_combine_t; /*kind=normal*/
    typedef err_map_symbol_int_element_ptr_t map_symbol_int_element_ptr_t; /*kind=normal*/
    typedef err_v_int_map_t v_int_map_t; /*kind=normal*/
    typedef err_map_int_symbol_pair_ptr_t map_int_symbol_pair_ptr_t; /*kind=aggregate*/
    typedef err_v_buffer_element_ref_t v_buffer_element_ref_t; /*kind=normal*/
    typedef err_v_int_element_ptr_t v_int_element_ptr_t; /*kind=normal*/
    typedef err_map_int_char_p_element_ptr_t map_int_char_p_element_ptr_t; /*kind=normal*/
    typedef err_map_int_symbol_pair_ptr_cmp_t map_int_symbol_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_v_callback_index_t v_callback_index_t; /*kind=normal*/
    typedef err_map_int_bool_element_ptr_t map_int_bool_element_ptr_t; /*kind=normal*/
    typedef err_v_char_const_p_element_ref_t v_char_const_p_element_ref_t; /*kind=normal*/
    typedef err_map_symbol_stream_index_t map_symbol_stream_index_t; /*kind=normal*/
    typedef err_map_int_char_p_pair_ptr_cmp_t map_int_char_p_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_map_int_v_callback_pair_ptr_t map_int_v_callback_pair_ptr_t; /*kind=aggregate*/
    typedef err_map_char_p_char_p_key_result_t map_char_p_char_p_key_result_t; /*kind=normal*/
    typedef err_map_int_char_p_key_result_t map_int_char_p_key_result_t; /*kind=normal*/
    typedef err_map_int_int_pair_ptr_cmp_t map_int_int_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_v_message_value_t v_message_value_t; /*kind=normal*/
    typedef err_v_char_feature_t v_char_feature_t; /*kind=normal*/
    typedef err_map_int_bool_void_pair_cmp_t map_int_bool_void_pair_cmp_t; /*kind=normal*/
    typedef err_map_int_symbol_value_t map_int_symbol_value_t; /*kind=normal*/
    typedef err_map_int_v_stream_value_t map_int_v_stream_value_t; /*kind=normal*/
    typedef err_v_char_value_t v_char_value_t; /*kind=normal*/
    typedef err_map_char_p_char_p_value_t map_char_p_char_p_value_t; /*kind=normal*/
    typedef err_v_buffer_size_t v_buffer_size_t; /*kind=normal*/
    typedef err_map_symbol_stream_element_ptr_t map_symbol_stream_element_ptr_t; /*kind=normal*/
    typedef err_map_symbol_string_pair_ptr_cmp_t map_symbol_string_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_map_int_map_int_v_callback_pair_t map_int_map_int_v_callback_pair_t; /*kind=aggregate*/
    typedef err_symtab_pair_ptr_t symtab_pair_ptr_t; /*kind=aggregate*/
    typedef err_map_int_bool_value_t map_int_bool_value_t; /*kind=normal*/
    typedef err_map_int_v_callback_index_t map_int_v_callback_index_t; /*kind=normal*/
    typedef err_v_buffer_combine_t v_buffer_combine_t; /*kind=normal*/
    typedef err_map_symbol_int_value_t map_symbol_int_value_t; /*kind=normal*/
    typedef err_symtab_void_pair_cmp_t symtab_void_pair_cmp_t; /*kind=normal*/
    typedef err_map_int_v_stream_pair_ptr_t map_int_v_stream_pair_ptr_t; /*kind=aggregate*/
    typedef err_map_symbol_int_index_t map_symbol_int_index_t; /*kind=normal*/
    typedef err_map_int_bool_pair_ptr_t map_int_bool_pair_ptr_t; /*kind=aggregate*/
    typedef err_v_stream_combine_t v_stream_combine_t; /*kind=normal*/
    typedef err_map_int_bool_feature_t map_int_bool_feature_t; /*kind=normal*/
    typedef err_v_buffer_index_t v_buffer_index_t; /*kind=normal*/
    typedef err_map_int_v_callback_feature_t map_int_v_callback_feature_t; /*kind=normal*/
    typedef err_map_file_stream_index_t map_file_stream_index_t; /*kind=normal*/
    typedef err_v_callback_cmp_t v_callback_cmp_t; /*kind=normal*/
    typedef err_map_int_callback_pair_ptr_t map_int_callback_pair_ptr_t; /*kind=aggregate*/
    typedef err_v_char_const_p_element_ptr_t v_char_const_p_element_ptr_t; /*kind=normal*/
    typedef err_map_file_stream_pair_t map_file_stream_pair_t; /*kind=aggregate*/
    typedef err_v_char_cnt_t v_char_cnt_t; /*kind=normal*/
    typedef err_map_int_symbol_pair_t map_int_symbol_pair_t; /*kind=aggregate*/
    typedef err_v_buffer_cnt_t v_buffer_cnt_t; /*kind=normal*/
    typedef err_v_buffer_map_t v_buffer_map_t; /*kind=normal*/
    typedef err_map_int_v_callback_pair_ptr_cmp_t map_int_v_callback_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_map_int_v_stream_pair_t map_int_v_stream_pair_t; /*kind=aggregate*/
    typedef err_map_char_p_char_p_void_pair_cmp_t map_char_p_char_p_void_pair_cmp_t; /*kind=normal*/
    typedef err_map_int_map_int_v_callback_pair_ptr_cmp_t map_int_map_int_v_callback_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_v_stream_index_t v_stream_index_t; /*kind=normal*/
    typedef err_map_file_stream_element_ptr_t map_file_stream_element_ptr_t; /*kind=normal*/
    typedef err_v_char_const_p_cnt_t v_char_const_p_cnt_t; /*kind=normal*/
    typedef err_map_int_callback_key_result_t map_int_callback_key_result_t; /*kind=normal*/
    typedef err_v_stream_size_t v_stream_size_t; /*kind=normal*/
    typedef err_v_callback_element_ref_t v_callback_element_ref_t; /*kind=normal*/
    typedef err_v_buffer_feature_t v_buffer_feature_t; /*kind=normal*/
    typedef err_map_symbol_stream_pair_cmp_t map_symbol_stream_pair_cmp_t; /*kind=normal*/
    typedef err_v_int_cnt_t v_int_cnt_t; /*kind=normal*/
    typedef err_v_callback_cnt_t v_callback_cnt_t; /*kind=normal*/
    typedef err_v_callback_combine_t v_callback_combine_t; /*kind=normal*/
    typedef err_symtab_pair_cmp_t symtab_pair_cmp_t; /*kind=normal*/
    typedef err_v_buffer_cpp_feature_t v_buffer_cpp_feature_t; /*kind=normal*/
    typedef err_v_int_index_t v_int_index_t; /*kind=normal*/
    typedef err_map_int_char_p_pair_t map_int_char_p_pair_t; /*kind=aggregate*/
    typedef err_map_int_callback_feature_t map_int_callback_feature_t; /*kind=normal*/
    typedef err_map_char_p_char_p_pair_t map_char_p_char_p_pair_t; /*kind=aggregate*/
    typedef err_map_int_callback_void_pair_cmp_t map_int_callback_void_pair_cmp_t; /*kind=normal*/
    typedef err_v_stream_cmp_t v_stream_cmp_t; /*kind=normal*/
    typedef err_map_symbol_string_value_t map_symbol_string_value_t; /*kind=normal*/
    typedef err_v_stream_value_t v_stream_value_t; /*kind=normal*/
    typedef err_map_file_stream_key_result_t map_file_stream_key_result_t; /*kind=normal*/
    typedef err_map_int_v_callback_value_t map_int_v_callback_value_t; /*kind=normal*/
    typedef err_map_int_map_int_v_callback_pair_ptr_t map_int_map_int_v_callback_pair_ptr_t; /*kind=aggregate*/
    typedef err_v_callback_feature_t v_callback_feature_t; /*kind=normal*/
    typedef err_symtab_value_t symtab_value_t; /*kind=normal*/
    typedef err_v_char_const_p_index_t v_char_const_p_index_t; /*kind=normal*/
    typedef err_map_symbol_string_pair_cmp_t map_symbol_string_pair_cmp_t; /*kind=normal*/
    typedef err_v_buffer_element_ptr_t v_buffer_element_ptr_t; /*kind=normal*/
    typedef err_map_int_callback_pair_cmp_t map_int_callback_pair_cmp_t; /*kind=normal*/
    typedef err_map_int_bool_index_t map_int_bool_index_t; /*kind=normal*/
    typedef err_map_int_callback_value_t map_int_callback_value_t; /*kind=normal*/
    typedef err_map_file_stream_feature_t map_file_stream_feature_t; /*kind=normal*/
    typedef err_map_symbol_stream_value_t map_symbol_stream_value_t; /*kind=normal*/
    typedef err_v_message_feature_t v_message_feature_t; /*kind=normal*/
    typedef err_v_stream_element_ptr_t v_stream_element_ptr_t; /*kind=normal*/
    typedef err_map_int_v_stream_key_result_t map_int_v_stream_key_result_t; /*kind=normal*/
    typedef err_v_message_element_ptr_t v_message_element_ptr_t; /*kind=normal*/
    typedef err_map_file_stream_pair_cmp_t map_file_stream_pair_cmp_t; /*kind=normal*/
    typedef err_v_int_cpp_feature_t v_int_cpp_feature_t; /*kind=normal*/
    typedef err_map_int_symbol_void_pair_cmp_t map_int_symbol_void_pair_cmp_t; /*kind=normal*/
    typedef err_map_int_symbol_element_ptr_t map_int_symbol_element_ptr_t; /*kind=normal*/
    typedef err_map_symbol_int_pair_ptr_cmp_t map_symbol_int_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_v_stream_cpp_feature_t v_stream_cpp_feature_t; /*kind=normal*/
    typedef err_v_stream_element_ref_t v_stream_element_ref_t; /*kind=normal*/
    typedef err_map_file_stream_pair_ptr_t map_file_stream_pair_ptr_t; /*kind=aggregate*/
    typedef err_v_char_element_ref_t v_char_element_ref_t; /*kind=normal*/
    typedef err_map_symbol_int_feature_t map_symbol_int_feature_t; /*kind=normal*/
    typedef err_v_char_map_t v_char_map_t; /*kind=normal*/
    typedef err_v_int_value_t v_int_value_t; /*kind=normal*/
    typedef err_v_char_const_p_size_t v_char_const_p_size_t; /*kind=normal*/
    typedef err_map_char_p_char_p_pair_ptr_t map_char_p_char_p_pair_ptr_t; /*kind=aggregate*/
    typedef err_v_char_const_p_value_t v_char_const_p_value_t; /*kind=normal*/
    typedef err_map_int_v_stream_element_ptr_t map_int_v_stream_element_ptr_t; /*kind=normal*/
    typedef err_map_int_v_callback_element_ptr_t map_int_v_callback_element_ptr_t; /*kind=normal*/
    typedef err_map_int_callback_pair_t map_int_callback_pair_t; /*kind=aggregate*/
    typedef err_map_symbol_stream_pair_ptr_cmp_t map_symbol_stream_pair_ptr_cmp_t; /*kind=normal*/
    typedef err_map_char_p_char_p_element_ptr_t map_char_p_char_p_element_ptr_t; /*kind=normal*/
    typedef err_map_file_stream_void_pair_cmp_t map_file_stream_void_pair_cmp_t; /*kind=normal*/
    typedef err_map_int_symbol_pair_cmp_t map_int_symbol_pair_cmp_t; /*kind=normal*/
    typedef err_v_stream_cnt_t v_stream_cnt_t; /*kind=normal*/
    typedef err_symtab_key_result_t symtab_key_result_t; /*kind=normal*/
    typedef err_map_int_int_feature_t map_int_int_feature_t; /*kind=normal*/
};
#endif
#ifdef ERR_ERWIN_NAMESPACE
#    define v_int_feature_t err_v_int_feature_t
#    define map_symbol_string_pair_t err_map_symbol_string_pair_t
#    define map_symbol_string_index_t err_map_symbol_string_index_t
#    define map_file_stream_pair_ptr_cmp_t err_map_file_stream_pair_ptr_cmp_t
#    define map_int_int_void_pair_cmp_t err_map_int_int_void_pair_cmp_t
#  ifdef __cplusplus
#    define v_message_cpp_feature_t err_v_message_cpp_feature_t
#  endif
#  ifdef __cplusplus
#    define v_char_const_p_cpp_feature_t err_v_char_const_p_cpp_feature_t
#  endif
#    define map_int_int_value_t err_map_int_int_value_t
#    define map_int_map_int_v_callback_void_pair_cmp_t err_map_int_map_int_v_callback_void_pair_cmp_t
#    define map_int_int_index_t err_map_int_int_index_t
#    define map_int_bool_pair_cmp_t err_map_int_bool_pair_cmp_t
#    define map_symbol_string_feature_t err_map_symbol_string_feature_t
#  ifdef __cplusplus
#    define v_int_element_ref_t err_v_int_element_ref_t
#  endif
#    define v_int_cmp_t err_v_int_cmp_t
#    define map_char_p_char_p_feature_t err_map_char_p_char_p_feature_t
#    define map_int_map_int_v_callback_pair_cmp_t err_map_int_map_int_v_callback_pair_cmp_t
#    define map_int_v_callback_void_pair_cmp_t err_map_int_v_callback_void_pair_cmp_t
#    define map_char_p_char_p_pair_cmp_t err_map_char_p_char_p_pair_cmp_t
#    define map_int_v_stream_void_pair_cmp_t err_map_int_v_stream_void_pair_cmp_t
#    define v_char_quotation_method_t err_v_char_quotation_method_t
#    define v_message_cnt_t err_v_message_cnt_t
#    define map_symbol_string_void_pair_cmp_t err_map_symbol_string_void_pair_cmp_t
#    define map_int_map_int_v_callback_value_t err_map_int_map_int_v_callback_value_t
#    define map_symbol_stream_key_result_t err_map_symbol_stream_key_result_t
#    define map_int_symbol_index_t err_map_int_symbol_index_t
#    define map_int_int_pair_t err_map_int_int_pair_t
#    define v_message_map_t err_v_message_map_t
#    define v_char_cmp_t err_v_char_cmp_t
#    define map_int_v_callback_pair_t err_map_int_v_callback_pair_t
#    define map_int_callback_index_t err_map_int_callback_index_t
#    define map_int_map_int_v_callback_index_t err_map_int_map_int_v_callback_index_t
#    define map_int_symbol_feature_t err_map_int_symbol_feature_t
#    define symtab_pair_t err_symtab_pair_t
#    define map_int_int_key_result_t err_map_int_int_key_result_t
#    define map_symbol_int_key_result_t err_map_symbol_int_key_result_t
#    define map_int_char_p_value_t err_map_int_char_p_value_t
#    define map_int_char_p_void_pair_cmp_t err_map_int_char_p_void_pair_cmp_t
#    define v_stream_map_t err_v_stream_map_t
#    define symtab_feature_t err_symtab_feature_t
#    define map_int_bool_pair_ptr_cmp_t err_map_int_bool_pair_ptr_cmp_t
#    define map_int_v_stream_feature_t err_map_int_v_stream_feature_t
#    define v_message_cmp_t err_v_message_cmp_t
#    define map_int_int_element_ptr_t err_map_int_int_element_ptr_t
#    define map_int_v_stream_index_t err_map_int_v_stream_index_t
#    define map_int_map_int_v_callback_feature_t err_map_int_map_int_v_callback_feature_t
#    define map_char_p_char_p_pair_ptr_cmp_t err_map_char_p_char_p_pair_ptr_cmp_t
#    define map_int_char_p_pair_ptr_t err_map_int_char_p_pair_ptr_t
#    define v_char_const_p_feature_t err_v_char_const_p_feature_t
#    define map_symbol_int_pair_cmp_t err_map_symbol_int_pair_cmp_t
#    define v_callback_size_t err_v_callback_size_t
#    define map_file_stream_value_t err_map_file_stream_value_t
#    define map_int_char_p_index_t err_map_int_char_p_index_t
#    define map_char_p_char_p_index_t err_map_char_p_char_p_index_t
#    define symtab_index_t err_symtab_index_t
#    define v_message_index_t err_v_message_index_t
#    define map_int_v_callback_key_result_t err_map_int_v_callback_key_result_t
#    define map_int_bool_pair_t err_map_int_bool_pair_t
#    define v_callback_map_t err_v_callback_map_t
#    define map_symbol_string_pair_ptr_t err_map_symbol_string_pair_ptr_t
#    define map_symbol_int_pair_t err_map_symbol_int_pair_t
#    define map_int_map_int_v_callback_element_ptr_t err_map_int_map_int_v_callback_element_ptr_t
#    define map_symbol_stream_pair_ptr_t err_map_symbol_stream_pair_ptr_t
#    define map_int_bool_key_result_t err_map_int_bool_key_result_t
#    define v_char_const_p_combine_t err_v_char_const_p_combine_t
#  ifdef __cplusplus
#    define v_char_cpp_feature_t err_v_char_cpp_feature_t
#  endif
#    define map_int_int_pair_ptr_t err_map_int_int_pair_ptr_t
#    define map_int_callback_element_ptr_t err_map_int_callback_element_ptr_t
#    define map_symbol_stream_void_pair_cmp_t err_map_symbol_stream_void_pair_cmp_t
#  ifdef __cplusplus
#    define v_callback_cpp_feature_t err_v_callback_cpp_feature_t
#  endif
#    define map_symbol_stream_feature_t err_map_symbol_stream_feature_t
#    define v_message_combine_t err_v_message_combine_t
#    define v_char_format_info_t err_v_char_format_info_t
#    define v_stream_feature_t err_v_stream_feature_t
#    define map_symbol_int_void_pair_cmp_t err_map_symbol_int_void_pair_cmp_t
#    define map_int_v_stream_pair_ptr_cmp_t err_map_int_v_stream_pair_ptr_cmp_t
#    define v_char_const_p_cmp_t err_v_char_const_p_cmp_t
#    define map_int_char_p_pair_cmp_t err_map_int_char_p_pair_cmp_t
#    define v_message_size_t err_v_message_size_t
#  ifdef __cplusplus
#    define v_message_element_ref_t err_v_message_element_ref_t
#  endif
#    define v_buffer_value_t err_v_buffer_value_t
#    define map_int_map_int_v_callback_key_result_t err_map_int_map_int_v_callback_key_result_t
#    define map_symbol_string_element_ptr_t err_map_symbol_string_element_ptr_t
#    define symtab_pair_ptr_cmp_t err_symtab_pair_ptr_cmp_t
#    define v_char_size_t err_v_char_size_t
#    define v_char_combine_t err_v_char_combine_t
#    define map_int_v_callback_pair_cmp_t err_map_int_v_callback_pair_cmp_t
#    define map_int_callback_pair_ptr_cmp_t err_map_int_callback_pair_ptr_cmp_t
#    define v_buffer_cmp_t err_v_buffer_cmp_t
#    define map_int_symbol_key_result_t err_map_int_symbol_key_result_t
#    define map_int_int_pair_cmp_t err_map_int_int_pair_cmp_t
#    define map_symbol_string_key_result_t err_map_symbol_string_key_result_t
#    define v_callback_value_t err_v_callback_value_t
#    define map_symbol_int_pair_ptr_t err_map_symbol_int_pair_ptr_t
#    define map_symbol_stream_pair_t err_map_symbol_stream_pair_t
#    define v_int_size_t err_v_int_size_t
#    define v_char_index_t err_v_char_index_t
#    define v_char_const_p_map_t err_v_char_const_p_map_t
#    define map_int_char_p_feature_t err_map_int_char_p_feature_t
#    define v_char_element_ptr_t err_v_char_element_ptr_t
#    define map_int_v_stream_pair_cmp_t err_map_int_v_stream_pair_cmp_t
#    define v_callback_element_ptr_t err_v_callback_element_ptr_t
#    define v_int_combine_t err_v_int_combine_t
#    define map_symbol_int_element_ptr_t err_map_symbol_int_element_ptr_t
#    define v_int_map_t err_v_int_map_t
#    define map_int_symbol_pair_ptr_t err_map_int_symbol_pair_ptr_t
#  ifdef __cplusplus
#    define v_buffer_element_ref_t err_v_buffer_element_ref_t
#  endif
#    define v_int_element_ptr_t err_v_int_element_ptr_t
#    define map_int_char_p_element_ptr_t err_map_int_char_p_element_ptr_t
#    define map_int_symbol_pair_ptr_cmp_t err_map_int_symbol_pair_ptr_cmp_t
#    define v_callback_index_t err_v_callback_index_t
#    define map_int_bool_element_ptr_t err_map_int_bool_element_ptr_t
#  ifdef __cplusplus
#    define v_char_const_p_element_ref_t err_v_char_const_p_element_ref_t
#  endif
#    define map_symbol_stream_index_t err_map_symbol_stream_index_t
#    define map_int_char_p_pair_ptr_cmp_t err_map_int_char_p_pair_ptr_cmp_t
#    define map_int_v_callback_pair_ptr_t err_map_int_v_callback_pair_ptr_t
#    define map_char_p_char_p_key_result_t err_map_char_p_char_p_key_result_t
#    define map_int_char_p_key_result_t err_map_int_char_p_key_result_t
#    define map_int_int_pair_ptr_cmp_t err_map_int_int_pair_ptr_cmp_t
#    define v_message_value_t err_v_message_value_t
#    define v_char_feature_t err_v_char_feature_t
#    define map_int_bool_void_pair_cmp_t err_map_int_bool_void_pair_cmp_t
#    define map_int_symbol_value_t err_map_int_symbol_value_t
#    define map_int_v_stream_value_t err_map_int_v_stream_value_t
#    define v_char_value_t err_v_char_value_t
#    define map_char_p_char_p_value_t err_map_char_p_char_p_value_t
#    define v_buffer_size_t err_v_buffer_size_t
#    define map_symbol_stream_element_ptr_t err_map_symbol_stream_element_ptr_t
#    define map_symbol_string_pair_ptr_cmp_t err_map_symbol_string_pair_ptr_cmp_t
#    define map_int_map_int_v_callback_pair_t err_map_int_map_int_v_callback_pair_t
#    define symtab_pair_ptr_t err_symtab_pair_ptr_t
#    define map_int_bool_value_t err_map_int_bool_value_t
#    define map_int_v_callback_index_t err_map_int_v_callback_index_t
#    define v_buffer_combine_t err_v_buffer_combine_t
#    define map_symbol_int_value_t err_map_symbol_int_value_t
#    define symtab_void_pair_cmp_t err_symtab_void_pair_cmp_t
#    define map_int_v_stream_pair_ptr_t err_map_int_v_stream_pair_ptr_t
#    define map_symbol_int_index_t err_map_symbol_int_index_t
#    define map_int_bool_pair_ptr_t err_map_int_bool_pair_ptr_t
#    define v_stream_combine_t err_v_stream_combine_t
#    define map_int_bool_feature_t err_map_int_bool_feature_t
#    define v_buffer_index_t err_v_buffer_index_t
#    define map_int_v_callback_feature_t err_map_int_v_callback_feature_t
#    define map_file_stream_index_t err_map_file_stream_index_t
#    define v_callback_cmp_t err_v_callback_cmp_t
#    define map_int_callback_pair_ptr_t err_map_int_callback_pair_ptr_t
#    define v_char_const_p_element_ptr_t err_v_char_const_p_element_ptr_t
#    define map_file_stream_pair_t err_map_file_stream_pair_t
#    define v_char_cnt_t err_v_char_cnt_t
#    define map_int_symbol_pair_t err_map_int_symbol_pair_t
#    define v_buffer_cnt_t err_v_buffer_cnt_t
#    define v_buffer_map_t err_v_buffer_map_t
#    define map_int_v_callback_pair_ptr_cmp_t err_map_int_v_callback_pair_ptr_cmp_t
#    define map_int_v_stream_pair_t err_map_int_v_stream_pair_t
#    define map_char_p_char_p_void_pair_cmp_t err_map_char_p_char_p_void_pair_cmp_t
#    define map_int_map_int_v_callback_pair_ptr_cmp_t err_map_int_map_int_v_callback_pair_ptr_cmp_t
#    define v_stream_index_t err_v_stream_index_t
#    define map_file_stream_element_ptr_t err_map_file_stream_element_ptr_t
#    define v_char_const_p_cnt_t err_v_char_const_p_cnt_t
#    define map_int_callback_key_result_t err_map_int_callback_key_result_t
#    define v_stream_size_t err_v_stream_size_t
#  ifdef __cplusplus
#    define v_callback_element_ref_t err_v_callback_element_ref_t
#  endif
#    define v_buffer_feature_t err_v_buffer_feature_t
#    define map_symbol_stream_pair_cmp_t err_map_symbol_stream_pair_cmp_t
#    define v_int_cnt_t err_v_int_cnt_t
#    define v_callback_cnt_t err_v_callback_cnt_t
#    define v_callback_combine_t err_v_callback_combine_t
#    define symtab_pair_cmp_t err_symtab_pair_cmp_t
#  ifdef __cplusplus
#    define v_buffer_cpp_feature_t err_v_buffer_cpp_feature_t
#  endif
#    define v_int_index_t err_v_int_index_t
#    define map_int_char_p_pair_t err_map_int_char_p_pair_t
#    define map_int_callback_feature_t err_map_int_callback_feature_t
#    define map_char_p_char_p_pair_t err_map_char_p_char_p_pair_t
#    define map_int_callback_void_pair_cmp_t err_map_int_callback_void_pair_cmp_t
#    define v_stream_cmp_t err_v_stream_cmp_t
#    define map_symbol_string_value_t err_map_symbol_string_value_t
#    define v_stream_value_t err_v_stream_value_t
#    define map_file_stream_key_result_t err_map_file_stream_key_result_t
#    define map_int_v_callback_value_t err_map_int_v_callback_value_t
#    define map_int_map_int_v_callback_pair_ptr_t err_map_int_map_int_v_callback_pair_ptr_t
#    define v_callback_feature_t err_v_callback_feature_t
#    define symtab_value_t err_symtab_value_t
#    define v_char_const_p_index_t err_v_char_const_p_index_t
#    define map_symbol_string_pair_cmp_t err_map_symbol_string_pair_cmp_t
#    define v_buffer_element_ptr_t err_v_buffer_element_ptr_t
#    define map_int_callback_pair_cmp_t err_map_int_callback_pair_cmp_t
#    define map_int_bool_index_t err_map_int_bool_index_t
#    define map_int_callback_value_t err_map_int_callback_value_t
#    define map_file_stream_feature_t err_map_file_stream_feature_t
#    define map_symbol_stream_value_t err_map_symbol_stream_value_t
#    define v_message_feature_t err_v_message_feature_t
#    define v_stream_element_ptr_t err_v_stream_element_ptr_t
#    define map_int_v_stream_key_result_t err_map_int_v_stream_key_result_t
#    define v_message_element_ptr_t err_v_message_element_ptr_t
#    define map_file_stream_pair_cmp_t err_map_file_stream_pair_cmp_t
#  ifdef __cplusplus
#    define v_int_cpp_feature_t err_v_int_cpp_feature_t
#  endif
#    define map_int_symbol_void_pair_cmp_t err_map_int_symbol_void_pair_cmp_t
#    define map_int_symbol_element_ptr_t err_map_int_symbol_element_ptr_t
#    define map_symbol_int_pair_ptr_cmp_t err_map_symbol_int_pair_ptr_cmp_t
#  ifdef __cplusplus
#    define v_stream_cpp_feature_t err_v_stream_cpp_feature_t
#  endif
#  ifdef __cplusplus
#    define v_stream_element_ref_t err_v_stream_element_ref_t
#  endif
#    define map_file_stream_pair_ptr_t err_map_file_stream_pair_ptr_t
#  ifdef __cplusplus
#    define v_char_element_ref_t err_v_char_element_ref_t
#  endif
#    define map_symbol_int_feature_t err_map_symbol_int_feature_t
#    define v_char_map_t err_v_char_map_t
#    define v_int_value_t err_v_int_value_t
#    define v_char_const_p_size_t err_v_char_const_p_size_t
#    define map_char_p_char_p_pair_ptr_t err_map_char_p_char_p_pair_ptr_t
#    define v_char_const_p_value_t err_v_char_const_p_value_t
#    define map_int_v_stream_element_ptr_t err_map_int_v_stream_element_ptr_t
#    define map_int_v_callback_element_ptr_t err_map_int_v_callback_element_ptr_t
#    define map_int_callback_pair_t err_map_int_callback_pair_t
#    define map_symbol_stream_pair_ptr_cmp_t err_map_symbol_stream_pair_ptr_cmp_t
#    define map_char_p_char_p_element_ptr_t err_map_char_p_char_p_element_ptr_t
#    define map_file_stream_void_pair_cmp_t err_map_file_stream_void_pair_cmp_t
#    define map_int_symbol_pair_cmp_t err_map_int_symbol_pair_cmp_t
#    define v_stream_cnt_t err_v_stream_cnt_t
#    define symtab_key_result_t err_symtab_key_result_t
#    define map_int_int_feature_t err_map_int_int_feature_t
#endif
/* @@End: #include@@ */

#endif /* ERR_ERWIN_ERWINALL_H */
