/*-*- Mode: C -*-*/
/*
 * Time-stamp: <Fri, 24 Aug 2007 18:00:21 +0200 theiling>
 * Author: Henrik Theiling
 * Description:
 *    Templates for vectors (= resizable arrays)
 *    Theses can also be used as stacks.
 *
 * @@Begin: Licencing and Copying@@
 * 
 * Copyright (c) Henrik Theiling
 * Licence Version 2, Special Version for Erwin.
 * 
 * The term 'this software' used in the following, additional to its
 * usual usage, also includes the instantiated source files generated by
 * tools of this package.
 * 
 * This software is provided 'as-is', without warranty of any kind,
 * express or implied.  In no event will the authors or copyright holders
 * be held liable for any damages arising from the use of this software.
 * 
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 * 
 * 1. The origin of this software must not be misrepresented; you must
 * not claim that you wrote the original software. If you use this
 * software in a product, an acknowledgment in the product documentation
 * would be appreciated.
 * 
 * 2. Altered source versions must be plainly marked as such, and must
 * not be misrepresented as being the original software.
 * 
 * 3. You must not use any of the names of the authors or copyright
 * holders of the original software for advertising or publicity
 * pertaining to distribution without specific, written prior permission.
 * 
 * 4. If you change this software and redistribute parts or all of it in
 * any form, you must make the source code of the altered version of this
 * software available.  As an exception, files that were generated by
 * tools of this package may be used freely, including modification.
 * 
 * 5. This notice must not be removed or altered from any source
 * distribution.
 * 
 * This licence is governed by the Laws of Germany.  Disputes shall be
 * settled by Saarbruecken City Court.
 * 
 * @@End: Licencing and Copying@@
 *
 * ---------------------------------------------------------------------- */
#ifdef ERWIN_DEBUG_INCLUDE
#warning "Including vector.h."
#endif

#ifndef ERR_ERWIN_VECTOR_H
#define ERR_ERWIN_VECTOR_H

#ifdef ERWIN_DEBUG_INCLUDE
#warning "First inclusion of vector.h."
#endif
#ifdef ERR_ERWIN_COMPILING
#  include "error/erwin/defs.h"
#else
#  include <error/erwin/defs.h>
#endif

#ifdef ERR_ERWIN_ADAM_NAME

#define err_erwininternalvectorerrno err_erwininternalvectorerrno
#define err_erwininternalvectorstrerror err_erwininternalvectorstrerror
#define ERR_ERWININTERNALVECTOROK ERR_ERWININTERNALVECTOROK
#define ERR_ERWININTERNALVECTORISOK ERR_ERWININTERNALVECTORISOK
#define ERR_ERWININTERNALVECTORISERROR ERR_ERWININTERNALVECTORISERROR
#define ERR_ERWININTERNALVECTORISWARNING ERR_ERWININTERNALVECTORISWARNING
#define ERR_ERWININTERNALVECTORERRNOMEM ERR_ERWININTERNALVECTORERRNOMEM
#define ERR_ERWININTERNALVECTORERROUTOFRANGE ERR_ERWININTERNALVECTORERROUTOFRANGE
#define ERR_ERWININTERNALVECTORERRTOOLARGE ERR_ERWININTERNALVECTORERRTOOLARGE
#define ERR_ERWININTERNALVECTORERRASSERTIONFAILED ERR_ERWININTERNALVECTORERRASSERTIONFAILED
#define ERR_ERWININTERNALVECTORERRNOTCOMPILED ERR_ERWININTERNALVECTORERRNOTCOMPILED
#define ERR_ERWININTERNALVECTORERRIO ERR_ERWININTERNALVECTORERRIO
#define ERR_ERWININTERNALVECTORWARNOUTOFRANGE ERR_ERWININTERNALVECTORWARNOUTOFRANGE
#define ERR_ERWININTERNALVECTORWARNEMPTY ERR_ERWININTERNALVECTORWARNEMPTY

#else /* !defined(ERR_ERWIN_ADAM_NAME) */

#ifdef __cplusplus
extern "C" {
#endif

/* must be in sync with vector.c: */
#if !defined(ERR_ERWIN_THREAD_SAFE) || ERR_ERWIN_USE_THREAD_KEYWORD
extern ERR_ERWIN_THREAD_LOCAL int err_erwininternalvectorerrno;
#elif ERR_ERWIN_USE_PTHREAD
extern int *err_erwininternalvectorerrnoptr(void);
#define err_erwininternalvectorerrno (*err_erwininternalvectorerrnoptr())
#endif

extern char const *err_erwininternalvectorstrerror (int) ATTR_PURE;

#define ERR_ERWININTERNALVECTOROK                  1

#define ERR_ERWININTERNALVECTORISOK(X)             ((X) == ERR_ERWININTERNALVECTOROK)
#define ERR_ERWININTERNALVECTORISERROR(X)          ((X) <  ERR_ERWININTERNALVECTOROK)
#define ERR_ERWININTERNALVECTORISWARNING(X)        ((X) >  ERR_ERWININTERNALVECTOROK)

#define ERR_ERWININTERNALVECTORERRNOMEM            (-2)
#define ERR_ERWININTERNALVECTORERROUTOFRANGE       (-4)
#define ERR_ERWININTERNALVECTORERRASSERTIONFAILED  (-5)
#define ERR_ERWININTERNALVECTORERRNOTCOMPILED      (-6)
#define ERR_ERWININTERNALVECTORERRIO               (-7)
#define ERR_ERWININTERNALVECTORERRTOOLARGE         (-8)

#define ERR_ERWININTERNALVECTORWARNOUTOFRANGE      3
        /* do not write +3, g++ 2.7.2.3 will not see that that is a constant! */
#define ERR_ERWININTERNALVECTORWARNEMPTY           5

#ifdef __cplusplus
}
#endif

#endif /* defined(ERR_ERWIN_ADAM_NAME) */

#endif /* AI_ERWIN_VECTOR_H */
