/* -*- Mode: C -*-
 *
 * Author: Henrik Theiling
 * Description:
 *     This file contains all the additional assembly parts.
 *     There should be a generic version of each part of assembly code written
 *     in C so that this is exchangable.
 *
 * @@Begin: Licencing and Copying@@
 *
 * Copyright (c) Henrik Theiling
 * Licence Version 2, Special Version for Erwin.
 *
 * The term 'this software' used in the following, additional to its
 * usual usage, also includes the instantiated source files generated by
 * tools of this package.
 *
 * This software is provided 'as-is', without warranty of any kind,
 * express or implied.  In no event will the authors or copyright holders
 * be held liable for any damages arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must
 * not claim that you wrote the original software. If you use this
 * software in a product, an acknowledgment in the product documentation
 * would be appreciated.
 *
 * 2. Altered source versions must be plainly marked as such, and must
 * not be misrepresented as being the original software.
 *
 * 3. You must not use any of the names of the authors or copyright
 * holders of the original software for advertising or publicity
 * pertaining to distribution without specific, written prior permission.
 *
 * 4. If you change this software and redistribute parts or all of it in
 * any form, you must make the source code of the altered version of this
 * software available.  As an exception, files that were generated by
 * tools of this package may be used freely, including modification.
 *
 * 5. This notice must not be removed or altered from any source
 * distribution.
 *
 * This licence is governed by the Laws of Germany.  Disputes shall be
 * settled by Saarbruecken City Court.
 *
 * @@End: Licencing and Copying@@
 *
 */

#ifdef ERWIN_DEBUG_INCLUDE
#warning "Including asm.h."
#endif

#ifndef ERWIN_ASM_H
#define ERWIN_ASM_H

#ifdef ERWIN_DEBUG_INCLUDE
#warning "First inclusion of asm.h."
#endif

#ifdef ERWIN_REQUIRE_DETERMINISM
#  ifndef SIZEOF_HASHVAL_T
#  define SIZEOF_HASHVAL_T 4
#  endif /* !defined SIZEOF_HASHVAL_T */
#endif

#if defined(SIZEOF_HASHVAL_T) && SIZEOF_HASHVAL_T == 8 && defined(ERWIN_U64)
/* User forces 64 bit hashval. */
/* Note: this is a new feature so the user can preselect a given size
 * of the hash values.  Since ERWIN_HASHVAL_64 does not have a Global
 * prefix, we cannot #define that macro in this case.  The new interface
 * is now to check the value of ERWIN_SIZEOF_HASHVAL_T. */

   /* User forces 64 bits, so ERWIN_U64 better be defined. */
   typedef ERWIN_U64                     hashval_t;
#  define HASHVAL_C(X)            ERWIN_U64_C(X)
#  ifndef hashval_t_TYPE_INFO
#  define hashval_t_TYPE_INFO    ERWIN_U64_TYPE_INFO
#  endif /* !defined hashval_t_TYPE_INFO */
#  ifndef HASHVAL_T_CMP
#  define HASHVAL_T_CMP   ERWIN_U64_CMP
#  endif /* !defined HASHVAL_T_CMP */
#  ifndef HASHVAL_T_HASH
#  define HASHVAL_T_HASH  ERWIN_U64_HASH
#  endif /* !defined HASHVAL_T_HASH */
#  define erwin_swap_hash         erwin_swap64
#  define hashval_t_hash          erwin_u64_hash

#elif defined(SIZEOF_HASHVAL_T) && SIZEOF_HASHVAL_T == 4
/* User forces 32 bit hashval. */

   typedef ERWIN_U32 hashval_t;
#  define HASHVAL_C(X)            X
#  ifndef hashval_t_TYPE_INFO
#  define hashval_t_TYPE_INFO    unsigned_TYPE_INFO
#  endif /* !defined hashval_t_TYPE_INFO */
#  ifndef HASHVAL_T_CMP
#  define HASHVAL_T_CMP   UNSIGNED_CMP
#  endif /* !defined HASHVAL_T_CMP */
#  ifndef HASHVAL_T_HASH
#  define HASHVAL_T_HASH  UNSIGNED_HASH
#  endif /* !defined HASHVAL_T_HASH */
#  define erwin_swap_hash         erwin_swap32
#  define hashval_t_hash          erwin_u32_hash

#elif defined(SIZEOF_HASHVAL_T)
#  error "The forced SIZEOF_HASHVAL_T cannot be used."
#elif SIZEOF_LONG >= 8

   typedef unsigned long hashval_t;
#  define ERWIN_HASHVAL_64               1 /*deprecated*/
#  define SIZEOF_HASHVAL_T        8
#  define HASHVAL_C(X)            ERWIN_UL(X)
#  ifndef hashval_t_TYPE_INFO
#  define hashval_t_TYPE_INFO    unsigned_long_TYPE_INFO
#  endif /* !defined hashval_t_TYPE_INFO */
#  ifndef HASHVAL_T_CMP
#  define HASHVAL_T_CMP   UNSIGNED_LONG_CMP
#  endif /* !defined HASHVAL_T_CMP */
#  ifndef HASHVAL_T_HASH
#  define HASHVAL_T_HASH  UNSIGNED_LONG_HASH
#  endif /* !defined HASHVAL_T_HASH */
#  define erwin_swap_hash         erwin_swap64
#  define hashval_t_hash          long_hash

#elif (SIZEOF_VOIDP == 8) && defined(ERWIN_U64)

   typedef ERWIN_U64                     hashval_t;
#  define ERWIN_HASHVAL_64               1 /*deprecated*/
#  define SIZEOF_HASHVAL_T        8
#  define HASHVAL_C(X)            ERWIN_U64_C(X)
#  ifndef hashval_t_TYPE_INFO
#  define hashval_t_TYPE_INFO    ERWIN_U64_TYPE_INFO
#  endif /* !defined hashval_t_TYPE_INFO */
#  ifndef HASHVAL_T_CMP
#  define HASHVAL_T_CMP   ERWIN_U64_CMP
#  endif /* !defined HASHVAL_T_CMP */
#  ifndef HASHVAL_T_HASH
#  define HASHVAL_T_HASH  ERWIN_U64_HASH
#  endif /* !defined HASHVAL_T_HASH */
#  define erwin_swap_hash         erwin_swap64
#  define hashval_t_hash          erwin_u64_hash

#else

   typedef ERWIN_U32 hashval_t;
#  define ERWIN_HASHVAL_64               0 /*deprecated*/
#  define SIZEOF_HASHVAL_T        4
#  define HASHVAL_C(X)            X
#  ifndef hashval_t_TYPE_INFO
#  define hashval_t_TYPE_INFO    unsigned_TYPE_INFO
#  endif /* !defined hashval_t_TYPE_INFO */
#  ifndef HASHVAL_T_CMP
#  define HASHVAL_T_CMP   UNSIGNED_CMP
#  endif /* !defined HASHVAL_T_CMP */
#  ifndef HASHVAL_T_HASH
#  define HASHVAL_T_HASH  UNSIGNED_HASH
#  endif /* !defined HASHVAL_T_HASH */
#  define erwin_swap_hash         erwin_swap32
#  define hashval_t_hash          erwin_u32_hash

#endif

#ifndef HASHVAL_CAST
#define HASHVAL_CAST(X) ((hashval_t)(unsigned long)(X))
#endif /* !defined HASHVAL_CAST */

/* Prototypes: */
ERWIN_WRAPPER hashval_t erwin_mulh (hashval_t, hashval_t)
    ATTR_CONST;

ERWIN_WRAPPER ERWIN_U32 erwin_mulh32 (ERWIN_U32, ERWIN_U32) ATTR_CONST;
#ifdef ERWIN_U64
ERWIN_WRAPPER ERWIN_U64 erwin_mulh64 (ERWIN_U64, ERWIN_U64) ATTR_CONST;
#endif


ERWIN_WRAPPER hashval_t erwin_golden_mul (hashval_t, hashval_t)
    ATTR_CONST;

ERWIN_WRAPPER ERWIN_U32 erwin_golden_mul32 (ERWIN_U32, ERWIN_U32) ATTR_CONST;
#ifdef ERWIN_U64
ERWIN_WRAPPER ERWIN_U64 erwin_golden_mul64 (ERWIN_U64, ERWIN_U64) ATTR_CONST;
#endif


ERWIN_WRAPPER int erwin_count_bits       (unsigned long) ATTR_CONST;
ERWIN_WRAPPER int erwin_count_bits_non0  (unsigned long) ATTR_CONST;
ERWIN_WRAPPER int erwin_trailing_0s      (unsigned long) ATTR_CONST;
ERWIN_WRAPPER int erwin_trailing_0s_non0 (unsigned long) ATTR_CONST;

ERWIN_WRAPPER int erwin_sign             (long) ATTR_CONST;
#ifdef ERWIN_S64
ERWIN_WRAPPER int erwin_sign64           (ERWIN_S64) ATTR_CONST;
#endif

ERWIN_WRAPPER int erwin_count_set_bits  (unsigned long) ATTR_CONST;

ERWIN_WRAPPER ERWIN_BOOL erwin_is_power2          (unsigned long) ATTR_CONST;
ERWIN_WRAPPER unsigned long     erwin_next_power2        (unsigned long) ATTR_CONST;
ERWIN_WRAPPER unsigned long     erwin_next_power2_minus1 (unsigned long) ATTR_CONST;
ERWIN_WRAPPER unsigned long     erwin_prev_power2        (unsigned long) ATTR_CONST;

ERWIN_WRAPPER ERWIN_U16 erwin_rol16   (ERWIN_U16, unsigned) ATTR_CONST;
ERWIN_WRAPPER ERWIN_U16 erwin_ror16   (ERWIN_U16, unsigned) ATTR_CONST;
ERWIN_WRAPPER ERWIN_U16 erwin_rol1_16 (ERWIN_U16)           ATTR_CONST;
ERWIN_WRAPPER ERWIN_U16 erwin_ror1_16 (ERWIN_U16)           ATTR_CONST;

ERWIN_WRAPPER ERWIN_U32 erwin_rol32   (ERWIN_U32, unsigned) ATTR_CONST;
ERWIN_WRAPPER ERWIN_U32 erwin_ror32   (ERWIN_U32, unsigned) ATTR_CONST;
ERWIN_WRAPPER ERWIN_U32 erwin_rol1_32 (ERWIN_U32)           ATTR_CONST;
ERWIN_WRAPPER ERWIN_U32 erwin_ror1_32 (ERWIN_U32)           ATTR_CONST;

#ifdef ERWIN_U64
ERWIN_WRAPPER ERWIN_U64 erwin_rol64   (ERWIN_U64, unsigned) ATTR_CONST;
ERWIN_WRAPPER ERWIN_U64 erwin_ror64   (ERWIN_U64, unsigned) ATTR_CONST;
ERWIN_WRAPPER ERWIN_U64 erwin_rol1_64 (ERWIN_U64)           ATTR_CONST;
ERWIN_WRAPPER ERWIN_U64 erwin_ror1_64 (ERWIN_U64)           ATTR_CONST;
#endif

ERWIN_WRAPPER hashval_t erwin_rol  (hashval_t, unsigned) ATTR_CONST;
ERWIN_WRAPPER hashval_t erwin_ror  (hashval_t, unsigned) ATTR_CONST;
ERWIN_WRAPPER hashval_t erwin_rol1 (hashval_t)           ATTR_CONST;
ERWIN_WRAPPER hashval_t erwin_ror1 (hashval_t)           ATTR_CONST;

ERWIN_WRAPPER ERWIN_U16 erwin_swap16    (ERWIN_U16 x) ATTR_CONST;
ERWIN_WRAPPER ERWIN_U32 erwin_swap32_16 (ERWIN_U32 x) ATTR_CONST;
ERWIN_WRAPPER ERWIN_U32 erwin_swap32    (ERWIN_U32 x) ATTR_CONST;

#ifdef ERWIN_U64
ERWIN_WRAPPER ERWIN_U64 erwin_swap64_32 (ERWIN_U64 x) ATTR_CONST;
ERWIN_WRAPPER ERWIN_U64 erwin_swap64_16 (ERWIN_U64 x) ATTR_CONST;
ERWIN_WRAPPER ERWIN_U64 erwin_swap64    (ERWIN_U64 x) ATTR_CONST;
#endif

ERWIN_WRAPPER hashval_t erwin_swap       (hashval_t x) ATTR_CONST;
ERWIN_WRAPPER hashval_t erwin_swap_low32 (hashval_t x) ATTR_CONST;

ERWIN_WRAPPER ERWIN_U32 erwin_bitswap32_8 (ERWIN_U32 x) ATTR_CONST;
ERWIN_WRAPPER ERWIN_U32 erwin_bitswap32   (ERWIN_U32 x) ATTR_CONST;

#ifdef ERWIN_U64
ERWIN_WRAPPER ERWIN_U64 erwin_bitswap64_8 (ERWIN_U64 x) ATTR_CONST;
ERWIN_WRAPPER ERWIN_U64 erwin_bitswap64   (ERWIN_U64 x) ATTR_CONST;
#endif

ERWIN_WRAPPER hashval_t erwin_bitswap_8 (hashval_t x) ATTR_CONST;
ERWIN_WRAPPER hashval_t erwin_bitswap   (hashval_t x) ATTR_CONST;

#ifdef erwin_mul_ok
#  ifdef __GNUC__
#    warning "Some older Erwin header was included before this.  Trying to fix."
#  endif
#  undef erwin_mul_ok
#endif
ERWIN_WRAPPER ERWIN_BOOL erwin_mul_ok(size_t a, size_t b) ATTR_CONST;

/* Note: There is currently no 64-bit variant for 32-bit machines,
 *       so the slower generic code will be used. */
#if defined(ERWIN_GNUC_I386_ASM)
#  ifdef ERWIN_COMPILING
#    include "erwin/asm_i386.h"
#  else
#    include <erwin/asm_i386.h>
#  endif
#elif defined(ERWIN_GNUC_X86_64_ASM)
#  ifdef ERWIN_COMPILING
#    include "erwin/asm_8664.h"
#  else
#    include <erwin/asm_8664.h>
#  endif
#elif defined(ERWIN_GNUC_PPC_ASM)
#  ifdef ERWIN_COMPILING
#    include "erwin/asm_ppc.h"
#  else
#    include <erwin/asm_ppc.h>
#  endif
#elif defined(ERWIN_MSVC_I386_ASM)
#  ifdef ERWIN_COMPILING
#    include "erwin/asm_msvc.h"
#  else
#    include <erwin/asm_msvc.h>
#  endif
#endif


/* Define those generically that are not defined yet: */
#ifdef ERWIN_COMPILING
#  include "erwin/asm_gen.h"
#else
#  include <erwin/asm_gen.h>
#endif


#endif
