/* -*- Mode: C -*- */
/*
 * Author: Henrik Theiling
 *
 * @@Begin: Licencing and Copying@@
 * 
 * Copyright (c) Henrik Theiling
 * Licence Version 2, Special Version for Erwin.
 * 
 * The term 'this software' used in the following, additional to its
 * usual usage, also includes the instantiated source files generated by
 * tools of this package.
 * 
 * This software is provided 'as-is', without warranty of any kind,
 * express or implied.  In no event will the authors or copyright holders
 * be held liable for any damages arising from the use of this software.
 * 
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 * 
 * 1. The origin of this software must not be misrepresented; you must
 * not claim that you wrote the original software. If you use this
 * software in a product, an acknowledgment in the product documentation
 * would be appreciated.
 * 
 * 2. Altered source versions must be plainly marked as such, and must
 * not be misrepresented as being the original software.
 * 
 * 3. You must not use any of the names of the authors or copyright
 * holders of the original software for advertising or publicity
 * pertaining to distribution without specific, written prior permission.
 * 
 * 4. If you change this software and redistribute parts or all of it in
 * any form, you must make the source code of the altered version of this
 * software available.  As an exception, files that were generated by
 * tools of this package may be used freely, including modification.
 * 
 * 5. This notice must not be removed or altered from any source
 * distribution.
 * 
 * This licence is governed by the Laws of Germany.  Disputes shall be
 * settled by Saarbruecken City Court.
 * 
 * @@End: Licencing and Copying@@
 *
 * Do not include this, it is for the implementation only!  Anything in this
 * file can and will change.
 */

#ifdef ERWIN_DEBUG_INCLUDE
#warning "Including base_i.h."
#endif

#ifndef ERWIN_BASE_I_H
#define ERWIN_BASE_I_H

#ifdef ERWIN_DEBUG_INCLUDE
#warning "First inclusion of base_i.h."
#endif

#ifdef ERWIN_COMPILING
#  include "erwin/base.h"
#else
#  include <erwin/base.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

extern ERWIN_BOOL erwin_initialised;

/* initialisers of modules */
extern void erwin_init_map (void);

#ifdef __cplusplus
}
#endif

#endif
