/* -*- Mode: C -*- */
/* Generated Tue Aug 19 15:44:10 GMT 2008
 */

#ifdef ERWIN_DEBUG_INCLUDE
#warning "Including map_board_p_node_p_d.h"
#endif

#ifndef ERWIN_MAP_BOARD_P_NODE_P_D_h
#define ERWIN_MAP_BOARD_P_NODE_P_D_h

#ifdef ERWIN_DEBUG_INCLUDE
#warning "First inclusion of map_board_p_node_p_d.h"
#endif

#include "map_u.h"
#include "map_board_p_node_p_u.h"


#ifndef HAVE_BOARD_P_CMP
#define HAVE_BOARD_P_CMP
#endif

/* Preface */
#  define MAP_BOARD_P_NODE_P_INDEX_IS_VOID 0
#  define MAP_BOARD_P_NODE_P_INDEX_IS_INT 0
#  define MAP_BOARD_P_NODE_P_INDEX_IS_CHAR 0

/* CONSTANT_ZERO */
#if MAP_BOARD_P_NODE_P_INDEX_IS_VOID
#  undef MAP_BOARD_P_NODE_P_CONSTANT_ZERO
#  define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 1
#  undef MAP_BOARD_P_NODE_P_DYN_ZERO
#elif defined(MAP_BOARD_P_NODE_P_CONSTANT_ZERO)
#  if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_CONSTANT_ZERO)
#    undef MAP_BOARD_P_NODE_P_CONSTANT_ZERO
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 1
#  else
#    undef MAP_BOARD_P_NODE_P_CONSTANT_ZERO
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 0
#  endif
#elif defined(MAP_BOARD_P_NODE_P_DYN_ZERO)
#  if !ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_DYN_ZERO)
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 1
#  else
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 0
#  endif
#elif defined(NODE_P_HAS_CONSTANT_ZERO)
#  if ERWIN_BOOL_VALUE(NODE_P_HAS_CONSTANT_ZERO)
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 1
#  else
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 0
#  endif
#elif defined(MAP_CONSTANT_ZERO)
#  if ERWIN_BOOL_VALUE(MAP_CONSTANT_ZERO)
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 1
#  else
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 0
#  endif
#elif defined(MAP_DYN_ZERO)
#  if !ERWIN_BOOL_VALUE(MAP_DYN_ZERO)
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 1
#  else
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 0
#  endif
#elif defined(ERWIN_CONSTANT_ZERO)
#  if ERWIN_BOOL_VALUE(ERWIN_CONSTANT_ZERO)
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 1
#  else
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 0
#  endif
#elif defined(ERWIN_DYN_ZERO)
#  if !ERWIN_BOOL_VALUE(ERWIN_DYN_ZERO)
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 1
#  else
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 0
#  endif
#elif defined(ALL_ERWIN_CONSTANT_ZERO)
#  if ERWIN_BOOL_VALUE(ALL_ERWIN_CONSTANT_ZERO)
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 1
#  else
#    define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 0
#  endif
#elif !defined(ALL_ERWIN_DYN_ZERO)
#  define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 0
#elif !ERWIN_BOOL_VALUE(ALL_ERWIN_DYN_ZERO)
#  define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 1
#else
#  define MAP_BOARD_P_NODE_P_CONSTANT_ZERO 0
#endif
#if !defined(MAP_BOARD_P_NODE_P_DYN_ZERO)
#elif MAP_BOARD_P_NODE_P_CONSTANT_ZERO == ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_DYN_ZERO)
#  error "Inconsistency: MAP_BOARD_P_NODE_P_CONSTANT_ZERO == MAP_BOARD_P_NODE_P_DYN_ZERO"
#endif
#if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_CONSTANT_ZERO)
#  define MAP_BOARD_P_NODE_P_DYN_ZERO 0
#else
#  define MAP_BOARD_P_NODE_P_DYN_ZERO 1
#endif

/* USE_DEFAULT_ARGS */
#if !defined(__cplusplus)
#  undef MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS
#  define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 0
#  undef MAP_BOARD_P_NODE_P_NO_DEFAULT_ARGS
#elif defined(MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS)
#  if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS)
#    undef MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 1
#  else
#    undef MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 0
#  endif
#elif defined(MAP_BOARD_P_NODE_P_NO_DEFAULT_ARGS)
#  if !ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_NO_DEFAULT_ARGS)
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 1
#  else
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 0
#  endif
#elif defined(MAP_USE_DEFAULT_ARGS)
#  if ERWIN_BOOL_VALUE(MAP_USE_DEFAULT_ARGS)
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 1
#  else
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 0
#  endif
#elif defined(MAP_NO_DEFAULT_ARGS)
#  if !ERWIN_BOOL_VALUE(MAP_NO_DEFAULT_ARGS)
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 1
#  else
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 0
#  endif
#elif defined(ERWIN_USE_DEFAULT_ARGS)
#  if ERWIN_BOOL_VALUE(ERWIN_USE_DEFAULT_ARGS)
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 1
#  else
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 0
#  endif
#elif defined(ERWIN_NO_DEFAULT_ARGS)
#  if !ERWIN_BOOL_VALUE(ERWIN_NO_DEFAULT_ARGS)
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 1
#  else
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 0
#  endif
#elif defined(ALL_ERWIN_USE_DEFAULT_ARGS)
#  if ERWIN_BOOL_VALUE(ALL_ERWIN_USE_DEFAULT_ARGS)
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 1
#  else
#    define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 0
#  endif
#elif !defined(ALL_ERWIN_NO_DEFAULT_ARGS)
#  define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 1
#elif !ERWIN_BOOL_VALUE(ALL_ERWIN_NO_DEFAULT_ARGS)
#  define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 1
#else
#  define MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS 0
#endif
#if !defined(MAP_BOARD_P_NODE_P_NO_DEFAULT_ARGS)
#elif MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS == ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_NO_DEFAULT_ARGS)
#  error "Inconsistency: MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS == MAP_BOARD_P_NODE_P_NO_DEFAULT_ARGS"
#endif
#if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS)
#  define MAP_BOARD_P_NODE_P_NO_DEFAULT_ARGS 0
#else
#  define MAP_BOARD_P_NODE_P_NO_DEFAULT_ARGS 1
#endif
#if defined(MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS) && MAP_BOARD_P_NODE_P_USE_DEFAULT_ARGS
#  define MAP_BOARD_P_NODE_P_DEFAULT_ARG(X) = X
#else
#  define MAP_BOARD_P_NODE_P_DEFAULT_ARG(X)
#endif

/* SUPER_CLASS */
#if !defined(__cplusplus)
#elif defined(MAP_BOARD_P_NODE_P_SUPER_CLASS)
#elif defined(MAP_SUPER_CLASS)
#  define MAP_BOARD_P_NODE_P_SUPER_CLASS MAP_SUPER_CLASS
#elif defined(ERWIN_SUPER_CLASS)
#  define MAP_BOARD_P_NODE_P_SUPER_CLASS ERWIN_SUPER_CLASS
#elif defined(ALL_ERWIN_SUPER_CLASS)
#  define MAP_BOARD_P_NODE_P_SUPER_CLASS ALL_ERWIN_SUPER_CLASS
#endif

/* SUPER_CLASS_ACCESS */
#if !defined(__cplusplus)
#elif defined(MAP_BOARD_P_NODE_P_SUPER_CLASS_ACCESS)
#elif defined(MAP_SUPER_CLASS_ACCESS)
#  define MAP_BOARD_P_NODE_P_SUPER_CLASS_ACCESS MAP_SUPER_CLASS_ACCESS
#elif defined(ERWIN_SUPER_CLASS_ACCESS)
#  define MAP_BOARD_P_NODE_P_SUPER_CLASS_ACCESS ERWIN_SUPER_CLASS_ACCESS
#elif defined(ALL_ERWIN_SUPER_CLASS_ACCESS)
#  define MAP_BOARD_P_NODE_P_SUPER_CLASS_ACCESS ALL_ERWIN_SUPER_CLASS_ACCESS
#else
#  define MAP_BOARD_P_NODE_P_SUPER_CLASS_ACCESS private
#endif

/* STD_MEMBERS */
#if defined(MAP_BOARD_P_NODE_P_TYPE_INFO_STD_MEMBERS)
#elif defined(map_board_p_node_p_t_TYPE_INFO_STD_MEMBERS)
#  define MAP_BOARD_P_NODE_P_TYPE_INFO_STD_MEMBERS map_board_p_node_p_t_TYPE_INFO_STD_MEMBERS
#endif
#if defined(MAP_BOARD_P_NODE_P_STD_MEMBERS)
#elif defined(MAP_STD_MEMBERS)
#  define MAP_BOARD_P_NODE_P_STD_MEMBERS(CLASS_NAME) MAP_STD_MEMBERS(CLASS_NAME)
#  define MAP_BOARD_P_NODE_P_TYPE_INFO_STD_MEMBERS MAP_TYPE_INFO_STD_MEMBERS
#elif defined(ERWIN_STD_MEMBERS)
#  define MAP_BOARD_P_NODE_P_STD_MEMBERS(CLASS_NAME) ERWIN_STD_MEMBERS(CLASS_NAME)
#  define MAP_BOARD_P_NODE_P_TYPE_INFO_STD_MEMBERS ERWIN_TYPE_INFO_STD_MEMBERS
#elif defined(ALL_ERWIN_STD_MEMBERS)
#  define MAP_BOARD_P_NODE_P_STD_MEMBERS(CLASS_NAME) ALL_ERWIN_STD_MEMBERS(CLASS_NAME)
#  define MAP_BOARD_P_NODE_P_TYPE_INFO_STD_MEMBERS ALL_ERWIN_TYPE_INFO_STD_MEMBERS
#else
#  define MAP_BOARD_P_NODE_P_STD_MEMBERS(CLASS_NAME)
#  define MAP_BOARD_P_NODE_P_TYPE_INFO_STD_MEMBERS
#endif

/* HAVE_SIG */
#if defined(MAP_BOARD_P_NODE_P_HAVE_SIG)
#  if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_HAVE_SIG)
#    undef MAP_BOARD_P_NODE_P_HAVE_SIG
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#  else
#    undef MAP_BOARD_P_NODE_P_HAVE_SIG
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#  endif
#elif defined(MAP_BOARD_P_NODE_P_NO_SIG)
#  if !ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_NO_SIG)
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#  else
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#  endif
#elif defined(MAP_BOARD_P_NODE_P_FORCE_SIG)
#  if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_FORCE_SIG)
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#  else
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#  endif
#elif defined(MAP_HAVE_SIG)
#  if ERWIN_BOOL_VALUE(MAP_HAVE_SIG)
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#  else
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#  endif
#elif defined(MAP_NO_SIG)
#  if !ERWIN_BOOL_VALUE(MAP_NO_SIG)
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#  else
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#  endif
#elif defined(MAP_FORCE_SIG)
#  if ERWIN_BOOL_VALUE(MAP_FORCE_SIG)
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#  else
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#  endif
#elif defined(ERWIN_HAVE_SIG)
#  if ERWIN_BOOL_VALUE(ERWIN_HAVE_SIG)
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#  else
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#  endif
#elif defined(ERWIN_NO_SIG)
#  if !ERWIN_BOOL_VALUE(ERWIN_NO_SIG)
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#  else
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#  endif
#elif defined(ERWIN_FORCE_SIG)
#  if ERWIN_BOOL_VALUE(ERWIN_FORCE_SIG)
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#  else
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#  endif
#elif defined(ALL_ERWIN_HAVE_SIG)
#  if ERWIN_BOOL_VALUE(ALL_ERWIN_HAVE_SIG)
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#  else
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#  endif
#elif defined(ALL_ERWIN_NO_SIG)
#  if !ERWIN_BOOL_VALUE(ALL_ERWIN_NO_SIG)
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#  else
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#  endif
#elif defined(ALL_ERWIN_FORCE_SIG)
#  if ERWIN_BOOL_VALUE(ALL_ERWIN_FORCE_SIG)
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#  else
#    define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#  endif
#elif defined(DEVEL)
#  define MAP_BOARD_P_NODE_P_HAVE_SIG 1
#else
#  define MAP_BOARD_P_NODE_P_HAVE_SIG 0
#endif
#if !defined(MAP_BOARD_P_NODE_P_NO_SIG)
#elif MAP_BOARD_P_NODE_P_HAVE_SIG == ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_NO_SIG)
#  error "Inconsistency: MAP_BOARD_P_NODE_P_HAVE_SIG == MAP_BOARD_P_NODE_P_NO_SIG"
#endif
#if !defined(MAP_BOARD_P_NODE_P_FORCE_SIG)
#elif MAP_BOARD_P_NODE_P_HAVE_SIG != ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_FORCE_SIG)
#  error "Inconsistency: MAP_BOARD_P_NODE_P_HAVE_SIG != MAP_BOARD_P_NODE_P_FORCE_SIG"
#endif
#if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_HAVE_SIG)
#  define MAP_BOARD_P_NODE_P_NO_SIG 0
#else
#  define MAP_BOARD_P_NODE_P_NO_SIG 1
#endif

/* PROFILE */
#if defined(MAP_BOARD_P_NODE_P_PROFILE)
#  if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_PROFILE)
#    undef MAP_BOARD_P_NODE_P_PROFILE
#    define MAP_BOARD_P_NODE_P_PROFILE 1
#  else
#    undef MAP_BOARD_P_NODE_P_PROFILE
#    define MAP_BOARD_P_NODE_P_PROFILE 0
#  endif
#elif defined(MAP_PROFILE)
#  if ERWIN_BOOL_VALUE(MAP_PROFILE)
#    define MAP_BOARD_P_NODE_P_PROFILE 1
#  else
#    define MAP_BOARD_P_NODE_P_PROFILE 0
#  endif
#elif defined(ERWIN_PROFILE)
#  if ERWIN_BOOL_VALUE(ERWIN_PROFILE)
#    define MAP_BOARD_P_NODE_P_PROFILE 1
#  else
#    define MAP_BOARD_P_NODE_P_PROFILE 0
#  endif
#elif !defined(ALL_ERWIN_PROFILE)
#  define MAP_BOARD_P_NODE_P_PROFILE 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_PROFILE)
#  define MAP_BOARD_P_NODE_P_PROFILE 1
#else
#  define MAP_BOARD_P_NODE_P_PROFILE 0
#endif

/* ALLOW_NULL */
#if defined(MAP_BOARD_P_NODE_P_ALLOW_NULL)
#  if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_ALLOW_NULL)
#    undef MAP_BOARD_P_NODE_P_ALLOW_NULL
#    define MAP_BOARD_P_NODE_P_ALLOW_NULL 1
#  else
#    undef MAP_BOARD_P_NODE_P_ALLOW_NULL
#    define MAP_BOARD_P_NODE_P_ALLOW_NULL 0
#  endif
#elif defined(MAP_ALLOW_NULL)
#  if ERWIN_BOOL_VALUE(MAP_ALLOW_NULL)
#    define MAP_BOARD_P_NODE_P_ALLOW_NULL 1
#  else
#    define MAP_BOARD_P_NODE_P_ALLOW_NULL 0
#  endif
#elif defined(ERWIN_ALLOW_NULL)
#  if ERWIN_BOOL_VALUE(ERWIN_ALLOW_NULL)
#    define MAP_BOARD_P_NODE_P_ALLOW_NULL 1
#  else
#    define MAP_BOARD_P_NODE_P_ALLOW_NULL 0
#  endif
#elif !defined(ALL_ERWIN_ALLOW_NULL)
#  define MAP_BOARD_P_NODE_P_ALLOW_NULL 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_ALLOW_NULL)
#  define MAP_BOARD_P_NODE_P_ALLOW_NULL 1
#else
#  define MAP_BOARD_P_NODE_P_ALLOW_NULL 0
#endif

/* DIRECT_RECURSION */
#if !defined(__cplusplus)
#elif defined(MAP_BOARD_P_NODE_P_DIRECT_RECURSION)
#  if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_DIRECT_RECURSION)
#    undef MAP_BOARD_P_NODE_P_DIRECT_RECURSION
#    define MAP_BOARD_P_NODE_P_DIRECT_RECURSION 1
#  else
#    undef MAP_BOARD_P_NODE_P_DIRECT_RECURSION
#    define MAP_BOARD_P_NODE_P_DIRECT_RECURSION 0
#  endif
#elif defined(MAP_DIRECT_RECURSION)
#  if ERWIN_BOOL_VALUE(MAP_DIRECT_RECURSION)
#    define MAP_BOARD_P_NODE_P_DIRECT_RECURSION 1
#  else
#    define MAP_BOARD_P_NODE_P_DIRECT_RECURSION 0
#  endif
#elif defined(ERWIN_DIRECT_RECURSION)
#  if ERWIN_BOOL_VALUE(ERWIN_DIRECT_RECURSION)
#    define MAP_BOARD_P_NODE_P_DIRECT_RECURSION 1
#  else
#    define MAP_BOARD_P_NODE_P_DIRECT_RECURSION 0
#  endif
#elif !defined(ALL_ERWIN_DIRECT_RECURSION)
#  define MAP_BOARD_P_NODE_P_DIRECT_RECURSION 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_DIRECT_RECURSION)
#  define MAP_BOARD_P_NODE_P_DIRECT_RECURSION 1
#else
#  define MAP_BOARD_P_NODE_P_DIRECT_RECURSION 0
#endif

/* HAVE_INT_CONSTRUCTOR */
#if defined(__cplusplus)
#  if MAP_BOARD_P_NODE_P_DYN_ZERO && MAP_BOARD_P_NODE_P_INDEX_IS_INT
#    undef MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR
#    define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 0
#    undef MAP_BOARD_P_NODE_P_NO_INT_CONSTRUCTOR
#  elif defined(MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR)
#    if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR)
#      undef MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 1
#    else
#      undef MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif defined(MAP_BOARD_P_NODE_P_NO_INT_CONSTRUCTOR)
#    if !ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_NO_INT_CONSTRUCTOR)
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 1
#    else
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif defined(MAP_HAVE_INT_CONSTRUCTOR)
#    if ERWIN_BOOL_VALUE(MAP_HAVE_INT_CONSTRUCTOR)
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 1
#    else
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif defined(MAP_NO_INT_CONSTRUCTOR)
#    if !ERWIN_BOOL_VALUE(MAP_NO_INT_CONSTRUCTOR)
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 1
#    else
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif defined(ERWIN_HAVE_INT_CONSTRUCTOR)
#    if ERWIN_BOOL_VALUE(ERWIN_HAVE_INT_CONSTRUCTOR)
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 1
#    else
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif defined(ERWIN_NO_INT_CONSTRUCTOR)
#    if !ERWIN_BOOL_VALUE(ERWIN_NO_INT_CONSTRUCTOR)
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 1
#    else
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif defined(ALL_ERWIN_HAVE_INT_CONSTRUCTOR)
#    if ERWIN_BOOL_VALUE(ALL_ERWIN_HAVE_INT_CONSTRUCTOR)
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 1
#    else
#      define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif !defined(ALL_ERWIN_NO_INT_CONSTRUCTOR)
#    define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 1
#  elif !ERWIN_BOOL_VALUE(ALL_ERWIN_NO_INT_CONSTRUCTOR)
#    define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 1
#  else
#    define MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR 0
#  endif
#  if !defined(MAP_BOARD_P_NODE_P_NO_INT_CONSTRUCTOR)
#  elif MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR == ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_NO_INT_CONSTRUCTOR)
#    error "Inconsistency: MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR == MAP_BOARD_P_NODE_P_NO_INT_CONSTRUCTOR"
#  endif
#  if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_HAVE_INT_CONSTRUCTOR)
#    define MAP_BOARD_P_NODE_P_NO_INT_CONSTRUCTOR 0
#  else
#    define MAP_BOARD_P_NODE_P_NO_INT_CONSTRUCTOR 1
#  endif
#endif

/* MANY_CASTS */
#if !defined(__cplusplus)
#  undef MAP_BOARD_P_NODE_P_MANY_CASTS
#  define MAP_BOARD_P_NODE_P_MANY_CASTS 0
#elif defined(MAP_BOARD_P_NODE_P_MANY_CASTS)
#  if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_MANY_CASTS)
#    undef MAP_BOARD_P_NODE_P_MANY_CASTS
#    define MAP_BOARD_P_NODE_P_MANY_CASTS 1
#  else
#    undef MAP_BOARD_P_NODE_P_MANY_CASTS
#    define MAP_BOARD_P_NODE_P_MANY_CASTS 0
#  endif
#elif defined(MAP_MANY_CASTS)
#  if ERWIN_BOOL_VALUE(MAP_MANY_CASTS)
#    define MAP_BOARD_P_NODE_P_MANY_CASTS 1
#  else
#    define MAP_BOARD_P_NODE_P_MANY_CASTS 0
#  endif
#elif defined(ERWIN_MANY_CASTS)
#  if ERWIN_BOOL_VALUE(ERWIN_MANY_CASTS)
#    define MAP_BOARD_P_NODE_P_MANY_CASTS 1
#  else
#    define MAP_BOARD_P_NODE_P_MANY_CASTS 0
#  endif
#elif !defined(ALL_ERWIN_MANY_CASTS)
#  define MAP_BOARD_P_NODE_P_MANY_CASTS 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_MANY_CASTS)
#  define MAP_BOARD_P_NODE_P_MANY_CASTS 1
#else
#  define MAP_BOARD_P_NODE_P_MANY_CASTS 0
#endif
#if defined(MAP_BOARD_P_NODE_P_MANY_CASTS) && MAP_BOARD_P_NODE_P_MANY_CASTS
#  define MAP_BOARD_P_NODE_P_DEFAULT_ARG_MANY(X) MAP_BOARD_P_NODE_P_DEFAULT_ARG(X)
#else
#  define MAP_BOARD_P_NODE_P_DEFAULT_ARG_MANY(X)
#endif

/* # */
#ifdef MAP_BOARD_P_NODE_P_IMPLEMENTATION


#define BOARD_P_HASH board_hash
#define BOARD_P_CMP board_cmp

#ifdef ERWIN_COMPILING
#  include "erwin/defaults.h"
#  include "erwin/forwards.h"
#else
#  include <erwin/defaults.h>
#  include <erwin/forwards.h>
#endif

/* NOMEM_IS_FATAL */
#if defined(MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL)
#  if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL)
#    undef MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL
#    define MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL 1
#  else
#    undef MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL
#    define MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL 0
#  endif
#elif defined(MAP_NOMEM_IS_FATAL)
#  if ERWIN_BOOL_VALUE(MAP_NOMEM_IS_FATAL)
#    define MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL 1
#  else
#    define MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL 0
#  endif
#elif defined(ERWIN_NOMEM_IS_FATAL)
#  if ERWIN_BOOL_VALUE(ERWIN_NOMEM_IS_FATAL)
#    define MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL 1
#  else
#    define MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL 0
#  endif
#elif !defined(ALL_ERWIN_NOMEM_IS_FATAL)
#  define MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_NOMEM_IS_FATAL)
#  define MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL 1
#else
#  define MAP_BOARD_P_NODE_P_NOMEM_IS_FATAL 0
#endif

/* ASSERTION_FAILED_HANDLER */
#if defined(MAP_BOARD_P_NODE_P_ASSERTION_FAILED_HANDLER)
#elif defined(MAP_ASSERTION_FAILED_HANDLER)
#  define MAP_BOARD_P_NODE_P_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK) MAP_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK)
#elif defined(ERWIN_ASSERTION_FAILED_HANDLER)
#  define MAP_BOARD_P_NODE_P_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK) ERWIN_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK)
#elif defined(ALL_ERWIN_ASSERTION_FAILED_HANDLER)
#  define MAP_BOARD_P_NODE_P_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK) ALL_ERWIN_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK)
#else
#  define MAP_BOARD_P_NODE_P_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK) ERWIN_DEFAULT_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK)
#endif

/* OPTIMISE_SIZE */
#if defined(MAP_BOARD_P_NODE_P_OPTIMISE_SIZE)
#  if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_OPTIMISE_SIZE)
#    undef MAP_BOARD_P_NODE_P_OPTIMISE_SIZE
#    define MAP_BOARD_P_NODE_P_OPTIMISE_SIZE 1
#  else
#    undef MAP_BOARD_P_NODE_P_OPTIMISE_SIZE
#    define MAP_BOARD_P_NODE_P_OPTIMISE_SIZE 0
#  endif
#elif defined(MAP_OPTIMISE_SIZE)
#  if ERWIN_BOOL_VALUE(MAP_OPTIMISE_SIZE)
#    define MAP_BOARD_P_NODE_P_OPTIMISE_SIZE 1
#  else
#    define MAP_BOARD_P_NODE_P_OPTIMISE_SIZE 0
#  endif
#elif defined(ERWIN_OPTIMISE_SIZE)
#  if ERWIN_BOOL_VALUE(ERWIN_OPTIMISE_SIZE)
#    define MAP_BOARD_P_NODE_P_OPTIMISE_SIZE 1
#  else
#    define MAP_BOARD_P_NODE_P_OPTIMISE_SIZE 0
#  endif
#elif !defined(ALL_ERWIN_OPTIMISE_SIZE)
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_OPTIMISE_SIZE)
#  define MAP_BOARD_P_NODE_P_OPTIMISE_SIZE 1
#else
#  define MAP_BOARD_P_NODE_P_OPTIMISE_SIZE 0
#endif

/* SPLIT */
#if defined(MAP_BOARD_P_NODE_P_SPLIT)
#  if ERWIN_BOOL_VALUE(MAP_BOARD_P_NODE_P_SPLIT)
#    undef MAP_BOARD_P_NODE_P_SPLIT
#    define MAP_BOARD_P_NODE_P_SPLIT 1
#  else
#    undef MAP_BOARD_P_NODE_P_SPLIT
#    define MAP_BOARD_P_NODE_P_SPLIT 0
#  endif
#elif defined(MAP_SPLIT)
#  if ERWIN_BOOL_VALUE(MAP_SPLIT)
#    define MAP_BOARD_P_NODE_P_SPLIT 1
#  else
#    define MAP_BOARD_P_NODE_P_SPLIT 0
#  endif
#elif defined(ERWIN_SPLIT)
#  if ERWIN_BOOL_VALUE(ERWIN_SPLIT)
#    define MAP_BOARD_P_NODE_P_SPLIT 1
#  else
#    define MAP_BOARD_P_NODE_P_SPLIT 0
#  endif
#elif !defined(ALL_ERWIN_SPLIT)
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_SPLIT)
#  define MAP_BOARD_P_NODE_P_SPLIT 1
#else
#  define MAP_BOARD_P_NODE_P_SPLIT 0
#endif

/* INITIAL_SIZE */
#if defined(MAP_BOARD_P_NODE_P_INITIAL_SIZE)
#elif defined(MAP_INITIAL_SIZE)
#  define MAP_BOARD_P_NODE_P_INITIAL_SIZE MAP_INITIAL_SIZE
#elif defined(ERWIN_INITIAL_SIZE)
#  define MAP_BOARD_P_NODE_P_INITIAL_SIZE ERWIN_INITIAL_SIZE
#elif defined(ALL_ERWIN_INITIAL_SIZE)
#  define MAP_BOARD_P_NODE_P_INITIAL_SIZE ALL_ERWIN_INITIAL_SIZE
#else
#  define MAP_BOARD_P_NODE_P_INITIAL_SIZE 4
#endif

/* MINIMAL_SIZE */
#if defined(MAP_BOARD_P_NODE_P_MINIMAL_SIZE)
#elif defined(MAP_MINIMAL_SIZE)
#  define MAP_BOARD_P_NODE_P_MINIMAL_SIZE MAP_MINIMAL_SIZE
#elif defined(ERWIN_MINIMAL_SIZE)
#  define MAP_BOARD_P_NODE_P_MINIMAL_SIZE ERWIN_MINIMAL_SIZE
#elif defined(ALL_ERWIN_MINIMAL_SIZE)
#  define MAP_BOARD_P_NODE_P_MINIMAL_SIZE ALL_ERWIN_MINIMAL_SIZE
#else
#  define MAP_BOARD_P_NODE_P_MINIMAL_SIZE 4
#endif

/* TRIGGER_DENOMINATOR */
#if defined(MAP_BOARD_P_NODE_P_TRIGGER_DENOMINATOR)
#elif defined(MAP_TRIGGER_DENOMINATOR)
#  define MAP_BOARD_P_NODE_P_TRIGGER_DENOMINATOR MAP_TRIGGER_DENOMINATOR
#elif defined(ERWIN_TRIGGER_DENOMINATOR)
#  define MAP_BOARD_P_NODE_P_TRIGGER_DENOMINATOR ERWIN_TRIGGER_DENOMINATOR
#elif defined(ALL_ERWIN_TRIGGER_DENOMINATOR)
#  define MAP_BOARD_P_NODE_P_TRIGGER_DENOMINATOR ALL_ERWIN_TRIGGER_DENOMINATOR
#else
#  define MAP_BOARD_P_NODE_P_TRIGGER_DENOMINATOR 5
#endif

/* TRIGGER_NUMERATOR */
#if defined(MAP_BOARD_P_NODE_P_TRIGGER_NUMERATOR)
#elif defined(MAP_TRIGGER_NUMERATOR)
#  define MAP_BOARD_P_NODE_P_TRIGGER_NUMERATOR MAP_TRIGGER_NUMERATOR
#elif defined(ERWIN_TRIGGER_NUMERATOR)
#  define MAP_BOARD_P_NODE_P_TRIGGER_NUMERATOR ERWIN_TRIGGER_NUMERATOR
#elif defined(ALL_ERWIN_TRIGGER_NUMERATOR)
#  define MAP_BOARD_P_NODE_P_TRIGGER_NUMERATOR ALL_ERWIN_TRIGGER_NUMERATOR
#else
#  define MAP_BOARD_P_NODE_P_TRIGGER_NUMERATOR 4
#endif

/* PLAIN_LIST_LENGTH */
#if defined(MAP_BOARD_P_NODE_P_PLAIN_LIST_LENGTH)
#elif defined(MAP_PLAIN_LIST_LENGTH)
#  define MAP_BOARD_P_NODE_P_PLAIN_LIST_LENGTH MAP_PLAIN_LIST_LENGTH
#elif defined(ERWIN_PLAIN_LIST_LENGTH)
#  define MAP_BOARD_P_NODE_P_PLAIN_LIST_LENGTH ERWIN_PLAIN_LIST_LENGTH
#elif defined(ALL_ERWIN_PLAIN_LIST_LENGTH)
#  define MAP_BOARD_P_NODE_P_PLAIN_LIST_LENGTH ALL_ERWIN_PLAIN_LIST_LENGTH
#elif !defined(MAP_BOARD_P_NODE_P_TRIGGER_NUMERATOR)
#elif defined(MAP_BOARD_P_NODE_P_TRIGGER_DENOMINATOR)
#  define MAP_BOARD_P_NODE_P_PLAIN_LIST_LENGTH (5 * (MAP_BOARD_P_NODE_P_TRIGGER_NUMERATOR)) / (MAP_BOARD_P_NODE_P_TRIGGER_DENOMINATOR)
#endif

/* HASH_RAW */
#if defined(BOARD_P_HASH_RAW)
#elif defined(BOARD_P_HASHVAL)
#  define BOARD_P_HASH_RAW(X) BOARD_P_HASHVAL(X)
#else
#  define BOARD_P_HASH_RAW(X) ERWIN_DEFAULT_HASH_RAW(X)
#endif

/* HASH_RAW */
#if defined(NODE_P_HASH_RAW)
#elif defined(NODE_P_HASHVAL)
#  define NODE_P_HASH_RAW(X) NODE_P_HASHVAL(X)
#endif

/* HASH */
#if defined(BOARD_P_HASH)
#elif defined(BOARD_P_HASH_RAW)
#  define BOARD_P_HASH(X) hashval_t_hash((BOARD_P_HASH_RAW(X)))
#endif

/* HASH */
#if defined(NODE_P_HASH)
#elif MAP_BOARD_P_NODE_P_INDEX_IS_VOID
#  define NODE_P_HASH(X) ERWIN_HASH_INIT8
#elif defined(NODE_P_HASH_RAW)
#  define NODE_P_HASH(X) hashval_t_hash((NODE_P_HASH_RAW(X)))
#endif

/* CMP */
#if defined(BOARD_P_CMP_PROVIDED)
#elif defined(BOARD_P_CMP)
#  define BOARD_P_CMP_PROVIDED 1
#else
#  define BOARD_P_CMP_PROVIDED 0
#endif
#if defined(BOARD_P_CMP)
#elif BOARD_P_CMP_PROVIDED
#  error "Inconsistency: BOARD_P_CMP_PROVIDED is true but BOARD_P_CMP is undefined."
#endif

/* CMP */
#if defined(NODE_P_CMP_PROVIDED)
#elif MAP_BOARD_P_NODE_P_INDEX_IS_VOID
#  define NODE_P_CMP_PROVIDED 0
#  undef NODE_P_CMP
#  define NODE_P_CMP(A,B) 0
#elif defined(NODE_P_CMP)
#  define NODE_P_CMP_PROVIDED 1
#else
#  define NODE_P_CMP_PROVIDED 0
#endif
#if defined(NODE_P_CMP)
#elif NODE_P_CMP_PROVIDED
#  error "Inconsistency: NODE_P_CMP_PROVIDED is true but NODE_P_CMP is undefined."
#endif

/* DETCMP */
#if defined(BOARD_P_DETCMP_PROVIDED)
#elif defined(BOARD_P_DETCMP)
#  define BOARD_P_DETCMP_PROVIDED 1
#else
#  if defined(BOARD_P_CMP)
#    define BOARD_P_DETCMP(A,B) BOARD_P_CMP(A,B)
#  endif
#  define BOARD_P_DETCMP_PROVIDED 0
#endif
#if defined(BOARD_P_DETCMP)
#elif BOARD_P_DETCMP_PROVIDED
#  error "Inconsistency: BOARD_P_DETCMP_PROVIDED is true but BOARD_P_DETCMP is undefined."
#endif
#if defined(BOARD_P_DETCMP)
#elif !defined(ERWIN_REQUIRE_DETERMINISM)
#elif !defined(ERWIN_WEAK_DETERMINISM)
#  error "Need BOARD_P_DETCMP or BOARD_P_CMP when enforcing determinism. Try to #define BOARD_P_DETCMP(x,y) false_if_reached_pk(BOARD_P_DETCMP) if you think you never invoke it."
#endif

/* DETCMP */
#if defined(NODE_P_DETCMP_PROVIDED)
#elif MAP_BOARD_P_NODE_P_INDEX_IS_VOID
#  define NODE_P_DETCMP_PROVIDED 0
#  undef NODE_P_DETCMP
#  define NODE_P_DETCMP(A,B) 0
#elif defined(NODE_P_DETCMP)
#  define NODE_P_DETCMP_PROVIDED 1
#else
#  if defined(NODE_P_CMP)
#    define NODE_P_DETCMP(A,B) NODE_P_CMP(A,B)
#  endif
#  define NODE_P_DETCMP_PROVIDED 0
#endif
#if defined(NODE_P_DETCMP)
#elif NODE_P_DETCMP_PROVIDED
#  error "Inconsistency: NODE_P_DETCMP_PROVIDED is true but NODE_P_DETCMP is undefined."
#endif
#if defined(NODE_P_DETCMP)
#elif !defined(ERWIN_REQUIRE_DETERMINISM)
#elif !defined(ERWIN_WEAK_DETERMINISM)
#  error "Need NODE_P_DETCMP or NODE_P_CMP when enforcing determinism. Try to #define NODE_P_DETCMP(x,y) false_if_reached_pk(NODE_P_DETCMP) if you think you never invoke it."
#endif

/* EQUAL */
#if defined(BOARD_P_EQUAL_PROVIDED)
#elif defined(BOARD_P_EQUAL)
#  define BOARD_P_EQUAL_PROVIDED 1
#else
#  if !BOARD_P_CMP_PROVIDED
#    define BOARD_P_EQUAL(A,B) (A) == (B)
#  elif defined(BOARD_P_CMP)
#    define BOARD_P_EQUAL(A,B) (BOARD_P_CMP(A,B)) == 0
#  endif
#  define BOARD_P_EQUAL_PROVIDED 0
#endif
#if defined(BOARD_P_EQUAL)
#elif BOARD_P_EQUAL_PROVIDED
#  error "Inconsistency: BOARD_P_EQUAL_PROVIDED is true but BOARD_P_EQUAL is undefined."
#endif

/* EQUAL */

/* ICOPY */
#if defined(BOARD_P_ICOPY_PROVIDED)
#elif defined(BOARD_P_ICOPY)
#  define BOARD_P_ICOPY_PROVIDED 1
#elif defined(BOARD_P_COPY)
#  define BOARD_P_ICOPY_PROVIDED 1
#  define BOARD_P_ICOPY(TO_BE_COPIED,ERR_P) BOARD_P_COPY(TO_BE_COPIED,ERR_P)
#else
#  define BOARD_P_ICOPY(TO_BE_COPIED,ERR_P) TO_BE_COPIED
#  define BOARD_P_ICOPY_PROVIDED 0
#endif
#if defined(BOARD_P_ICOPY)
#elif BOARD_P_ICOPY_PROVIDED
#  error "Inconsistency: BOARD_P_ICOPY_PROVIDED is true but BOARD_P_ICOPY is undefined."
#endif

/* IFREE */
#if defined(BOARD_P_IFREE_PROVIDED)
#elif defined(BOARD_P_IFREE)
#  define BOARD_P_IFREE_PROVIDED 1
#elif defined(BOARD_P_FREE)
#  define BOARD_P_IFREE_PROVIDED 1
#  define BOARD_P_IFREE(TO_BE_DESTROYED) BOARD_P_FREE(TO_BE_DESTROYED)
#else
#  define BOARD_P_IFREE(TO_BE_DESTROYED)
#  define BOARD_P_IFREE_PROVIDED 0
#endif
#if defined(BOARD_P_IFREE)
#elif BOARD_P_IFREE_PROVIDED
#  error "Inconsistency: BOARD_P_IFREE_PROVIDED is true but BOARD_P_IFREE is undefined."
#endif

/* ZERO */
#if !defined(BOARD_P_ZERO)
#  define BOARD_P_ZERO (Board * )0
#endif

/* OCOPY */
#if defined(NODE_P_OCOPY_PROVIDED)
#elif MAP_BOARD_P_NODE_P_INDEX_IS_VOID
#  define NODE_P_OCOPY_PROVIDED 0
#  undef NODE_P_OCOPY
#  define NODE_P_OCOPY(TO_BE_COPIED,ERR_P) TO_BE_COPIED
#  undef NODE_P_COPY
#elif defined(NODE_P_OCOPY)
#  define NODE_P_OCOPY_PROVIDED 1
#elif defined(NODE_P_COPY)
#  define NODE_P_OCOPY_PROVIDED 1
#  define NODE_P_OCOPY(TO_BE_COPIED,ERR_P) NODE_P_COPY(TO_BE_COPIED,ERR_P)
#else
#  define NODE_P_OCOPY(TO_BE_COPIED,ERR_P) TO_BE_COPIED
#  define NODE_P_OCOPY_PROVIDED 0
#endif
#if defined(NODE_P_OCOPY)
#elif NODE_P_OCOPY_PROVIDED
#  error "Inconsistency: NODE_P_OCOPY_PROVIDED is true but NODE_P_OCOPY is undefined."
#endif

/* OFREE */
#if defined(NODE_P_OFREE_PROVIDED)
#elif MAP_BOARD_P_NODE_P_INDEX_IS_VOID
#  define NODE_P_OFREE_PROVIDED 0
#  undef NODE_P_OFREE
#  define NODE_P_OFREE(TO_BE_DESTROYED)
#  undef NODE_P_FREE
#elif defined(NODE_P_OFREE)
#  define NODE_P_OFREE_PROVIDED 1
#elif defined(NODE_P_FREE)
#  define NODE_P_OFREE_PROVIDED 1
#  define NODE_P_OFREE(TO_BE_DESTROYED) NODE_P_FREE(TO_BE_DESTROYED)
#else
#  define NODE_P_OFREE(TO_BE_DESTROYED)
#  define NODE_P_OFREE_PROVIDED 0
#endif
#if defined(NODE_P_OFREE)
#elif NODE_P_OFREE_PROVIDED
#  error "Inconsistency: NODE_P_OFREE_PROVIDED is true but NODE_P_OFREE is undefined."
#endif

/* ZERO */
#if defined(NODE_P_ZERO)
#elif MAP_BOARD_P_NODE_P_INDEX_IS_VOID
#  define NODE_P_ZERO (Node * )0
#else
#  define NODE_P_ZERO (Node * )0
#endif

/* ENSURE_VALUE */
#if defined(MAP_BOARD_P_NODE_P_ENSURE_VALUE)
#elif defined(NODE_P_ENSURE_VALUE)
#  define MAP_BOARD_P_NODE_P_ENSURE_VALUE(SELF,KEY,COPY_ERR) NODE_P_ENSURE_VALUE(COPY_ERR)
#elif defined(MAP_ENSURE_VALUE)
#  define MAP_BOARD_P_NODE_P_ENSURE_VALUE(SELF,KEY,COPY_ERR) MAP_ENSURE_VALUE(SELF,KEY,COPY_ERR)
#elif defined(ERWIN_ENSURE_VALUE)
#  define MAP_BOARD_P_NODE_P_ENSURE_VALUE(SELF,KEY,COPY_ERR) ERWIN_ENSURE_VALUE(SELF,KEY,COPY_ERR)
#elif defined(ALL_ERWIN_ENSURE_VALUE)
#  define MAP_BOARD_P_NODE_P_ENSURE_VALUE(SELF,KEY,COPY_ERR) ALL_ERWIN_ENSURE_VALUE(SELF,KEY,COPY_ERR)
#elif defined(NODE_P_OCOPY)
#  define MAP_BOARD_P_NODE_P_ENSURE_VALUE(SELF,KEY,COPY_ERR) NODE_P_OCOPY((ZERO(SELF)),COPY_ERR)
#endif

#endif /* MAP_BOARD_P_NODE_P_IMPLEMENTATION */
#endif /* !defined(ERWIN_MAP_BOARD_P_NODE_P_D_h) */
