
#ifndef ERWIN_MAP_INT_RGBCOLOUR_P_f_h
#define ERWIN_MAP_INT_RGBCOLOUR_P_f_h

struct map_int_rgbcolour_p_t;
#ifndef __cplusplus
typedef struct map_int_rgbcolour_p_t map_int_rgbcolour_p_t;
#endif
typedef struct map_int_rgbcolour_p_t MapIntRgbcolourP;

typedef map_int_rgbcolour_p_t *map_int_rgbcolour_p_t_p;

typedef map_int_rgbcolour_p_t const *map_int_rgbcolour_p_t_const_p;

#define MAP_INT_RGBCOLOUR_P_SIG 1711612181



#ifdef MAP_INT_RGBCOLOUR_P_TP_DEEP
#  if MAP_INT_RGBCOLOUR_P_TP_DEEP
#    ifndef MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY
#      define MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY 1
#    endif
#    ifndef MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE
#      define MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY
#      define MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY 0
#    endif
#    ifndef MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE
#      define MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY
#define MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY 0
#endif /* !defined MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY */

#ifndef MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE
#define MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE 0
#endif /* !defined MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE */

#ifdef MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP
#  if MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP
#    ifndef MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COPY
#      define MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COPY 1
#    endif
#    ifndef MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COMPARE
#      define MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COPY
#      define MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COPY 0
#    endif
#    ifndef MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COMPARE
#      define MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COPY
#define MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COPY 0
#endif /* !defined MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COPY */

#ifndef MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COMPARE
#define MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COMPARE 0
#endif /* !defined MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COMPARE */

#ifdef CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP
#  if CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP
#    ifndef CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY
#      define CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY 1
#    endif
#    ifndef CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE
#      define CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY
#      define CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY 0
#    endif
#    ifndef CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE
#      define CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY
#define CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY 0
#endif /* !defined CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY */

#ifndef CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE
#define CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE 0
#endif /* !defined CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE */

#ifdef MAPINTRGBCOLOURPP_DEEP
#  if MAPINTRGBCOLOURPP_DEEP
#    ifndef MAPINTRGBCOLOURPP_DEEP_COPY
#      define MAPINTRGBCOLOURPP_DEEP_COPY 1
#    endif
#    ifndef MAPINTRGBCOLOURPP_DEEP_COMPARE
#      define MAPINTRGBCOLOURPP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAPINTRGBCOLOURPP_DEEP_COPY
#      define MAPINTRGBCOLOURPP_DEEP_COPY 0
#    endif
#    ifndef MAPINTRGBCOLOURPP_DEEP_COMPARE
#      define MAPINTRGBCOLOURPP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAPINTRGBCOLOURPP_DEEP_COPY
#define MAPINTRGBCOLOURPP_DEEP_COPY 0
#endif /* !defined MAPINTRGBCOLOURPP_DEEP_COPY */

#ifndef MAPINTRGBCOLOURPP_DEEP_COMPARE
#define MAPINTRGBCOLOURPP_DEEP_COMPARE 0
#endif /* !defined MAPINTRGBCOLOURPP_DEEP_COMPARE */

#ifdef MAPINTRGBCOLOURP_CONSTP_DEEP
#  if MAPINTRGBCOLOURP_CONSTP_DEEP
#    ifndef MAPINTRGBCOLOURP_CONSTP_DEEP_COPY
#      define MAPINTRGBCOLOURP_CONSTP_DEEP_COPY 1
#    endif
#    ifndef MAPINTRGBCOLOURP_CONSTP_DEEP_COMPARE
#      define MAPINTRGBCOLOURP_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAPINTRGBCOLOURP_CONSTP_DEEP_COPY
#      define MAPINTRGBCOLOURP_CONSTP_DEEP_COPY 0
#    endif
#    ifndef MAPINTRGBCOLOURP_CONSTP_DEEP_COMPARE
#      define MAPINTRGBCOLOURP_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAPINTRGBCOLOURP_CONSTP_DEEP_COPY
#define MAPINTRGBCOLOURP_CONSTP_DEEP_COPY 0
#endif /* !defined MAPINTRGBCOLOURP_CONSTP_DEEP_COPY */

#ifndef MAPINTRGBCOLOURP_CONSTP_DEEP_COMPARE
#define MAPINTRGBCOLOURP_CONSTP_DEEP_COMPARE 0
#endif /* !defined MAPINTRGBCOLOURP_CONSTP_DEEP_COMPARE */

#ifdef CONST_MAPINTRGBCOLOURPP_DEEP
#  if CONST_MAPINTRGBCOLOURPP_DEEP
#    ifndef CONST_MAPINTRGBCOLOURPP_DEEP_COPY
#      define CONST_MAPINTRGBCOLOURPP_DEEP_COPY 1
#    endif
#    ifndef CONST_MAPINTRGBCOLOURPP_DEEP_COMPARE
#      define CONST_MAPINTRGBCOLOURPP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef CONST_MAPINTRGBCOLOURPP_DEEP_COPY
#      define CONST_MAPINTRGBCOLOURPP_DEEP_COPY 0
#    endif
#    ifndef CONST_MAPINTRGBCOLOURPP_DEEP_COMPARE
#      define CONST_MAPINTRGBCOLOURPP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef CONST_MAPINTRGBCOLOURPP_DEEP_COPY
#define CONST_MAPINTRGBCOLOURPP_DEEP_COPY 0
#endif /* !defined CONST_MAPINTRGBCOLOURPP_DEEP_COPY */

#ifndef CONST_MAPINTRGBCOLOURPP_DEEP_COMPARE
#define CONST_MAPINTRGBCOLOURPP_DEEP_COMPARE 0
#endif /* !defined CONST_MAPINTRGBCOLOURPP_DEEP_COMPARE */

#ifdef MAP_INT_RGBCOLOUR_P_T_P_DEEP
#  if MAP_INT_RGBCOLOUR_P_T_P_DEEP
#    ifndef MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY
#      define MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY 1
#    endif
#    ifndef MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE
#      define MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY
#      define MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY 0
#    endif
#    ifndef MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE
#      define MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY
#define MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY 0
#endif /* !defined MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY */

#ifndef MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE
#define MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE 0
#endif /* !defined MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE */

#ifdef MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP
#  if MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP
#    ifndef MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COPY
#      define MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COPY 1
#    endif
#    ifndef MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COMPARE
#      define MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COPY
#      define MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COPY 0
#    endif
#    ifndef MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COMPARE
#      define MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COPY
#define MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COPY 0
#endif /* !defined MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COPY */

#ifndef MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COMPARE
#define MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COMPARE 0
#endif /* !defined MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COMPARE */

#ifdef CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP
#  if CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP
#    ifndef CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY
#      define CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY 1
#    endif
#    ifndef CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE
#      define CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY
#      define CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY 0
#    endif
#    ifndef CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE
#      define CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY
#define CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY 0
#endif /* !defined CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY */

#ifndef CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE
#define CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE 0
#endif /* !defined CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE */

#ifdef MAPINTRGBCOLOURP_P_DEEP
#  if MAPINTRGBCOLOURP_P_DEEP
#    ifndef MAPINTRGBCOLOURP_P_DEEP_COPY
#      define MAPINTRGBCOLOURP_P_DEEP_COPY 1
#    endif
#    ifndef MAPINTRGBCOLOURP_P_DEEP_COMPARE
#      define MAPINTRGBCOLOURP_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAPINTRGBCOLOURP_P_DEEP_COPY
#      define MAPINTRGBCOLOURP_P_DEEP_COPY 0
#    endif
#    ifndef MAPINTRGBCOLOURP_P_DEEP_COMPARE
#      define MAPINTRGBCOLOURP_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAPINTRGBCOLOURP_P_DEEP_COPY
#define MAPINTRGBCOLOURP_P_DEEP_COPY 0
#endif /* !defined MAPINTRGBCOLOURP_P_DEEP_COPY */

#ifndef MAPINTRGBCOLOURP_P_DEEP_COMPARE
#define MAPINTRGBCOLOURP_P_DEEP_COMPARE 0
#endif /* !defined MAPINTRGBCOLOURP_P_DEEP_COMPARE */

#ifdef MAPINTRGBCOLOURP_CONST_P_DEEP
#  if MAPINTRGBCOLOURP_CONST_P_DEEP
#    ifndef MAPINTRGBCOLOURP_CONST_P_DEEP_COPY
#      define MAPINTRGBCOLOURP_CONST_P_DEEP_COPY 1
#    endif
#    ifndef MAPINTRGBCOLOURP_CONST_P_DEEP_COMPARE
#      define MAPINTRGBCOLOURP_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAPINTRGBCOLOURP_CONST_P_DEEP_COPY
#      define MAPINTRGBCOLOURP_CONST_P_DEEP_COPY 0
#    endif
#    ifndef MAPINTRGBCOLOURP_CONST_P_DEEP_COMPARE
#      define MAPINTRGBCOLOURP_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAPINTRGBCOLOURP_CONST_P_DEEP_COPY
#define MAPINTRGBCOLOURP_CONST_P_DEEP_COPY 0
#endif /* !defined MAPINTRGBCOLOURP_CONST_P_DEEP_COPY */

#ifndef MAPINTRGBCOLOURP_CONST_P_DEEP_COMPARE
#define MAPINTRGBCOLOURP_CONST_P_DEEP_COMPARE 0
#endif /* !defined MAPINTRGBCOLOURP_CONST_P_DEEP_COMPARE */

#ifdef CONST_MAPINTRGBCOLOURP_P_DEEP
#  if CONST_MAPINTRGBCOLOURP_P_DEEP
#    ifndef CONST_MAPINTRGBCOLOURP_P_DEEP_COPY
#      define CONST_MAPINTRGBCOLOURP_P_DEEP_COPY 1
#    endif
#    ifndef CONST_MAPINTRGBCOLOURP_P_DEEP_COMPARE
#      define CONST_MAPINTRGBCOLOURP_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef CONST_MAPINTRGBCOLOURP_P_DEEP_COPY
#      define CONST_MAPINTRGBCOLOURP_P_DEEP_COPY 0
#    endif
#    ifndef CONST_MAPINTRGBCOLOURP_P_DEEP_COMPARE
#      define CONST_MAPINTRGBCOLOURP_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef CONST_MAPINTRGBCOLOURP_P_DEEP_COPY
#define CONST_MAPINTRGBCOLOURP_P_DEEP_COPY 0
#endif /* !defined CONST_MAPINTRGBCOLOURP_P_DEEP_COPY */

#ifndef CONST_MAPINTRGBCOLOURP_P_DEEP_COMPARE
#define CONST_MAPINTRGBCOLOURP_P_DEEP_COMPARE 0
#endif /* !defined CONST_MAPINTRGBCOLOURP_P_DEEP_COMPARE */

#if MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE && !defined(MAP_INT_RGBCOLOUR_P_TP_HASH_RAW)
#define MAP_INT_RGBCOLOUR_P_TP_HASH_RAW(A1) map_int_rgbcolour_p_hash_raw((A1))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COMPARE && !defined(MAP_INT_RGBCOLOUR_P_T_CONSTP_HASH_RAW)
#define MAP_INT_RGBCOLOUR_P_T_CONSTP_HASH_RAW(A1) map_int_rgbcolour_p_hash_raw((A1))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE && !defined(CONST_MAP_INT_RGBCOLOUR_P_TP_HASH_RAW)
#define CONST_MAP_INT_RGBCOLOUR_P_TP_HASH_RAW(A1) map_int_rgbcolour_p_hash_raw((A1))
#endif

#if MAPINTRGBCOLOURPP_DEEP_COMPARE && !defined(MAPINTRGBCOLOURPP_HASH_RAW)
#define MAPINTRGBCOLOURPP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if MAPINTRGBCOLOURP_CONSTP_DEEP_COMPARE && !defined(MAPINTRGBCOLOURP_CONSTP_HASH_RAW)
#define MAPINTRGBCOLOURP_CONSTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if CONST_MAPINTRGBCOLOURPP_DEEP_COMPARE && !defined(CONST_MAPINTRGBCOLOURPP_HASH_RAW)
#define CONST_MAPINTRGBCOLOURPP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE && !defined(MAP_INT_RGBCOLOUR_P_T_P_HASH_RAW)
#define MAP_INT_RGBCOLOUR_P_T_P_HASH_RAW(A1) map_int_rgbcolour_p_hash_raw((A1))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COMPARE && !defined(MAP_INT_RGBCOLOUR_P_T_CONST_P_HASH_RAW)
#define MAP_INT_RGBCOLOUR_P_T_CONST_P_HASH_RAW(A1) map_int_rgbcolour_p_hash_raw((A1))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE && !defined(CONST_MAP_INT_RGBCOLOUR_P_T_P_HASH_RAW)
#define CONST_MAP_INT_RGBCOLOUR_P_T_P_HASH_RAW(A1) map_int_rgbcolour_p_hash_raw((A1))
#endif

#if MAPINTRGBCOLOURP_P_DEEP_COMPARE && !defined(MAPINTRGBCOLOURP_P_HASH_RAW)
#define MAPINTRGBCOLOURP_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if MAPINTRGBCOLOURP_CONST_P_DEEP_COMPARE && !defined(MAPINTRGBCOLOURP_CONST_P_HASH_RAW)
#define MAPINTRGBCOLOURP_CONST_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if CONST_MAPINTRGBCOLOURP_P_DEEP_COMPARE && !defined(CONST_MAPINTRGBCOLOURP_P_HASH_RAW)
#define CONST_MAPINTRGBCOLOURP_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#ifndef MAPINTRGBCOLOURP_HASH_RAW
#define MAPINTRGBCOLOURP_HASH_RAW(A1) ((A1).hash_raw())
#endif

#if MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE && !defined(MAP_INT_RGBCOLOUR_P_TP_CMP)
#define MAP_INT_RGBCOLOUR_P_TP_CMP(A1,A2) map_int_rgbcolour_p_cmp((A1),(A2))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COMPARE && !defined(MAP_INT_RGBCOLOUR_P_T_CONSTP_CMP)
#define MAP_INT_RGBCOLOUR_P_T_CONSTP_CMP(A1,A2) map_int_rgbcolour_p_cmp((A1),(A2))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE && !defined(CONST_MAP_INT_RGBCOLOUR_P_TP_CMP)
#define CONST_MAP_INT_RGBCOLOUR_P_TP_CMP(A1,A2) map_int_rgbcolour_p_cmp((A1),(A2))
#endif

#if MAPINTRGBCOLOURPP_DEEP_COMPARE && !defined(MAPINTRGBCOLOURPP_CMP)
#define MAPINTRGBCOLOURPP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if MAPINTRGBCOLOURP_CONSTP_DEEP_COMPARE && !defined(MAPINTRGBCOLOURP_CONSTP_CMP)
#define MAPINTRGBCOLOURP_CONSTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if CONST_MAPINTRGBCOLOURPP_DEEP_COMPARE && !defined(CONST_MAPINTRGBCOLOURPP_CMP)
#define CONST_MAPINTRGBCOLOURPP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE && !defined(MAP_INT_RGBCOLOUR_P_T_P_CMP)
#define MAP_INT_RGBCOLOUR_P_T_P_CMP(A1,A2) map_int_rgbcolour_p_cmp((A1),(A2))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COMPARE && !defined(MAP_INT_RGBCOLOUR_P_T_CONST_P_CMP)
#define MAP_INT_RGBCOLOUR_P_T_CONST_P_CMP(A1,A2) map_int_rgbcolour_p_cmp((A1),(A2))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE && !defined(CONST_MAP_INT_RGBCOLOUR_P_T_P_CMP)
#define CONST_MAP_INT_RGBCOLOUR_P_T_P_CMP(A1,A2) map_int_rgbcolour_p_cmp((A1),(A2))
#endif

#if MAPINTRGBCOLOURP_P_DEEP_COMPARE && !defined(MAPINTRGBCOLOURP_P_CMP)
#define MAPINTRGBCOLOURP_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if MAPINTRGBCOLOURP_CONST_P_DEEP_COMPARE && !defined(MAPINTRGBCOLOURP_CONST_P_CMP)
#define MAPINTRGBCOLOURP_CONST_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if CONST_MAPINTRGBCOLOURP_P_DEEP_COMPARE && !defined(CONST_MAPINTRGBCOLOURP_P_CMP)
#define CONST_MAPINTRGBCOLOURP_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#ifndef MAPINTRGBCOLOURP_CMP
#define MAPINTRGBCOLOURP_CMP(A1,A2) ((A1).cmp((A2)))
#endif

#ifndef MAPINTRGBCOLOURP_ZERO
#define MAPINTRGBCOLOURP_ZERO (MapIntRgbcolourP::static_zero())
#endif

#if MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE && !defined(MAP_INT_RGBCOLOUR_P_TP_EQUAL)
#define MAP_INT_RGBCOLOUR_P_TP_EQUAL(A1,A2) map_int_rgbcolour_p_equal((A1),(A2))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COMPARE && !defined(MAP_INT_RGBCOLOUR_P_T_CONSTP_EQUAL)
#define MAP_INT_RGBCOLOUR_P_T_CONSTP_EQUAL(A1,A2) map_int_rgbcolour_p_equal((A1),(A2))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COMPARE && !defined(CONST_MAP_INT_RGBCOLOUR_P_TP_EQUAL)
#define CONST_MAP_INT_RGBCOLOUR_P_TP_EQUAL(A1,A2) map_int_rgbcolour_p_equal((A1),(A2))
#endif

#if MAPINTRGBCOLOURPP_DEEP_COMPARE && !defined(MAPINTRGBCOLOURPP_EQUAL)
#define MAPINTRGBCOLOURPP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if MAPINTRGBCOLOURP_CONSTP_DEEP_COMPARE && !defined(MAPINTRGBCOLOURP_CONSTP_EQUAL)
#define MAPINTRGBCOLOURP_CONSTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if CONST_MAPINTRGBCOLOURPP_DEEP_COMPARE && !defined(CONST_MAPINTRGBCOLOURPP_EQUAL)
#define CONST_MAPINTRGBCOLOURPP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE && !defined(MAP_INT_RGBCOLOUR_P_T_P_EQUAL)
#define MAP_INT_RGBCOLOUR_P_T_P_EQUAL(A1,A2) map_int_rgbcolour_p_equal((A1),(A2))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COMPARE && !defined(MAP_INT_RGBCOLOUR_P_T_CONST_P_EQUAL)
#define MAP_INT_RGBCOLOUR_P_T_CONST_P_EQUAL(A1,A2) map_int_rgbcolour_p_equal((A1),(A2))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COMPARE && !defined(CONST_MAP_INT_RGBCOLOUR_P_T_P_EQUAL)
#define CONST_MAP_INT_RGBCOLOUR_P_T_P_EQUAL(A1,A2) map_int_rgbcolour_p_equal((A1),(A2))
#endif

#if MAPINTRGBCOLOURP_P_DEEP_COMPARE && !defined(MAPINTRGBCOLOURP_P_EQUAL)
#define MAPINTRGBCOLOURP_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if MAPINTRGBCOLOURP_CONST_P_DEEP_COMPARE && !defined(MAPINTRGBCOLOURP_CONST_P_EQUAL)
#define MAPINTRGBCOLOURP_CONST_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if CONST_MAPINTRGBCOLOURP_P_DEEP_COMPARE && !defined(CONST_MAPINTRGBCOLOURP_P_EQUAL)
#define CONST_MAPINTRGBCOLOURP_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#ifndef MAPINTRGBCOLOURP_EQUAL
#define MAPINTRGBCOLOURP_EQUAL(A1,A2) ((A1).equal((A2)))
#endif

#if MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_TP_ICOPY)
#define MAP_INT_RGBCOLOUR_P_TP_ICOPY(A1,A2) map_int_rgbcolour_p_copy_err((A1),(A2))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_T_CONSTP_ICOPY)
#define MAP_INT_RGBCOLOUR_P_T_CONSTP_ICOPY(A1,A2) map_int_rgbcolour_p_copy_err((A1),(A2))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY && !defined(CONST_MAP_INT_RGBCOLOUR_P_TP_ICOPY)
#define CONST_MAP_INT_RGBCOLOUR_P_TP_ICOPY(A1,A2) map_int_rgbcolour_p_copy_err((A1),(A2))
#endif

#if MAPINTRGBCOLOURPP_DEEP_COPY && !defined(MAPINTRGBCOLOURPP_ICOPY)
#define MAPINTRGBCOLOURPP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAPINTRGBCOLOURP_CONSTP_DEEP_COPY && !defined(MAPINTRGBCOLOURP_CONSTP_ICOPY)
#define MAPINTRGBCOLOURP_CONSTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if CONST_MAPINTRGBCOLOURPP_DEEP_COPY && !defined(CONST_MAPINTRGBCOLOURPP_ICOPY)
#define CONST_MAPINTRGBCOLOURPP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_T_P_ICOPY)
#define MAP_INT_RGBCOLOUR_P_T_P_ICOPY(A1,A2) map_int_rgbcolour_p_copy_err((A1),(A2))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_T_CONST_P_ICOPY)
#define MAP_INT_RGBCOLOUR_P_T_CONST_P_ICOPY(A1,A2) map_int_rgbcolour_p_copy_err((A1),(A2))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY && !defined(CONST_MAP_INT_RGBCOLOUR_P_T_P_ICOPY)
#define CONST_MAP_INT_RGBCOLOUR_P_T_P_ICOPY(A1,A2) map_int_rgbcolour_p_copy_err((A1),(A2))
#endif

#if MAPINTRGBCOLOURP_P_DEEP_COPY && !defined(MAPINTRGBCOLOURP_P_ICOPY)
#define MAPINTRGBCOLOURP_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAPINTRGBCOLOURP_CONST_P_DEEP_COPY && !defined(MAPINTRGBCOLOURP_CONST_P_ICOPY)
#define MAPINTRGBCOLOURP_CONST_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if CONST_MAPINTRGBCOLOURP_P_DEEP_COPY && !defined(CONST_MAPINTRGBCOLOURP_P_ICOPY)
#define CONST_MAPINTRGBCOLOURP_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_TP_OCOPY)
#define MAP_INT_RGBCOLOUR_P_TP_OCOPY(A1,A2) map_int_rgbcolour_p_copy_err((A1),(A2))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_T_CONSTP_OCOPY)
#define MAP_INT_RGBCOLOUR_P_T_CONSTP_OCOPY(A1,A2) map_int_rgbcolour_p_copy_err((A1),(A2))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY && !defined(CONST_MAP_INT_RGBCOLOUR_P_TP_OCOPY)
#define CONST_MAP_INT_RGBCOLOUR_P_TP_OCOPY(A1,A2) map_int_rgbcolour_p_copy_err((A1),(A2))
#endif

#if MAPINTRGBCOLOURPP_DEEP_COPY && !defined(MAPINTRGBCOLOURPP_OCOPY)
#define MAPINTRGBCOLOURPP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAPINTRGBCOLOURP_CONSTP_DEEP_COPY && !defined(MAPINTRGBCOLOURP_CONSTP_OCOPY)
#define MAPINTRGBCOLOURP_CONSTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if CONST_MAPINTRGBCOLOURPP_DEEP_COPY && !defined(CONST_MAPINTRGBCOLOURPP_OCOPY)
#define CONST_MAPINTRGBCOLOURPP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_T_P_OCOPY)
#define MAP_INT_RGBCOLOUR_P_T_P_OCOPY(A1,A2) map_int_rgbcolour_p_copy_err((A1),(A2))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_T_CONST_P_OCOPY)
#define MAP_INT_RGBCOLOUR_P_T_CONST_P_OCOPY(A1,A2) map_int_rgbcolour_p_copy_err((A1),(A2))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY && !defined(CONST_MAP_INT_RGBCOLOUR_P_T_P_OCOPY)
#define CONST_MAP_INT_RGBCOLOUR_P_T_P_OCOPY(A1,A2) map_int_rgbcolour_p_copy_err((A1),(A2))
#endif

#if MAPINTRGBCOLOURP_P_DEEP_COPY && !defined(MAPINTRGBCOLOURP_P_OCOPY)
#define MAPINTRGBCOLOURP_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAPINTRGBCOLOURP_CONST_P_DEEP_COPY && !defined(MAPINTRGBCOLOURP_CONST_P_OCOPY)
#define MAPINTRGBCOLOURP_CONST_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if CONST_MAPINTRGBCOLOURP_P_DEEP_COPY && !defined(CONST_MAPINTRGBCOLOURP_P_OCOPY)
#define CONST_MAPINTRGBCOLOURP_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_TP_IFREE)
#define MAP_INT_RGBCOLOUR_P_TP_IFREE(A1) map_int_rgbcolour_p_delete((A1))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_T_CONSTP_IFREE)
#define MAP_INT_RGBCOLOUR_P_T_CONSTP_IFREE(A1) map_int_rgbcolour_p_delete((A1))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY && !defined(CONST_MAP_INT_RGBCOLOUR_P_TP_IFREE)
#define CONST_MAP_INT_RGBCOLOUR_P_TP_IFREE(A1) map_int_rgbcolour_p_delete((A1))
#endif

#if MAPINTRGBCOLOURPP_DEEP_COPY && !defined(MAPINTRGBCOLOURPP_IFREE)
#define MAPINTRGBCOLOURPP_IFREE(A1) delete((A1))
#endif

#if MAPINTRGBCOLOURP_CONSTP_DEEP_COPY && !defined(MAPINTRGBCOLOURP_CONSTP_IFREE)
#define MAPINTRGBCOLOURP_CONSTP_IFREE(A1) delete((A1))
#endif

#if CONST_MAPINTRGBCOLOURPP_DEEP_COPY && !defined(CONST_MAPINTRGBCOLOURPP_IFREE)
#define CONST_MAPINTRGBCOLOURPP_IFREE(A1) delete((A1))
#endif

#if MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_T_P_IFREE)
#define MAP_INT_RGBCOLOUR_P_T_P_IFREE(A1) map_int_rgbcolour_p_delete((A1))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_T_CONST_P_IFREE)
#define MAP_INT_RGBCOLOUR_P_T_CONST_P_IFREE(A1) map_int_rgbcolour_p_delete((A1))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY && !defined(CONST_MAP_INT_RGBCOLOUR_P_T_P_IFREE)
#define CONST_MAP_INT_RGBCOLOUR_P_T_P_IFREE(A1) map_int_rgbcolour_p_delete((A1))
#endif

#if MAPINTRGBCOLOURP_P_DEEP_COPY && !defined(MAPINTRGBCOLOURP_P_IFREE)
#define MAPINTRGBCOLOURP_P_IFREE(A1) delete((A1))
#endif

#if MAPINTRGBCOLOURP_CONST_P_DEEP_COPY && !defined(MAPINTRGBCOLOURP_CONST_P_IFREE)
#define MAPINTRGBCOLOURP_CONST_P_IFREE(A1) delete((A1))
#endif

#if CONST_MAPINTRGBCOLOURP_P_DEEP_COPY && !defined(CONST_MAPINTRGBCOLOURP_P_IFREE)
#define CONST_MAPINTRGBCOLOURP_P_IFREE(A1) delete((A1))
#endif

#if MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_TP_OFREE)
#define MAP_INT_RGBCOLOUR_P_TP_OFREE(A1) map_int_rgbcolour_p_delete((A1))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONSTP_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_T_CONSTP_OFREE)
#define MAP_INT_RGBCOLOUR_P_T_CONSTP_OFREE(A1) map_int_rgbcolour_p_delete((A1))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_TP_DEEP_COPY && !defined(CONST_MAP_INT_RGBCOLOUR_P_TP_OFREE)
#define CONST_MAP_INT_RGBCOLOUR_P_TP_OFREE(A1) map_int_rgbcolour_p_delete((A1))
#endif

#if MAPINTRGBCOLOURPP_DEEP_COPY && !defined(MAPINTRGBCOLOURPP_OFREE)
#define MAPINTRGBCOLOURPP_OFREE(A1) delete((A1))
#endif

#if MAPINTRGBCOLOURP_CONSTP_DEEP_COPY && !defined(MAPINTRGBCOLOURP_CONSTP_OFREE)
#define MAPINTRGBCOLOURP_CONSTP_OFREE(A1) delete((A1))
#endif

#if CONST_MAPINTRGBCOLOURPP_DEEP_COPY && !defined(CONST_MAPINTRGBCOLOURPP_OFREE)
#define CONST_MAPINTRGBCOLOURPP_OFREE(A1) delete((A1))
#endif

#if MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_T_P_OFREE)
#define MAP_INT_RGBCOLOUR_P_T_P_OFREE(A1) map_int_rgbcolour_p_delete((A1))
#endif

#if MAP_INT_RGBCOLOUR_P_T_CONST_P_DEEP_COPY && !defined(MAP_INT_RGBCOLOUR_P_T_CONST_P_OFREE)
#define MAP_INT_RGBCOLOUR_P_T_CONST_P_OFREE(A1) map_int_rgbcolour_p_delete((A1))
#endif

#if CONST_MAP_INT_RGBCOLOUR_P_T_P_DEEP_COPY && !defined(CONST_MAP_INT_RGBCOLOUR_P_T_P_OFREE)
#define CONST_MAP_INT_RGBCOLOUR_P_T_P_OFREE(A1) map_int_rgbcolour_p_delete((A1))
#endif

#if MAPINTRGBCOLOURP_P_DEEP_COPY && !defined(MAPINTRGBCOLOURP_P_OFREE)
#define MAPINTRGBCOLOURP_P_OFREE(A1) delete((A1))
#endif

#if MAPINTRGBCOLOURP_CONST_P_DEEP_COPY && !defined(MAPINTRGBCOLOURP_CONST_P_OFREE)
#define MAPINTRGBCOLOURP_CONST_P_OFREE(A1) delete((A1))
#endif

#if CONST_MAPINTRGBCOLOURP_P_DEEP_COPY && !defined(CONST_MAPINTRGBCOLOURP_P_OFREE)
#define CONST_MAPINTRGBCOLOURP_P_OFREE(A1) delete((A1))
#endif

#ifndef MAPINTRGBCOLOURP_CONSTRUCTOR
#define MAPINTRGBCOLOURP_CONSTRUCTOR(A1) ((A1)._constructor())
#endif

#ifndef MAPINTRGBCOLOURP_DESTRUCTOR
#define MAPINTRGBCOLOURP_DESTRUCTOR(A1) ((A1)._destructor())
#endif


#endif /* defined ERWIN_MAP_INT_RGBCOLOUR_P_f_h */

