
#if defined(MAP_INT_CHAR_P_TP_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined MAP_INT_CHAR_P_TP_BEING_USED */

#if defined(MAP_INT_CHAR_P_T_CONSTP_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined MAP_INT_CHAR_P_T_CONSTP_BEING_USED */

#if defined(CONST_MAP_INT_CHAR_P_TP_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined CONST_MAP_INT_CHAR_P_TP_BEING_USED */

#if defined(MAPINTCHARPP_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined MAPINTCHARPP_BEING_USED */

#if defined(MAPINTCHARP_CONSTP_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined MAPINTCHARP_CONSTP_BEING_USED */

#if defined(CONST_MAPINTCHARPP_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined CONST_MAPINTCHARPP_BEING_USED */

#if defined(MAP_INT_CHAR_P_T_P_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined MAP_INT_CHAR_P_T_P_BEING_USED */

#if defined(MAP_INT_CHAR_P_T_CONST_P_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined MAP_INT_CHAR_P_T_CONST_P_BEING_USED */

#if defined(CONST_MAP_INT_CHAR_P_T_P_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined CONST_MAP_INT_CHAR_P_T_P_BEING_USED */

#if defined(MAPINTCHARP_P_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined MAPINTCHARP_P_BEING_USED */

#if defined(MAPINTCHARP_CONST_P_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined MAPINTCHARP_CONST_P_BEING_USED */

#if defined(CONST_MAPINTCHARP_P_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined CONST_MAPINTCHARP_P_BEING_USED */

#if defined(MAPINTCHARP_BEING_USED) && !defined(MAP_INT_CHAR_P_NEED_HEADER)
#define MAP_INT_CHAR_P_NEED_HEADER 1
#endif /* defined MAPINTCHARP_BEING_USED */



#ifdef MAP_INT_CHAR_P_NEED_HEADER
#include "map_int_char_p.h"
#endif

