
#ifndef ERWIN_MAP_BOARD_P_NODE_P_f_h
#define ERWIN_MAP_BOARD_P_NODE_P_f_h

struct map_board_p_node_p_t;
#ifndef __cplusplus
typedef struct map_board_p_node_p_t map_board_p_node_p_t;
#endif
typedef struct map_board_p_node_p_t MapBoardPNodeP;

typedef map_board_p_node_p_t *map_board_p_node_p_t_p;

typedef map_board_p_node_p_t const *map_board_p_node_p_t_const_p;

#define MAP_BOARD_P_NODE_P_SIG 2087550311



#ifdef MAP_BOARD_P_NODE_P_TP_DEEP
#  if MAP_BOARD_P_NODE_P_TP_DEEP
#    ifndef MAP_BOARD_P_NODE_P_TP_DEEP_COPY
#      define MAP_BOARD_P_NODE_P_TP_DEEP_COPY 1
#    endif
#    ifndef MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE
#      define MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAP_BOARD_P_NODE_P_TP_DEEP_COPY
#      define MAP_BOARD_P_NODE_P_TP_DEEP_COPY 0
#    endif
#    ifndef MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE
#      define MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAP_BOARD_P_NODE_P_TP_DEEP_COPY
#define MAP_BOARD_P_NODE_P_TP_DEEP_COPY 0
#endif /* !defined MAP_BOARD_P_NODE_P_TP_DEEP_COPY */

#ifndef MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE
#define MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE 0
#endif /* !defined MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE */

#ifdef MAP_BOARD_P_NODE_P_T_CONSTP_DEEP
#  if MAP_BOARD_P_NODE_P_T_CONSTP_DEEP
#    ifndef MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COPY
#      define MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COPY 1
#    endif
#    ifndef MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COMPARE
#      define MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COPY
#      define MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COPY 0
#    endif
#    ifndef MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COMPARE
#      define MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COPY
#define MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COPY 0
#endif /* !defined MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COPY */

#ifndef MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COMPARE
#define MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COMPARE 0
#endif /* !defined MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COMPARE */

#ifdef CONST_MAP_BOARD_P_NODE_P_TP_DEEP
#  if CONST_MAP_BOARD_P_NODE_P_TP_DEEP
#    ifndef CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COPY
#      define CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COPY 1
#    endif
#    ifndef CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE
#      define CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COPY
#      define CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COPY 0
#    endif
#    ifndef CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE
#      define CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COPY
#define CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COPY 0
#endif /* !defined CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COPY */

#ifndef CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE
#define CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE 0
#endif /* !defined CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE */

#ifdef MAPBOARDPNODEPP_DEEP
#  if MAPBOARDPNODEPP_DEEP
#    ifndef MAPBOARDPNODEPP_DEEP_COPY
#      define MAPBOARDPNODEPP_DEEP_COPY 1
#    endif
#    ifndef MAPBOARDPNODEPP_DEEP_COMPARE
#      define MAPBOARDPNODEPP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAPBOARDPNODEPP_DEEP_COPY
#      define MAPBOARDPNODEPP_DEEP_COPY 0
#    endif
#    ifndef MAPBOARDPNODEPP_DEEP_COMPARE
#      define MAPBOARDPNODEPP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAPBOARDPNODEPP_DEEP_COPY
#define MAPBOARDPNODEPP_DEEP_COPY 0
#endif /* !defined MAPBOARDPNODEPP_DEEP_COPY */

#ifndef MAPBOARDPNODEPP_DEEP_COMPARE
#define MAPBOARDPNODEPP_DEEP_COMPARE 0
#endif /* !defined MAPBOARDPNODEPP_DEEP_COMPARE */

#ifdef MAPBOARDPNODEP_CONSTP_DEEP
#  if MAPBOARDPNODEP_CONSTP_DEEP
#    ifndef MAPBOARDPNODEP_CONSTP_DEEP_COPY
#      define MAPBOARDPNODEP_CONSTP_DEEP_COPY 1
#    endif
#    ifndef MAPBOARDPNODEP_CONSTP_DEEP_COMPARE
#      define MAPBOARDPNODEP_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAPBOARDPNODEP_CONSTP_DEEP_COPY
#      define MAPBOARDPNODEP_CONSTP_DEEP_COPY 0
#    endif
#    ifndef MAPBOARDPNODEP_CONSTP_DEEP_COMPARE
#      define MAPBOARDPNODEP_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAPBOARDPNODEP_CONSTP_DEEP_COPY
#define MAPBOARDPNODEP_CONSTP_DEEP_COPY 0
#endif /* !defined MAPBOARDPNODEP_CONSTP_DEEP_COPY */

#ifndef MAPBOARDPNODEP_CONSTP_DEEP_COMPARE
#define MAPBOARDPNODEP_CONSTP_DEEP_COMPARE 0
#endif /* !defined MAPBOARDPNODEP_CONSTP_DEEP_COMPARE */

#ifdef CONST_MAPBOARDPNODEPP_DEEP
#  if CONST_MAPBOARDPNODEPP_DEEP
#    ifndef CONST_MAPBOARDPNODEPP_DEEP_COPY
#      define CONST_MAPBOARDPNODEPP_DEEP_COPY 1
#    endif
#    ifndef CONST_MAPBOARDPNODEPP_DEEP_COMPARE
#      define CONST_MAPBOARDPNODEPP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef CONST_MAPBOARDPNODEPP_DEEP_COPY
#      define CONST_MAPBOARDPNODEPP_DEEP_COPY 0
#    endif
#    ifndef CONST_MAPBOARDPNODEPP_DEEP_COMPARE
#      define CONST_MAPBOARDPNODEPP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef CONST_MAPBOARDPNODEPP_DEEP_COPY
#define CONST_MAPBOARDPNODEPP_DEEP_COPY 0
#endif /* !defined CONST_MAPBOARDPNODEPP_DEEP_COPY */

#ifndef CONST_MAPBOARDPNODEPP_DEEP_COMPARE
#define CONST_MAPBOARDPNODEPP_DEEP_COMPARE 0
#endif /* !defined CONST_MAPBOARDPNODEPP_DEEP_COMPARE */

#ifdef MAP_BOARD_P_NODE_P_T_P_DEEP
#  if MAP_BOARD_P_NODE_P_T_P_DEEP
#    ifndef MAP_BOARD_P_NODE_P_T_P_DEEP_COPY
#      define MAP_BOARD_P_NODE_P_T_P_DEEP_COPY 1
#    endif
#    ifndef MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE
#      define MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAP_BOARD_P_NODE_P_T_P_DEEP_COPY
#      define MAP_BOARD_P_NODE_P_T_P_DEEP_COPY 0
#    endif
#    ifndef MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE
#      define MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAP_BOARD_P_NODE_P_T_P_DEEP_COPY
#define MAP_BOARD_P_NODE_P_T_P_DEEP_COPY 0
#endif /* !defined MAP_BOARD_P_NODE_P_T_P_DEEP_COPY */

#ifndef MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE
#define MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE 0
#endif /* !defined MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE */

#ifdef MAP_BOARD_P_NODE_P_T_CONST_P_DEEP
#  if MAP_BOARD_P_NODE_P_T_CONST_P_DEEP
#    ifndef MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COPY
#      define MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COPY 1
#    endif
#    ifndef MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COMPARE
#      define MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COPY
#      define MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COPY 0
#    endif
#    ifndef MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COMPARE
#      define MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COPY
#define MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COPY 0
#endif /* !defined MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COPY */

#ifndef MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COMPARE
#define MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COMPARE 0
#endif /* !defined MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COMPARE */

#ifdef CONST_MAP_BOARD_P_NODE_P_T_P_DEEP
#  if CONST_MAP_BOARD_P_NODE_P_T_P_DEEP
#    ifndef CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COPY
#      define CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COPY 1
#    endif
#    ifndef CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE
#      define CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COPY
#      define CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COPY 0
#    endif
#    ifndef CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE
#      define CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COPY
#define CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COPY 0
#endif /* !defined CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COPY */

#ifndef CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE
#define CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE 0
#endif /* !defined CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE */

#ifdef MAPBOARDPNODEP_P_DEEP
#  if MAPBOARDPNODEP_P_DEEP
#    ifndef MAPBOARDPNODEP_P_DEEP_COPY
#      define MAPBOARDPNODEP_P_DEEP_COPY 1
#    endif
#    ifndef MAPBOARDPNODEP_P_DEEP_COMPARE
#      define MAPBOARDPNODEP_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAPBOARDPNODEP_P_DEEP_COPY
#      define MAPBOARDPNODEP_P_DEEP_COPY 0
#    endif
#    ifndef MAPBOARDPNODEP_P_DEEP_COMPARE
#      define MAPBOARDPNODEP_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAPBOARDPNODEP_P_DEEP_COPY
#define MAPBOARDPNODEP_P_DEEP_COPY 0
#endif /* !defined MAPBOARDPNODEP_P_DEEP_COPY */

#ifndef MAPBOARDPNODEP_P_DEEP_COMPARE
#define MAPBOARDPNODEP_P_DEEP_COMPARE 0
#endif /* !defined MAPBOARDPNODEP_P_DEEP_COMPARE */

#ifdef MAPBOARDPNODEP_CONST_P_DEEP
#  if MAPBOARDPNODEP_CONST_P_DEEP
#    ifndef MAPBOARDPNODEP_CONST_P_DEEP_COPY
#      define MAPBOARDPNODEP_CONST_P_DEEP_COPY 1
#    endif
#    ifndef MAPBOARDPNODEP_CONST_P_DEEP_COMPARE
#      define MAPBOARDPNODEP_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef MAPBOARDPNODEP_CONST_P_DEEP_COPY
#      define MAPBOARDPNODEP_CONST_P_DEEP_COPY 0
#    endif
#    ifndef MAPBOARDPNODEP_CONST_P_DEEP_COMPARE
#      define MAPBOARDPNODEP_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef MAPBOARDPNODEP_CONST_P_DEEP_COPY
#define MAPBOARDPNODEP_CONST_P_DEEP_COPY 0
#endif /* !defined MAPBOARDPNODEP_CONST_P_DEEP_COPY */

#ifndef MAPBOARDPNODEP_CONST_P_DEEP_COMPARE
#define MAPBOARDPNODEP_CONST_P_DEEP_COMPARE 0
#endif /* !defined MAPBOARDPNODEP_CONST_P_DEEP_COMPARE */

#ifdef CONST_MAPBOARDPNODEP_P_DEEP
#  if CONST_MAPBOARDPNODEP_P_DEEP
#    ifndef CONST_MAPBOARDPNODEP_P_DEEP_COPY
#      define CONST_MAPBOARDPNODEP_P_DEEP_COPY 1
#    endif
#    ifndef CONST_MAPBOARDPNODEP_P_DEEP_COMPARE
#      define CONST_MAPBOARDPNODEP_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef CONST_MAPBOARDPNODEP_P_DEEP_COPY
#      define CONST_MAPBOARDPNODEP_P_DEEP_COPY 0
#    endif
#    ifndef CONST_MAPBOARDPNODEP_P_DEEP_COMPARE
#      define CONST_MAPBOARDPNODEP_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef CONST_MAPBOARDPNODEP_P_DEEP_COPY
#define CONST_MAPBOARDPNODEP_P_DEEP_COPY 0
#endif /* !defined CONST_MAPBOARDPNODEP_P_DEEP_COPY */

#ifndef CONST_MAPBOARDPNODEP_P_DEEP_COMPARE
#define CONST_MAPBOARDPNODEP_P_DEEP_COMPARE 0
#endif /* !defined CONST_MAPBOARDPNODEP_P_DEEP_COMPARE */

#if MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE && !defined(MAP_BOARD_P_NODE_P_TP_HASH_RAW)
#define MAP_BOARD_P_NODE_P_TP_HASH_RAW(A1) map_board_p_node_p_hash_raw((A1))
#endif

#if MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COMPARE && !defined(MAP_BOARD_P_NODE_P_T_CONSTP_HASH_RAW)
#define MAP_BOARD_P_NODE_P_T_CONSTP_HASH_RAW(A1) map_board_p_node_p_hash_raw((A1))
#endif

#if CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE && !defined(CONST_MAP_BOARD_P_NODE_P_TP_HASH_RAW)
#define CONST_MAP_BOARD_P_NODE_P_TP_HASH_RAW(A1) map_board_p_node_p_hash_raw((A1))
#endif

#if MAPBOARDPNODEPP_DEEP_COMPARE && !defined(MAPBOARDPNODEPP_HASH_RAW)
#define MAPBOARDPNODEPP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if MAPBOARDPNODEP_CONSTP_DEEP_COMPARE && !defined(MAPBOARDPNODEP_CONSTP_HASH_RAW)
#define MAPBOARDPNODEP_CONSTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if CONST_MAPBOARDPNODEPP_DEEP_COMPARE && !defined(CONST_MAPBOARDPNODEPP_HASH_RAW)
#define CONST_MAPBOARDPNODEPP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE && !defined(MAP_BOARD_P_NODE_P_T_P_HASH_RAW)
#define MAP_BOARD_P_NODE_P_T_P_HASH_RAW(A1) map_board_p_node_p_hash_raw((A1))
#endif

#if MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COMPARE && !defined(MAP_BOARD_P_NODE_P_T_CONST_P_HASH_RAW)
#define MAP_BOARD_P_NODE_P_T_CONST_P_HASH_RAW(A1) map_board_p_node_p_hash_raw((A1))
#endif

#if CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE && !defined(CONST_MAP_BOARD_P_NODE_P_T_P_HASH_RAW)
#define CONST_MAP_BOARD_P_NODE_P_T_P_HASH_RAW(A1) map_board_p_node_p_hash_raw((A1))
#endif

#if MAPBOARDPNODEP_P_DEEP_COMPARE && !defined(MAPBOARDPNODEP_P_HASH_RAW)
#define MAPBOARDPNODEP_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if MAPBOARDPNODEP_CONST_P_DEEP_COMPARE && !defined(MAPBOARDPNODEP_CONST_P_HASH_RAW)
#define MAPBOARDPNODEP_CONST_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if CONST_MAPBOARDPNODEP_P_DEEP_COMPARE && !defined(CONST_MAPBOARDPNODEP_P_HASH_RAW)
#define CONST_MAPBOARDPNODEP_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#ifndef MAPBOARDPNODEP_HASH_RAW
#define MAPBOARDPNODEP_HASH_RAW(A1) ((A1).hash_raw())
#endif

#if MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE && !defined(MAP_BOARD_P_NODE_P_TP_CMP)
#define MAP_BOARD_P_NODE_P_TP_CMP(A1,A2) map_board_p_node_p_cmp((A1),(A2))
#endif

#if MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COMPARE && !defined(MAP_BOARD_P_NODE_P_T_CONSTP_CMP)
#define MAP_BOARD_P_NODE_P_T_CONSTP_CMP(A1,A2) map_board_p_node_p_cmp((A1),(A2))
#endif

#if CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE && !defined(CONST_MAP_BOARD_P_NODE_P_TP_CMP)
#define CONST_MAP_BOARD_P_NODE_P_TP_CMP(A1,A2) map_board_p_node_p_cmp((A1),(A2))
#endif

#if MAPBOARDPNODEPP_DEEP_COMPARE && !defined(MAPBOARDPNODEPP_CMP)
#define MAPBOARDPNODEPP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if MAPBOARDPNODEP_CONSTP_DEEP_COMPARE && !defined(MAPBOARDPNODEP_CONSTP_CMP)
#define MAPBOARDPNODEP_CONSTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if CONST_MAPBOARDPNODEPP_DEEP_COMPARE && !defined(CONST_MAPBOARDPNODEPP_CMP)
#define CONST_MAPBOARDPNODEPP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE && !defined(MAP_BOARD_P_NODE_P_T_P_CMP)
#define MAP_BOARD_P_NODE_P_T_P_CMP(A1,A2) map_board_p_node_p_cmp((A1),(A2))
#endif

#if MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COMPARE && !defined(MAP_BOARD_P_NODE_P_T_CONST_P_CMP)
#define MAP_BOARD_P_NODE_P_T_CONST_P_CMP(A1,A2) map_board_p_node_p_cmp((A1),(A2))
#endif

#if CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE && !defined(CONST_MAP_BOARD_P_NODE_P_T_P_CMP)
#define CONST_MAP_BOARD_P_NODE_P_T_P_CMP(A1,A2) map_board_p_node_p_cmp((A1),(A2))
#endif

#if MAPBOARDPNODEP_P_DEEP_COMPARE && !defined(MAPBOARDPNODEP_P_CMP)
#define MAPBOARDPNODEP_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if MAPBOARDPNODEP_CONST_P_DEEP_COMPARE && !defined(MAPBOARDPNODEP_CONST_P_CMP)
#define MAPBOARDPNODEP_CONST_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if CONST_MAPBOARDPNODEP_P_DEEP_COMPARE && !defined(CONST_MAPBOARDPNODEP_P_CMP)
#define CONST_MAPBOARDPNODEP_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#ifndef MAPBOARDPNODEP_CMP
#define MAPBOARDPNODEP_CMP(A1,A2) ((A1).cmp((A2)))
#endif

#ifndef MAPBOARDPNODEP_ZERO
#define MAPBOARDPNODEP_ZERO (MapBoardPNodeP::static_zero())
#endif

#if MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE && !defined(MAP_BOARD_P_NODE_P_TP_EQUAL)
#define MAP_BOARD_P_NODE_P_TP_EQUAL(A1,A2) map_board_p_node_p_equal((A1),(A2))
#endif

#if MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COMPARE && !defined(MAP_BOARD_P_NODE_P_T_CONSTP_EQUAL)
#define MAP_BOARD_P_NODE_P_T_CONSTP_EQUAL(A1,A2) map_board_p_node_p_equal((A1),(A2))
#endif

#if CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COMPARE && !defined(CONST_MAP_BOARD_P_NODE_P_TP_EQUAL)
#define CONST_MAP_BOARD_P_NODE_P_TP_EQUAL(A1,A2) map_board_p_node_p_equal((A1),(A2))
#endif

#if MAPBOARDPNODEPP_DEEP_COMPARE && !defined(MAPBOARDPNODEPP_EQUAL)
#define MAPBOARDPNODEPP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if MAPBOARDPNODEP_CONSTP_DEEP_COMPARE && !defined(MAPBOARDPNODEP_CONSTP_EQUAL)
#define MAPBOARDPNODEP_CONSTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if CONST_MAPBOARDPNODEPP_DEEP_COMPARE && !defined(CONST_MAPBOARDPNODEPP_EQUAL)
#define CONST_MAPBOARDPNODEPP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE && !defined(MAP_BOARD_P_NODE_P_T_P_EQUAL)
#define MAP_BOARD_P_NODE_P_T_P_EQUAL(A1,A2) map_board_p_node_p_equal((A1),(A2))
#endif

#if MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COMPARE && !defined(MAP_BOARD_P_NODE_P_T_CONST_P_EQUAL)
#define MAP_BOARD_P_NODE_P_T_CONST_P_EQUAL(A1,A2) map_board_p_node_p_equal((A1),(A2))
#endif

#if CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COMPARE && !defined(CONST_MAP_BOARD_P_NODE_P_T_P_EQUAL)
#define CONST_MAP_BOARD_P_NODE_P_T_P_EQUAL(A1,A2) map_board_p_node_p_equal((A1),(A2))
#endif

#if MAPBOARDPNODEP_P_DEEP_COMPARE && !defined(MAPBOARDPNODEP_P_EQUAL)
#define MAPBOARDPNODEP_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if MAPBOARDPNODEP_CONST_P_DEEP_COMPARE && !defined(MAPBOARDPNODEP_CONST_P_EQUAL)
#define MAPBOARDPNODEP_CONST_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if CONST_MAPBOARDPNODEP_P_DEEP_COMPARE && !defined(CONST_MAPBOARDPNODEP_P_EQUAL)
#define CONST_MAPBOARDPNODEP_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#ifndef MAPBOARDPNODEP_EQUAL
#define MAPBOARDPNODEP_EQUAL(A1,A2) ((A1).equal((A2)))
#endif

#if MAP_BOARD_P_NODE_P_TP_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_TP_ICOPY)
#define MAP_BOARD_P_NODE_P_TP_ICOPY(A1,A2) map_board_p_node_p_copy_err((A1),(A2))
#endif

#if MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_T_CONSTP_ICOPY)
#define MAP_BOARD_P_NODE_P_T_CONSTP_ICOPY(A1,A2) map_board_p_node_p_copy_err((A1),(A2))
#endif

#if CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COPY && !defined(CONST_MAP_BOARD_P_NODE_P_TP_ICOPY)
#define CONST_MAP_BOARD_P_NODE_P_TP_ICOPY(A1,A2) map_board_p_node_p_copy_err((A1),(A2))
#endif

#if MAPBOARDPNODEPP_DEEP_COPY && !defined(MAPBOARDPNODEPP_ICOPY)
#define MAPBOARDPNODEPP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAPBOARDPNODEP_CONSTP_DEEP_COPY && !defined(MAPBOARDPNODEP_CONSTP_ICOPY)
#define MAPBOARDPNODEP_CONSTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if CONST_MAPBOARDPNODEPP_DEEP_COPY && !defined(CONST_MAPBOARDPNODEPP_ICOPY)
#define CONST_MAPBOARDPNODEPP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAP_BOARD_P_NODE_P_T_P_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_T_P_ICOPY)
#define MAP_BOARD_P_NODE_P_T_P_ICOPY(A1,A2) map_board_p_node_p_copy_err((A1),(A2))
#endif

#if MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_T_CONST_P_ICOPY)
#define MAP_BOARD_P_NODE_P_T_CONST_P_ICOPY(A1,A2) map_board_p_node_p_copy_err((A1),(A2))
#endif

#if CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COPY && !defined(CONST_MAP_BOARD_P_NODE_P_T_P_ICOPY)
#define CONST_MAP_BOARD_P_NODE_P_T_P_ICOPY(A1,A2) map_board_p_node_p_copy_err((A1),(A2))
#endif

#if MAPBOARDPNODEP_P_DEEP_COPY && !defined(MAPBOARDPNODEP_P_ICOPY)
#define MAPBOARDPNODEP_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAPBOARDPNODEP_CONST_P_DEEP_COPY && !defined(MAPBOARDPNODEP_CONST_P_ICOPY)
#define MAPBOARDPNODEP_CONST_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if CONST_MAPBOARDPNODEP_P_DEEP_COPY && !defined(CONST_MAPBOARDPNODEP_P_ICOPY)
#define CONST_MAPBOARDPNODEP_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAP_BOARD_P_NODE_P_TP_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_TP_OCOPY)
#define MAP_BOARD_P_NODE_P_TP_OCOPY(A1,A2) map_board_p_node_p_copy_err((A1),(A2))
#endif

#if MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_T_CONSTP_OCOPY)
#define MAP_BOARD_P_NODE_P_T_CONSTP_OCOPY(A1,A2) map_board_p_node_p_copy_err((A1),(A2))
#endif

#if CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COPY && !defined(CONST_MAP_BOARD_P_NODE_P_TP_OCOPY)
#define CONST_MAP_BOARD_P_NODE_P_TP_OCOPY(A1,A2) map_board_p_node_p_copy_err((A1),(A2))
#endif

#if MAPBOARDPNODEPP_DEEP_COPY && !defined(MAPBOARDPNODEPP_OCOPY)
#define MAPBOARDPNODEPP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAPBOARDPNODEP_CONSTP_DEEP_COPY && !defined(MAPBOARDPNODEP_CONSTP_OCOPY)
#define MAPBOARDPNODEP_CONSTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if CONST_MAPBOARDPNODEPP_DEEP_COPY && !defined(CONST_MAPBOARDPNODEPP_OCOPY)
#define CONST_MAPBOARDPNODEPP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAP_BOARD_P_NODE_P_T_P_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_T_P_OCOPY)
#define MAP_BOARD_P_NODE_P_T_P_OCOPY(A1,A2) map_board_p_node_p_copy_err((A1),(A2))
#endif

#if MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_T_CONST_P_OCOPY)
#define MAP_BOARD_P_NODE_P_T_CONST_P_OCOPY(A1,A2) map_board_p_node_p_copy_err((A1),(A2))
#endif

#if CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COPY && !defined(CONST_MAP_BOARD_P_NODE_P_T_P_OCOPY)
#define CONST_MAP_BOARD_P_NODE_P_T_P_OCOPY(A1,A2) map_board_p_node_p_copy_err((A1),(A2))
#endif

#if MAPBOARDPNODEP_P_DEEP_COPY && !defined(MAPBOARDPNODEP_P_OCOPY)
#define MAPBOARDPNODEP_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAPBOARDPNODEP_CONST_P_DEEP_COPY && !defined(MAPBOARDPNODEP_CONST_P_OCOPY)
#define MAPBOARDPNODEP_CONST_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if CONST_MAPBOARDPNODEP_P_DEEP_COPY && !defined(CONST_MAPBOARDPNODEP_P_OCOPY)
#define CONST_MAPBOARDPNODEP_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if MAP_BOARD_P_NODE_P_TP_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_TP_IFREE)
#define MAP_BOARD_P_NODE_P_TP_IFREE(A1) map_board_p_node_p_delete((A1))
#endif

#if MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_T_CONSTP_IFREE)
#define MAP_BOARD_P_NODE_P_T_CONSTP_IFREE(A1) map_board_p_node_p_delete((A1))
#endif

#if CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COPY && !defined(CONST_MAP_BOARD_P_NODE_P_TP_IFREE)
#define CONST_MAP_BOARD_P_NODE_P_TP_IFREE(A1) map_board_p_node_p_delete((A1))
#endif

#if MAPBOARDPNODEPP_DEEP_COPY && !defined(MAPBOARDPNODEPP_IFREE)
#define MAPBOARDPNODEPP_IFREE(A1) delete((A1))
#endif

#if MAPBOARDPNODEP_CONSTP_DEEP_COPY && !defined(MAPBOARDPNODEP_CONSTP_IFREE)
#define MAPBOARDPNODEP_CONSTP_IFREE(A1) delete((A1))
#endif

#if CONST_MAPBOARDPNODEPP_DEEP_COPY && !defined(CONST_MAPBOARDPNODEPP_IFREE)
#define CONST_MAPBOARDPNODEPP_IFREE(A1) delete((A1))
#endif

#if MAP_BOARD_P_NODE_P_T_P_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_T_P_IFREE)
#define MAP_BOARD_P_NODE_P_T_P_IFREE(A1) map_board_p_node_p_delete((A1))
#endif

#if MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_T_CONST_P_IFREE)
#define MAP_BOARD_P_NODE_P_T_CONST_P_IFREE(A1) map_board_p_node_p_delete((A1))
#endif

#if CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COPY && !defined(CONST_MAP_BOARD_P_NODE_P_T_P_IFREE)
#define CONST_MAP_BOARD_P_NODE_P_T_P_IFREE(A1) map_board_p_node_p_delete((A1))
#endif

#if MAPBOARDPNODEP_P_DEEP_COPY && !defined(MAPBOARDPNODEP_P_IFREE)
#define MAPBOARDPNODEP_P_IFREE(A1) delete((A1))
#endif

#if MAPBOARDPNODEP_CONST_P_DEEP_COPY && !defined(MAPBOARDPNODEP_CONST_P_IFREE)
#define MAPBOARDPNODEP_CONST_P_IFREE(A1) delete((A1))
#endif

#if CONST_MAPBOARDPNODEP_P_DEEP_COPY && !defined(CONST_MAPBOARDPNODEP_P_IFREE)
#define CONST_MAPBOARDPNODEP_P_IFREE(A1) delete((A1))
#endif

#if MAP_BOARD_P_NODE_P_TP_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_TP_OFREE)
#define MAP_BOARD_P_NODE_P_TP_OFREE(A1) map_board_p_node_p_delete((A1))
#endif

#if MAP_BOARD_P_NODE_P_T_CONSTP_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_T_CONSTP_OFREE)
#define MAP_BOARD_P_NODE_P_T_CONSTP_OFREE(A1) map_board_p_node_p_delete((A1))
#endif

#if CONST_MAP_BOARD_P_NODE_P_TP_DEEP_COPY && !defined(CONST_MAP_BOARD_P_NODE_P_TP_OFREE)
#define CONST_MAP_BOARD_P_NODE_P_TP_OFREE(A1) map_board_p_node_p_delete((A1))
#endif

#if MAPBOARDPNODEPP_DEEP_COPY && !defined(MAPBOARDPNODEPP_OFREE)
#define MAPBOARDPNODEPP_OFREE(A1) delete((A1))
#endif

#if MAPBOARDPNODEP_CONSTP_DEEP_COPY && !defined(MAPBOARDPNODEP_CONSTP_OFREE)
#define MAPBOARDPNODEP_CONSTP_OFREE(A1) delete((A1))
#endif

#if CONST_MAPBOARDPNODEPP_DEEP_COPY && !defined(CONST_MAPBOARDPNODEPP_OFREE)
#define CONST_MAPBOARDPNODEPP_OFREE(A1) delete((A1))
#endif

#if MAP_BOARD_P_NODE_P_T_P_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_T_P_OFREE)
#define MAP_BOARD_P_NODE_P_T_P_OFREE(A1) map_board_p_node_p_delete((A1))
#endif

#if MAP_BOARD_P_NODE_P_T_CONST_P_DEEP_COPY && !defined(MAP_BOARD_P_NODE_P_T_CONST_P_OFREE)
#define MAP_BOARD_P_NODE_P_T_CONST_P_OFREE(A1) map_board_p_node_p_delete((A1))
#endif

#if CONST_MAP_BOARD_P_NODE_P_T_P_DEEP_COPY && !defined(CONST_MAP_BOARD_P_NODE_P_T_P_OFREE)
#define CONST_MAP_BOARD_P_NODE_P_T_P_OFREE(A1) map_board_p_node_p_delete((A1))
#endif

#if MAPBOARDPNODEP_P_DEEP_COPY && !defined(MAPBOARDPNODEP_P_OFREE)
#define MAPBOARDPNODEP_P_OFREE(A1) delete((A1))
#endif

#if MAPBOARDPNODEP_CONST_P_DEEP_COPY && !defined(MAPBOARDPNODEP_CONST_P_OFREE)
#define MAPBOARDPNODEP_CONST_P_OFREE(A1) delete((A1))
#endif

#if CONST_MAPBOARDPNODEP_P_DEEP_COPY && !defined(CONST_MAPBOARDPNODEP_P_OFREE)
#define CONST_MAPBOARDPNODEP_P_OFREE(A1) delete((A1))
#endif

#ifndef MAPBOARDPNODEP_CONSTRUCTOR
#define MAPBOARDPNODEP_CONSTRUCTOR(A1) ((A1)._constructor())
#endif

#ifndef MAPBOARDPNODEP_DESTRUCTOR
#define MAPBOARDPNODEP_DESTRUCTOR(A1) ((A1)._destructor())
#endif


#endif /* defined ERWIN_MAP_BOARD_P_NODE_P_f_h */

