
#ifndef ERWIN_MAP_BOARD_P_NODE_P_ti_h
#define ERWIN_MAP_BOARD_P_NODE_P_ti_h

#define map_board_p_node_p_hashlist_t_KIND STRUCT
#define map_board_p_node_p_hashlist_t_TYPE_INFO  TYPE_INFO_NAME(map_board_p_node_p_hashlist_t)
extern  TYPE_INFO_T(map_board_p_node_p_hashlist_t);

#define map_board_p_node_p_hashlist_t_p_KIND  POINTER
#define map_board_p_node_p_hashlist_t_p_TYPE_INFO  TYPE_INFO_NAME(map_board_p_node_p_hashlist_t_p)
extern  TYPE_INFO_T(map_board_p_node_p_hashlist_t_p);

#define map_board_p_node_p_hashlist_t_const_p_KIND POINTER
#define map_board_p_node_p_hashlist_t_const_p_TYPE_INFO  TYPE_INFO_NAME(map_board_p_node_p_hashlist_t_const_p)
extern  TYPE_INFO_T(map_board_p_node_p_hashlist_t_const_p);

#define map_board_p_node_p_internal_Iterator_KIND STRUCT
#define map_board_p_node_p_internal_Iterator_TYPE_INFO  TYPE_INFO_NAME(map_board_p_node_p_internal_Iterator)
extern  TYPE_INFO_T(map_board_p_node_p_internal_Iterator);

#define map_board_p_node_p_t_KIND STRUCT
#define map_board_p_node_p_t_TYPE_INFO  TYPE_INFO_NAME(map_board_p_node_p_t)
extern  TYPE_INFO_T(map_board_p_node_p_t);

#define map_board_p_node_p_t_p_KIND POINTER
#define map_board_p_node_p_t_p_TYPE_INFO  TYPE_INFO_NAME(map_board_p_node_p_t_p)
extern  TYPE_INFO_T(map_board_p_node_p_t_p);

#define map_board_p_node_p_t_const_p_KIND POINTER
#define map_board_p_node_p_t_const_p_TYPE_INFO  TYPE_INFO_NAME(map_board_p_node_p_t_const_p)
extern  TYPE_INFO_T(map_board_p_node_p_t_const_p);

#define map_board_p_node_p_content_KIND VECTOR
#define map_board_p_node_p_content_TYPE_INFO  TYPE_INFO_NAME(map_board_p_node_p_content)
extern  TYPE_INFO_T(map_board_p_node_p_content);

#define map_board_p_node_p_content_p_KIND POINTER
#define map_board_p_node_p_content_p_TYPE_INFO  TYPE_INFO_NAME(map_board_p_node_p_content_p)
extern  TYPE_INFO_T(map_board_p_node_p_content_p);

#define MapBoardPNodeP_TYPE_INFO          map_board_p_node_p_t_TYPE_INFO
#define MapBoardPNodeP_p_TYPE_INFO        map_board_p_node_p_t_p_TYPE_INFO
#define MapBoardPNodeP_const_p_TYPE_INFO  map_board_p_node_p_t_const_p_TYPE_INFO

#endif /* defined ERWIN_MAP_BOARD_P_NODE_P_ti_h */

