
#if defined(MAP_INT_RGBCOLOUR_P_TP_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined MAP_INT_RGBCOLOUR_P_TP_BEING_USED */

#if defined(MAP_INT_RGBCOLOUR_P_T_CONSTP_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined MAP_INT_RGBCOLOUR_P_T_CONSTP_BEING_USED */

#if defined(CONST_MAP_INT_RGBCOLOUR_P_TP_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined CONST_MAP_INT_RGBCOLOUR_P_TP_BEING_USED */

#if defined(MAPINTRGBCOLOURPP_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined MAPINTRGBCOLOURPP_BEING_USED */

#if defined(MAPINTRGBCOLOURP_CONSTP_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined MAPINTRGBCOLOURP_CONSTP_BEING_USED */

#if defined(CONST_MAPINTRGBCOLOURPP_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined CONST_MAPINTRGBCOLOURPP_BEING_USED */

#if defined(MAP_INT_RGBCOLOUR_P_T_P_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined MAP_INT_RGBCOLOUR_P_T_P_BEING_USED */

#if defined(MAP_INT_RGBCOLOUR_P_T_CONST_P_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined MAP_INT_RGBCOLOUR_P_T_CONST_P_BEING_USED */

#if defined(CONST_MAP_INT_RGBCOLOUR_P_T_P_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined CONST_MAP_INT_RGBCOLOUR_P_T_P_BEING_USED */

#if defined(MAPINTRGBCOLOURP_P_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined MAPINTRGBCOLOURP_P_BEING_USED */

#if defined(MAPINTRGBCOLOURP_CONST_P_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined MAPINTRGBCOLOURP_CONST_P_BEING_USED */

#if defined(CONST_MAPINTRGBCOLOURP_P_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined CONST_MAPINTRGBCOLOURP_P_BEING_USED */

#if defined(MAPINTRGBCOLOURP_BEING_USED) && !defined(MAP_INT_RGBCOLOUR_P_NEED_HEADER)
#define MAP_INT_RGBCOLOUR_P_NEED_HEADER 1
#endif /* defined MAPINTRGBCOLOURP_BEING_USED */



#ifdef MAP_INT_RGBCOLOUR_P_NEED_HEADER
#include "map_int_rgbcolour_p.h"
#endif

