
#if defined(MAP_BOARD_P_NODE_P_TP_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined MAP_BOARD_P_NODE_P_TP_BEING_USED */

#if defined(MAP_BOARD_P_NODE_P_T_CONSTP_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined MAP_BOARD_P_NODE_P_T_CONSTP_BEING_USED */

#if defined(CONST_MAP_BOARD_P_NODE_P_TP_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined CONST_MAP_BOARD_P_NODE_P_TP_BEING_USED */

#if defined(MAPBOARDPNODEPP_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined MAPBOARDPNODEPP_BEING_USED */

#if defined(MAPBOARDPNODEP_CONSTP_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined MAPBOARDPNODEP_CONSTP_BEING_USED */

#if defined(CONST_MAPBOARDPNODEPP_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined CONST_MAPBOARDPNODEPP_BEING_USED */

#if defined(MAP_BOARD_P_NODE_P_T_P_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined MAP_BOARD_P_NODE_P_T_P_BEING_USED */

#if defined(MAP_BOARD_P_NODE_P_T_CONST_P_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined MAP_BOARD_P_NODE_P_T_CONST_P_BEING_USED */

#if defined(CONST_MAP_BOARD_P_NODE_P_T_P_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined CONST_MAP_BOARD_P_NODE_P_T_P_BEING_USED */

#if defined(MAPBOARDPNODEP_P_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined MAPBOARDPNODEP_P_BEING_USED */

#if defined(MAPBOARDPNODEP_CONST_P_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined MAPBOARDPNODEP_CONST_P_BEING_USED */

#if defined(CONST_MAPBOARDPNODEP_P_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined CONST_MAPBOARDPNODEP_P_BEING_USED */

#if defined(MAPBOARDPNODEP_BEING_USED) && !defined(MAP_BOARD_P_NODE_P_NEED_HEADER)
#define MAP_BOARD_P_NODE_P_NEED_HEADER 1
#endif /* defined MAPBOARDPNODEP_BEING_USED */



#ifdef MAP_BOARD_P_NODE_P_NEED_HEADER
#include "map_board_p_node_p.h"
#endif

