
#if defined(VECTOR_CHAR_P_TP_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined VECTOR_CHAR_P_TP_BEING_USED */

#if defined(VECTOR_CHAR_P_T_CONSTP_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined VECTOR_CHAR_P_T_CONSTP_BEING_USED */

#if defined(CONST_VECTOR_CHAR_P_TP_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined CONST_VECTOR_CHAR_P_TP_BEING_USED */

#if defined(VECTORCHARPP_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined VECTORCHARPP_BEING_USED */

#if defined(VECTORCHARP_CONSTP_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined VECTORCHARP_CONSTP_BEING_USED */

#if defined(CONST_VECTORCHARPP_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined CONST_VECTORCHARPP_BEING_USED */

#if defined(VECTOR_CHAR_P_T_P_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined VECTOR_CHAR_P_T_P_BEING_USED */

#if defined(VECTOR_CHAR_P_T_CONST_P_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined VECTOR_CHAR_P_T_CONST_P_BEING_USED */

#if defined(CONST_VECTOR_CHAR_P_T_P_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined CONST_VECTOR_CHAR_P_T_P_BEING_USED */

#if defined(VECTORCHARP_P_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined VECTORCHARP_P_BEING_USED */

#if defined(VECTORCHARP_CONST_P_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined VECTORCHARP_CONST_P_BEING_USED */

#if defined(CONST_VECTORCHARP_P_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined CONST_VECTORCHARP_P_BEING_USED */

#if defined(VECTORCHARP_BEING_USED) && !defined(VECTOR_CHAR_P_NEED_HEADER)
#define VECTOR_CHAR_P_NEED_HEADER 1
#endif /* defined VECTORCHARP_BEING_USED */



#ifdef VECTOR_CHAR_P_NEED_HEADER
#include "vector_char_p.h"
#endif

