
#if defined(VECTOR_NODE_P_TP_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined VECTOR_NODE_P_TP_BEING_USED */

#if defined(VECTOR_NODE_P_T_CONSTP_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined VECTOR_NODE_P_T_CONSTP_BEING_USED */

#if defined(CONST_VECTOR_NODE_P_TP_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined CONST_VECTOR_NODE_P_TP_BEING_USED */

#if defined(VECTORNODEPP_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined VECTORNODEPP_BEING_USED */

#if defined(VECTORNODEP_CONSTP_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined VECTORNODEP_CONSTP_BEING_USED */

#if defined(CONST_VECTORNODEPP_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined CONST_VECTORNODEPP_BEING_USED */

#if defined(VECTOR_NODE_P_T_P_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined VECTOR_NODE_P_T_P_BEING_USED */

#if defined(VECTOR_NODE_P_T_CONST_P_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined VECTOR_NODE_P_T_CONST_P_BEING_USED */

#if defined(CONST_VECTOR_NODE_P_T_P_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined CONST_VECTOR_NODE_P_T_P_BEING_USED */

#if defined(VECTORNODEP_P_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined VECTORNODEP_P_BEING_USED */

#if defined(VECTORNODEP_CONST_P_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined VECTORNODEP_CONST_P_BEING_USED */

#if defined(CONST_VECTORNODEP_P_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined CONST_VECTORNODEP_P_BEING_USED */

#if defined(VECTORNODEP_BEING_USED) && !defined(VECTOR_NODE_P_NEED_HEADER)
#define VECTOR_NODE_P_NEED_HEADER 1
#endif /* defined VECTORNODEP_BEING_USED */



#ifdef VECTOR_NODE_P_NEED_HEADER
#include "vector_node_p.h"
#endif

