
#if defined(VECTOR_EDGE_P_TP_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined VECTOR_EDGE_P_TP_BEING_USED */

#if defined(VECTOR_EDGE_P_T_CONSTP_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined VECTOR_EDGE_P_T_CONSTP_BEING_USED */

#if defined(CONST_VECTOR_EDGE_P_TP_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined CONST_VECTOR_EDGE_P_TP_BEING_USED */

#if defined(VECTOREDGEPP_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined VECTOREDGEPP_BEING_USED */

#if defined(VECTOREDGEP_CONSTP_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined VECTOREDGEP_CONSTP_BEING_USED */

#if defined(CONST_VECTOREDGEPP_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined CONST_VECTOREDGEPP_BEING_USED */

#if defined(VECTOR_EDGE_P_T_P_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined VECTOR_EDGE_P_T_P_BEING_USED */

#if defined(VECTOR_EDGE_P_T_CONST_P_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined VECTOR_EDGE_P_T_CONST_P_BEING_USED */

#if defined(CONST_VECTOR_EDGE_P_T_P_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined CONST_VECTOR_EDGE_P_T_P_BEING_USED */

#if defined(VECTOREDGEP_P_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined VECTOREDGEP_P_BEING_USED */

#if defined(VECTOREDGEP_CONST_P_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined VECTOREDGEP_CONST_P_BEING_USED */

#if defined(CONST_VECTOREDGEP_P_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined CONST_VECTOREDGEP_P_BEING_USED */

#if defined(VECTOREDGEP_BEING_USED) && !defined(VECTOR_EDGE_P_NEED_HEADER)
#define VECTOR_EDGE_P_NEED_HEADER 1
#endif /* defined VECTOREDGEP_BEING_USED */



#ifdef VECTOR_EDGE_P_NEED_HEADER
#include "vector_edge_p.h"
#endif

