
#if defined(VECTOR_CAR_P_TP_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined VECTOR_CAR_P_TP_BEING_USED */

#if defined(VECTOR_CAR_P_T_CONSTP_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined VECTOR_CAR_P_T_CONSTP_BEING_USED */

#if defined(CONST_VECTOR_CAR_P_TP_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined CONST_VECTOR_CAR_P_TP_BEING_USED */

#if defined(VECTORCARPP_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined VECTORCARPP_BEING_USED */

#if defined(VECTORCARP_CONSTP_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined VECTORCARP_CONSTP_BEING_USED */

#if defined(CONST_VECTORCARPP_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined CONST_VECTORCARPP_BEING_USED */

#if defined(VECTOR_CAR_P_T_P_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined VECTOR_CAR_P_T_P_BEING_USED */

#if defined(VECTOR_CAR_P_T_CONST_P_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined VECTOR_CAR_P_T_CONST_P_BEING_USED */

#if defined(CONST_VECTOR_CAR_P_T_P_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined CONST_VECTOR_CAR_P_T_P_BEING_USED */

#if defined(VECTORCARP_P_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined VECTORCARP_P_BEING_USED */

#if defined(VECTORCARP_CONST_P_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined VECTORCARP_CONST_P_BEING_USED */

#if defined(CONST_VECTORCARP_P_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined CONST_VECTORCARP_P_BEING_USED */

#if defined(VECTORCARP_BEING_USED) && !defined(VECTOR_CAR_P_NEED_HEADER)
#define VECTOR_CAR_P_NEED_HEADER 1
#endif /* defined VECTORCARP_BEING_USED */



#ifdef VECTOR_CAR_P_NEED_HEADER
#include "vector_car_p.h"
#endif

