
#if defined(VECTOR_BOARD_P_TP_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined VECTOR_BOARD_P_TP_BEING_USED */

#if defined(VECTOR_BOARD_P_T_CONSTP_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined VECTOR_BOARD_P_T_CONSTP_BEING_USED */

#if defined(CONST_VECTOR_BOARD_P_TP_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined CONST_VECTOR_BOARD_P_TP_BEING_USED */

#if defined(VECTORBOARDPP_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined VECTORBOARDPP_BEING_USED */

#if defined(VECTORBOARDP_CONSTP_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined VECTORBOARDP_CONSTP_BEING_USED */

#if defined(CONST_VECTORBOARDPP_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined CONST_VECTORBOARDPP_BEING_USED */

#if defined(VECTOR_BOARD_P_T_P_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined VECTOR_BOARD_P_T_P_BEING_USED */

#if defined(VECTOR_BOARD_P_T_CONST_P_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined VECTOR_BOARD_P_T_CONST_P_BEING_USED */

#if defined(CONST_VECTOR_BOARD_P_T_P_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined CONST_VECTOR_BOARD_P_T_P_BEING_USED */

#if defined(VECTORBOARDP_P_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined VECTORBOARDP_P_BEING_USED */

#if defined(VECTORBOARDP_CONST_P_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined VECTORBOARDP_CONST_P_BEING_USED */

#if defined(CONST_VECTORBOARDP_P_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined CONST_VECTORBOARDP_P_BEING_USED */

#if defined(VECTORBOARDP_BEING_USED) && !defined(VECTOR_BOARD_P_NEED_HEADER)
#define VECTOR_BOARD_P_NEED_HEADER 1
#endif /* defined VECTORBOARDP_BEING_USED */



#ifdef VECTOR_BOARD_P_NEED_HEADER
#include "vector_board_p.h"
#endif

