
#ifndef ERWIN_ERR_V_CHAR_CONST_P_f_h
#define ERWIN_ERR_V_CHAR_CONST_P_f_h

/* Unification of ErrVCharConstP and err_v_char_const_p_t: they are identical now. */
struct err_v_char_const_p_t;

#ifndef __cplusplus
typedef struct err_v_char_const_p_t err_v_char_const_p_t;
#endif /* not defined __cplusplus */

typedef err_v_char_const_p_t ErrVCharConstP;

typedef err_v_char_const_p_t *err_v_char_const_p_t_p;

typedef err_v_char_const_p_t const *err_v_char_const_p_t_const_p;

#define ERR_V_CHAR_CONST_P_SIG 860961882



#ifdef ERR_ERR_V_CHAR_CONST_P_TP_DEEP
#  if ERR_ERR_V_CHAR_CONST_P_TP_DEEP
#    ifndef ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COPY
#      define ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE
#      define ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COPY
#      define ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE
#      define ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COPY
#define ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COPY 0
#endif /* !defined ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COPY */

#ifndef ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE
#define ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE */

#ifdef ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP
#  if ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP
#    ifndef ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COPY
#      define ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COPY
#      define ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COPY
#define ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COPY */

#ifndef ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COMPARE
#define ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP
#  if ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP
#    ifndef ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COPY
#      define ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COPY
#      define ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COPY
#define ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COPY */

#ifndef ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE
#define ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE */

#ifdef ERR_ERRVCHARCONSTPP_DEEP
#  if ERR_ERRVCHARCONSTPP_DEEP
#    ifndef ERR_ERRVCHARCONSTPP_DEEP_COPY
#      define ERR_ERRVCHARCONSTPP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRVCHARCONSTPP_DEEP_COMPARE
#      define ERR_ERRVCHARCONSTPP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRVCHARCONSTPP_DEEP_COPY
#      define ERR_ERRVCHARCONSTPP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRVCHARCONSTPP_DEEP_COMPARE
#      define ERR_ERRVCHARCONSTPP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRVCHARCONSTPP_DEEP_COPY
#define ERR_ERRVCHARCONSTPP_DEEP_COPY 0
#endif /* !defined ERR_ERRVCHARCONSTPP_DEEP_COPY */

#ifndef ERR_ERRVCHARCONSTPP_DEEP_COMPARE
#define ERR_ERRVCHARCONSTPP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRVCHARCONSTPP_DEEP_COMPARE */

#ifdef ERR_ERRVCHARCONSTP_CONSTP_DEEP
#  if ERR_ERRVCHARCONSTP_CONSTP_DEEP
#    ifndef ERR_ERRVCHARCONSTP_CONSTP_DEEP_COPY
#      define ERR_ERRVCHARCONSTP_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRVCHARCONSTP_CONSTP_DEEP_COMPARE
#      define ERR_ERRVCHARCONSTP_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRVCHARCONSTP_CONSTP_DEEP_COPY
#      define ERR_ERRVCHARCONSTP_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRVCHARCONSTP_CONSTP_DEEP_COMPARE
#      define ERR_ERRVCHARCONSTP_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRVCHARCONSTP_CONSTP_DEEP_COPY
#define ERR_ERRVCHARCONSTP_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERRVCHARCONSTP_CONSTP_DEEP_COPY */

#ifndef ERR_ERRVCHARCONSTP_CONSTP_DEEP_COMPARE
#define ERR_ERRVCHARCONSTP_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRVCHARCONSTP_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERRVCHARCONSTPP_DEEP
#  if ERR_CONST_ERRVCHARCONSTPP_DEEP
#    ifndef ERR_CONST_ERRVCHARCONSTPP_DEEP_COPY
#      define ERR_CONST_ERRVCHARCONSTPP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRVCHARCONSTPP_DEEP_COMPARE
#      define ERR_CONST_ERRVCHARCONSTPP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRVCHARCONSTPP_DEEP_COPY
#      define ERR_CONST_ERRVCHARCONSTPP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRVCHARCONSTPP_DEEP_COMPARE
#      define ERR_CONST_ERRVCHARCONSTPP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRVCHARCONSTPP_DEEP_COPY
#define ERR_CONST_ERRVCHARCONSTPP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRVCHARCONSTPP_DEEP_COPY */

#ifndef ERR_CONST_ERRVCHARCONSTPP_DEEP_COMPARE
#define ERR_CONST_ERRVCHARCONSTPP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRVCHARCONSTPP_DEEP_COMPARE */

#ifdef ERR_ERR_V_CHAR_CONST_P_T_P_DEEP
#  if ERR_ERR_V_CHAR_CONST_P_T_P_DEEP
#    ifndef ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY
#      define ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE
#      define ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY
#      define ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE
#      define ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY
#define ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY */

#ifndef ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE
#define ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE */

#ifdef ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP
#  if ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP
#    ifndef ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COPY
#      define ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COPY
#      define ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COPY
#define ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COPY */

#ifndef ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COMPARE
#define ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP
#  if ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP
#    ifndef ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY
#      define ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY
#      define ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY
#define ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY */

#ifndef ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE
#define ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE */

#ifdef ERR_ERRVCHARCONSTP_P_DEEP
#  if ERR_ERRVCHARCONSTP_P_DEEP
#    ifndef ERR_ERRVCHARCONSTP_P_DEEP_COPY
#      define ERR_ERRVCHARCONSTP_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRVCHARCONSTP_P_DEEP_COMPARE
#      define ERR_ERRVCHARCONSTP_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRVCHARCONSTP_P_DEEP_COPY
#      define ERR_ERRVCHARCONSTP_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRVCHARCONSTP_P_DEEP_COMPARE
#      define ERR_ERRVCHARCONSTP_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRVCHARCONSTP_P_DEEP_COPY
#define ERR_ERRVCHARCONSTP_P_DEEP_COPY 0
#endif /* !defined ERR_ERRVCHARCONSTP_P_DEEP_COPY */

#ifndef ERR_ERRVCHARCONSTP_P_DEEP_COMPARE
#define ERR_ERRVCHARCONSTP_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRVCHARCONSTP_P_DEEP_COMPARE */

#ifdef ERR_ERRVCHARCONSTP_CONST_P_DEEP
#  if ERR_ERRVCHARCONSTP_CONST_P_DEEP
#    ifndef ERR_ERRVCHARCONSTP_CONST_P_DEEP_COPY
#      define ERR_ERRVCHARCONSTP_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRVCHARCONSTP_CONST_P_DEEP_COMPARE
#      define ERR_ERRVCHARCONSTP_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRVCHARCONSTP_CONST_P_DEEP_COPY
#      define ERR_ERRVCHARCONSTP_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRVCHARCONSTP_CONST_P_DEEP_COMPARE
#      define ERR_ERRVCHARCONSTP_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRVCHARCONSTP_CONST_P_DEEP_COPY
#define ERR_ERRVCHARCONSTP_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERRVCHARCONSTP_CONST_P_DEEP_COPY */

#ifndef ERR_ERRVCHARCONSTP_CONST_P_DEEP_COMPARE
#define ERR_ERRVCHARCONSTP_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRVCHARCONSTP_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERRVCHARCONSTP_P_DEEP
#  if ERR_CONST_ERRVCHARCONSTP_P_DEEP
#    ifndef ERR_CONST_ERRVCHARCONSTP_P_DEEP_COPY
#      define ERR_CONST_ERRVCHARCONSTP_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRVCHARCONSTP_P_DEEP_COMPARE
#      define ERR_CONST_ERRVCHARCONSTP_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRVCHARCONSTP_P_DEEP_COPY
#      define ERR_CONST_ERRVCHARCONSTP_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRVCHARCONSTP_P_DEEP_COMPARE
#      define ERR_CONST_ERRVCHARCONSTP_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRVCHARCONSTP_P_DEEP_COPY
#define ERR_CONST_ERRVCHARCONSTP_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRVCHARCONSTP_P_DEEP_COPY */

#ifndef ERR_CONST_ERRVCHARCONSTP_P_DEEP_COMPARE
#define ERR_CONST_ERRVCHARCONSTP_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRVCHARCONSTP_P_DEEP_COMPARE */

#if ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE && !defined(ERR_ERR_V_CHAR_CONST_P_TP_HASH_RAW)
#define ERR_ERR_V_CHAR_CONST_P_TP_HASH_RAW(A1) err_v_char_const_p_hash_raw((A1))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_V_CHAR_CONST_P_T_CONSTP_HASH_RAW)
#define ERR_ERR_V_CHAR_CONST_P_T_CONSTP_HASH_RAW(A1) err_v_char_const_p_hash_raw((A1))
#endif

#if ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_V_CHAR_CONST_P_TP_HASH_RAW)
#define ERR_CONST_ERR_V_CHAR_CONST_P_TP_HASH_RAW(A1) err_v_char_const_p_hash_raw((A1))
#endif

#if ERR_ERRVCHARCONSTPP_DEEP_COMPARE && !defined(ERR_ERRVCHARCONSTPP_HASH_RAW)
#define ERR_ERRVCHARCONSTPP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRVCHARCONSTP_CONSTP_DEEP_COMPARE && !defined(ERR_ERRVCHARCONSTP_CONSTP_HASH_RAW)
#define ERR_ERRVCHARCONSTP_CONSTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRVCHARCONSTPP_DEEP_COMPARE && !defined(ERR_CONST_ERRVCHARCONSTPP_HASH_RAW)
#define ERR_CONST_ERRVCHARCONSTPP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE && !defined(ERR_ERR_V_CHAR_CONST_P_T_P_HASH_RAW)
#define ERR_ERR_V_CHAR_CONST_P_T_P_HASH_RAW(A1) err_v_char_const_p_hash_raw((A1))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_V_CHAR_CONST_P_T_CONST_P_HASH_RAW)
#define ERR_ERR_V_CHAR_CONST_P_T_CONST_P_HASH_RAW(A1) err_v_char_const_p_hash_raw((A1))
#endif

#if ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_V_CHAR_CONST_P_T_P_HASH_RAW)
#define ERR_CONST_ERR_V_CHAR_CONST_P_T_P_HASH_RAW(A1) err_v_char_const_p_hash_raw((A1))
#endif

#if ERR_ERRVCHARCONSTP_P_DEEP_COMPARE && !defined(ERR_ERRVCHARCONSTP_P_HASH_RAW)
#define ERR_ERRVCHARCONSTP_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRVCHARCONSTP_CONST_P_DEEP_COMPARE && !defined(ERR_ERRVCHARCONSTP_CONST_P_HASH_RAW)
#define ERR_ERRVCHARCONSTP_CONST_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRVCHARCONSTP_P_DEEP_COMPARE && !defined(ERR_CONST_ERRVCHARCONSTP_P_HASH_RAW)
#define ERR_CONST_ERRVCHARCONSTP_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#ifndef ERR_ERRVCHARCONSTP_HASH_RAW
#define ERR_ERRVCHARCONSTP_HASH_RAW(A1) ((A1).hash_raw())
#endif

#if ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE && !defined(ERR_ERR_V_CHAR_CONST_P_TP_CMP)
#define ERR_ERR_V_CHAR_CONST_P_TP_CMP(A1,A2) err_v_char_const_p_cmp((A1),(A2),NULL)
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_V_CHAR_CONST_P_T_CONSTP_CMP)
#define ERR_ERR_V_CHAR_CONST_P_T_CONSTP_CMP(A1,A2) err_v_char_const_p_cmp((A1),(A2),NULL)
#endif

#if ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_V_CHAR_CONST_P_TP_CMP)
#define ERR_CONST_ERR_V_CHAR_CONST_P_TP_CMP(A1,A2) err_v_char_const_p_cmp((A1),(A2),NULL)
#endif

#if ERR_ERRVCHARCONSTPP_DEEP_COMPARE && !defined(ERR_ERRVCHARCONSTPP_CMP)
#define ERR_ERRVCHARCONSTPP_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_ERRVCHARCONSTP_CONSTP_DEEP_COMPARE && !defined(ERR_ERRVCHARCONSTP_CONSTP_CMP)
#define ERR_ERRVCHARCONSTP_CONSTP_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_CONST_ERRVCHARCONSTPP_DEEP_COMPARE && !defined(ERR_CONST_ERRVCHARCONSTPP_CMP)
#define ERR_CONST_ERRVCHARCONSTPP_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE && !defined(ERR_ERR_V_CHAR_CONST_P_T_P_CMP)
#define ERR_ERR_V_CHAR_CONST_P_T_P_CMP(A1,A2) err_v_char_const_p_cmp((A1),(A2),NULL)
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_V_CHAR_CONST_P_T_CONST_P_CMP)
#define ERR_ERR_V_CHAR_CONST_P_T_CONST_P_CMP(A1,A2) err_v_char_const_p_cmp((A1),(A2),NULL)
#endif

#if ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_V_CHAR_CONST_P_T_P_CMP)
#define ERR_CONST_ERR_V_CHAR_CONST_P_T_P_CMP(A1,A2) err_v_char_const_p_cmp((A1),(A2),NULL)
#endif

#if ERR_ERRVCHARCONSTP_P_DEEP_COMPARE && !defined(ERR_ERRVCHARCONSTP_P_CMP)
#define ERR_ERRVCHARCONSTP_P_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_ERRVCHARCONSTP_CONST_P_DEEP_COMPARE && !defined(ERR_ERRVCHARCONSTP_CONST_P_CMP)
#define ERR_ERRVCHARCONSTP_CONST_P_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_CONST_ERRVCHARCONSTP_P_DEEP_COMPARE && !defined(ERR_CONST_ERRVCHARCONSTP_P_CMP)
#define ERR_CONST_ERRVCHARCONSTP_P_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#ifndef ERR_ERRVCHARCONSTP_CMP
#define ERR_ERRVCHARCONSTP_CMP(A1,A2) ((A1).cmp((A2),NULL))
#endif

#ifndef ERR_ERRVCHARCONSTP_ZERO
#define ERR_ERRVCHARCONSTP_ZERO (ErrVCharConstP::static_zero())
#endif

#if ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_TP_ICOPY)
#define ERR_ERR_V_CHAR_CONST_P_TP_ICOPY(A1,A2) err_v_char_const_p_copy_err((A1),(A2))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_T_CONSTP_ICOPY)
#define ERR_ERR_V_CHAR_CONST_P_T_CONSTP_ICOPY(A1,A2) err_v_char_const_p_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COPY && !defined(ERR_CONST_ERR_V_CHAR_CONST_P_TP_ICOPY)
#define ERR_CONST_ERR_V_CHAR_CONST_P_TP_ICOPY(A1,A2) err_v_char_const_p_copy_err((A1),(A2))
#endif

#if ERR_ERRVCHARCONSTPP_DEEP_COPY && !defined(ERR_ERRVCHARCONSTPP_ICOPY)
#define ERR_ERRVCHARCONSTPP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRVCHARCONSTP_CONSTP_DEEP_COPY && !defined(ERR_ERRVCHARCONSTP_CONSTP_ICOPY)
#define ERR_ERRVCHARCONSTP_CONSTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRVCHARCONSTPP_DEEP_COPY && !defined(ERR_CONST_ERRVCHARCONSTPP_ICOPY)
#define ERR_CONST_ERRVCHARCONSTPP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_T_P_ICOPY)
#define ERR_ERR_V_CHAR_CONST_P_T_P_ICOPY(A1,A2) err_v_char_const_p_copy_err((A1),(A2))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_T_CONST_P_ICOPY)
#define ERR_ERR_V_CHAR_CONST_P_T_CONST_P_ICOPY(A1,A2) err_v_char_const_p_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_V_CHAR_CONST_P_T_P_ICOPY)
#define ERR_CONST_ERR_V_CHAR_CONST_P_T_P_ICOPY(A1,A2) err_v_char_const_p_copy_err((A1),(A2))
#endif

#if ERR_ERRVCHARCONSTP_P_DEEP_COPY && !defined(ERR_ERRVCHARCONSTP_P_ICOPY)
#define ERR_ERRVCHARCONSTP_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRVCHARCONSTP_CONST_P_DEEP_COPY && !defined(ERR_ERRVCHARCONSTP_CONST_P_ICOPY)
#define ERR_ERRVCHARCONSTP_CONST_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRVCHARCONSTP_P_DEEP_COPY && !defined(ERR_CONST_ERRVCHARCONSTP_P_ICOPY)
#define ERR_CONST_ERRVCHARCONSTP_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_TP_OCOPY)
#define ERR_ERR_V_CHAR_CONST_P_TP_OCOPY(A1,A2) err_v_char_const_p_copy_err((A1),(A2))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_T_CONSTP_OCOPY)
#define ERR_ERR_V_CHAR_CONST_P_T_CONSTP_OCOPY(A1,A2) err_v_char_const_p_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COPY && !defined(ERR_CONST_ERR_V_CHAR_CONST_P_TP_OCOPY)
#define ERR_CONST_ERR_V_CHAR_CONST_P_TP_OCOPY(A1,A2) err_v_char_const_p_copy_err((A1),(A2))
#endif

#if ERR_ERRVCHARCONSTPP_DEEP_COPY && !defined(ERR_ERRVCHARCONSTPP_OCOPY)
#define ERR_ERRVCHARCONSTPP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRVCHARCONSTP_CONSTP_DEEP_COPY && !defined(ERR_ERRVCHARCONSTP_CONSTP_OCOPY)
#define ERR_ERRVCHARCONSTP_CONSTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRVCHARCONSTPP_DEEP_COPY && !defined(ERR_CONST_ERRVCHARCONSTPP_OCOPY)
#define ERR_CONST_ERRVCHARCONSTPP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_T_P_OCOPY)
#define ERR_ERR_V_CHAR_CONST_P_T_P_OCOPY(A1,A2) err_v_char_const_p_copy_err((A1),(A2))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_T_CONST_P_OCOPY)
#define ERR_ERR_V_CHAR_CONST_P_T_CONST_P_OCOPY(A1,A2) err_v_char_const_p_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_V_CHAR_CONST_P_T_P_OCOPY)
#define ERR_CONST_ERR_V_CHAR_CONST_P_T_P_OCOPY(A1,A2) err_v_char_const_p_copy_err((A1),(A2))
#endif

#if ERR_ERRVCHARCONSTP_P_DEEP_COPY && !defined(ERR_ERRVCHARCONSTP_P_OCOPY)
#define ERR_ERRVCHARCONSTP_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRVCHARCONSTP_CONST_P_DEEP_COPY && !defined(ERR_ERRVCHARCONSTP_CONST_P_OCOPY)
#define ERR_ERRVCHARCONSTP_CONST_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRVCHARCONSTP_P_DEEP_COPY && !defined(ERR_CONST_ERRVCHARCONSTP_P_OCOPY)
#define ERR_CONST_ERRVCHARCONSTP_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_TP_IFREE)
#define ERR_ERR_V_CHAR_CONST_P_TP_IFREE(A1) err_v_char_const_p_delete((A1))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_T_CONSTP_IFREE)
#define ERR_ERR_V_CHAR_CONST_P_T_CONSTP_IFREE(A1) err_v_char_const_p_delete((A1))
#endif

#if ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COPY && !defined(ERR_CONST_ERR_V_CHAR_CONST_P_TP_IFREE)
#define ERR_CONST_ERR_V_CHAR_CONST_P_TP_IFREE(A1) err_v_char_const_p_delete((A1))
#endif

#if ERR_ERRVCHARCONSTPP_DEEP_COPY && !defined(ERR_ERRVCHARCONSTPP_IFREE)
#define ERR_ERRVCHARCONSTPP_IFREE(A1) delete((A1))
#endif

#if ERR_ERRVCHARCONSTP_CONSTP_DEEP_COPY && !defined(ERR_ERRVCHARCONSTP_CONSTP_IFREE)
#define ERR_ERRVCHARCONSTP_CONSTP_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRVCHARCONSTPP_DEEP_COPY && !defined(ERR_CONST_ERRVCHARCONSTPP_IFREE)
#define ERR_CONST_ERRVCHARCONSTPP_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_T_P_IFREE)
#define ERR_ERR_V_CHAR_CONST_P_T_P_IFREE(A1) err_v_char_const_p_delete((A1))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_T_CONST_P_IFREE)
#define ERR_ERR_V_CHAR_CONST_P_T_CONST_P_IFREE(A1) err_v_char_const_p_delete((A1))
#endif

#if ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_V_CHAR_CONST_P_T_P_IFREE)
#define ERR_CONST_ERR_V_CHAR_CONST_P_T_P_IFREE(A1) err_v_char_const_p_delete((A1))
#endif

#if ERR_ERRVCHARCONSTP_P_DEEP_COPY && !defined(ERR_ERRVCHARCONSTP_P_IFREE)
#define ERR_ERRVCHARCONSTP_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERRVCHARCONSTP_CONST_P_DEEP_COPY && !defined(ERR_ERRVCHARCONSTP_CONST_P_IFREE)
#define ERR_ERRVCHARCONSTP_CONST_P_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRVCHARCONSTP_P_DEEP_COPY && !defined(ERR_CONST_ERRVCHARCONSTP_P_IFREE)
#define ERR_CONST_ERRVCHARCONSTP_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_V_CHAR_CONST_P_TP_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_TP_OFREE)
#define ERR_ERR_V_CHAR_CONST_P_TP_OFREE(A1) err_v_char_const_p_delete((A1))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_T_CONSTP_OFREE)
#define ERR_ERR_V_CHAR_CONST_P_T_CONSTP_OFREE(A1) err_v_char_const_p_delete((A1))
#endif

#if ERR_CONST_ERR_V_CHAR_CONST_P_TP_DEEP_COPY && !defined(ERR_CONST_ERR_V_CHAR_CONST_P_TP_OFREE)
#define ERR_CONST_ERR_V_CHAR_CONST_P_TP_OFREE(A1) err_v_char_const_p_delete((A1))
#endif

#if ERR_ERRVCHARCONSTPP_DEEP_COPY && !defined(ERR_ERRVCHARCONSTPP_OFREE)
#define ERR_ERRVCHARCONSTPP_OFREE(A1) delete((A1))
#endif

#if ERR_ERRVCHARCONSTP_CONSTP_DEEP_COPY && !defined(ERR_ERRVCHARCONSTP_CONSTP_OFREE)
#define ERR_ERRVCHARCONSTP_CONSTP_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRVCHARCONSTPP_DEEP_COPY && !defined(ERR_CONST_ERRVCHARCONSTPP_OFREE)
#define ERR_CONST_ERRVCHARCONSTPP_OFREE(A1) delete((A1))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_T_P_OFREE)
#define ERR_ERR_V_CHAR_CONST_P_T_P_OFREE(A1) err_v_char_const_p_delete((A1))
#endif

#if ERR_ERR_V_CHAR_CONST_P_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_V_CHAR_CONST_P_T_CONST_P_OFREE)
#define ERR_ERR_V_CHAR_CONST_P_T_CONST_P_OFREE(A1) err_v_char_const_p_delete((A1))
#endif

#if ERR_CONST_ERR_V_CHAR_CONST_P_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_V_CHAR_CONST_P_T_P_OFREE)
#define ERR_CONST_ERR_V_CHAR_CONST_P_T_P_OFREE(A1) err_v_char_const_p_delete((A1))
#endif

#if ERR_ERRVCHARCONSTP_P_DEEP_COPY && !defined(ERR_ERRVCHARCONSTP_P_OFREE)
#define ERR_ERRVCHARCONSTP_P_OFREE(A1) delete((A1))
#endif

#if ERR_ERRVCHARCONSTP_CONST_P_DEEP_COPY && !defined(ERR_ERRVCHARCONSTP_CONST_P_OFREE)
#define ERR_ERRVCHARCONSTP_CONST_P_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRVCHARCONSTP_P_DEEP_COPY && !defined(ERR_CONST_ERRVCHARCONSTP_P_OFREE)
#define ERR_CONST_ERRVCHARCONSTP_P_OFREE(A1) delete((A1))
#endif

#ifndef ERR_ERRVCHARCONSTP_CONSTRUCTOR
#define ERR_ERRVCHARCONSTP_CONSTRUCTOR(A1) ((A1)._constructor())
#endif

#ifndef ERR_ERRVCHARCONSTP_DESTRUCTOR
#define ERR_ERRVCHARCONSTP_DESTRUCTOR(A1) ((A1)._destructor())
#endif


#endif /* defined ERWIN_ERR_V_CHAR_CONST_P_f_h */

