
#if defined(ERR_ERR_V_CALLBACK_TP_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERR_V_CALLBACK_TP_BEING_USED */

#if defined(ERR_ERR_V_CALLBACK_T_CONSTP_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERR_V_CALLBACK_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_V_CALLBACK_TP_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_V_CALLBACK_TP_BEING_USED */

#if defined(ERR_ERRVCALLBACKP_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRVCALLBACKP_BEING_USED */

#if defined(ERR_ERRVCALLBACK_CONSTP_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRVCALLBACK_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRVCALLBACKP_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRVCALLBACKP_BEING_USED */

#if defined(ERR_ERR_V_CALLBACK_T_P_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERR_V_CALLBACK_T_P_BEING_USED */

#if defined(ERR_ERR_V_CALLBACK_T_CONST_P_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERR_V_CALLBACK_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_V_CALLBACK_T_P_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_V_CALLBACK_T_P_BEING_USED */

#if defined(ERR_ERRVCALLBACK_P_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRVCALLBACK_P_BEING_USED */

#if defined(ERR_ERRVCALLBACK_CONST_P_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRVCALLBACK_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRVCALLBACK_P_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRVCALLBACK_P_BEING_USED */

#if defined(ERR_ERRVCALLBACK_BEING_USED) && !defined(ERR_V_CALLBACK_NEED_HEADER)
#define ERR_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRVCALLBACK_BEING_USED */



#ifdef ERR_V_CALLBACK_NEED_HEADER
#include "error/err_v_callback.h"
#endif

