
#if defined(ERR_ERR_SYMTAB_TP_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_ERR_SYMTAB_TP_BEING_USED */

#if defined(ERR_ERR_SYMTAB_T_CONSTP_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_ERR_SYMTAB_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_SYMTAB_TP_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_SYMTAB_TP_BEING_USED */

#if defined(ERR_ERRSYMTABP_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_ERRSYMTABP_BEING_USED */

#if defined(ERR_ERRSYMTAB_CONSTP_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_ERRSYMTAB_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRSYMTABP_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRSYMTABP_BEING_USED */

#if defined(ERR_ERR_SYMTAB_T_P_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_ERR_SYMTAB_T_P_BEING_USED */

#if defined(ERR_ERR_SYMTAB_T_CONST_P_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_ERR_SYMTAB_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_SYMTAB_T_P_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_SYMTAB_T_P_BEING_USED */

#if defined(ERR_ERRSYMTAB_P_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_ERRSYMTAB_P_BEING_USED */

#if defined(ERR_ERRSYMTAB_CONST_P_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_ERRSYMTAB_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRSYMTAB_P_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRSYMTAB_P_BEING_USED */

#if defined(ERR_ERRSYMTAB_BEING_USED) && !defined(ERR_SYMTAB_NEED_HEADER)
#define ERR_SYMTAB_NEED_HEADER 1
#endif /* defined ERR_ERRSYMTAB_BEING_USED */



#ifdef ERR_SYMTAB_NEED_HEADER
#include "error/err_symtab.h"
#endif

