
#ifndef ERWIN_ERR_MAP_CHAR_P_CHAR_P_f_h
#define ERWIN_ERR_MAP_CHAR_P_CHAR_P_f_h

struct err_map_char_p_char_p_t;
#ifndef __cplusplus
typedef struct err_map_char_p_char_p_t err_map_char_p_char_p_t;
#endif
typedef struct err_map_char_p_char_p_t ErrMapCharPCharP;

typedef err_map_char_p_char_p_t *err_map_char_p_char_p_t_p;

typedef err_map_char_p_char_p_t const *err_map_char_p_char_p_t_const_p;

#define ERR_MAP_CHAR_P_CHAR_P_SIG 962769685



#ifdef ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP
#  if ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY
#define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY */

#ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE
#define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP
#  if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COPY
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COPY
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COPY
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COPY */

#ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COMPARE
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP
#  if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP
#    ifndef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY
#      define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY
#      define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY */

#ifndef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE */

#ifdef ERR_ERRMAPCHARPCHARPP_DEEP
#  if ERR_ERRMAPCHARPCHARPP_DEEP
#    ifndef ERR_ERRMAPCHARPCHARPP_DEEP_COPY
#      define ERR_ERRMAPCHARPCHARPP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPCHARPCHARPP_DEEP_COMPARE
#      define ERR_ERRMAPCHARPCHARPP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPCHARPCHARPP_DEEP_COPY
#      define ERR_ERRMAPCHARPCHARPP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPCHARPCHARPP_DEEP_COMPARE
#      define ERR_ERRMAPCHARPCHARPP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPCHARPCHARPP_DEEP_COPY
#define ERR_ERRMAPCHARPCHARPP_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPCHARPCHARPP_DEEP_COPY */

#ifndef ERR_ERRMAPCHARPCHARPP_DEEP_COMPARE
#define ERR_ERRMAPCHARPCHARPP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPCHARPCHARPP_DEEP_COMPARE */

#ifdef ERR_ERRMAPCHARPCHARP_CONSTP_DEEP
#  if ERR_ERRMAPCHARPCHARP_CONSTP_DEEP
#    ifndef ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COPY
#      define ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COMPARE
#      define ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COPY
#      define ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COMPARE
#      define ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COPY
#define ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COPY */

#ifndef ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COMPARE
#define ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERRMAPCHARPCHARPP_DEEP
#  if ERR_CONST_ERRMAPCHARPCHARPP_DEEP
#    ifndef ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COPY
#      define ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COMPARE
#      define ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COPY
#      define ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COMPARE
#      define ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COPY
#define ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COPY */

#ifndef ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COMPARE
#define ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP
#  if ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY */

#ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP
#  if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COPY
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COPY
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COPY
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COPY */

#ifndef ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COMPARE
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP
#  if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP
#    ifndef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY
#      define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY
#      define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY */

#ifndef ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE */

#ifdef ERR_ERRMAPCHARPCHARP_P_DEEP
#  if ERR_ERRMAPCHARPCHARP_P_DEEP
#    ifndef ERR_ERRMAPCHARPCHARP_P_DEEP_COPY
#      define ERR_ERRMAPCHARPCHARP_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPCHARPCHARP_P_DEEP_COMPARE
#      define ERR_ERRMAPCHARPCHARP_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPCHARPCHARP_P_DEEP_COPY
#      define ERR_ERRMAPCHARPCHARP_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPCHARPCHARP_P_DEEP_COMPARE
#      define ERR_ERRMAPCHARPCHARP_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPCHARPCHARP_P_DEEP_COPY
#define ERR_ERRMAPCHARPCHARP_P_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPCHARPCHARP_P_DEEP_COPY */

#ifndef ERR_ERRMAPCHARPCHARP_P_DEEP_COMPARE
#define ERR_ERRMAPCHARPCHARP_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPCHARPCHARP_P_DEEP_COMPARE */

#ifdef ERR_ERRMAPCHARPCHARP_CONST_P_DEEP
#  if ERR_ERRMAPCHARPCHARP_CONST_P_DEEP
#    ifndef ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COPY
#      define ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COMPARE
#      define ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COPY
#      define ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COMPARE
#      define ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COPY
#define ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COPY */

#ifndef ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COMPARE
#define ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERRMAPCHARPCHARP_P_DEEP
#  if ERR_CONST_ERRMAPCHARPCHARP_P_DEEP
#    ifndef ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COPY
#      define ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COMPARE
#      define ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COPY
#      define ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COMPARE
#      define ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COPY
#define ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COPY */

#ifndef ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COMPARE
#define ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COMPARE */

#if ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_TP_HASH_RAW)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_HASH_RAW(A1) err_map_char_p_char_p_hash_raw((A1))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_HASH_RAW)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_HASH_RAW(A1) err_map_char_p_char_p_hash_raw((A1))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_HASH_RAW)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_HASH_RAW(A1) err_map_char_p_char_p_hash_raw((A1))
#endif

#if ERR_ERRMAPCHARPCHARPP_DEEP_COMPARE && !defined(ERR_ERRMAPCHARPCHARPP_HASH_RAW)
#define ERR_ERRMAPCHARPCHARPP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPCHARPCHARP_CONSTP_HASH_RAW)
#define ERR_ERRMAPCHARPCHARP_CONSTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPCHARPCHARPP_HASH_RAW)
#define ERR_CONST_ERRMAPCHARPCHARPP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_HASH_RAW)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_HASH_RAW(A1) err_map_char_p_char_p_hash_raw((A1))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_HASH_RAW)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_HASH_RAW(A1) err_map_char_p_char_p_hash_raw((A1))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_HASH_RAW)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_HASH_RAW(A1) err_map_char_p_char_p_hash_raw((A1))
#endif

#if ERR_ERRMAPCHARPCHARP_P_DEEP_COMPARE && !defined(ERR_ERRMAPCHARPCHARP_P_HASH_RAW)
#define ERR_ERRMAPCHARPCHARP_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPCHARPCHARP_CONST_P_HASH_RAW)
#define ERR_ERRMAPCHARPCHARP_CONST_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPCHARPCHARP_P_HASH_RAW)
#define ERR_CONST_ERRMAPCHARPCHARP_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#ifndef ERR_ERRMAPCHARPCHARP_HASH_RAW
#define ERR_ERRMAPCHARPCHARP_HASH_RAW(A1) ((A1).hash_raw())
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_TP_CMP)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_CMP(A1,A2) err_map_char_p_char_p_cmp((A1),(A2))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_CMP)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_CMP(A1,A2) err_map_char_p_char_p_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_CMP)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_CMP(A1,A2) err_map_char_p_char_p_cmp((A1),(A2))
#endif

#if ERR_ERRMAPCHARPCHARPP_DEEP_COMPARE && !defined(ERR_ERRMAPCHARPCHARPP_CMP)
#define ERR_ERRMAPCHARPCHARPP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPCHARPCHARP_CONSTP_CMP)
#define ERR_ERRMAPCHARPCHARP_CONSTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPCHARPCHARPP_CMP)
#define ERR_CONST_ERRMAPCHARPCHARPP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_CMP)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_CMP(A1,A2) err_map_char_p_char_p_cmp((A1),(A2))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_CMP)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_CMP(A1,A2) err_map_char_p_char_p_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_CMP)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_CMP(A1,A2) err_map_char_p_char_p_cmp((A1),(A2))
#endif

#if ERR_ERRMAPCHARPCHARP_P_DEEP_COMPARE && !defined(ERR_ERRMAPCHARPCHARP_P_CMP)
#define ERR_ERRMAPCHARPCHARP_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPCHARPCHARP_CONST_P_CMP)
#define ERR_ERRMAPCHARPCHARP_CONST_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPCHARPCHARP_P_CMP)
#define ERR_CONST_ERRMAPCHARPCHARP_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#ifndef ERR_ERRMAPCHARPCHARP_CMP
#define ERR_ERRMAPCHARPCHARP_CMP(A1,A2) ((A1).cmp((A2)))
#endif

#ifndef ERR_ERRMAPCHARPCHARP_ZERO
#define ERR_ERRMAPCHARPCHARP_ZERO (ErrMapCharPCharP::static_zero())
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_TP_EQUAL)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_EQUAL(A1,A2) err_map_char_p_char_p_equal((A1),(A2))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_EQUAL)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_EQUAL(A1,A2) err_map_char_p_char_p_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_EQUAL)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_EQUAL(A1,A2) err_map_char_p_char_p_equal((A1),(A2))
#endif

#if ERR_ERRMAPCHARPCHARPP_DEEP_COMPARE && !defined(ERR_ERRMAPCHARPCHARPP_EQUAL)
#define ERR_ERRMAPCHARPCHARPP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPCHARPCHARP_CONSTP_EQUAL)
#define ERR_ERRMAPCHARPCHARP_CONSTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPCHARPCHARPP_EQUAL)
#define ERR_CONST_ERRMAPCHARPCHARPP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_EQUAL)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_EQUAL(A1,A2) err_map_char_p_char_p_equal((A1),(A2))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_EQUAL)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_EQUAL(A1,A2) err_map_char_p_char_p_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_EQUAL)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_EQUAL(A1,A2) err_map_char_p_char_p_equal((A1),(A2))
#endif

#if ERR_ERRMAPCHARPCHARP_P_DEEP_COMPARE && !defined(ERR_ERRMAPCHARPCHARP_P_EQUAL)
#define ERR_ERRMAPCHARPCHARP_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPCHARPCHARP_CONST_P_EQUAL)
#define ERR_ERRMAPCHARPCHARP_CONST_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPCHARPCHARP_P_EQUAL)
#define ERR_CONST_ERRMAPCHARPCHARP_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#ifndef ERR_ERRMAPCHARPCHARP_EQUAL
#define ERR_ERRMAPCHARPCHARP_EQUAL(A1,A2) ((A1).equal((A2)))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_TP_ICOPY)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_ICOPY(A1,A2) err_map_char_p_char_p_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_ICOPY)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_ICOPY(A1,A2) err_map_char_p_char_p_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_ICOPY)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_ICOPY(A1,A2) err_map_char_p_char_p_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPCHARPCHARPP_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARPP_ICOPY)
#define ERR_ERRMAPCHARPCHARPP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARP_CONSTP_ICOPY)
#define ERR_ERRMAPCHARPCHARP_CONSTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COPY && !defined(ERR_CONST_ERRMAPCHARPCHARPP_ICOPY)
#define ERR_CONST_ERRMAPCHARPCHARPP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_ICOPY)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_ICOPY(A1,A2) err_map_char_p_char_p_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_ICOPY)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_ICOPY(A1,A2) err_map_char_p_char_p_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_ICOPY)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_ICOPY(A1,A2) err_map_char_p_char_p_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPCHARPCHARP_P_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARP_P_ICOPY)
#define ERR_ERRMAPCHARPCHARP_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARP_CONST_P_ICOPY)
#define ERR_ERRMAPCHARPCHARP_CONST_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPCHARPCHARP_P_ICOPY)
#define ERR_CONST_ERRMAPCHARPCHARP_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_TP_OCOPY)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_OCOPY(A1,A2) err_map_char_p_char_p_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_OCOPY)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_OCOPY(A1,A2) err_map_char_p_char_p_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_OCOPY)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_OCOPY(A1,A2) err_map_char_p_char_p_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPCHARPCHARPP_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARPP_OCOPY)
#define ERR_ERRMAPCHARPCHARPP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARP_CONSTP_OCOPY)
#define ERR_ERRMAPCHARPCHARP_CONSTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COPY && !defined(ERR_CONST_ERRMAPCHARPCHARPP_OCOPY)
#define ERR_CONST_ERRMAPCHARPCHARPP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_OCOPY)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_OCOPY(A1,A2) err_map_char_p_char_p_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_OCOPY)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_OCOPY(A1,A2) err_map_char_p_char_p_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_OCOPY)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_OCOPY(A1,A2) err_map_char_p_char_p_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPCHARPCHARP_P_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARP_P_OCOPY)
#define ERR_ERRMAPCHARPCHARP_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARP_CONST_P_OCOPY)
#define ERR_ERRMAPCHARPCHARP_CONST_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPCHARPCHARP_P_OCOPY)
#define ERR_CONST_ERRMAPCHARPCHARP_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_TP_IFREE)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_IFREE(A1) err_map_char_p_char_p_delete((A1))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_IFREE)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_IFREE(A1) err_map_char_p_char_p_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_IFREE)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_IFREE(A1) err_map_char_p_char_p_delete((A1))
#endif

#if ERR_ERRMAPCHARPCHARPP_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARPP_IFREE)
#define ERR_ERRMAPCHARPCHARPP_IFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARP_CONSTP_IFREE)
#define ERR_ERRMAPCHARPCHARP_CONSTP_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COPY && !defined(ERR_CONST_ERRMAPCHARPCHARPP_IFREE)
#define ERR_CONST_ERRMAPCHARPCHARPP_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_IFREE)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_IFREE(A1) err_map_char_p_char_p_delete((A1))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_IFREE)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_IFREE(A1) err_map_char_p_char_p_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_IFREE)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_IFREE(A1) err_map_char_p_char_p_delete((A1))
#endif

#if ERR_ERRMAPCHARPCHARP_P_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARP_P_IFREE)
#define ERR_ERRMAPCHARPCHARP_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARP_CONST_P_IFREE)
#define ERR_ERRMAPCHARPCHARP_CONST_P_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPCHARPCHARP_P_IFREE)
#define ERR_CONST_ERRMAPCHARPCHARP_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_TP_OFREE)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_TP_OFREE(A1) err_map_char_p_char_p_delete((A1))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_OFREE)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_OFREE(A1) err_map_char_p_char_p_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_OFREE)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_OFREE(A1) err_map_char_p_char_p_delete((A1))
#endif

#if ERR_ERRMAPCHARPCHARPP_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARPP_OFREE)
#define ERR_ERRMAPCHARPCHARPP_OFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPCHARPCHARP_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARP_CONSTP_OFREE)
#define ERR_ERRMAPCHARPCHARP_CONSTP_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPCHARPCHARPP_DEEP_COPY && !defined(ERR_CONST_ERRMAPCHARPCHARPP_OFREE)
#define ERR_CONST_ERRMAPCHARPCHARPP_OFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_OFREE)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_OFREE(A1) err_map_char_p_char_p_delete((A1))
#endif

#if ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_OFREE)
#define ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_OFREE(A1) err_map_char_p_char_p_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_OFREE)
#define ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_OFREE(A1) err_map_char_p_char_p_delete((A1))
#endif

#if ERR_ERRMAPCHARPCHARP_P_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARP_P_OFREE)
#define ERR_ERRMAPCHARPCHARP_P_OFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPCHARPCHARP_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPCHARPCHARP_CONST_P_OFREE)
#define ERR_ERRMAPCHARPCHARP_CONST_P_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPCHARPCHARP_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPCHARPCHARP_P_OFREE)
#define ERR_CONST_ERRMAPCHARPCHARP_P_OFREE(A1) delete((A1))
#endif

#ifndef ERR_ERRMAPCHARPCHARP_CONSTRUCTOR
#define ERR_ERRMAPCHARPCHARP_CONSTRUCTOR(A1) ((A1)._constructor())
#endif

#ifndef ERR_ERRMAPCHARPCHARP_DESTRUCTOR
#define ERR_ERRMAPCHARPCHARP_DESTRUCTOR(A1) ((A1)._destructor())
#endif


#endif /* defined ERWIN_ERR_MAP_CHAR_P_CHAR_P_f_h */

