
#ifndef ERWIN_ERR_MAP_SYMBOL_INT_ti_h
#define ERWIN_ERR_MAP_SYMBOL_INT_ti_h

#define err_map_symbol_int_hashlist_t_KIND STRUCT
#define err_map_symbol_int_hashlist_t_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_int_hashlist_t)
extern  TYPE_INFO_T(err_map_symbol_int_hashlist_t);

#define err_map_symbol_int_hashlist_t_p_KIND  POINTER
#define err_map_symbol_int_hashlist_t_p_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_int_hashlist_t_p)
extern  TYPE_INFO_T(err_map_symbol_int_hashlist_t_p);

#define err_map_symbol_int_hashlist_t_const_p_KIND POINTER
#define err_map_symbol_int_hashlist_t_const_p_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_int_hashlist_t_const_p)
extern  TYPE_INFO_T(err_map_symbol_int_hashlist_t_const_p);

#define err_map_symbol_int_internal_Iterator_KIND STRUCT
#define err_map_symbol_int_internal_Iterator_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_int_internal_Iterator)
extern  TYPE_INFO_T(err_map_symbol_int_internal_Iterator);

#define err_map_symbol_int_t_KIND STRUCT
#define err_map_symbol_int_t_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_int_t)
extern  TYPE_INFO_T(err_map_symbol_int_t);

#define err_map_symbol_int_t_p_KIND POINTER
#define err_map_symbol_int_t_p_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_int_t_p)
extern  TYPE_INFO_T(err_map_symbol_int_t_p);

#define err_map_symbol_int_t_const_p_KIND POINTER
#define err_map_symbol_int_t_const_p_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_int_t_const_p)
extern  TYPE_INFO_T(err_map_symbol_int_t_const_p);

#define err_map_symbol_int_content_KIND VECTOR
#define err_map_symbol_int_content_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_int_content)
extern  TYPE_INFO_T(err_map_symbol_int_content);

#define err_map_symbol_int_content_p_KIND POINTER
#define err_map_symbol_int_content_p_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_int_content_p)
extern  TYPE_INFO_T(err_map_symbol_int_content_p);

#define ErrMapSymbolInt_TYPE_INFO          err_map_symbol_int_t_TYPE_INFO
#define ErrMapSymbolInt_p_TYPE_INFO        err_map_symbol_int_t_p_TYPE_INFO
#define ErrMapSymbolInt_const_p_TYPE_INFO  err_map_symbol_int_t_const_p_TYPE_INFO

#endif /* defined ERWIN_ERR_MAP_SYMBOL_INT_ti_h */

