
#if defined(ERR_ERR_MAP_FILE_STREAM_TP_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_FILE_STREAM_TP_BEING_USED */

#if defined(ERR_ERR_MAP_FILE_STREAM_T_CONSTP_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_FILE_STREAM_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_FILE_STREAM_TP_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_FILE_STREAM_TP_BEING_USED */

#if defined(ERR_ERRMAPFILESTREAMP_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPFILESTREAMP_BEING_USED */

#if defined(ERR_ERRMAPFILESTREAM_CONSTP_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPFILESTREAM_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRMAPFILESTREAMP_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPFILESTREAMP_BEING_USED */

#if defined(ERR_ERR_MAP_FILE_STREAM_T_P_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_FILE_STREAM_T_P_BEING_USED */

#if defined(ERR_ERR_MAP_FILE_STREAM_T_CONST_P_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_FILE_STREAM_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_FILE_STREAM_T_P_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_FILE_STREAM_T_P_BEING_USED */

#if defined(ERR_ERRMAPFILESTREAM_P_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPFILESTREAM_P_BEING_USED */

#if defined(ERR_ERRMAPFILESTREAM_CONST_P_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPFILESTREAM_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRMAPFILESTREAM_P_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPFILESTREAM_P_BEING_USED */

#if defined(ERR_ERRMAPFILESTREAM_BEING_USED) && !defined(ERR_MAP_FILE_STREAM_NEED_HEADER)
#define ERR_MAP_FILE_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPFILESTREAM_BEING_USED */



#ifdef ERR_MAP_FILE_STREAM_NEED_HEADER
#include "error/err_map_file_stream.h"
#endif

