
#ifndef ERWIN_ERR_MAP_INT_CALLBACK_f_h
#define ERWIN_ERR_MAP_INT_CALLBACK_f_h

struct err_map_int_callback_t;
#ifndef __cplusplus
typedef struct err_map_int_callback_t err_map_int_callback_t;
#endif
typedef struct err_map_int_callback_t ErrMapIntCallback;

typedef err_map_int_callback_t *err_map_int_callback_t_p;

typedef err_map_int_callback_t const *err_map_int_callback_t_const_p;

#define ERR_MAP_INT_CALLBACK_SIG 473364954



#ifdef ERR_ERR_MAP_INT_CALLBACK_TP_DEEP
#  if ERR_ERR_MAP_INT_CALLBACK_TP_DEEP
#    ifndef ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY
#      define ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY
#      define ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY
#define ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY */

#ifndef ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE
#define ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP
#  if ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP
#    ifndef ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COPY
#      define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COPY
#      define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COPY
#define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COPY */

#ifndef ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COMPARE
#define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP
#  if ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP
#    ifndef ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY
#      define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY
#      define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY
#define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY */

#ifndef ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE
#define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE */

#ifdef ERR_ERRMAPINTCALLBACKP_DEEP
#  if ERR_ERRMAPINTCALLBACKP_DEEP
#    ifndef ERR_ERRMAPINTCALLBACKP_DEEP_COPY
#      define ERR_ERRMAPINTCALLBACKP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPINTCALLBACKP_DEEP_COMPARE
#      define ERR_ERRMAPINTCALLBACKP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPINTCALLBACKP_DEEP_COPY
#      define ERR_ERRMAPINTCALLBACKP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPINTCALLBACKP_DEEP_COMPARE
#      define ERR_ERRMAPINTCALLBACKP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPINTCALLBACKP_DEEP_COPY
#define ERR_ERRMAPINTCALLBACKP_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPINTCALLBACKP_DEEP_COPY */

#ifndef ERR_ERRMAPINTCALLBACKP_DEEP_COMPARE
#define ERR_ERRMAPINTCALLBACKP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPINTCALLBACKP_DEEP_COMPARE */

#ifdef ERR_ERRMAPINTCALLBACK_CONSTP_DEEP
#  if ERR_ERRMAPINTCALLBACK_CONSTP_DEEP
#    ifndef ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COPY
#      define ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COMPARE
#      define ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COPY
#      define ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COMPARE
#      define ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COPY
#define ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COPY */

#ifndef ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COMPARE
#define ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERRMAPINTCALLBACKP_DEEP
#  if ERR_CONST_ERRMAPINTCALLBACKP_DEEP
#    ifndef ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COPY
#      define ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COMPARE
#      define ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COPY
#      define ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COMPARE
#      define ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COPY
#define ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COPY */

#ifndef ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COMPARE
#define ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP
#  if ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP
#    ifndef ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY
#      define ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY
#      define ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY
#define ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY */

#ifndef ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE
#define ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP
#  if ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP
#    ifndef ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COPY
#      define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COPY
#      define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COPY
#define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COPY */

#ifndef ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COMPARE
#define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP
#  if ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP
#    ifndef ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY
#      define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY
#      define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY
#define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY */

#ifndef ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE
#define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE */

#ifdef ERR_ERRMAPINTCALLBACK_P_DEEP
#  if ERR_ERRMAPINTCALLBACK_P_DEEP
#    ifndef ERR_ERRMAPINTCALLBACK_P_DEEP_COPY
#      define ERR_ERRMAPINTCALLBACK_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPINTCALLBACK_P_DEEP_COMPARE
#      define ERR_ERRMAPINTCALLBACK_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPINTCALLBACK_P_DEEP_COPY
#      define ERR_ERRMAPINTCALLBACK_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPINTCALLBACK_P_DEEP_COMPARE
#      define ERR_ERRMAPINTCALLBACK_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPINTCALLBACK_P_DEEP_COPY
#define ERR_ERRMAPINTCALLBACK_P_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPINTCALLBACK_P_DEEP_COPY */

#ifndef ERR_ERRMAPINTCALLBACK_P_DEEP_COMPARE
#define ERR_ERRMAPINTCALLBACK_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPINTCALLBACK_P_DEEP_COMPARE */

#ifdef ERR_ERRMAPINTCALLBACK_CONST_P_DEEP
#  if ERR_ERRMAPINTCALLBACK_CONST_P_DEEP
#    ifndef ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COPY
#      define ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COMPARE
#      define ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COPY
#      define ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COMPARE
#      define ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COPY
#define ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COPY */

#ifndef ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COMPARE
#define ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERRMAPINTCALLBACK_P_DEEP
#  if ERR_CONST_ERRMAPINTCALLBACK_P_DEEP
#    ifndef ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COPY
#      define ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COMPARE
#      define ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COPY
#      define ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COMPARE
#      define ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COPY
#define ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COPY */

#ifndef ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COMPARE
#define ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COMPARE */

#if ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_CALLBACK_TP_HASH_RAW)
#define ERR_ERR_MAP_INT_CALLBACK_TP_HASH_RAW(A1) err_map_int_callback_hash_raw((A1))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_HASH_RAW)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_HASH_RAW(A1) err_map_int_callback_hash_raw((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_TP_HASH_RAW)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_HASH_RAW(A1) err_map_int_callback_hash_raw((A1))
#endif

#if ERR_ERRMAPINTCALLBACKP_DEEP_COMPARE && !defined(ERR_ERRMAPINTCALLBACKP_HASH_RAW)
#define ERR_ERRMAPINTCALLBACKP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPINTCALLBACK_CONSTP_HASH_RAW)
#define ERR_ERRMAPINTCALLBACK_CONSTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTCALLBACKP_HASH_RAW)
#define ERR_CONST_ERRMAPINTCALLBACKP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_CALLBACK_T_P_HASH_RAW)
#define ERR_ERR_MAP_INT_CALLBACK_T_P_HASH_RAW(A1) err_map_int_callback_hash_raw((A1))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_HASH_RAW)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_HASH_RAW(A1) err_map_int_callback_hash_raw((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_HASH_RAW)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_HASH_RAW(A1) err_map_int_callback_hash_raw((A1))
#endif

#if ERR_ERRMAPINTCALLBACK_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTCALLBACK_P_HASH_RAW)
#define ERR_ERRMAPINTCALLBACK_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTCALLBACK_CONST_P_HASH_RAW)
#define ERR_ERRMAPINTCALLBACK_CONST_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTCALLBACK_P_HASH_RAW)
#define ERR_CONST_ERRMAPINTCALLBACK_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#ifndef ERR_ERRMAPINTCALLBACK_HASH_RAW
#define ERR_ERRMAPINTCALLBACK_HASH_RAW(A1) ((A1).hash_raw())
#endif

#if ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_CALLBACK_TP_CMP)
#define ERR_ERR_MAP_INT_CALLBACK_TP_CMP(A1,A2) err_map_int_callback_cmp((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_CMP)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_CMP(A1,A2) err_map_int_callback_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_TP_CMP)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_CMP(A1,A2) err_map_int_callback_cmp((A1),(A2))
#endif

#if ERR_ERRMAPINTCALLBACKP_DEEP_COMPARE && !defined(ERR_ERRMAPINTCALLBACKP_CMP)
#define ERR_ERRMAPINTCALLBACKP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPINTCALLBACK_CONSTP_CMP)
#define ERR_ERRMAPINTCALLBACK_CONSTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTCALLBACKP_CMP)
#define ERR_CONST_ERRMAPINTCALLBACKP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_CALLBACK_T_P_CMP)
#define ERR_ERR_MAP_INT_CALLBACK_T_P_CMP(A1,A2) err_map_int_callback_cmp((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_CMP)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_CMP(A1,A2) err_map_int_callback_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_CMP)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_CMP(A1,A2) err_map_int_callback_cmp((A1),(A2))
#endif

#if ERR_ERRMAPINTCALLBACK_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTCALLBACK_P_CMP)
#define ERR_ERRMAPINTCALLBACK_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTCALLBACK_CONST_P_CMP)
#define ERR_ERRMAPINTCALLBACK_CONST_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTCALLBACK_P_CMP)
#define ERR_CONST_ERRMAPINTCALLBACK_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#ifndef ERR_ERRMAPINTCALLBACK_CMP
#define ERR_ERRMAPINTCALLBACK_CMP(A1,A2) ((A1).cmp((A2)))
#endif

#ifndef ERR_ERRMAPINTCALLBACK_ZERO
#define ERR_ERRMAPINTCALLBACK_ZERO (ErrMapIntCallback::static_zero())
#endif

#if ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_CALLBACK_TP_EQUAL)
#define ERR_ERR_MAP_INT_CALLBACK_TP_EQUAL(A1,A2) err_map_int_callback_equal((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_EQUAL)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_EQUAL(A1,A2) err_map_int_callback_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_TP_EQUAL)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_EQUAL(A1,A2) err_map_int_callback_equal((A1),(A2))
#endif

#if ERR_ERRMAPINTCALLBACKP_DEEP_COMPARE && !defined(ERR_ERRMAPINTCALLBACKP_EQUAL)
#define ERR_ERRMAPINTCALLBACKP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPINTCALLBACK_CONSTP_EQUAL)
#define ERR_ERRMAPINTCALLBACK_CONSTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTCALLBACKP_EQUAL)
#define ERR_CONST_ERRMAPINTCALLBACKP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_CALLBACK_T_P_EQUAL)
#define ERR_ERR_MAP_INT_CALLBACK_T_P_EQUAL(A1,A2) err_map_int_callback_equal((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_EQUAL)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_EQUAL(A1,A2) err_map_int_callback_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_EQUAL)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_EQUAL(A1,A2) err_map_int_callback_equal((A1),(A2))
#endif

#if ERR_ERRMAPINTCALLBACK_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTCALLBACK_P_EQUAL)
#define ERR_ERRMAPINTCALLBACK_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTCALLBACK_CONST_P_EQUAL)
#define ERR_ERRMAPINTCALLBACK_CONST_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTCALLBACK_P_EQUAL)
#define ERR_CONST_ERRMAPINTCALLBACK_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#ifndef ERR_ERRMAPINTCALLBACK_EQUAL
#define ERR_ERRMAPINTCALLBACK_EQUAL(A1,A2) ((A1).equal((A2)))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_TP_ICOPY)
#define ERR_ERR_MAP_INT_CALLBACK_TP_ICOPY(A1,A2) err_map_int_callback_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_ICOPY)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_ICOPY(A1,A2) err_map_int_callback_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_TP_ICOPY)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_ICOPY(A1,A2) err_map_int_callback_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPINTCALLBACKP_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACKP_ICOPY)
#define ERR_ERRMAPINTCALLBACKP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACK_CONSTP_ICOPY)
#define ERR_ERRMAPINTCALLBACK_CONSTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTCALLBACKP_ICOPY)
#define ERR_CONST_ERRMAPINTCALLBACKP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_T_P_ICOPY)
#define ERR_ERR_MAP_INT_CALLBACK_T_P_ICOPY(A1,A2) err_map_int_callback_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_ICOPY)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_ICOPY(A1,A2) err_map_int_callback_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_ICOPY)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_ICOPY(A1,A2) err_map_int_callback_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPINTCALLBACK_P_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACK_P_ICOPY)
#define ERR_ERRMAPINTCALLBACK_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACK_CONST_P_ICOPY)
#define ERR_ERRMAPINTCALLBACK_CONST_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTCALLBACK_P_ICOPY)
#define ERR_CONST_ERRMAPINTCALLBACK_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_TP_OCOPY)
#define ERR_ERR_MAP_INT_CALLBACK_TP_OCOPY(A1,A2) err_map_int_callback_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_OCOPY)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_OCOPY(A1,A2) err_map_int_callback_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_TP_OCOPY)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_OCOPY(A1,A2) err_map_int_callback_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPINTCALLBACKP_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACKP_OCOPY)
#define ERR_ERRMAPINTCALLBACKP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACK_CONSTP_OCOPY)
#define ERR_ERRMAPINTCALLBACK_CONSTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTCALLBACKP_OCOPY)
#define ERR_CONST_ERRMAPINTCALLBACKP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_T_P_OCOPY)
#define ERR_ERR_MAP_INT_CALLBACK_T_P_OCOPY(A1,A2) err_map_int_callback_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_OCOPY)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_OCOPY(A1,A2) err_map_int_callback_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_OCOPY)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_OCOPY(A1,A2) err_map_int_callback_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPINTCALLBACK_P_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACK_P_OCOPY)
#define ERR_ERRMAPINTCALLBACK_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACK_CONST_P_OCOPY)
#define ERR_ERRMAPINTCALLBACK_CONST_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTCALLBACK_P_OCOPY)
#define ERR_CONST_ERRMAPINTCALLBACK_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_TP_IFREE)
#define ERR_ERR_MAP_INT_CALLBACK_TP_IFREE(A1) err_map_int_callback_delete((A1))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_IFREE)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_IFREE(A1) err_map_int_callback_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_TP_IFREE)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_IFREE(A1) err_map_int_callback_delete((A1))
#endif

#if ERR_ERRMAPINTCALLBACKP_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACKP_IFREE)
#define ERR_ERRMAPINTCALLBACKP_IFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACK_CONSTP_IFREE)
#define ERR_ERRMAPINTCALLBACK_CONSTP_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTCALLBACKP_IFREE)
#define ERR_CONST_ERRMAPINTCALLBACKP_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_T_P_IFREE)
#define ERR_ERR_MAP_INT_CALLBACK_T_P_IFREE(A1) err_map_int_callback_delete((A1))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_IFREE)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_IFREE(A1) err_map_int_callback_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_IFREE)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_IFREE(A1) err_map_int_callback_delete((A1))
#endif

#if ERR_ERRMAPINTCALLBACK_P_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACK_P_IFREE)
#define ERR_ERRMAPINTCALLBACK_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACK_CONST_P_IFREE)
#define ERR_ERRMAPINTCALLBACK_CONST_P_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTCALLBACK_P_IFREE)
#define ERR_CONST_ERRMAPINTCALLBACK_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_TP_OFREE)
#define ERR_ERR_MAP_INT_CALLBACK_TP_OFREE(A1) err_map_int_callback_delete((A1))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_OFREE)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_OFREE(A1) err_map_int_callback_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_TP_OFREE)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_TP_OFREE(A1) err_map_int_callback_delete((A1))
#endif

#if ERR_ERRMAPINTCALLBACKP_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACKP_OFREE)
#define ERR_ERRMAPINTCALLBACKP_OFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPINTCALLBACK_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACK_CONSTP_OFREE)
#define ERR_ERRMAPINTCALLBACK_CONSTP_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPINTCALLBACKP_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTCALLBACKP_OFREE)
#define ERR_CONST_ERRMAPINTCALLBACKP_OFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_T_P_OFREE)
#define ERR_ERR_MAP_INT_CALLBACK_T_P_OFREE(A1) err_map_int_callback_delete((A1))
#endif

#if ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_OFREE)
#define ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_OFREE(A1) err_map_int_callback_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_OFREE)
#define ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_OFREE(A1) err_map_int_callback_delete((A1))
#endif

#if ERR_ERRMAPINTCALLBACK_P_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACK_P_OFREE)
#define ERR_ERRMAPINTCALLBACK_P_OFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPINTCALLBACK_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPINTCALLBACK_CONST_P_OFREE)
#define ERR_ERRMAPINTCALLBACK_CONST_P_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPINTCALLBACK_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTCALLBACK_P_OFREE)
#define ERR_CONST_ERRMAPINTCALLBACK_P_OFREE(A1) delete((A1))
#endif

#ifndef ERR_ERRMAPINTCALLBACK_CONSTRUCTOR
#define ERR_ERRMAPINTCALLBACK_CONSTRUCTOR(A1) ((A1)._constructor())
#endif

#ifndef ERR_ERRMAPINTCALLBACK_DESTRUCTOR
#define ERR_ERRMAPINTCALLBACK_DESTRUCTOR(A1) ((A1)._destructor())
#endif


#endif /* defined ERWIN_ERR_MAP_INT_CALLBACK_f_h */

