
#ifndef ERWIN_ERR_MAP_SYMBOL_STRING_f_h
#define ERWIN_ERR_MAP_SYMBOL_STRING_f_h

struct err_map_symbol_string_t;
#ifndef __cplusplus
typedef struct err_map_symbol_string_t err_map_symbol_string_t;
#endif
typedef struct err_map_symbol_string_t ErrMapSymbolString;

typedef err_map_symbol_string_t *err_map_symbol_string_t_p;

typedef err_map_symbol_string_t const *err_map_symbol_string_t_const_p;

#define ERR_MAP_SYMBOL_STRING_SIG 2108692241



#ifdef ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP
#  if ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY
#define ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY */

#ifndef ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE
#define ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP
#  if ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COPY
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COPY */

#ifndef ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COMPARE
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP
#  if ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY
#      define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY
#      define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY */

#ifndef ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE */

#ifdef ERR_ERRMAPSYMBOLSTRINGP_DEEP
#  if ERR_ERRMAPSYMBOLSTRINGP_DEEP
#    ifndef ERR_ERRMAPSYMBOLSTRINGP_DEEP_COPY
#      define ERR_ERRMAPSYMBOLSTRINGP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPSYMBOLSTRINGP_DEEP_COPY
#      define ERR_ERRMAPSYMBOLSTRINGP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPSYMBOLSTRINGP_DEEP_COPY
#define ERR_ERRMAPSYMBOLSTRINGP_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPSYMBOLSTRINGP_DEEP_COPY */

#ifndef ERR_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE
#define ERR_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE */

#ifdef ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP
#  if ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP
#    ifndef ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COPY
#      define ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COPY
#      define ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COPY
#define ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COPY */

#ifndef ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COMPARE
#define ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP
#  if ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP
#    ifndef ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COPY
#      define ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE
#      define ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COPY
#      define ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE
#      define ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COPY
#define ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COPY */

#ifndef ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE
#define ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP
#  if ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY
#define ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY */

#ifndef ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE
#define ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP
#  if ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COPY
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COPY */

#ifndef ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COMPARE
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP
#  if ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY
#      define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY
#      define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY */

#ifndef ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE */

#ifdef ERR_ERRMAPSYMBOLSTRING_P_DEEP
#  if ERR_ERRMAPSYMBOLSTRING_P_DEEP
#    ifndef ERR_ERRMAPSYMBOLSTRING_P_DEEP_COPY
#      define ERR_ERRMAPSYMBOLSTRING_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPSYMBOLSTRING_P_DEEP_COPY
#      define ERR_ERRMAPSYMBOLSTRING_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPSYMBOLSTRING_P_DEEP_COPY
#define ERR_ERRMAPSYMBOLSTRING_P_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPSYMBOLSTRING_P_DEEP_COPY */

#ifndef ERR_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE
#define ERR_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE */

#ifdef ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP
#  if ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP
#    ifndef ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COPY
#      define ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COPY
#      define ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COPY
#define ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COPY */

#ifndef ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COMPARE
#define ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP
#  if ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP
#    ifndef ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COPY
#      define ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE
#      define ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COPY
#      define ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE
#      define ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COPY
#define ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COPY */

#ifndef ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE
#define ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE */

#if ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_STRING_TP_HASH_RAW)
#define ERR_ERR_MAP_SYMBOL_STRING_TP_HASH_RAW(A1) err_map_symbol_string_hash_raw((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_HASH_RAW)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_HASH_RAW(A1) err_map_symbol_string_hash_raw((A1))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_HASH_RAW)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_HASH_RAW(A1) err_map_symbol_string_hash_raw((A1))
#endif

#if ERR_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLSTRINGP_HASH_RAW)
#define ERR_ERRMAPSYMBOLSTRINGP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLSTRING_CONSTP_HASH_RAW)
#define ERR_ERRMAPSYMBOLSTRING_CONSTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPSYMBOLSTRINGP_HASH_RAW)
#define ERR_CONST_ERRMAPSYMBOLSTRINGP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_P_HASH_RAW)
#define ERR_ERR_MAP_SYMBOL_STRING_T_P_HASH_RAW(A1) err_map_symbol_string_hash_raw((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_HASH_RAW)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_HASH_RAW(A1) err_map_symbol_string_hash_raw((A1))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_HASH_RAW)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_HASH_RAW(A1) err_map_symbol_string_hash_raw((A1))
#endif

#if ERR_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLSTRING_P_HASH_RAW)
#define ERR_ERRMAPSYMBOLSTRING_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLSTRING_CONST_P_HASH_RAW)
#define ERR_ERRMAPSYMBOLSTRING_CONST_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPSYMBOLSTRING_P_HASH_RAW)
#define ERR_CONST_ERRMAPSYMBOLSTRING_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#ifndef ERR_ERRMAPSYMBOLSTRING_HASH_RAW
#define ERR_ERRMAPSYMBOLSTRING_HASH_RAW(A1) ((A1).hash_raw())
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_STRING_TP_CMP)
#define ERR_ERR_MAP_SYMBOL_STRING_TP_CMP(A1,A2) err_map_symbol_string_cmp((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_CMP)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_CMP(A1,A2) err_map_symbol_string_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_CMP)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_CMP(A1,A2) err_map_symbol_string_cmp((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLSTRINGP_CMP)
#define ERR_ERRMAPSYMBOLSTRINGP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLSTRING_CONSTP_CMP)
#define ERR_ERRMAPSYMBOLSTRING_CONSTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPSYMBOLSTRINGP_CMP)
#define ERR_CONST_ERRMAPSYMBOLSTRINGP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_P_CMP)
#define ERR_ERR_MAP_SYMBOL_STRING_T_P_CMP(A1,A2) err_map_symbol_string_cmp((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_CMP)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_CMP(A1,A2) err_map_symbol_string_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_CMP)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_CMP(A1,A2) err_map_symbol_string_cmp((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLSTRING_P_CMP)
#define ERR_ERRMAPSYMBOLSTRING_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLSTRING_CONST_P_CMP)
#define ERR_ERRMAPSYMBOLSTRING_CONST_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPSYMBOLSTRING_P_CMP)
#define ERR_CONST_ERRMAPSYMBOLSTRING_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#ifndef ERR_ERRMAPSYMBOLSTRING_CMP
#define ERR_ERRMAPSYMBOLSTRING_CMP(A1,A2) ((A1).cmp((A2)))
#endif

#ifndef ERR_ERRMAPSYMBOLSTRING_ZERO
#define ERR_ERRMAPSYMBOLSTRING_ZERO (ErrMapSymbolString::static_zero())
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_STRING_TP_EQUAL)
#define ERR_ERR_MAP_SYMBOL_STRING_TP_EQUAL(A1,A2) err_map_symbol_string_equal((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_EQUAL)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_EQUAL(A1,A2) err_map_symbol_string_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_EQUAL)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_EQUAL(A1,A2) err_map_symbol_string_equal((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLSTRINGP_EQUAL)
#define ERR_ERRMAPSYMBOLSTRINGP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLSTRING_CONSTP_EQUAL)
#define ERR_ERRMAPSYMBOLSTRING_CONSTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPSYMBOLSTRINGP_EQUAL)
#define ERR_CONST_ERRMAPSYMBOLSTRINGP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_P_EQUAL)
#define ERR_ERR_MAP_SYMBOL_STRING_T_P_EQUAL(A1,A2) err_map_symbol_string_equal((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_EQUAL)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_EQUAL(A1,A2) err_map_symbol_string_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_EQUAL)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_EQUAL(A1,A2) err_map_symbol_string_equal((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLSTRING_P_EQUAL)
#define ERR_ERRMAPSYMBOLSTRING_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLSTRING_CONST_P_EQUAL)
#define ERR_ERRMAPSYMBOLSTRING_CONST_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPSYMBOLSTRING_P_EQUAL)
#define ERR_CONST_ERRMAPSYMBOLSTRING_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#ifndef ERR_ERRMAPSYMBOLSTRING_EQUAL
#define ERR_ERRMAPSYMBOLSTRING_EQUAL(A1,A2) ((A1).equal((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_TP_ICOPY)
#define ERR_ERR_MAP_SYMBOL_STRING_TP_ICOPY(A1,A2) err_map_symbol_string_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_ICOPY)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_ICOPY(A1,A2) err_map_symbol_string_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_ICOPY)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_ICOPY(A1,A2) err_map_symbol_string_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLSTRINGP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRINGP_ICOPY)
#define ERR_ERRMAPSYMBOLSTRINGP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRING_CONSTP_ICOPY)
#define ERR_ERRMAPSYMBOLSTRING_CONSTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLSTRINGP_ICOPY)
#define ERR_CONST_ERRMAPSYMBOLSTRINGP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_P_ICOPY)
#define ERR_ERR_MAP_SYMBOL_STRING_T_P_ICOPY(A1,A2) err_map_symbol_string_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_ICOPY)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_ICOPY(A1,A2) err_map_symbol_string_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_ICOPY)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_ICOPY(A1,A2) err_map_symbol_string_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLSTRING_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRING_P_ICOPY)
#define ERR_ERRMAPSYMBOLSTRING_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRING_CONST_P_ICOPY)
#define ERR_ERRMAPSYMBOLSTRING_CONST_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLSTRING_P_ICOPY)
#define ERR_CONST_ERRMAPSYMBOLSTRING_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_TP_OCOPY)
#define ERR_ERR_MAP_SYMBOL_STRING_TP_OCOPY(A1,A2) err_map_symbol_string_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_OCOPY)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_OCOPY(A1,A2) err_map_symbol_string_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_OCOPY)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_OCOPY(A1,A2) err_map_symbol_string_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLSTRINGP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRINGP_OCOPY)
#define ERR_ERRMAPSYMBOLSTRINGP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRING_CONSTP_OCOPY)
#define ERR_ERRMAPSYMBOLSTRING_CONSTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLSTRINGP_OCOPY)
#define ERR_CONST_ERRMAPSYMBOLSTRINGP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_P_OCOPY)
#define ERR_ERR_MAP_SYMBOL_STRING_T_P_OCOPY(A1,A2) err_map_symbol_string_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_OCOPY)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_OCOPY(A1,A2) err_map_symbol_string_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_OCOPY)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_OCOPY(A1,A2) err_map_symbol_string_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLSTRING_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRING_P_OCOPY)
#define ERR_ERRMAPSYMBOLSTRING_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRING_CONST_P_OCOPY)
#define ERR_ERRMAPSYMBOLSTRING_CONST_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLSTRING_P_OCOPY)
#define ERR_CONST_ERRMAPSYMBOLSTRING_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_TP_IFREE)
#define ERR_ERR_MAP_SYMBOL_STRING_TP_IFREE(A1) err_map_symbol_string_delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_IFREE)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_IFREE(A1) err_map_symbol_string_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_IFREE)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_IFREE(A1) err_map_symbol_string_delete((A1))
#endif

#if ERR_ERRMAPSYMBOLSTRINGP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRINGP_IFREE)
#define ERR_ERRMAPSYMBOLSTRINGP_IFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRING_CONSTP_IFREE)
#define ERR_ERRMAPSYMBOLSTRING_CONSTP_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLSTRINGP_IFREE)
#define ERR_CONST_ERRMAPSYMBOLSTRINGP_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_P_IFREE)
#define ERR_ERR_MAP_SYMBOL_STRING_T_P_IFREE(A1) err_map_symbol_string_delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_IFREE)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_IFREE(A1) err_map_symbol_string_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_IFREE)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_IFREE(A1) err_map_symbol_string_delete((A1))
#endif

#if ERR_ERRMAPSYMBOLSTRING_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRING_P_IFREE)
#define ERR_ERRMAPSYMBOLSTRING_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRING_CONST_P_IFREE)
#define ERR_ERRMAPSYMBOLSTRING_CONST_P_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLSTRING_P_IFREE)
#define ERR_CONST_ERRMAPSYMBOLSTRING_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_TP_OFREE)
#define ERR_ERR_MAP_SYMBOL_STRING_TP_OFREE(A1) err_map_symbol_string_delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_OFREE)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_OFREE(A1) err_map_symbol_string_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_OFREE)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_OFREE(A1) err_map_symbol_string_delete((A1))
#endif

#if ERR_ERRMAPSYMBOLSTRINGP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRINGP_OFREE)
#define ERR_ERRMAPSYMBOLSTRINGP_OFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRING_CONSTP_OFREE)
#define ERR_ERRMAPSYMBOLSTRING_CONSTP_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRINGP_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLSTRINGP_OFREE)
#define ERR_CONST_ERRMAPSYMBOLSTRINGP_OFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_P_OFREE)
#define ERR_ERR_MAP_SYMBOL_STRING_T_P_OFREE(A1) err_map_symbol_string_delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_OFREE)
#define ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_OFREE(A1) err_map_symbol_string_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_OFREE)
#define ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_OFREE(A1) err_map_symbol_string_delete((A1))
#endif

#if ERR_ERRMAPSYMBOLSTRING_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRING_P_OFREE)
#define ERR_ERRMAPSYMBOLSTRING_P_OFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPSYMBOLSTRING_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLSTRING_CONST_P_OFREE)
#define ERR_ERRMAPSYMBOLSTRING_CONST_P_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPSYMBOLSTRING_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLSTRING_P_OFREE)
#define ERR_CONST_ERRMAPSYMBOLSTRING_P_OFREE(A1) delete((A1))
#endif

#ifndef ERR_ERRMAPSYMBOLSTRING_CONSTRUCTOR
#define ERR_ERRMAPSYMBOLSTRING_CONSTRUCTOR(A1) ((A1)._constructor())
#endif

#ifndef ERR_ERRMAPSYMBOLSTRING_DESTRUCTOR
#define ERR_ERRMAPSYMBOLSTRING_DESTRUCTOR(A1) ((A1)._destructor())
#endif


#endif /* defined ERWIN_ERR_MAP_SYMBOL_STRING_f_h */

