
#if defined(ERR_ERR_V_STREAM_TP_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_V_STREAM_TP_BEING_USED */

#if defined(ERR_ERR_V_STREAM_T_CONSTP_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_V_STREAM_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_V_STREAM_TP_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_V_STREAM_TP_BEING_USED */

#if defined(ERR_ERRVSTREAMP_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRVSTREAMP_BEING_USED */

#if defined(ERR_ERRVSTREAM_CONSTP_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRVSTREAM_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRVSTREAMP_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRVSTREAMP_BEING_USED */

#if defined(ERR_ERR_V_STREAM_T_P_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_V_STREAM_T_P_BEING_USED */

#if defined(ERR_ERR_V_STREAM_T_CONST_P_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_V_STREAM_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_V_STREAM_T_P_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_V_STREAM_T_P_BEING_USED */

#if defined(ERR_ERRVSTREAM_P_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRVSTREAM_P_BEING_USED */

#if defined(ERR_ERRVSTREAM_CONST_P_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRVSTREAM_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRVSTREAM_P_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRVSTREAM_P_BEING_USED */

#if defined(ERR_ERRVSTREAM_BEING_USED) && !defined(ERR_V_STREAM_NEED_HEADER)
#define ERR_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRVSTREAM_BEING_USED */



#ifdef ERR_V_STREAM_NEED_HEADER
#include "error/err_v_stream.h"
#endif

