
#if defined(ERR_ERR_MAP_INT_MAP_INT_V_CALLBACK_TP_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_MAP_INT_V_CALLBACK_TP_BEING_USED */

#if defined(ERR_ERR_MAP_INT_MAP_INT_V_CALLBACK_T_CONSTP_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_MAP_INT_V_CALLBACK_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_INT_MAP_INT_V_CALLBACK_TP_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_INT_MAP_INT_V_CALLBACK_TP_BEING_USED */

#if defined(ERR_ERRMAPINTMAPINTVCALLBACKP_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTMAPINTVCALLBACKP_BEING_USED */

#if defined(ERR_ERRMAPINTMAPINTVCALLBACK_CONSTP_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTMAPINTVCALLBACK_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRMAPINTMAPINTVCALLBACKP_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPINTMAPINTVCALLBACKP_BEING_USED */

#if defined(ERR_ERR_MAP_INT_MAP_INT_V_CALLBACK_T_P_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_MAP_INT_V_CALLBACK_T_P_BEING_USED */

#if defined(ERR_ERR_MAP_INT_MAP_INT_V_CALLBACK_T_CONST_P_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_MAP_INT_V_CALLBACK_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_INT_MAP_INT_V_CALLBACK_T_P_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_INT_MAP_INT_V_CALLBACK_T_P_BEING_USED */

#if defined(ERR_ERRMAPINTMAPINTVCALLBACK_P_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTMAPINTVCALLBACK_P_BEING_USED */

#if defined(ERR_ERRMAPINTMAPINTVCALLBACK_CONST_P_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTMAPINTVCALLBACK_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRMAPINTMAPINTVCALLBACK_P_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPINTMAPINTVCALLBACK_P_BEING_USED */

#if defined(ERR_ERRMAPINTMAPINTVCALLBACK_BEING_USED) && !defined(ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTMAPINTVCALLBACK_BEING_USED */



#ifdef ERR_MAP_INT_MAP_INT_V_CALLBACK_NEED_HEADER
#include "error/err_map_int_map_int_v_callback.h"
#endif

