/* -*- Mode: C -*- */
/* Generated Wed Sep 17 00:48:24 GMT 2008
 */
/* Author: Henrik Theiling
 *
 * Implementation specific header file.  Only err_v_message.c should
 * include this.
 */
/*
 * Copyright (c) 1999-2002 Henrik Theiling
 * 
 * This file was generated by tools of the Erwin library.  It may be used
 * freely.
 * 
 * This software is provided 'as-is', without warranty of any kind,
 * express or implied.  In no event will the authors or copyright holders
 * be held liable for any damages arising from the use of this software.
 * 
 * Disputes shall be settled by Saarbruecken City Court.
*/

#ifdef ERWIN_DEBUG_INCLUDE
#warning "Including err_v_message_i.h"
#endif

#ifndef ERWIN_ERR_V_MESSAGE_I_h
#define ERWIN_ERR_V_MESSAGE_I_h

#ifdef ERWIN_DEBUG_INCLUDE
#warning "First inclusion of err_v_message_i.h"
#endif

/* Note:
 *    Due to complex constraints and a lot of necessary rewriting,
 *    we currently switch off INLINE_STORE when LOW_MEM is requested.
 *    One problem is a common pattern here:
 *
 *       ...ensure_size_add...
 *       CODE: do something to the vector
 *       self->m_nentries= new_size.
 *
 *   The problem is that the CODE in the middle needs self->m_nentries to
 *   decide whether the table is on the heap or inline when INLINE_STORE
 *   and LOW_MEM is activated at the same time.  In the above code, it
 *   cannot rely on self->m_nentries, however, so we'd need to restructure
 *   a lot of code, e.g. by having TABLE2 additional to TABLE, which is
 *   passed the new size (switching the order of assignment isn't always
 *   possible, since, e.g. init_tail requires self->m_nentries to be the
 *   *old* value).
 */
#if ERR_V_MESSAGE_LOW_MEM
#  undef  ERR_V_MESSAGE_INLINE_STORE
#  define ERR_V_MESSAGE_INLINE_STORE 0
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define err_v_message_record_table(X) X

#if ERR_V_MESSAGE_LOW_MEM
#  define err_v_message_record_tablesize(X)
#else
#  define err_v_message_record_tablesize(X) X
#endif

#define err_v_message_record_nentries(X) X

#ifdef ERR_ERWIN_THREAD_SAFE
#  define err_v_message_record_errno(X) X
#else
#  define err_v_message_record_errno(X)
#endif

#if ERR_V_MESSAGE_DYN_ZERO
#  define err_v_message_record_zero(X) X
#else
#  define err_v_message_record_zero(X)
#endif

#if ERR_V_MESSAGE_HAVE_SIG
#  define err_v_message_record_sig(X) X
#else
#  define err_v_message_record_sig(X)
#endif

#if ERR_V_MESSAGE_POSITION_POINTER
#  define err_v_message_record_pos(X) X
#else
#  define err_v_message_record_pos(X)
#endif

typedef err_message_t * err_v_message_content;
typedef err_v_message_content *err_v_message_content_p;

#define err_v_message_record                                               \
        err_v_message_record_sig       (int m_sig;)                        \
        err_v_message_record_table     (err_v_message_content_p m_table;)         \
        err_v_message_record_tablesize (err_v_message_size_t m_tablesize;)        \
        err_v_message_record_nentries  (err_v_message_size_t m_nentries;)         \
        err_v_message_record_pos       (err_v_message_index_t m_pos;)             \
        err_v_message_record_errno     (ERR_ERWIN_MUTABLE int m_errno;) \
        err_v_message_record_zero      (err_message_t *  m_zero;)

#ifdef ERR_ERWIN_COMPAT_2_0_264

#ifdef ERR_ERWIN_COMPAT_2_0_248
struct _err_v_message_t
#else
struct err_v_message_t
#endif
{
    err_v_message_record
};

#endif

/* Force linker error when .c and .h are compiled inconsistently */
#if !defined (ERR_V_MESSAGE_IMPLEMENTATION) && defined(ERWIN_WEAK_STORAGE) && !defined(NDEBUG) && !defined(ERR_ERWIN_NO_LINKER_TRICKS)
#ifdef __cplusplus
extern "C" {
#endif
#if ERR_V_MESSAGE_DYN_ZERO
ERWIN_WEAK_STORAGE void err_v_message_variable_zero_element_expected(void) ERWIN_LINK_WEAK;
ERWIN_WEAK_STORAGE void err_v_message_variable_zero_element_expected(void) {}
#else
ERWIN_WEAK_STORAGE void err_v_message_constant_zero_element_expected(void) ERWIN_LINK_WEAK;
ERWIN_WEAK_STORAGE void err_v_message_constant_zero_element_expected(void) {}
#endif
#ifdef __cplusplus
}
#endif
#endif

#ifdef __cplusplus
}
#endif

#endif
