
#if defined(ERR_ERR_MAP_INT_CALLBACK_TP_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_CALLBACK_TP_BEING_USED */

#if defined(ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_CALLBACK_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_INT_CALLBACK_TP_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_INT_CALLBACK_TP_BEING_USED */

#if defined(ERR_ERRMAPINTCALLBACKP_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTCALLBACKP_BEING_USED */

#if defined(ERR_ERRMAPINTCALLBACK_CONSTP_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTCALLBACK_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRMAPINTCALLBACKP_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPINTCALLBACKP_BEING_USED */

#if defined(ERR_ERR_MAP_INT_CALLBACK_T_P_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_CALLBACK_T_P_BEING_USED */

#if defined(ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_CALLBACK_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_INT_CALLBACK_T_P_BEING_USED */

#if defined(ERR_ERRMAPINTCALLBACK_P_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTCALLBACK_P_BEING_USED */

#if defined(ERR_ERRMAPINTCALLBACK_CONST_P_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTCALLBACK_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRMAPINTCALLBACK_P_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPINTCALLBACK_P_BEING_USED */

#if defined(ERR_ERRMAPINTCALLBACK_BEING_USED) && !defined(ERR_MAP_INT_CALLBACK_NEED_HEADER)
#define ERR_MAP_INT_CALLBACK_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTCALLBACK_BEING_USED */



#ifdef ERR_MAP_INT_CALLBACK_NEED_HEADER
#include "error/err_map_int_callback.h"
#endif

