
#if defined(ERR_ERR_MAP_INT_INT_TP_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_INT_TP_BEING_USED */

#if defined(ERR_ERR_MAP_INT_INT_T_CONSTP_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_INT_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_INT_INT_TP_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_INT_INT_TP_BEING_USED */

#if defined(ERR_ERRMAPINTINTP_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTINTP_BEING_USED */

#if defined(ERR_ERRMAPINTINT_CONSTP_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTINT_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRMAPINTINTP_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPINTINTP_BEING_USED */

#if defined(ERR_ERR_MAP_INT_INT_T_P_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_INT_T_P_BEING_USED */

#if defined(ERR_ERR_MAP_INT_INT_T_CONST_P_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_INT_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_INT_INT_T_P_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_INT_INT_T_P_BEING_USED */

#if defined(ERR_ERRMAPINTINT_P_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTINT_P_BEING_USED */

#if defined(ERR_ERRMAPINTINT_CONST_P_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTINT_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRMAPINTINT_P_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPINTINT_P_BEING_USED */

#if defined(ERR_ERRMAPINTINT_BEING_USED) && !defined(ERR_MAP_INT_INT_NEED_HEADER)
#define ERR_MAP_INT_INT_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTINT_BEING_USED */



#ifdef ERR_MAP_INT_INT_NEED_HEADER
#include "error/err_map_int_int.h"
#endif

