
#if defined(ERR_ERR_MAP_SYMBOL_STRING_TP_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_SYMBOL_STRING_TP_BEING_USED */

#if defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_SYMBOL_STRING_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_SYMBOL_STRING_TP_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLSTRINGP_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLSTRINGP_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLSTRING_CONSTP_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLSTRING_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRMAPSYMBOLSTRINGP_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPSYMBOLSTRINGP_BEING_USED */

#if defined(ERR_ERR_MAP_SYMBOL_STRING_T_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_SYMBOL_STRING_T_P_BEING_USED */

#if defined(ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_SYMBOL_STRING_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_SYMBOL_STRING_T_P_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLSTRING_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLSTRING_P_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLSTRING_CONST_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLSTRING_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRMAPSYMBOLSTRING_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPSYMBOLSTRING_P_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLSTRING_BEING_USED) && !defined(ERR_MAP_SYMBOL_STRING_NEED_HEADER)
#define ERR_MAP_SYMBOL_STRING_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLSTRING_BEING_USED */



#ifdef ERR_MAP_SYMBOL_STRING_NEED_HEADER
#include "error/err_map_symbol_string.h"
#endif

