
#if defined(ERR_ERR_V_BUFFER_TP_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_ERR_V_BUFFER_TP_BEING_USED */

#if defined(ERR_ERR_V_BUFFER_T_CONSTP_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_ERR_V_BUFFER_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_V_BUFFER_TP_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_V_BUFFER_TP_BEING_USED */

#if defined(ERR_ERRVBUFFERP_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_ERRVBUFFERP_BEING_USED */

#if defined(ERR_ERRVBUFFER_CONSTP_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_ERRVBUFFER_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRVBUFFERP_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRVBUFFERP_BEING_USED */

#if defined(ERR_ERR_V_BUFFER_T_P_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_ERR_V_BUFFER_T_P_BEING_USED */

#if defined(ERR_ERR_V_BUFFER_T_CONST_P_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_ERR_V_BUFFER_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_V_BUFFER_T_P_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_V_BUFFER_T_P_BEING_USED */

#if defined(ERR_ERRVBUFFER_P_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_ERRVBUFFER_P_BEING_USED */

#if defined(ERR_ERRVBUFFER_CONST_P_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_ERRVBUFFER_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRVBUFFER_P_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRVBUFFER_P_BEING_USED */

#if defined(ERR_ERRVBUFFER_BEING_USED) && !defined(ERR_V_BUFFER_NEED_HEADER)
#define ERR_V_BUFFER_NEED_HEADER 1
#endif /* defined ERR_ERRVBUFFER_BEING_USED */



#ifdef ERR_V_BUFFER_NEED_HEADER
#include "error/err_v_buffer.h"
#endif

