
#ifndef ERWIN_ERR_SYMTAB_f_h
#define ERWIN_ERR_SYMTAB_f_h

struct err_symtab_t;
#ifndef __cplusplus
typedef struct err_symtab_t err_symtab_t;
#endif
typedef struct err_symtab_t ErrSymtab;

typedef err_symtab_t *err_symtab_t_p;

typedef err_symtab_t const *err_symtab_t_const_p;

#define ERR_SYMTAB_SIG 924433059



#ifdef ERR_ERR_SYMTAB_TP_DEEP
#  if ERR_ERR_SYMTAB_TP_DEEP
#    ifndef ERR_ERR_SYMTAB_TP_DEEP_COPY
#      define ERR_ERR_SYMTAB_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_SYMTAB_TP_DEEP_COMPARE
#      define ERR_ERR_SYMTAB_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_SYMTAB_TP_DEEP_COPY
#      define ERR_ERR_SYMTAB_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_SYMTAB_TP_DEEP_COMPARE
#      define ERR_ERR_SYMTAB_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_SYMTAB_TP_DEEP_COPY
#define ERR_ERR_SYMTAB_TP_DEEP_COPY 0
#endif /* !defined ERR_ERR_SYMTAB_TP_DEEP_COPY */

#ifndef ERR_ERR_SYMTAB_TP_DEEP_COMPARE
#define ERR_ERR_SYMTAB_TP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_SYMTAB_TP_DEEP_COMPARE */

#ifdef ERR_ERR_SYMTAB_T_CONSTP_DEEP
#  if ERR_ERR_SYMTAB_T_CONSTP_DEEP
#    ifndef ERR_ERR_SYMTAB_T_CONSTP_DEEP_COPY
#      define ERR_ERR_SYMTAB_T_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_SYMTAB_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_SYMTAB_T_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_SYMTAB_T_CONSTP_DEEP_COPY
#      define ERR_ERR_SYMTAB_T_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_SYMTAB_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_SYMTAB_T_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_SYMTAB_T_CONSTP_DEEP_COPY
#define ERR_ERR_SYMTAB_T_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERR_SYMTAB_T_CONSTP_DEEP_COPY */

#ifndef ERR_ERR_SYMTAB_T_CONSTP_DEEP_COMPARE
#define ERR_ERR_SYMTAB_T_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_SYMTAB_T_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_SYMTAB_TP_DEEP
#  if ERR_CONST_ERR_SYMTAB_TP_DEEP
#    ifndef ERR_CONST_ERR_SYMTAB_TP_DEEP_COPY
#      define ERR_CONST_ERR_SYMTAB_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_SYMTAB_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_SYMTAB_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_SYMTAB_TP_DEEP_COPY
#      define ERR_CONST_ERR_SYMTAB_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_SYMTAB_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_SYMTAB_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_SYMTAB_TP_DEEP_COPY
#define ERR_CONST_ERR_SYMTAB_TP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_SYMTAB_TP_DEEP_COPY */

#ifndef ERR_CONST_ERR_SYMTAB_TP_DEEP_COMPARE
#define ERR_CONST_ERR_SYMTAB_TP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_SYMTAB_TP_DEEP_COMPARE */

#ifdef ERR_ERRSYMTABP_DEEP
#  if ERR_ERRSYMTABP_DEEP
#    ifndef ERR_ERRSYMTABP_DEEP_COPY
#      define ERR_ERRSYMTABP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRSYMTABP_DEEP_COMPARE
#      define ERR_ERRSYMTABP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRSYMTABP_DEEP_COPY
#      define ERR_ERRSYMTABP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRSYMTABP_DEEP_COMPARE
#      define ERR_ERRSYMTABP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRSYMTABP_DEEP_COPY
#define ERR_ERRSYMTABP_DEEP_COPY 0
#endif /* !defined ERR_ERRSYMTABP_DEEP_COPY */

#ifndef ERR_ERRSYMTABP_DEEP_COMPARE
#define ERR_ERRSYMTABP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRSYMTABP_DEEP_COMPARE */

#ifdef ERR_ERRSYMTAB_CONSTP_DEEP
#  if ERR_ERRSYMTAB_CONSTP_DEEP
#    ifndef ERR_ERRSYMTAB_CONSTP_DEEP_COPY
#      define ERR_ERRSYMTAB_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRSYMTAB_CONSTP_DEEP_COMPARE
#      define ERR_ERRSYMTAB_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRSYMTAB_CONSTP_DEEP_COPY
#      define ERR_ERRSYMTAB_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRSYMTAB_CONSTP_DEEP_COMPARE
#      define ERR_ERRSYMTAB_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRSYMTAB_CONSTP_DEEP_COPY
#define ERR_ERRSYMTAB_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERRSYMTAB_CONSTP_DEEP_COPY */

#ifndef ERR_ERRSYMTAB_CONSTP_DEEP_COMPARE
#define ERR_ERRSYMTAB_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRSYMTAB_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERRSYMTABP_DEEP
#  if ERR_CONST_ERRSYMTABP_DEEP
#    ifndef ERR_CONST_ERRSYMTABP_DEEP_COPY
#      define ERR_CONST_ERRSYMTABP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRSYMTABP_DEEP_COMPARE
#      define ERR_CONST_ERRSYMTABP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRSYMTABP_DEEP_COPY
#      define ERR_CONST_ERRSYMTABP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRSYMTABP_DEEP_COMPARE
#      define ERR_CONST_ERRSYMTABP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRSYMTABP_DEEP_COPY
#define ERR_CONST_ERRSYMTABP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRSYMTABP_DEEP_COPY */

#ifndef ERR_CONST_ERRSYMTABP_DEEP_COMPARE
#define ERR_CONST_ERRSYMTABP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRSYMTABP_DEEP_COMPARE */

#ifdef ERR_ERR_SYMTAB_T_P_DEEP
#  if ERR_ERR_SYMTAB_T_P_DEEP
#    ifndef ERR_ERR_SYMTAB_T_P_DEEP_COPY
#      define ERR_ERR_SYMTAB_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_SYMTAB_T_P_DEEP_COMPARE
#      define ERR_ERR_SYMTAB_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_SYMTAB_T_P_DEEP_COPY
#      define ERR_ERR_SYMTAB_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_SYMTAB_T_P_DEEP_COMPARE
#      define ERR_ERR_SYMTAB_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_SYMTAB_T_P_DEEP_COPY
#define ERR_ERR_SYMTAB_T_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_SYMTAB_T_P_DEEP_COPY */

#ifndef ERR_ERR_SYMTAB_T_P_DEEP_COMPARE
#define ERR_ERR_SYMTAB_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_SYMTAB_T_P_DEEP_COMPARE */

#ifdef ERR_ERR_SYMTAB_T_CONST_P_DEEP
#  if ERR_ERR_SYMTAB_T_CONST_P_DEEP
#    ifndef ERR_ERR_SYMTAB_T_CONST_P_DEEP_COPY
#      define ERR_ERR_SYMTAB_T_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_SYMTAB_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_SYMTAB_T_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_SYMTAB_T_CONST_P_DEEP_COPY
#      define ERR_ERR_SYMTAB_T_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_SYMTAB_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_SYMTAB_T_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_SYMTAB_T_CONST_P_DEEP_COPY
#define ERR_ERR_SYMTAB_T_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_SYMTAB_T_CONST_P_DEEP_COPY */

#ifndef ERR_ERR_SYMTAB_T_CONST_P_DEEP_COMPARE
#define ERR_ERR_SYMTAB_T_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_SYMTAB_T_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_SYMTAB_T_P_DEEP
#  if ERR_CONST_ERR_SYMTAB_T_P_DEEP
#    ifndef ERR_CONST_ERR_SYMTAB_T_P_DEEP_COPY
#      define ERR_CONST_ERR_SYMTAB_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_SYMTAB_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_SYMTAB_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_SYMTAB_T_P_DEEP_COPY
#      define ERR_CONST_ERR_SYMTAB_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_SYMTAB_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_SYMTAB_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_SYMTAB_T_P_DEEP_COPY
#define ERR_CONST_ERR_SYMTAB_T_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_SYMTAB_T_P_DEEP_COPY */

#ifndef ERR_CONST_ERR_SYMTAB_T_P_DEEP_COMPARE
#define ERR_CONST_ERR_SYMTAB_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_SYMTAB_T_P_DEEP_COMPARE */

#ifdef ERR_ERRSYMTAB_P_DEEP
#  if ERR_ERRSYMTAB_P_DEEP
#    ifndef ERR_ERRSYMTAB_P_DEEP_COPY
#      define ERR_ERRSYMTAB_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRSYMTAB_P_DEEP_COMPARE
#      define ERR_ERRSYMTAB_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRSYMTAB_P_DEEP_COPY
#      define ERR_ERRSYMTAB_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRSYMTAB_P_DEEP_COMPARE
#      define ERR_ERRSYMTAB_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRSYMTAB_P_DEEP_COPY
#define ERR_ERRSYMTAB_P_DEEP_COPY 0
#endif /* !defined ERR_ERRSYMTAB_P_DEEP_COPY */

#ifndef ERR_ERRSYMTAB_P_DEEP_COMPARE
#define ERR_ERRSYMTAB_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRSYMTAB_P_DEEP_COMPARE */

#ifdef ERR_ERRSYMTAB_CONST_P_DEEP
#  if ERR_ERRSYMTAB_CONST_P_DEEP
#    ifndef ERR_ERRSYMTAB_CONST_P_DEEP_COPY
#      define ERR_ERRSYMTAB_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRSYMTAB_CONST_P_DEEP_COMPARE
#      define ERR_ERRSYMTAB_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRSYMTAB_CONST_P_DEEP_COPY
#      define ERR_ERRSYMTAB_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRSYMTAB_CONST_P_DEEP_COMPARE
#      define ERR_ERRSYMTAB_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRSYMTAB_CONST_P_DEEP_COPY
#define ERR_ERRSYMTAB_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERRSYMTAB_CONST_P_DEEP_COPY */

#ifndef ERR_ERRSYMTAB_CONST_P_DEEP_COMPARE
#define ERR_ERRSYMTAB_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRSYMTAB_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERRSYMTAB_P_DEEP
#  if ERR_CONST_ERRSYMTAB_P_DEEP
#    ifndef ERR_CONST_ERRSYMTAB_P_DEEP_COPY
#      define ERR_CONST_ERRSYMTAB_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRSYMTAB_P_DEEP_COMPARE
#      define ERR_CONST_ERRSYMTAB_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRSYMTAB_P_DEEP_COPY
#      define ERR_CONST_ERRSYMTAB_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRSYMTAB_P_DEEP_COMPARE
#      define ERR_CONST_ERRSYMTAB_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRSYMTAB_P_DEEP_COPY
#define ERR_CONST_ERRSYMTAB_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRSYMTAB_P_DEEP_COPY */

#ifndef ERR_CONST_ERRSYMTAB_P_DEEP_COMPARE
#define ERR_CONST_ERRSYMTAB_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRSYMTAB_P_DEEP_COMPARE */

#if ERR_ERR_SYMTAB_TP_DEEP_COMPARE && !defined(ERR_ERR_SYMTAB_TP_HASH_RAW)
#define ERR_ERR_SYMTAB_TP_HASH_RAW(A1) err_symtab_hash_raw((A1))
#endif

#if ERR_ERR_SYMTAB_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_SYMTAB_T_CONSTP_HASH_RAW)
#define ERR_ERR_SYMTAB_T_CONSTP_HASH_RAW(A1) err_symtab_hash_raw((A1))
#endif

#if ERR_CONST_ERR_SYMTAB_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_SYMTAB_TP_HASH_RAW)
#define ERR_CONST_ERR_SYMTAB_TP_HASH_RAW(A1) err_symtab_hash_raw((A1))
#endif

#if ERR_ERRSYMTABP_DEEP_COMPARE && !defined(ERR_ERRSYMTABP_HASH_RAW)
#define ERR_ERRSYMTABP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRSYMTAB_CONSTP_DEEP_COMPARE && !defined(ERR_ERRSYMTAB_CONSTP_HASH_RAW)
#define ERR_ERRSYMTAB_CONSTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRSYMTABP_DEEP_COMPARE && !defined(ERR_CONST_ERRSYMTABP_HASH_RAW)
#define ERR_CONST_ERRSYMTABP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERR_SYMTAB_T_P_DEEP_COMPARE && !defined(ERR_ERR_SYMTAB_T_P_HASH_RAW)
#define ERR_ERR_SYMTAB_T_P_HASH_RAW(A1) err_symtab_hash_raw((A1))
#endif

#if ERR_ERR_SYMTAB_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_SYMTAB_T_CONST_P_HASH_RAW)
#define ERR_ERR_SYMTAB_T_CONST_P_HASH_RAW(A1) err_symtab_hash_raw((A1))
#endif

#if ERR_CONST_ERR_SYMTAB_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_SYMTAB_T_P_HASH_RAW)
#define ERR_CONST_ERR_SYMTAB_T_P_HASH_RAW(A1) err_symtab_hash_raw((A1))
#endif

#if ERR_ERRSYMTAB_P_DEEP_COMPARE && !defined(ERR_ERRSYMTAB_P_HASH_RAW)
#define ERR_ERRSYMTAB_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRSYMTAB_CONST_P_DEEP_COMPARE && !defined(ERR_ERRSYMTAB_CONST_P_HASH_RAW)
#define ERR_ERRSYMTAB_CONST_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRSYMTAB_P_DEEP_COMPARE && !defined(ERR_CONST_ERRSYMTAB_P_HASH_RAW)
#define ERR_CONST_ERRSYMTAB_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#ifndef ERR_ERRSYMTAB_HASH_RAW
#define ERR_ERRSYMTAB_HASH_RAW(A1) ((A1).hash_raw())
#endif

#if ERR_ERR_SYMTAB_TP_DEEP_COMPARE && !defined(ERR_ERR_SYMTAB_TP_CMP)
#define ERR_ERR_SYMTAB_TP_CMP(A1,A2) err_symtab_cmp((A1),(A2))
#endif

#if ERR_ERR_SYMTAB_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_SYMTAB_T_CONSTP_CMP)
#define ERR_ERR_SYMTAB_T_CONSTP_CMP(A1,A2) err_symtab_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_SYMTAB_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_SYMTAB_TP_CMP)
#define ERR_CONST_ERR_SYMTAB_TP_CMP(A1,A2) err_symtab_cmp((A1),(A2))
#endif

#if ERR_ERRSYMTABP_DEEP_COMPARE && !defined(ERR_ERRSYMTABP_CMP)
#define ERR_ERRSYMTABP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRSYMTAB_CONSTP_DEEP_COMPARE && !defined(ERR_ERRSYMTAB_CONSTP_CMP)
#define ERR_ERRSYMTAB_CONSTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRSYMTABP_DEEP_COMPARE && !defined(ERR_CONST_ERRSYMTABP_CMP)
#define ERR_CONST_ERRSYMTABP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERR_SYMTAB_T_P_DEEP_COMPARE && !defined(ERR_ERR_SYMTAB_T_P_CMP)
#define ERR_ERR_SYMTAB_T_P_CMP(A1,A2) err_symtab_cmp((A1),(A2))
#endif

#if ERR_ERR_SYMTAB_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_SYMTAB_T_CONST_P_CMP)
#define ERR_ERR_SYMTAB_T_CONST_P_CMP(A1,A2) err_symtab_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_SYMTAB_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_SYMTAB_T_P_CMP)
#define ERR_CONST_ERR_SYMTAB_T_P_CMP(A1,A2) err_symtab_cmp((A1),(A2))
#endif

#if ERR_ERRSYMTAB_P_DEEP_COMPARE && !defined(ERR_ERRSYMTAB_P_CMP)
#define ERR_ERRSYMTAB_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRSYMTAB_CONST_P_DEEP_COMPARE && !defined(ERR_ERRSYMTAB_CONST_P_CMP)
#define ERR_ERRSYMTAB_CONST_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRSYMTAB_P_DEEP_COMPARE && !defined(ERR_CONST_ERRSYMTAB_P_CMP)
#define ERR_CONST_ERRSYMTAB_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#ifndef ERR_ERRSYMTAB_CMP
#define ERR_ERRSYMTAB_CMP(A1,A2) ((A1).cmp((A2)))
#endif

#ifndef ERR_ERRSYMTAB_ZERO
#define ERR_ERRSYMTAB_ZERO (ErrSymtab::static_zero())
#endif

#if ERR_ERR_SYMTAB_TP_DEEP_COMPARE && !defined(ERR_ERR_SYMTAB_TP_EQUAL)
#define ERR_ERR_SYMTAB_TP_EQUAL(A1,A2) err_symtab_equal((A1),(A2))
#endif

#if ERR_ERR_SYMTAB_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_SYMTAB_T_CONSTP_EQUAL)
#define ERR_ERR_SYMTAB_T_CONSTP_EQUAL(A1,A2) err_symtab_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_SYMTAB_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_SYMTAB_TP_EQUAL)
#define ERR_CONST_ERR_SYMTAB_TP_EQUAL(A1,A2) err_symtab_equal((A1),(A2))
#endif

#if ERR_ERRSYMTABP_DEEP_COMPARE && !defined(ERR_ERRSYMTABP_EQUAL)
#define ERR_ERRSYMTABP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRSYMTAB_CONSTP_DEEP_COMPARE && !defined(ERR_ERRSYMTAB_CONSTP_EQUAL)
#define ERR_ERRSYMTAB_CONSTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRSYMTABP_DEEP_COMPARE && !defined(ERR_CONST_ERRSYMTABP_EQUAL)
#define ERR_CONST_ERRSYMTABP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERR_SYMTAB_T_P_DEEP_COMPARE && !defined(ERR_ERR_SYMTAB_T_P_EQUAL)
#define ERR_ERR_SYMTAB_T_P_EQUAL(A1,A2) err_symtab_equal((A1),(A2))
#endif

#if ERR_ERR_SYMTAB_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_SYMTAB_T_CONST_P_EQUAL)
#define ERR_ERR_SYMTAB_T_CONST_P_EQUAL(A1,A2) err_symtab_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_SYMTAB_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_SYMTAB_T_P_EQUAL)
#define ERR_CONST_ERR_SYMTAB_T_P_EQUAL(A1,A2) err_symtab_equal((A1),(A2))
#endif

#if ERR_ERRSYMTAB_P_DEEP_COMPARE && !defined(ERR_ERRSYMTAB_P_EQUAL)
#define ERR_ERRSYMTAB_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRSYMTAB_CONST_P_DEEP_COMPARE && !defined(ERR_ERRSYMTAB_CONST_P_EQUAL)
#define ERR_ERRSYMTAB_CONST_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRSYMTAB_P_DEEP_COMPARE && !defined(ERR_CONST_ERRSYMTAB_P_EQUAL)
#define ERR_CONST_ERRSYMTAB_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#ifndef ERR_ERRSYMTAB_EQUAL
#define ERR_ERRSYMTAB_EQUAL(A1,A2) ((A1).equal((A2)))
#endif

#if ERR_ERR_SYMTAB_TP_DEEP_COPY && !defined(ERR_ERR_SYMTAB_TP_ICOPY)
#define ERR_ERR_SYMTAB_TP_ICOPY(A1,A2) err_symtab_copy_err((A1),(A2))
#endif

#if ERR_ERR_SYMTAB_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_SYMTAB_T_CONSTP_ICOPY)
#define ERR_ERR_SYMTAB_T_CONSTP_ICOPY(A1,A2) err_symtab_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_SYMTAB_TP_DEEP_COPY && !defined(ERR_CONST_ERR_SYMTAB_TP_ICOPY)
#define ERR_CONST_ERR_SYMTAB_TP_ICOPY(A1,A2) err_symtab_copy_err((A1),(A2))
#endif

#if ERR_ERRSYMTABP_DEEP_COPY && !defined(ERR_ERRSYMTABP_ICOPY)
#define ERR_ERRSYMTABP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRSYMTAB_CONSTP_DEEP_COPY && !defined(ERR_ERRSYMTAB_CONSTP_ICOPY)
#define ERR_ERRSYMTAB_CONSTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRSYMTABP_DEEP_COPY && !defined(ERR_CONST_ERRSYMTABP_ICOPY)
#define ERR_CONST_ERRSYMTABP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_SYMTAB_T_P_DEEP_COPY && !defined(ERR_ERR_SYMTAB_T_P_ICOPY)
#define ERR_ERR_SYMTAB_T_P_ICOPY(A1,A2) err_symtab_copy_err((A1),(A2))
#endif

#if ERR_ERR_SYMTAB_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_SYMTAB_T_CONST_P_ICOPY)
#define ERR_ERR_SYMTAB_T_CONST_P_ICOPY(A1,A2) err_symtab_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_SYMTAB_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_SYMTAB_T_P_ICOPY)
#define ERR_CONST_ERR_SYMTAB_T_P_ICOPY(A1,A2) err_symtab_copy_err((A1),(A2))
#endif

#if ERR_ERRSYMTAB_P_DEEP_COPY && !defined(ERR_ERRSYMTAB_P_ICOPY)
#define ERR_ERRSYMTAB_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRSYMTAB_CONST_P_DEEP_COPY && !defined(ERR_ERRSYMTAB_CONST_P_ICOPY)
#define ERR_ERRSYMTAB_CONST_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRSYMTAB_P_DEEP_COPY && !defined(ERR_CONST_ERRSYMTAB_P_ICOPY)
#define ERR_CONST_ERRSYMTAB_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_SYMTAB_TP_DEEP_COPY && !defined(ERR_ERR_SYMTAB_TP_OCOPY)
#define ERR_ERR_SYMTAB_TP_OCOPY(A1,A2) err_symtab_copy_err((A1),(A2))
#endif

#if ERR_ERR_SYMTAB_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_SYMTAB_T_CONSTP_OCOPY)
#define ERR_ERR_SYMTAB_T_CONSTP_OCOPY(A1,A2) err_symtab_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_SYMTAB_TP_DEEP_COPY && !defined(ERR_CONST_ERR_SYMTAB_TP_OCOPY)
#define ERR_CONST_ERR_SYMTAB_TP_OCOPY(A1,A2) err_symtab_copy_err((A1),(A2))
#endif

#if ERR_ERRSYMTABP_DEEP_COPY && !defined(ERR_ERRSYMTABP_OCOPY)
#define ERR_ERRSYMTABP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRSYMTAB_CONSTP_DEEP_COPY && !defined(ERR_ERRSYMTAB_CONSTP_OCOPY)
#define ERR_ERRSYMTAB_CONSTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRSYMTABP_DEEP_COPY && !defined(ERR_CONST_ERRSYMTABP_OCOPY)
#define ERR_CONST_ERRSYMTABP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_SYMTAB_T_P_DEEP_COPY && !defined(ERR_ERR_SYMTAB_T_P_OCOPY)
#define ERR_ERR_SYMTAB_T_P_OCOPY(A1,A2) err_symtab_copy_err((A1),(A2))
#endif

#if ERR_ERR_SYMTAB_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_SYMTAB_T_CONST_P_OCOPY)
#define ERR_ERR_SYMTAB_T_CONST_P_OCOPY(A1,A2) err_symtab_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_SYMTAB_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_SYMTAB_T_P_OCOPY)
#define ERR_CONST_ERR_SYMTAB_T_P_OCOPY(A1,A2) err_symtab_copy_err((A1),(A2))
#endif

#if ERR_ERRSYMTAB_P_DEEP_COPY && !defined(ERR_ERRSYMTAB_P_OCOPY)
#define ERR_ERRSYMTAB_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRSYMTAB_CONST_P_DEEP_COPY && !defined(ERR_ERRSYMTAB_CONST_P_OCOPY)
#define ERR_ERRSYMTAB_CONST_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRSYMTAB_P_DEEP_COPY && !defined(ERR_CONST_ERRSYMTAB_P_OCOPY)
#define ERR_CONST_ERRSYMTAB_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_SYMTAB_TP_DEEP_COPY && !defined(ERR_ERR_SYMTAB_TP_IFREE)
#define ERR_ERR_SYMTAB_TP_IFREE(A1) err_symtab_delete((A1))
#endif

#if ERR_ERR_SYMTAB_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_SYMTAB_T_CONSTP_IFREE)
#define ERR_ERR_SYMTAB_T_CONSTP_IFREE(A1) err_symtab_delete((A1))
#endif

#if ERR_CONST_ERR_SYMTAB_TP_DEEP_COPY && !defined(ERR_CONST_ERR_SYMTAB_TP_IFREE)
#define ERR_CONST_ERR_SYMTAB_TP_IFREE(A1) err_symtab_delete((A1))
#endif

#if ERR_ERRSYMTABP_DEEP_COPY && !defined(ERR_ERRSYMTABP_IFREE)
#define ERR_ERRSYMTABP_IFREE(A1) delete((A1))
#endif

#if ERR_ERRSYMTAB_CONSTP_DEEP_COPY && !defined(ERR_ERRSYMTAB_CONSTP_IFREE)
#define ERR_ERRSYMTAB_CONSTP_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRSYMTABP_DEEP_COPY && !defined(ERR_CONST_ERRSYMTABP_IFREE)
#define ERR_CONST_ERRSYMTABP_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_SYMTAB_T_P_DEEP_COPY && !defined(ERR_ERR_SYMTAB_T_P_IFREE)
#define ERR_ERR_SYMTAB_T_P_IFREE(A1) err_symtab_delete((A1))
#endif

#if ERR_ERR_SYMTAB_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_SYMTAB_T_CONST_P_IFREE)
#define ERR_ERR_SYMTAB_T_CONST_P_IFREE(A1) err_symtab_delete((A1))
#endif

#if ERR_CONST_ERR_SYMTAB_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_SYMTAB_T_P_IFREE)
#define ERR_CONST_ERR_SYMTAB_T_P_IFREE(A1) err_symtab_delete((A1))
#endif

#if ERR_ERRSYMTAB_P_DEEP_COPY && !defined(ERR_ERRSYMTAB_P_IFREE)
#define ERR_ERRSYMTAB_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERRSYMTAB_CONST_P_DEEP_COPY && !defined(ERR_ERRSYMTAB_CONST_P_IFREE)
#define ERR_ERRSYMTAB_CONST_P_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRSYMTAB_P_DEEP_COPY && !defined(ERR_CONST_ERRSYMTAB_P_IFREE)
#define ERR_CONST_ERRSYMTAB_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_SYMTAB_TP_DEEP_COPY && !defined(ERR_ERR_SYMTAB_TP_OFREE)
#define ERR_ERR_SYMTAB_TP_OFREE(A1) err_symtab_delete((A1))
#endif

#if ERR_ERR_SYMTAB_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_SYMTAB_T_CONSTP_OFREE)
#define ERR_ERR_SYMTAB_T_CONSTP_OFREE(A1) err_symtab_delete((A1))
#endif

#if ERR_CONST_ERR_SYMTAB_TP_DEEP_COPY && !defined(ERR_CONST_ERR_SYMTAB_TP_OFREE)
#define ERR_CONST_ERR_SYMTAB_TP_OFREE(A1) err_symtab_delete((A1))
#endif

#if ERR_ERRSYMTABP_DEEP_COPY && !defined(ERR_ERRSYMTABP_OFREE)
#define ERR_ERRSYMTABP_OFREE(A1) delete((A1))
#endif

#if ERR_ERRSYMTAB_CONSTP_DEEP_COPY && !defined(ERR_ERRSYMTAB_CONSTP_OFREE)
#define ERR_ERRSYMTAB_CONSTP_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRSYMTABP_DEEP_COPY && !defined(ERR_CONST_ERRSYMTABP_OFREE)
#define ERR_CONST_ERRSYMTABP_OFREE(A1) delete((A1))
#endif

#if ERR_ERR_SYMTAB_T_P_DEEP_COPY && !defined(ERR_ERR_SYMTAB_T_P_OFREE)
#define ERR_ERR_SYMTAB_T_P_OFREE(A1) err_symtab_delete((A1))
#endif

#if ERR_ERR_SYMTAB_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_SYMTAB_T_CONST_P_OFREE)
#define ERR_ERR_SYMTAB_T_CONST_P_OFREE(A1) err_symtab_delete((A1))
#endif

#if ERR_CONST_ERR_SYMTAB_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_SYMTAB_T_P_OFREE)
#define ERR_CONST_ERR_SYMTAB_T_P_OFREE(A1) err_symtab_delete((A1))
#endif

#if ERR_ERRSYMTAB_P_DEEP_COPY && !defined(ERR_ERRSYMTAB_P_OFREE)
#define ERR_ERRSYMTAB_P_OFREE(A1) delete((A1))
#endif

#if ERR_ERRSYMTAB_CONST_P_DEEP_COPY && !defined(ERR_ERRSYMTAB_CONST_P_OFREE)
#define ERR_ERRSYMTAB_CONST_P_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRSYMTAB_P_DEEP_COPY && !defined(ERR_CONST_ERRSYMTAB_P_OFREE)
#define ERR_CONST_ERRSYMTAB_P_OFREE(A1) delete((A1))
#endif

#ifndef ERR_ERRSYMTAB_CONSTRUCTOR
#define ERR_ERRSYMTAB_CONSTRUCTOR(A1) ((A1)._constructor())
#endif

#ifndef ERR_ERRSYMTAB_DESTRUCTOR
#define ERR_ERRSYMTAB_DESTRUCTOR(A1) ((A1)._destructor())
#endif


#endif /* defined ERWIN_ERR_SYMTAB_f_h */

