
#if defined(ERR_ERR_MAP_INT_SYMBOL_TP_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_SYMBOL_TP_BEING_USED */

#if defined(ERR_ERR_MAP_INT_SYMBOL_T_CONSTP_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_SYMBOL_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_INT_SYMBOL_TP_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_INT_SYMBOL_TP_BEING_USED */

#if defined(ERR_ERRMAPINTSYMBOLP_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTSYMBOLP_BEING_USED */

#if defined(ERR_ERRMAPINTSYMBOL_CONSTP_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTSYMBOL_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRMAPINTSYMBOLP_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPINTSYMBOLP_BEING_USED */

#if defined(ERR_ERR_MAP_INT_SYMBOL_T_P_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_SYMBOL_T_P_BEING_USED */

#if defined(ERR_ERR_MAP_INT_SYMBOL_T_CONST_P_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_SYMBOL_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_INT_SYMBOL_T_P_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_INT_SYMBOL_T_P_BEING_USED */

#if defined(ERR_ERRMAPINTSYMBOL_P_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTSYMBOL_P_BEING_USED */

#if defined(ERR_ERRMAPINTSYMBOL_CONST_P_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTSYMBOL_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRMAPINTSYMBOL_P_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPINTSYMBOL_P_BEING_USED */

#if defined(ERR_ERRMAPINTSYMBOL_BEING_USED) && !defined(ERR_MAP_INT_SYMBOL_NEED_HEADER)
#define ERR_MAP_INT_SYMBOL_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTSYMBOL_BEING_USED */



#ifdef ERR_MAP_INT_SYMBOL_NEED_HEADER
#include "error/err_map_int_symbol.h"
#endif

