
#ifndef ERWIN_ERR_MAP_SYMBOL_STRING_ti_h
#define ERWIN_ERR_MAP_SYMBOL_STRING_ti_h

#define err_map_symbol_string_hashlist_t_KIND STRUCT
#define err_map_symbol_string_hashlist_t_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_string_hashlist_t)
extern  TYPE_INFO_T(err_map_symbol_string_hashlist_t);

#define err_map_symbol_string_hashlist_t_p_KIND  POINTER
#define err_map_symbol_string_hashlist_t_p_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_string_hashlist_t_p)
extern  TYPE_INFO_T(err_map_symbol_string_hashlist_t_p);

#define err_map_symbol_string_hashlist_t_const_p_KIND POINTER
#define err_map_symbol_string_hashlist_t_const_p_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_string_hashlist_t_const_p)
extern  TYPE_INFO_T(err_map_symbol_string_hashlist_t_const_p);

#define err_map_symbol_string_internal_Iterator_KIND STRUCT
#define err_map_symbol_string_internal_Iterator_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_string_internal_Iterator)
extern  TYPE_INFO_T(err_map_symbol_string_internal_Iterator);

#define err_map_symbol_string_t_KIND STRUCT
#define err_map_symbol_string_t_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_string_t)
extern  TYPE_INFO_T(err_map_symbol_string_t);

#define err_map_symbol_string_t_p_KIND POINTER
#define err_map_symbol_string_t_p_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_string_t_p)
extern  TYPE_INFO_T(err_map_symbol_string_t_p);

#define err_map_symbol_string_t_const_p_KIND POINTER
#define err_map_symbol_string_t_const_p_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_string_t_const_p)
extern  TYPE_INFO_T(err_map_symbol_string_t_const_p);

#define err_map_symbol_string_content_KIND VECTOR
#define err_map_symbol_string_content_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_string_content)
extern  TYPE_INFO_T(err_map_symbol_string_content);

#define err_map_symbol_string_content_p_KIND POINTER
#define err_map_symbol_string_content_p_TYPE_INFO  TYPE_INFO_NAME(err_map_symbol_string_content_p)
extern  TYPE_INFO_T(err_map_symbol_string_content_p);

#define ErrMapSymbolString_TYPE_INFO          err_map_symbol_string_t_TYPE_INFO
#define ErrMapSymbolString_p_TYPE_INFO        err_map_symbol_string_t_p_TYPE_INFO
#define ErrMapSymbolString_const_p_TYPE_INFO  err_map_symbol_string_t_const_p_TYPE_INFO

#endif /* defined ERWIN_ERR_MAP_SYMBOL_STRING_ti_h */

