
#if defined(ERR_ERR_V_CHAR_TP_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_ERR_V_CHAR_TP_BEING_USED */

#if defined(ERR_ERR_V_CHAR_T_CONSTP_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_ERR_V_CHAR_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_V_CHAR_TP_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_V_CHAR_TP_BEING_USED */

#if defined(ERR_ERRVCHARP_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_ERRVCHARP_BEING_USED */

#if defined(ERR_ERRVCHAR_CONSTP_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_ERRVCHAR_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRVCHARP_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRVCHARP_BEING_USED */

#if defined(ERR_ERR_V_CHAR_T_P_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_ERR_V_CHAR_T_P_BEING_USED */

#if defined(ERR_ERR_V_CHAR_T_CONST_P_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_ERR_V_CHAR_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_V_CHAR_T_P_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_V_CHAR_T_P_BEING_USED */

#if defined(ERR_ERRVCHAR_P_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_ERRVCHAR_P_BEING_USED */

#if defined(ERR_ERRVCHAR_CONST_P_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_ERRVCHAR_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRVCHAR_P_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRVCHAR_P_BEING_USED */

#if defined(ERR_ERRVCHAR_BEING_USED) && !defined(ERR_V_CHAR_NEED_HEADER)
#define ERR_V_CHAR_NEED_HEADER 1
#endif /* defined ERR_ERRVCHAR_BEING_USED */



#ifdef ERR_V_CHAR_NEED_HEADER
#include "error/err_v_char.h"
#endif

