
#ifndef ERWIN_ERR_V_MESSAGE_f_h
#define ERWIN_ERR_V_MESSAGE_f_h

/* Unification of ErrVMessage and err_v_message_t: they are identical now. */
struct err_v_message_t;

#ifndef __cplusplus
typedef struct err_v_message_t err_v_message_t;
#endif /* not defined __cplusplus */

typedef err_v_message_t ErrVMessage;

typedef err_v_message_t *err_v_message_t_p;

typedef err_v_message_t const *err_v_message_t_const_p;

#define ERR_V_MESSAGE_SIG 1875852922



#ifdef ERR_ERR_V_MESSAGE_TP_DEEP
#  if ERR_ERR_V_MESSAGE_TP_DEEP
#    ifndef ERR_ERR_V_MESSAGE_TP_DEEP_COPY
#      define ERR_ERR_V_MESSAGE_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_V_MESSAGE_TP_DEEP_COMPARE
#      define ERR_ERR_V_MESSAGE_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_V_MESSAGE_TP_DEEP_COPY
#      define ERR_ERR_V_MESSAGE_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_V_MESSAGE_TP_DEEP_COMPARE
#      define ERR_ERR_V_MESSAGE_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_V_MESSAGE_TP_DEEP_COPY
#define ERR_ERR_V_MESSAGE_TP_DEEP_COPY 0
#endif /* !defined ERR_ERR_V_MESSAGE_TP_DEEP_COPY */

#ifndef ERR_ERR_V_MESSAGE_TP_DEEP_COMPARE
#define ERR_ERR_V_MESSAGE_TP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_V_MESSAGE_TP_DEEP_COMPARE */

#ifdef ERR_ERR_V_MESSAGE_T_CONSTP_DEEP
#  if ERR_ERR_V_MESSAGE_T_CONSTP_DEEP
#    ifndef ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COPY
#      define ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COPY
#      define ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COPY
#define ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COPY */

#ifndef ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COMPARE
#define ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_V_MESSAGE_TP_DEEP
#  if ERR_CONST_ERR_V_MESSAGE_TP_DEEP
#    ifndef ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COPY
#      define ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COPY
#      define ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COPY
#define ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COPY */

#ifndef ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COMPARE
#define ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COMPARE */

#ifdef ERR_ERRVMESSAGEP_DEEP
#  if ERR_ERRVMESSAGEP_DEEP
#    ifndef ERR_ERRVMESSAGEP_DEEP_COPY
#      define ERR_ERRVMESSAGEP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRVMESSAGEP_DEEP_COMPARE
#      define ERR_ERRVMESSAGEP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRVMESSAGEP_DEEP_COPY
#      define ERR_ERRVMESSAGEP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRVMESSAGEP_DEEP_COMPARE
#      define ERR_ERRVMESSAGEP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRVMESSAGEP_DEEP_COPY
#define ERR_ERRVMESSAGEP_DEEP_COPY 0
#endif /* !defined ERR_ERRVMESSAGEP_DEEP_COPY */

#ifndef ERR_ERRVMESSAGEP_DEEP_COMPARE
#define ERR_ERRVMESSAGEP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRVMESSAGEP_DEEP_COMPARE */

#ifdef ERR_ERRVMESSAGE_CONSTP_DEEP
#  if ERR_ERRVMESSAGE_CONSTP_DEEP
#    ifndef ERR_ERRVMESSAGE_CONSTP_DEEP_COPY
#      define ERR_ERRVMESSAGE_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRVMESSAGE_CONSTP_DEEP_COMPARE
#      define ERR_ERRVMESSAGE_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRVMESSAGE_CONSTP_DEEP_COPY
#      define ERR_ERRVMESSAGE_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRVMESSAGE_CONSTP_DEEP_COMPARE
#      define ERR_ERRVMESSAGE_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRVMESSAGE_CONSTP_DEEP_COPY
#define ERR_ERRVMESSAGE_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERRVMESSAGE_CONSTP_DEEP_COPY */

#ifndef ERR_ERRVMESSAGE_CONSTP_DEEP_COMPARE
#define ERR_ERRVMESSAGE_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRVMESSAGE_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERRVMESSAGEP_DEEP
#  if ERR_CONST_ERRVMESSAGEP_DEEP
#    ifndef ERR_CONST_ERRVMESSAGEP_DEEP_COPY
#      define ERR_CONST_ERRVMESSAGEP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRVMESSAGEP_DEEP_COMPARE
#      define ERR_CONST_ERRVMESSAGEP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRVMESSAGEP_DEEP_COPY
#      define ERR_CONST_ERRVMESSAGEP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRVMESSAGEP_DEEP_COMPARE
#      define ERR_CONST_ERRVMESSAGEP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRVMESSAGEP_DEEP_COPY
#define ERR_CONST_ERRVMESSAGEP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRVMESSAGEP_DEEP_COPY */

#ifndef ERR_CONST_ERRVMESSAGEP_DEEP_COMPARE
#define ERR_CONST_ERRVMESSAGEP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRVMESSAGEP_DEEP_COMPARE */

#ifdef ERR_ERR_V_MESSAGE_T_P_DEEP
#  if ERR_ERR_V_MESSAGE_T_P_DEEP
#    ifndef ERR_ERR_V_MESSAGE_T_P_DEEP_COPY
#      define ERR_ERR_V_MESSAGE_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_V_MESSAGE_T_P_DEEP_COMPARE
#      define ERR_ERR_V_MESSAGE_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_V_MESSAGE_T_P_DEEP_COPY
#      define ERR_ERR_V_MESSAGE_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_V_MESSAGE_T_P_DEEP_COMPARE
#      define ERR_ERR_V_MESSAGE_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_V_MESSAGE_T_P_DEEP_COPY
#define ERR_ERR_V_MESSAGE_T_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_V_MESSAGE_T_P_DEEP_COPY */

#ifndef ERR_ERR_V_MESSAGE_T_P_DEEP_COMPARE
#define ERR_ERR_V_MESSAGE_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_V_MESSAGE_T_P_DEEP_COMPARE */

#ifdef ERR_ERR_V_MESSAGE_T_CONST_P_DEEP
#  if ERR_ERR_V_MESSAGE_T_CONST_P_DEEP
#    ifndef ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COPY
#      define ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COPY
#      define ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COPY
#define ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COPY */

#ifndef ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COMPARE
#define ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_V_MESSAGE_T_P_DEEP
#  if ERR_CONST_ERR_V_MESSAGE_T_P_DEEP
#    ifndef ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COPY
#      define ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COPY
#      define ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COPY
#define ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COPY */

#ifndef ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COMPARE
#define ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COMPARE */

#ifdef ERR_ERRVMESSAGE_P_DEEP
#  if ERR_ERRVMESSAGE_P_DEEP
#    ifndef ERR_ERRVMESSAGE_P_DEEP_COPY
#      define ERR_ERRVMESSAGE_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRVMESSAGE_P_DEEP_COMPARE
#      define ERR_ERRVMESSAGE_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRVMESSAGE_P_DEEP_COPY
#      define ERR_ERRVMESSAGE_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRVMESSAGE_P_DEEP_COMPARE
#      define ERR_ERRVMESSAGE_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRVMESSAGE_P_DEEP_COPY
#define ERR_ERRVMESSAGE_P_DEEP_COPY 0
#endif /* !defined ERR_ERRVMESSAGE_P_DEEP_COPY */

#ifndef ERR_ERRVMESSAGE_P_DEEP_COMPARE
#define ERR_ERRVMESSAGE_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRVMESSAGE_P_DEEP_COMPARE */

#ifdef ERR_ERRVMESSAGE_CONST_P_DEEP
#  if ERR_ERRVMESSAGE_CONST_P_DEEP
#    ifndef ERR_ERRVMESSAGE_CONST_P_DEEP_COPY
#      define ERR_ERRVMESSAGE_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRVMESSAGE_CONST_P_DEEP_COMPARE
#      define ERR_ERRVMESSAGE_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRVMESSAGE_CONST_P_DEEP_COPY
#      define ERR_ERRVMESSAGE_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRVMESSAGE_CONST_P_DEEP_COMPARE
#      define ERR_ERRVMESSAGE_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRVMESSAGE_CONST_P_DEEP_COPY
#define ERR_ERRVMESSAGE_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERRVMESSAGE_CONST_P_DEEP_COPY */

#ifndef ERR_ERRVMESSAGE_CONST_P_DEEP_COMPARE
#define ERR_ERRVMESSAGE_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRVMESSAGE_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERRVMESSAGE_P_DEEP
#  if ERR_CONST_ERRVMESSAGE_P_DEEP
#    ifndef ERR_CONST_ERRVMESSAGE_P_DEEP_COPY
#      define ERR_CONST_ERRVMESSAGE_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRVMESSAGE_P_DEEP_COMPARE
#      define ERR_CONST_ERRVMESSAGE_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRVMESSAGE_P_DEEP_COPY
#      define ERR_CONST_ERRVMESSAGE_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRVMESSAGE_P_DEEP_COMPARE
#      define ERR_CONST_ERRVMESSAGE_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRVMESSAGE_P_DEEP_COPY
#define ERR_CONST_ERRVMESSAGE_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRVMESSAGE_P_DEEP_COPY */

#ifndef ERR_CONST_ERRVMESSAGE_P_DEEP_COMPARE
#define ERR_CONST_ERRVMESSAGE_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRVMESSAGE_P_DEEP_COMPARE */

#if ERR_ERR_V_MESSAGE_TP_DEEP_COMPARE && !defined(ERR_ERR_V_MESSAGE_TP_HASH_RAW)
#define ERR_ERR_V_MESSAGE_TP_HASH_RAW(A1) err_v_message_hash_raw((A1))
#endif

#if ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_V_MESSAGE_T_CONSTP_HASH_RAW)
#define ERR_ERR_V_MESSAGE_T_CONSTP_HASH_RAW(A1) err_v_message_hash_raw((A1))
#endif

#if ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_V_MESSAGE_TP_HASH_RAW)
#define ERR_CONST_ERR_V_MESSAGE_TP_HASH_RAW(A1) err_v_message_hash_raw((A1))
#endif

#if ERR_ERRVMESSAGEP_DEEP_COMPARE && !defined(ERR_ERRVMESSAGEP_HASH_RAW)
#define ERR_ERRVMESSAGEP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRVMESSAGE_CONSTP_DEEP_COMPARE && !defined(ERR_ERRVMESSAGE_CONSTP_HASH_RAW)
#define ERR_ERRVMESSAGE_CONSTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRVMESSAGEP_DEEP_COMPARE && !defined(ERR_CONST_ERRVMESSAGEP_HASH_RAW)
#define ERR_CONST_ERRVMESSAGEP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERR_V_MESSAGE_T_P_DEEP_COMPARE && !defined(ERR_ERR_V_MESSAGE_T_P_HASH_RAW)
#define ERR_ERR_V_MESSAGE_T_P_HASH_RAW(A1) err_v_message_hash_raw((A1))
#endif

#if ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_V_MESSAGE_T_CONST_P_HASH_RAW)
#define ERR_ERR_V_MESSAGE_T_CONST_P_HASH_RAW(A1) err_v_message_hash_raw((A1))
#endif

#if ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_V_MESSAGE_T_P_HASH_RAW)
#define ERR_CONST_ERR_V_MESSAGE_T_P_HASH_RAW(A1) err_v_message_hash_raw((A1))
#endif

#if ERR_ERRVMESSAGE_P_DEEP_COMPARE && !defined(ERR_ERRVMESSAGE_P_HASH_RAW)
#define ERR_ERRVMESSAGE_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRVMESSAGE_CONST_P_DEEP_COMPARE && !defined(ERR_ERRVMESSAGE_CONST_P_HASH_RAW)
#define ERR_ERRVMESSAGE_CONST_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRVMESSAGE_P_DEEP_COMPARE && !defined(ERR_CONST_ERRVMESSAGE_P_HASH_RAW)
#define ERR_CONST_ERRVMESSAGE_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#ifndef ERR_ERRVMESSAGE_HASH_RAW
#define ERR_ERRVMESSAGE_HASH_RAW(A1) ((A1).hash_raw())
#endif

#if ERR_ERR_V_MESSAGE_TP_DEEP_COMPARE && !defined(ERR_ERR_V_MESSAGE_TP_CMP)
#define ERR_ERR_V_MESSAGE_TP_CMP(A1,A2) err_v_message_cmp((A1),(A2),NULL)
#endif

#if ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_V_MESSAGE_T_CONSTP_CMP)
#define ERR_ERR_V_MESSAGE_T_CONSTP_CMP(A1,A2) err_v_message_cmp((A1),(A2),NULL)
#endif

#if ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_V_MESSAGE_TP_CMP)
#define ERR_CONST_ERR_V_MESSAGE_TP_CMP(A1,A2) err_v_message_cmp((A1),(A2),NULL)
#endif

#if ERR_ERRVMESSAGEP_DEEP_COMPARE && !defined(ERR_ERRVMESSAGEP_CMP)
#define ERR_ERRVMESSAGEP_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_ERRVMESSAGE_CONSTP_DEEP_COMPARE && !defined(ERR_ERRVMESSAGE_CONSTP_CMP)
#define ERR_ERRVMESSAGE_CONSTP_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_CONST_ERRVMESSAGEP_DEEP_COMPARE && !defined(ERR_CONST_ERRVMESSAGEP_CMP)
#define ERR_CONST_ERRVMESSAGEP_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_ERR_V_MESSAGE_T_P_DEEP_COMPARE && !defined(ERR_ERR_V_MESSAGE_T_P_CMP)
#define ERR_ERR_V_MESSAGE_T_P_CMP(A1,A2) err_v_message_cmp((A1),(A2),NULL)
#endif

#if ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_V_MESSAGE_T_CONST_P_CMP)
#define ERR_ERR_V_MESSAGE_T_CONST_P_CMP(A1,A2) err_v_message_cmp((A1),(A2),NULL)
#endif

#if ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_V_MESSAGE_T_P_CMP)
#define ERR_CONST_ERR_V_MESSAGE_T_P_CMP(A1,A2) err_v_message_cmp((A1),(A2),NULL)
#endif

#if ERR_ERRVMESSAGE_P_DEEP_COMPARE && !defined(ERR_ERRVMESSAGE_P_CMP)
#define ERR_ERRVMESSAGE_P_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_ERRVMESSAGE_CONST_P_DEEP_COMPARE && !defined(ERR_ERRVMESSAGE_CONST_P_CMP)
#define ERR_ERRVMESSAGE_CONST_P_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_CONST_ERRVMESSAGE_P_DEEP_COMPARE && !defined(ERR_CONST_ERRVMESSAGE_P_CMP)
#define ERR_CONST_ERRVMESSAGE_P_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#ifndef ERR_ERRVMESSAGE_CMP
#define ERR_ERRVMESSAGE_CMP(A1,A2) ((A1).cmp((A2),NULL))
#endif

#ifndef ERR_ERRVMESSAGE_ZERO
#define ERR_ERRVMESSAGE_ZERO (ErrVMessage::static_zero())
#endif

#if ERR_ERR_V_MESSAGE_TP_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_TP_ICOPY)
#define ERR_ERR_V_MESSAGE_TP_ICOPY(A1,A2) err_v_message_copy_err((A1),(A2))
#endif

#if ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_T_CONSTP_ICOPY)
#define ERR_ERR_V_MESSAGE_T_CONSTP_ICOPY(A1,A2) err_v_message_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COPY && !defined(ERR_CONST_ERR_V_MESSAGE_TP_ICOPY)
#define ERR_CONST_ERR_V_MESSAGE_TP_ICOPY(A1,A2) err_v_message_copy_err((A1),(A2))
#endif

#if ERR_ERRVMESSAGEP_DEEP_COPY && !defined(ERR_ERRVMESSAGEP_ICOPY)
#define ERR_ERRVMESSAGEP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRVMESSAGE_CONSTP_DEEP_COPY && !defined(ERR_ERRVMESSAGE_CONSTP_ICOPY)
#define ERR_ERRVMESSAGE_CONSTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRVMESSAGEP_DEEP_COPY && !defined(ERR_CONST_ERRVMESSAGEP_ICOPY)
#define ERR_CONST_ERRVMESSAGEP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_V_MESSAGE_T_P_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_T_P_ICOPY)
#define ERR_ERR_V_MESSAGE_T_P_ICOPY(A1,A2) err_v_message_copy_err((A1),(A2))
#endif

#if ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_T_CONST_P_ICOPY)
#define ERR_ERR_V_MESSAGE_T_CONST_P_ICOPY(A1,A2) err_v_message_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_V_MESSAGE_T_P_ICOPY)
#define ERR_CONST_ERR_V_MESSAGE_T_P_ICOPY(A1,A2) err_v_message_copy_err((A1),(A2))
#endif

#if ERR_ERRVMESSAGE_P_DEEP_COPY && !defined(ERR_ERRVMESSAGE_P_ICOPY)
#define ERR_ERRVMESSAGE_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRVMESSAGE_CONST_P_DEEP_COPY && !defined(ERR_ERRVMESSAGE_CONST_P_ICOPY)
#define ERR_ERRVMESSAGE_CONST_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRVMESSAGE_P_DEEP_COPY && !defined(ERR_CONST_ERRVMESSAGE_P_ICOPY)
#define ERR_CONST_ERRVMESSAGE_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_V_MESSAGE_TP_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_TP_OCOPY)
#define ERR_ERR_V_MESSAGE_TP_OCOPY(A1,A2) err_v_message_copy_err((A1),(A2))
#endif

#if ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_T_CONSTP_OCOPY)
#define ERR_ERR_V_MESSAGE_T_CONSTP_OCOPY(A1,A2) err_v_message_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COPY && !defined(ERR_CONST_ERR_V_MESSAGE_TP_OCOPY)
#define ERR_CONST_ERR_V_MESSAGE_TP_OCOPY(A1,A2) err_v_message_copy_err((A1),(A2))
#endif

#if ERR_ERRVMESSAGEP_DEEP_COPY && !defined(ERR_ERRVMESSAGEP_OCOPY)
#define ERR_ERRVMESSAGEP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRVMESSAGE_CONSTP_DEEP_COPY && !defined(ERR_ERRVMESSAGE_CONSTP_OCOPY)
#define ERR_ERRVMESSAGE_CONSTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRVMESSAGEP_DEEP_COPY && !defined(ERR_CONST_ERRVMESSAGEP_OCOPY)
#define ERR_CONST_ERRVMESSAGEP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_V_MESSAGE_T_P_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_T_P_OCOPY)
#define ERR_ERR_V_MESSAGE_T_P_OCOPY(A1,A2) err_v_message_copy_err((A1),(A2))
#endif

#if ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_T_CONST_P_OCOPY)
#define ERR_ERR_V_MESSAGE_T_CONST_P_OCOPY(A1,A2) err_v_message_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_V_MESSAGE_T_P_OCOPY)
#define ERR_CONST_ERR_V_MESSAGE_T_P_OCOPY(A1,A2) err_v_message_copy_err((A1),(A2))
#endif

#if ERR_ERRVMESSAGE_P_DEEP_COPY && !defined(ERR_ERRVMESSAGE_P_OCOPY)
#define ERR_ERRVMESSAGE_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRVMESSAGE_CONST_P_DEEP_COPY && !defined(ERR_ERRVMESSAGE_CONST_P_OCOPY)
#define ERR_ERRVMESSAGE_CONST_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRVMESSAGE_P_DEEP_COPY && !defined(ERR_CONST_ERRVMESSAGE_P_OCOPY)
#define ERR_CONST_ERRVMESSAGE_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_V_MESSAGE_TP_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_TP_IFREE)
#define ERR_ERR_V_MESSAGE_TP_IFREE(A1) err_v_message_delete((A1))
#endif

#if ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_T_CONSTP_IFREE)
#define ERR_ERR_V_MESSAGE_T_CONSTP_IFREE(A1) err_v_message_delete((A1))
#endif

#if ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COPY && !defined(ERR_CONST_ERR_V_MESSAGE_TP_IFREE)
#define ERR_CONST_ERR_V_MESSAGE_TP_IFREE(A1) err_v_message_delete((A1))
#endif

#if ERR_ERRVMESSAGEP_DEEP_COPY && !defined(ERR_ERRVMESSAGEP_IFREE)
#define ERR_ERRVMESSAGEP_IFREE(A1) delete((A1))
#endif

#if ERR_ERRVMESSAGE_CONSTP_DEEP_COPY && !defined(ERR_ERRVMESSAGE_CONSTP_IFREE)
#define ERR_ERRVMESSAGE_CONSTP_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRVMESSAGEP_DEEP_COPY && !defined(ERR_CONST_ERRVMESSAGEP_IFREE)
#define ERR_CONST_ERRVMESSAGEP_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_V_MESSAGE_T_P_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_T_P_IFREE)
#define ERR_ERR_V_MESSAGE_T_P_IFREE(A1) err_v_message_delete((A1))
#endif

#if ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_T_CONST_P_IFREE)
#define ERR_ERR_V_MESSAGE_T_CONST_P_IFREE(A1) err_v_message_delete((A1))
#endif

#if ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_V_MESSAGE_T_P_IFREE)
#define ERR_CONST_ERR_V_MESSAGE_T_P_IFREE(A1) err_v_message_delete((A1))
#endif

#if ERR_ERRVMESSAGE_P_DEEP_COPY && !defined(ERR_ERRVMESSAGE_P_IFREE)
#define ERR_ERRVMESSAGE_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERRVMESSAGE_CONST_P_DEEP_COPY && !defined(ERR_ERRVMESSAGE_CONST_P_IFREE)
#define ERR_ERRVMESSAGE_CONST_P_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRVMESSAGE_P_DEEP_COPY && !defined(ERR_CONST_ERRVMESSAGE_P_IFREE)
#define ERR_CONST_ERRVMESSAGE_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_V_MESSAGE_TP_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_TP_OFREE)
#define ERR_ERR_V_MESSAGE_TP_OFREE(A1) err_v_message_delete((A1))
#endif

#if ERR_ERR_V_MESSAGE_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_T_CONSTP_OFREE)
#define ERR_ERR_V_MESSAGE_T_CONSTP_OFREE(A1) err_v_message_delete((A1))
#endif

#if ERR_CONST_ERR_V_MESSAGE_TP_DEEP_COPY && !defined(ERR_CONST_ERR_V_MESSAGE_TP_OFREE)
#define ERR_CONST_ERR_V_MESSAGE_TP_OFREE(A1) err_v_message_delete((A1))
#endif

#if ERR_ERRVMESSAGEP_DEEP_COPY && !defined(ERR_ERRVMESSAGEP_OFREE)
#define ERR_ERRVMESSAGEP_OFREE(A1) delete((A1))
#endif

#if ERR_ERRVMESSAGE_CONSTP_DEEP_COPY && !defined(ERR_ERRVMESSAGE_CONSTP_OFREE)
#define ERR_ERRVMESSAGE_CONSTP_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRVMESSAGEP_DEEP_COPY && !defined(ERR_CONST_ERRVMESSAGEP_OFREE)
#define ERR_CONST_ERRVMESSAGEP_OFREE(A1) delete((A1))
#endif

#if ERR_ERR_V_MESSAGE_T_P_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_T_P_OFREE)
#define ERR_ERR_V_MESSAGE_T_P_OFREE(A1) err_v_message_delete((A1))
#endif

#if ERR_ERR_V_MESSAGE_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_V_MESSAGE_T_CONST_P_OFREE)
#define ERR_ERR_V_MESSAGE_T_CONST_P_OFREE(A1) err_v_message_delete((A1))
#endif

#if ERR_CONST_ERR_V_MESSAGE_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_V_MESSAGE_T_P_OFREE)
#define ERR_CONST_ERR_V_MESSAGE_T_P_OFREE(A1) err_v_message_delete((A1))
#endif

#if ERR_ERRVMESSAGE_P_DEEP_COPY && !defined(ERR_ERRVMESSAGE_P_OFREE)
#define ERR_ERRVMESSAGE_P_OFREE(A1) delete((A1))
#endif

#if ERR_ERRVMESSAGE_CONST_P_DEEP_COPY && !defined(ERR_ERRVMESSAGE_CONST_P_OFREE)
#define ERR_ERRVMESSAGE_CONST_P_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRVMESSAGE_P_DEEP_COPY && !defined(ERR_CONST_ERRVMESSAGE_P_OFREE)
#define ERR_CONST_ERRVMESSAGE_P_OFREE(A1) delete((A1))
#endif

#ifndef ERR_ERRVMESSAGE_CONSTRUCTOR
#define ERR_ERRVMESSAGE_CONSTRUCTOR(A1) ((A1)._constructor())
#endif

#ifndef ERR_ERRVMESSAGE_DESTRUCTOR
#define ERR_ERRVMESSAGE_DESTRUCTOR(A1) ((A1)._destructor())
#endif


#endif /* defined ERWIN_ERR_V_MESSAGE_f_h */

