
#if defined(ERR_ERR_MAP_CHAR_P_CHAR_P_TP_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_CHAR_P_CHAR_P_TP_BEING_USED */

#if defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_TP_BEING_USED */

#if defined(ERR_ERRMAPCHARPCHARPP_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_ERRMAPCHARPCHARPP_BEING_USED */

#if defined(ERR_ERRMAPCHARPCHARP_CONSTP_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_ERRMAPCHARPCHARP_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRMAPCHARPCHARPP_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPCHARPCHARPP_BEING_USED */

#if defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_CHAR_P_CHAR_P_T_P_BEING_USED */

#if defined(ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_CHAR_P_CHAR_P_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_CHAR_P_CHAR_P_T_P_BEING_USED */

#if defined(ERR_ERRMAPCHARPCHARP_P_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_ERRMAPCHARPCHARP_P_BEING_USED */

#if defined(ERR_ERRMAPCHARPCHARP_CONST_P_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_ERRMAPCHARPCHARP_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRMAPCHARPCHARP_P_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPCHARPCHARP_P_BEING_USED */

#if defined(ERR_ERRMAPCHARPCHARP_BEING_USED) && !defined(ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER)
#define ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER 1
#endif /* defined ERR_ERRMAPCHARPCHARP_BEING_USED */



#ifdef ERR_MAP_CHAR_P_CHAR_P_NEED_HEADER
#include "error/err_map_char_p_char_p.h"
#endif

