
#ifndef ERWIN_ERR_V_BUFFER_f_h
#define ERWIN_ERR_V_BUFFER_f_h

/* Unification of ErrVBuffer and err_v_buffer_t: they are identical now. */
struct err_v_buffer_t;

#ifndef __cplusplus
typedef struct err_v_buffer_t err_v_buffer_t;
#endif /* not defined __cplusplus */

typedef err_v_buffer_t ErrVBuffer;

typedef err_v_buffer_t *err_v_buffer_t_p;

typedef err_v_buffer_t const *err_v_buffer_t_const_p;

#define ERR_V_BUFFER_SIG 2136575116



#ifdef ERR_ERR_V_BUFFER_TP_DEEP
#  if ERR_ERR_V_BUFFER_TP_DEEP
#    ifndef ERR_ERR_V_BUFFER_TP_DEEP_COPY
#      define ERR_ERR_V_BUFFER_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_V_BUFFER_TP_DEEP_COMPARE
#      define ERR_ERR_V_BUFFER_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_V_BUFFER_TP_DEEP_COPY
#      define ERR_ERR_V_BUFFER_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_V_BUFFER_TP_DEEP_COMPARE
#      define ERR_ERR_V_BUFFER_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_V_BUFFER_TP_DEEP_COPY
#define ERR_ERR_V_BUFFER_TP_DEEP_COPY 0
#endif /* !defined ERR_ERR_V_BUFFER_TP_DEEP_COPY */

#ifndef ERR_ERR_V_BUFFER_TP_DEEP_COMPARE
#define ERR_ERR_V_BUFFER_TP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_V_BUFFER_TP_DEEP_COMPARE */

#ifdef ERR_ERR_V_BUFFER_T_CONSTP_DEEP
#  if ERR_ERR_V_BUFFER_T_CONSTP_DEEP
#    ifndef ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COPY
#      define ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COPY
#      define ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COPY
#define ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COPY */

#ifndef ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COMPARE
#define ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_V_BUFFER_TP_DEEP
#  if ERR_CONST_ERR_V_BUFFER_TP_DEEP
#    ifndef ERR_CONST_ERR_V_BUFFER_TP_DEEP_COPY
#      define ERR_CONST_ERR_V_BUFFER_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_V_BUFFER_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_V_BUFFER_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_V_BUFFER_TP_DEEP_COPY
#      define ERR_CONST_ERR_V_BUFFER_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_V_BUFFER_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_V_BUFFER_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_V_BUFFER_TP_DEEP_COPY
#define ERR_CONST_ERR_V_BUFFER_TP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_V_BUFFER_TP_DEEP_COPY */

#ifndef ERR_CONST_ERR_V_BUFFER_TP_DEEP_COMPARE
#define ERR_CONST_ERR_V_BUFFER_TP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_V_BUFFER_TP_DEEP_COMPARE */

#ifdef ERR_ERRVBUFFERP_DEEP
#  if ERR_ERRVBUFFERP_DEEP
#    ifndef ERR_ERRVBUFFERP_DEEP_COPY
#      define ERR_ERRVBUFFERP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRVBUFFERP_DEEP_COMPARE
#      define ERR_ERRVBUFFERP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRVBUFFERP_DEEP_COPY
#      define ERR_ERRVBUFFERP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRVBUFFERP_DEEP_COMPARE
#      define ERR_ERRVBUFFERP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRVBUFFERP_DEEP_COPY
#define ERR_ERRVBUFFERP_DEEP_COPY 0
#endif /* !defined ERR_ERRVBUFFERP_DEEP_COPY */

#ifndef ERR_ERRVBUFFERP_DEEP_COMPARE
#define ERR_ERRVBUFFERP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRVBUFFERP_DEEP_COMPARE */

#ifdef ERR_ERRVBUFFER_CONSTP_DEEP
#  if ERR_ERRVBUFFER_CONSTP_DEEP
#    ifndef ERR_ERRVBUFFER_CONSTP_DEEP_COPY
#      define ERR_ERRVBUFFER_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRVBUFFER_CONSTP_DEEP_COMPARE
#      define ERR_ERRVBUFFER_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRVBUFFER_CONSTP_DEEP_COPY
#      define ERR_ERRVBUFFER_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRVBUFFER_CONSTP_DEEP_COMPARE
#      define ERR_ERRVBUFFER_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRVBUFFER_CONSTP_DEEP_COPY
#define ERR_ERRVBUFFER_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERRVBUFFER_CONSTP_DEEP_COPY */

#ifndef ERR_ERRVBUFFER_CONSTP_DEEP_COMPARE
#define ERR_ERRVBUFFER_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRVBUFFER_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERRVBUFFERP_DEEP
#  if ERR_CONST_ERRVBUFFERP_DEEP
#    ifndef ERR_CONST_ERRVBUFFERP_DEEP_COPY
#      define ERR_CONST_ERRVBUFFERP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRVBUFFERP_DEEP_COMPARE
#      define ERR_CONST_ERRVBUFFERP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRVBUFFERP_DEEP_COPY
#      define ERR_CONST_ERRVBUFFERP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRVBUFFERP_DEEP_COMPARE
#      define ERR_CONST_ERRVBUFFERP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRVBUFFERP_DEEP_COPY
#define ERR_CONST_ERRVBUFFERP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRVBUFFERP_DEEP_COPY */

#ifndef ERR_CONST_ERRVBUFFERP_DEEP_COMPARE
#define ERR_CONST_ERRVBUFFERP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRVBUFFERP_DEEP_COMPARE */

#ifdef ERR_ERR_V_BUFFER_T_P_DEEP
#  if ERR_ERR_V_BUFFER_T_P_DEEP
#    ifndef ERR_ERR_V_BUFFER_T_P_DEEP_COPY
#      define ERR_ERR_V_BUFFER_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_V_BUFFER_T_P_DEEP_COMPARE
#      define ERR_ERR_V_BUFFER_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_V_BUFFER_T_P_DEEP_COPY
#      define ERR_ERR_V_BUFFER_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_V_BUFFER_T_P_DEEP_COMPARE
#      define ERR_ERR_V_BUFFER_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_V_BUFFER_T_P_DEEP_COPY
#define ERR_ERR_V_BUFFER_T_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_V_BUFFER_T_P_DEEP_COPY */

#ifndef ERR_ERR_V_BUFFER_T_P_DEEP_COMPARE
#define ERR_ERR_V_BUFFER_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_V_BUFFER_T_P_DEEP_COMPARE */

#ifdef ERR_ERR_V_BUFFER_T_CONST_P_DEEP
#  if ERR_ERR_V_BUFFER_T_CONST_P_DEEP
#    ifndef ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COPY
#      define ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COPY
#      define ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COPY
#define ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COPY */

#ifndef ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COMPARE
#define ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_V_BUFFER_T_P_DEEP
#  if ERR_CONST_ERR_V_BUFFER_T_P_DEEP
#    ifndef ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COPY
#      define ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COPY
#      define ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COPY
#define ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COPY */

#ifndef ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COMPARE
#define ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COMPARE */

#ifdef ERR_ERRVBUFFER_P_DEEP
#  if ERR_ERRVBUFFER_P_DEEP
#    ifndef ERR_ERRVBUFFER_P_DEEP_COPY
#      define ERR_ERRVBUFFER_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRVBUFFER_P_DEEP_COMPARE
#      define ERR_ERRVBUFFER_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRVBUFFER_P_DEEP_COPY
#      define ERR_ERRVBUFFER_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRVBUFFER_P_DEEP_COMPARE
#      define ERR_ERRVBUFFER_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRVBUFFER_P_DEEP_COPY
#define ERR_ERRVBUFFER_P_DEEP_COPY 0
#endif /* !defined ERR_ERRVBUFFER_P_DEEP_COPY */

#ifndef ERR_ERRVBUFFER_P_DEEP_COMPARE
#define ERR_ERRVBUFFER_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRVBUFFER_P_DEEP_COMPARE */

#ifdef ERR_ERRVBUFFER_CONST_P_DEEP
#  if ERR_ERRVBUFFER_CONST_P_DEEP
#    ifndef ERR_ERRVBUFFER_CONST_P_DEEP_COPY
#      define ERR_ERRVBUFFER_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRVBUFFER_CONST_P_DEEP_COMPARE
#      define ERR_ERRVBUFFER_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRVBUFFER_CONST_P_DEEP_COPY
#      define ERR_ERRVBUFFER_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRVBUFFER_CONST_P_DEEP_COMPARE
#      define ERR_ERRVBUFFER_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRVBUFFER_CONST_P_DEEP_COPY
#define ERR_ERRVBUFFER_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERRVBUFFER_CONST_P_DEEP_COPY */

#ifndef ERR_ERRVBUFFER_CONST_P_DEEP_COMPARE
#define ERR_ERRVBUFFER_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRVBUFFER_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERRVBUFFER_P_DEEP
#  if ERR_CONST_ERRVBUFFER_P_DEEP
#    ifndef ERR_CONST_ERRVBUFFER_P_DEEP_COPY
#      define ERR_CONST_ERRVBUFFER_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRVBUFFER_P_DEEP_COMPARE
#      define ERR_CONST_ERRVBUFFER_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRVBUFFER_P_DEEP_COPY
#      define ERR_CONST_ERRVBUFFER_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRVBUFFER_P_DEEP_COMPARE
#      define ERR_CONST_ERRVBUFFER_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRVBUFFER_P_DEEP_COPY
#define ERR_CONST_ERRVBUFFER_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRVBUFFER_P_DEEP_COPY */

#ifndef ERR_CONST_ERRVBUFFER_P_DEEP_COMPARE
#define ERR_CONST_ERRVBUFFER_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRVBUFFER_P_DEEP_COMPARE */

#if ERR_ERR_V_BUFFER_TP_DEEP_COMPARE && !defined(ERR_ERR_V_BUFFER_TP_HASH_RAW)
#define ERR_ERR_V_BUFFER_TP_HASH_RAW(A1) err_v_buffer_hash_raw((A1))
#endif

#if ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_V_BUFFER_T_CONSTP_HASH_RAW)
#define ERR_ERR_V_BUFFER_T_CONSTP_HASH_RAW(A1) err_v_buffer_hash_raw((A1))
#endif

#if ERR_CONST_ERR_V_BUFFER_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_V_BUFFER_TP_HASH_RAW)
#define ERR_CONST_ERR_V_BUFFER_TP_HASH_RAW(A1) err_v_buffer_hash_raw((A1))
#endif

#if ERR_ERRVBUFFERP_DEEP_COMPARE && !defined(ERR_ERRVBUFFERP_HASH_RAW)
#define ERR_ERRVBUFFERP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRVBUFFER_CONSTP_DEEP_COMPARE && !defined(ERR_ERRVBUFFER_CONSTP_HASH_RAW)
#define ERR_ERRVBUFFER_CONSTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRVBUFFERP_DEEP_COMPARE && !defined(ERR_CONST_ERRVBUFFERP_HASH_RAW)
#define ERR_CONST_ERRVBUFFERP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERR_V_BUFFER_T_P_DEEP_COMPARE && !defined(ERR_ERR_V_BUFFER_T_P_HASH_RAW)
#define ERR_ERR_V_BUFFER_T_P_HASH_RAW(A1) err_v_buffer_hash_raw((A1))
#endif

#if ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_V_BUFFER_T_CONST_P_HASH_RAW)
#define ERR_ERR_V_BUFFER_T_CONST_P_HASH_RAW(A1) err_v_buffer_hash_raw((A1))
#endif

#if ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_V_BUFFER_T_P_HASH_RAW)
#define ERR_CONST_ERR_V_BUFFER_T_P_HASH_RAW(A1) err_v_buffer_hash_raw((A1))
#endif

#if ERR_ERRVBUFFER_P_DEEP_COMPARE && !defined(ERR_ERRVBUFFER_P_HASH_RAW)
#define ERR_ERRVBUFFER_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRVBUFFER_CONST_P_DEEP_COMPARE && !defined(ERR_ERRVBUFFER_CONST_P_HASH_RAW)
#define ERR_ERRVBUFFER_CONST_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRVBUFFER_P_DEEP_COMPARE && !defined(ERR_CONST_ERRVBUFFER_P_HASH_RAW)
#define ERR_CONST_ERRVBUFFER_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#ifndef ERR_ERRVBUFFER_HASH_RAW
#define ERR_ERRVBUFFER_HASH_RAW(A1) ((A1).hash_raw())
#endif

#if ERR_ERR_V_BUFFER_TP_DEEP_COMPARE && !defined(ERR_ERR_V_BUFFER_TP_CMP)
#define ERR_ERR_V_BUFFER_TP_CMP(A1,A2) err_v_buffer_cmp((A1),(A2),NULL)
#endif

#if ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_V_BUFFER_T_CONSTP_CMP)
#define ERR_ERR_V_BUFFER_T_CONSTP_CMP(A1,A2) err_v_buffer_cmp((A1),(A2),NULL)
#endif

#if ERR_CONST_ERR_V_BUFFER_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_V_BUFFER_TP_CMP)
#define ERR_CONST_ERR_V_BUFFER_TP_CMP(A1,A2) err_v_buffer_cmp((A1),(A2),NULL)
#endif

#if ERR_ERRVBUFFERP_DEEP_COMPARE && !defined(ERR_ERRVBUFFERP_CMP)
#define ERR_ERRVBUFFERP_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_ERRVBUFFER_CONSTP_DEEP_COMPARE && !defined(ERR_ERRVBUFFER_CONSTP_CMP)
#define ERR_ERRVBUFFER_CONSTP_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_CONST_ERRVBUFFERP_DEEP_COMPARE && !defined(ERR_CONST_ERRVBUFFERP_CMP)
#define ERR_CONST_ERRVBUFFERP_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_ERR_V_BUFFER_T_P_DEEP_COMPARE && !defined(ERR_ERR_V_BUFFER_T_P_CMP)
#define ERR_ERR_V_BUFFER_T_P_CMP(A1,A2) err_v_buffer_cmp((A1),(A2),NULL)
#endif

#if ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_V_BUFFER_T_CONST_P_CMP)
#define ERR_ERR_V_BUFFER_T_CONST_P_CMP(A1,A2) err_v_buffer_cmp((A1),(A2),NULL)
#endif

#if ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_V_BUFFER_T_P_CMP)
#define ERR_CONST_ERR_V_BUFFER_T_P_CMP(A1,A2) err_v_buffer_cmp((A1),(A2),NULL)
#endif

#if ERR_ERRVBUFFER_P_DEEP_COMPARE && !defined(ERR_ERRVBUFFER_P_CMP)
#define ERR_ERRVBUFFER_P_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_ERRVBUFFER_CONST_P_DEEP_COMPARE && !defined(ERR_ERRVBUFFER_CONST_P_CMP)
#define ERR_ERRVBUFFER_CONST_P_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#if ERR_CONST_ERRVBUFFER_P_DEEP_COMPARE && !defined(ERR_CONST_ERRVBUFFER_P_CMP)
#define ERR_CONST_ERRVBUFFER_P_CMP(A1,A2) ((A1)->cmp((A2),NULL))
#endif

#ifndef ERR_ERRVBUFFER_CMP
#define ERR_ERRVBUFFER_CMP(A1,A2) ((A1).cmp((A2),NULL))
#endif

#ifndef ERR_ERRVBUFFER_ZERO
#define ERR_ERRVBUFFER_ZERO (ErrVBuffer::static_zero())
#endif

#if ERR_ERR_V_BUFFER_TP_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_TP_ICOPY)
#define ERR_ERR_V_BUFFER_TP_ICOPY(A1,A2) err_v_buffer_copy_err((A1),(A2))
#endif

#if ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_T_CONSTP_ICOPY)
#define ERR_ERR_V_BUFFER_T_CONSTP_ICOPY(A1,A2) err_v_buffer_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_V_BUFFER_TP_DEEP_COPY && !defined(ERR_CONST_ERR_V_BUFFER_TP_ICOPY)
#define ERR_CONST_ERR_V_BUFFER_TP_ICOPY(A1,A2) err_v_buffer_copy_err((A1),(A2))
#endif

#if ERR_ERRVBUFFERP_DEEP_COPY && !defined(ERR_ERRVBUFFERP_ICOPY)
#define ERR_ERRVBUFFERP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRVBUFFER_CONSTP_DEEP_COPY && !defined(ERR_ERRVBUFFER_CONSTP_ICOPY)
#define ERR_ERRVBUFFER_CONSTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRVBUFFERP_DEEP_COPY && !defined(ERR_CONST_ERRVBUFFERP_ICOPY)
#define ERR_CONST_ERRVBUFFERP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_V_BUFFER_T_P_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_T_P_ICOPY)
#define ERR_ERR_V_BUFFER_T_P_ICOPY(A1,A2) err_v_buffer_copy_err((A1),(A2))
#endif

#if ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_T_CONST_P_ICOPY)
#define ERR_ERR_V_BUFFER_T_CONST_P_ICOPY(A1,A2) err_v_buffer_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_V_BUFFER_T_P_ICOPY)
#define ERR_CONST_ERR_V_BUFFER_T_P_ICOPY(A1,A2) err_v_buffer_copy_err((A1),(A2))
#endif

#if ERR_ERRVBUFFER_P_DEEP_COPY && !defined(ERR_ERRVBUFFER_P_ICOPY)
#define ERR_ERRVBUFFER_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRVBUFFER_CONST_P_DEEP_COPY && !defined(ERR_ERRVBUFFER_CONST_P_ICOPY)
#define ERR_ERRVBUFFER_CONST_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRVBUFFER_P_DEEP_COPY && !defined(ERR_CONST_ERRVBUFFER_P_ICOPY)
#define ERR_CONST_ERRVBUFFER_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_V_BUFFER_TP_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_TP_OCOPY)
#define ERR_ERR_V_BUFFER_TP_OCOPY(A1,A2) err_v_buffer_copy_err((A1),(A2))
#endif

#if ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_T_CONSTP_OCOPY)
#define ERR_ERR_V_BUFFER_T_CONSTP_OCOPY(A1,A2) err_v_buffer_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_V_BUFFER_TP_DEEP_COPY && !defined(ERR_CONST_ERR_V_BUFFER_TP_OCOPY)
#define ERR_CONST_ERR_V_BUFFER_TP_OCOPY(A1,A2) err_v_buffer_copy_err((A1),(A2))
#endif

#if ERR_ERRVBUFFERP_DEEP_COPY && !defined(ERR_ERRVBUFFERP_OCOPY)
#define ERR_ERRVBUFFERP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRVBUFFER_CONSTP_DEEP_COPY && !defined(ERR_ERRVBUFFER_CONSTP_OCOPY)
#define ERR_ERRVBUFFER_CONSTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRVBUFFERP_DEEP_COPY && !defined(ERR_CONST_ERRVBUFFERP_OCOPY)
#define ERR_CONST_ERRVBUFFERP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_V_BUFFER_T_P_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_T_P_OCOPY)
#define ERR_ERR_V_BUFFER_T_P_OCOPY(A1,A2) err_v_buffer_copy_err((A1),(A2))
#endif

#if ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_T_CONST_P_OCOPY)
#define ERR_ERR_V_BUFFER_T_CONST_P_OCOPY(A1,A2) err_v_buffer_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_V_BUFFER_T_P_OCOPY)
#define ERR_CONST_ERR_V_BUFFER_T_P_OCOPY(A1,A2) err_v_buffer_copy_err((A1),(A2))
#endif

#if ERR_ERRVBUFFER_P_DEEP_COPY && !defined(ERR_ERRVBUFFER_P_OCOPY)
#define ERR_ERRVBUFFER_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRVBUFFER_CONST_P_DEEP_COPY && !defined(ERR_ERRVBUFFER_CONST_P_OCOPY)
#define ERR_ERRVBUFFER_CONST_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRVBUFFER_P_DEEP_COPY && !defined(ERR_CONST_ERRVBUFFER_P_OCOPY)
#define ERR_CONST_ERRVBUFFER_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_V_BUFFER_TP_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_TP_IFREE)
#define ERR_ERR_V_BUFFER_TP_IFREE(A1) err_v_buffer_delete((A1))
#endif

#if ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_T_CONSTP_IFREE)
#define ERR_ERR_V_BUFFER_T_CONSTP_IFREE(A1) err_v_buffer_delete((A1))
#endif

#if ERR_CONST_ERR_V_BUFFER_TP_DEEP_COPY && !defined(ERR_CONST_ERR_V_BUFFER_TP_IFREE)
#define ERR_CONST_ERR_V_BUFFER_TP_IFREE(A1) err_v_buffer_delete((A1))
#endif

#if ERR_ERRVBUFFERP_DEEP_COPY && !defined(ERR_ERRVBUFFERP_IFREE)
#define ERR_ERRVBUFFERP_IFREE(A1) delete((A1))
#endif

#if ERR_ERRVBUFFER_CONSTP_DEEP_COPY && !defined(ERR_ERRVBUFFER_CONSTP_IFREE)
#define ERR_ERRVBUFFER_CONSTP_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRVBUFFERP_DEEP_COPY && !defined(ERR_CONST_ERRVBUFFERP_IFREE)
#define ERR_CONST_ERRVBUFFERP_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_V_BUFFER_T_P_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_T_P_IFREE)
#define ERR_ERR_V_BUFFER_T_P_IFREE(A1) err_v_buffer_delete((A1))
#endif

#if ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_T_CONST_P_IFREE)
#define ERR_ERR_V_BUFFER_T_CONST_P_IFREE(A1) err_v_buffer_delete((A1))
#endif

#if ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_V_BUFFER_T_P_IFREE)
#define ERR_CONST_ERR_V_BUFFER_T_P_IFREE(A1) err_v_buffer_delete((A1))
#endif

#if ERR_ERRVBUFFER_P_DEEP_COPY && !defined(ERR_ERRVBUFFER_P_IFREE)
#define ERR_ERRVBUFFER_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERRVBUFFER_CONST_P_DEEP_COPY && !defined(ERR_ERRVBUFFER_CONST_P_IFREE)
#define ERR_ERRVBUFFER_CONST_P_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRVBUFFER_P_DEEP_COPY && !defined(ERR_CONST_ERRVBUFFER_P_IFREE)
#define ERR_CONST_ERRVBUFFER_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_V_BUFFER_TP_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_TP_OFREE)
#define ERR_ERR_V_BUFFER_TP_OFREE(A1) err_v_buffer_delete((A1))
#endif

#if ERR_ERR_V_BUFFER_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_T_CONSTP_OFREE)
#define ERR_ERR_V_BUFFER_T_CONSTP_OFREE(A1) err_v_buffer_delete((A1))
#endif

#if ERR_CONST_ERR_V_BUFFER_TP_DEEP_COPY && !defined(ERR_CONST_ERR_V_BUFFER_TP_OFREE)
#define ERR_CONST_ERR_V_BUFFER_TP_OFREE(A1) err_v_buffer_delete((A1))
#endif

#if ERR_ERRVBUFFERP_DEEP_COPY && !defined(ERR_ERRVBUFFERP_OFREE)
#define ERR_ERRVBUFFERP_OFREE(A1) delete((A1))
#endif

#if ERR_ERRVBUFFER_CONSTP_DEEP_COPY && !defined(ERR_ERRVBUFFER_CONSTP_OFREE)
#define ERR_ERRVBUFFER_CONSTP_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRVBUFFERP_DEEP_COPY && !defined(ERR_CONST_ERRVBUFFERP_OFREE)
#define ERR_CONST_ERRVBUFFERP_OFREE(A1) delete((A1))
#endif

#if ERR_ERR_V_BUFFER_T_P_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_T_P_OFREE)
#define ERR_ERR_V_BUFFER_T_P_OFREE(A1) err_v_buffer_delete((A1))
#endif

#if ERR_ERR_V_BUFFER_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_V_BUFFER_T_CONST_P_OFREE)
#define ERR_ERR_V_BUFFER_T_CONST_P_OFREE(A1) err_v_buffer_delete((A1))
#endif

#if ERR_CONST_ERR_V_BUFFER_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_V_BUFFER_T_P_OFREE)
#define ERR_CONST_ERR_V_BUFFER_T_P_OFREE(A1) err_v_buffer_delete((A1))
#endif

#if ERR_ERRVBUFFER_P_DEEP_COPY && !defined(ERR_ERRVBUFFER_P_OFREE)
#define ERR_ERRVBUFFER_P_OFREE(A1) delete((A1))
#endif

#if ERR_ERRVBUFFER_CONST_P_DEEP_COPY && !defined(ERR_ERRVBUFFER_CONST_P_OFREE)
#define ERR_ERRVBUFFER_CONST_P_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRVBUFFER_P_DEEP_COPY && !defined(ERR_CONST_ERRVBUFFER_P_OFREE)
#define ERR_CONST_ERRVBUFFER_P_OFREE(A1) delete((A1))
#endif

#ifndef ERR_ERRVBUFFER_CONSTRUCTOR
#define ERR_ERRVBUFFER_CONSTRUCTOR(A1) ((A1)._constructor())
#endif

#ifndef ERR_ERRVBUFFER_DESTRUCTOR
#define ERR_ERRVBUFFER_DESTRUCTOR(A1) ((A1)._destructor())
#endif


#endif /* defined ERWIN_ERR_V_BUFFER_f_h */

