
#ifndef ERWIN_ERR_MAP_INT_BOOL_f_h
#define ERWIN_ERR_MAP_INT_BOOL_f_h

struct err_map_int_bool_t;
#ifndef __cplusplus
typedef struct err_map_int_bool_t err_map_int_bool_t;
#endif
typedef struct err_map_int_bool_t ErrMapIntBool;

typedef err_map_int_bool_t *err_map_int_bool_t_p;

typedef err_map_int_bool_t const *err_map_int_bool_t_const_p;

#define ERR_MAP_INT_BOOL_SIG 1059999607



#ifdef ERR_ERR_MAP_INT_BOOL_TP_DEEP
#  if ERR_ERR_MAP_INT_BOOL_TP_DEEP
#    ifndef ERR_ERR_MAP_INT_BOOL_TP_DEEP_COPY
#      define ERR_ERR_MAP_INT_BOOL_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_INT_BOOL_TP_DEEP_COPY
#      define ERR_ERR_MAP_INT_BOOL_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_INT_BOOL_TP_DEEP_COPY
#define ERR_ERR_MAP_INT_BOOL_TP_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_INT_BOOL_TP_DEEP_COPY */

#ifndef ERR_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE
#define ERR_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP
#  if ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP
#    ifndef ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COPY
#      define ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COPY
#      define ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COPY
#define ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COPY */

#ifndef ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COMPARE
#define ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP
#  if ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP
#    ifndef ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COPY
#      define ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COPY
#      define ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COPY
#define ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COPY */

#ifndef ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE
#define ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE */

#ifdef ERR_ERRMAPINTBOOLP_DEEP
#  if ERR_ERRMAPINTBOOLP_DEEP
#    ifndef ERR_ERRMAPINTBOOLP_DEEP_COPY
#      define ERR_ERRMAPINTBOOLP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPINTBOOLP_DEEP_COMPARE
#      define ERR_ERRMAPINTBOOLP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPINTBOOLP_DEEP_COPY
#      define ERR_ERRMAPINTBOOLP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPINTBOOLP_DEEP_COMPARE
#      define ERR_ERRMAPINTBOOLP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPINTBOOLP_DEEP_COPY
#define ERR_ERRMAPINTBOOLP_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPINTBOOLP_DEEP_COPY */

#ifndef ERR_ERRMAPINTBOOLP_DEEP_COMPARE
#define ERR_ERRMAPINTBOOLP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPINTBOOLP_DEEP_COMPARE */

#ifdef ERR_ERRMAPINTBOOL_CONSTP_DEEP
#  if ERR_ERRMAPINTBOOL_CONSTP_DEEP
#    ifndef ERR_ERRMAPINTBOOL_CONSTP_DEEP_COPY
#      define ERR_ERRMAPINTBOOL_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPINTBOOL_CONSTP_DEEP_COMPARE
#      define ERR_ERRMAPINTBOOL_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPINTBOOL_CONSTP_DEEP_COPY
#      define ERR_ERRMAPINTBOOL_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPINTBOOL_CONSTP_DEEP_COMPARE
#      define ERR_ERRMAPINTBOOL_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPINTBOOL_CONSTP_DEEP_COPY
#define ERR_ERRMAPINTBOOL_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPINTBOOL_CONSTP_DEEP_COPY */

#ifndef ERR_ERRMAPINTBOOL_CONSTP_DEEP_COMPARE
#define ERR_ERRMAPINTBOOL_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPINTBOOL_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERRMAPINTBOOLP_DEEP
#  if ERR_CONST_ERRMAPINTBOOLP_DEEP
#    ifndef ERR_CONST_ERRMAPINTBOOLP_DEEP_COPY
#      define ERR_CONST_ERRMAPINTBOOLP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRMAPINTBOOLP_DEEP_COMPARE
#      define ERR_CONST_ERRMAPINTBOOLP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRMAPINTBOOLP_DEEP_COPY
#      define ERR_CONST_ERRMAPINTBOOLP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRMAPINTBOOLP_DEEP_COMPARE
#      define ERR_CONST_ERRMAPINTBOOLP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRMAPINTBOOLP_DEEP_COPY
#define ERR_CONST_ERRMAPINTBOOLP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRMAPINTBOOLP_DEEP_COPY */

#ifndef ERR_CONST_ERRMAPINTBOOLP_DEEP_COMPARE
#define ERR_CONST_ERRMAPINTBOOLP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRMAPINTBOOLP_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_INT_BOOL_T_P_DEEP
#  if ERR_ERR_MAP_INT_BOOL_T_P_DEEP
#    ifndef ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COPY
#      define ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COPY
#      define ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COPY
#define ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COPY */

#ifndef ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE
#define ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP
#  if ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP
#    ifndef ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COPY
#      define ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COPY
#      define ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COPY
#define ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COPY */

#ifndef ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COMPARE
#define ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP
#  if ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP
#    ifndef ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COPY
#      define ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COPY
#      define ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COPY
#define ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COPY */

#ifndef ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE
#define ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE */

#ifdef ERR_ERRMAPINTBOOL_P_DEEP
#  if ERR_ERRMAPINTBOOL_P_DEEP
#    ifndef ERR_ERRMAPINTBOOL_P_DEEP_COPY
#      define ERR_ERRMAPINTBOOL_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPINTBOOL_P_DEEP_COMPARE
#      define ERR_ERRMAPINTBOOL_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPINTBOOL_P_DEEP_COPY
#      define ERR_ERRMAPINTBOOL_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPINTBOOL_P_DEEP_COMPARE
#      define ERR_ERRMAPINTBOOL_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPINTBOOL_P_DEEP_COPY
#define ERR_ERRMAPINTBOOL_P_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPINTBOOL_P_DEEP_COPY */

#ifndef ERR_ERRMAPINTBOOL_P_DEEP_COMPARE
#define ERR_ERRMAPINTBOOL_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPINTBOOL_P_DEEP_COMPARE */

#ifdef ERR_ERRMAPINTBOOL_CONST_P_DEEP
#  if ERR_ERRMAPINTBOOL_CONST_P_DEEP
#    ifndef ERR_ERRMAPINTBOOL_CONST_P_DEEP_COPY
#      define ERR_ERRMAPINTBOOL_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPINTBOOL_CONST_P_DEEP_COMPARE
#      define ERR_ERRMAPINTBOOL_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPINTBOOL_CONST_P_DEEP_COPY
#      define ERR_ERRMAPINTBOOL_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPINTBOOL_CONST_P_DEEP_COMPARE
#      define ERR_ERRMAPINTBOOL_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPINTBOOL_CONST_P_DEEP_COPY
#define ERR_ERRMAPINTBOOL_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPINTBOOL_CONST_P_DEEP_COPY */

#ifndef ERR_ERRMAPINTBOOL_CONST_P_DEEP_COMPARE
#define ERR_ERRMAPINTBOOL_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPINTBOOL_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERRMAPINTBOOL_P_DEEP
#  if ERR_CONST_ERRMAPINTBOOL_P_DEEP
#    ifndef ERR_CONST_ERRMAPINTBOOL_P_DEEP_COPY
#      define ERR_CONST_ERRMAPINTBOOL_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRMAPINTBOOL_P_DEEP_COMPARE
#      define ERR_CONST_ERRMAPINTBOOL_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRMAPINTBOOL_P_DEEP_COPY
#      define ERR_CONST_ERRMAPINTBOOL_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRMAPINTBOOL_P_DEEP_COMPARE
#      define ERR_CONST_ERRMAPINTBOOL_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRMAPINTBOOL_P_DEEP_COPY
#define ERR_CONST_ERRMAPINTBOOL_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRMAPINTBOOL_P_DEEP_COPY */

#ifndef ERR_CONST_ERRMAPINTBOOL_P_DEEP_COMPARE
#define ERR_CONST_ERRMAPINTBOOL_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRMAPINTBOOL_P_DEEP_COMPARE */

#if ERR_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_BOOL_TP_HASH_RAW)
#define ERR_ERR_MAP_INT_BOOL_TP_HASH_RAW(A1) err_map_int_bool_hash_raw((A1))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_BOOL_T_CONSTP_HASH_RAW)
#define ERR_ERR_MAP_INT_BOOL_T_CONSTP_HASH_RAW(A1) err_map_int_bool_hash_raw((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_BOOL_TP_HASH_RAW)
#define ERR_CONST_ERR_MAP_INT_BOOL_TP_HASH_RAW(A1) err_map_int_bool_hash_raw((A1))
#endif

#if ERR_ERRMAPINTBOOLP_DEEP_COMPARE && !defined(ERR_ERRMAPINTBOOLP_HASH_RAW)
#define ERR_ERRMAPINTBOOLP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRMAPINTBOOL_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPINTBOOL_CONSTP_HASH_RAW)
#define ERR_ERRMAPINTBOOL_CONSTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRMAPINTBOOLP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTBOOLP_HASH_RAW)
#define ERR_CONST_ERRMAPINTBOOLP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_BOOL_T_P_HASH_RAW)
#define ERR_ERR_MAP_INT_BOOL_T_P_HASH_RAW(A1) err_map_int_bool_hash_raw((A1))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_BOOL_T_CONST_P_HASH_RAW)
#define ERR_ERR_MAP_INT_BOOL_T_CONST_P_HASH_RAW(A1) err_map_int_bool_hash_raw((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_BOOL_T_P_HASH_RAW)
#define ERR_CONST_ERR_MAP_INT_BOOL_T_P_HASH_RAW(A1) err_map_int_bool_hash_raw((A1))
#endif

#if ERR_ERRMAPINTBOOL_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTBOOL_P_HASH_RAW)
#define ERR_ERRMAPINTBOOL_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRMAPINTBOOL_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTBOOL_CONST_P_HASH_RAW)
#define ERR_ERRMAPINTBOOL_CONST_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRMAPINTBOOL_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTBOOL_P_HASH_RAW)
#define ERR_CONST_ERRMAPINTBOOL_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#ifndef ERR_ERRMAPINTBOOL_HASH_RAW
#define ERR_ERRMAPINTBOOL_HASH_RAW(A1) ((A1).hash_raw())
#endif

#if ERR_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_BOOL_TP_CMP)
#define ERR_ERR_MAP_INT_BOOL_TP_CMP(A1,A2) err_map_int_bool_cmp((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_BOOL_T_CONSTP_CMP)
#define ERR_ERR_MAP_INT_BOOL_T_CONSTP_CMP(A1,A2) err_map_int_bool_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_BOOL_TP_CMP)
#define ERR_CONST_ERR_MAP_INT_BOOL_TP_CMP(A1,A2) err_map_int_bool_cmp((A1),(A2))
#endif

#if ERR_ERRMAPINTBOOLP_DEEP_COMPARE && !defined(ERR_ERRMAPINTBOOLP_CMP)
#define ERR_ERRMAPINTBOOLP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRMAPINTBOOL_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPINTBOOL_CONSTP_CMP)
#define ERR_ERRMAPINTBOOL_CONSTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRMAPINTBOOLP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTBOOLP_CMP)
#define ERR_CONST_ERRMAPINTBOOLP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_BOOL_T_P_CMP)
#define ERR_ERR_MAP_INT_BOOL_T_P_CMP(A1,A2) err_map_int_bool_cmp((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_BOOL_T_CONST_P_CMP)
#define ERR_ERR_MAP_INT_BOOL_T_CONST_P_CMP(A1,A2) err_map_int_bool_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_BOOL_T_P_CMP)
#define ERR_CONST_ERR_MAP_INT_BOOL_T_P_CMP(A1,A2) err_map_int_bool_cmp((A1),(A2))
#endif

#if ERR_ERRMAPINTBOOL_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTBOOL_P_CMP)
#define ERR_ERRMAPINTBOOL_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRMAPINTBOOL_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTBOOL_CONST_P_CMP)
#define ERR_ERRMAPINTBOOL_CONST_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRMAPINTBOOL_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTBOOL_P_CMP)
#define ERR_CONST_ERRMAPINTBOOL_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#ifndef ERR_ERRMAPINTBOOL_CMP
#define ERR_ERRMAPINTBOOL_CMP(A1,A2) ((A1).cmp((A2)))
#endif

#ifndef ERR_ERRMAPINTBOOL_ZERO
#define ERR_ERRMAPINTBOOL_ZERO (ErrMapIntBool::static_zero())
#endif

#if ERR_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_BOOL_TP_EQUAL)
#define ERR_ERR_MAP_INT_BOOL_TP_EQUAL(A1,A2) err_map_int_bool_equal((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_BOOL_T_CONSTP_EQUAL)
#define ERR_ERR_MAP_INT_BOOL_T_CONSTP_EQUAL(A1,A2) err_map_int_bool_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_BOOL_TP_EQUAL)
#define ERR_CONST_ERR_MAP_INT_BOOL_TP_EQUAL(A1,A2) err_map_int_bool_equal((A1),(A2))
#endif

#if ERR_ERRMAPINTBOOLP_DEEP_COMPARE && !defined(ERR_ERRMAPINTBOOLP_EQUAL)
#define ERR_ERRMAPINTBOOLP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRMAPINTBOOL_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPINTBOOL_CONSTP_EQUAL)
#define ERR_ERRMAPINTBOOL_CONSTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRMAPINTBOOLP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTBOOLP_EQUAL)
#define ERR_CONST_ERRMAPINTBOOLP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_BOOL_T_P_EQUAL)
#define ERR_ERR_MAP_INT_BOOL_T_P_EQUAL(A1,A2) err_map_int_bool_equal((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_BOOL_T_CONST_P_EQUAL)
#define ERR_ERR_MAP_INT_BOOL_T_CONST_P_EQUAL(A1,A2) err_map_int_bool_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_BOOL_T_P_EQUAL)
#define ERR_CONST_ERR_MAP_INT_BOOL_T_P_EQUAL(A1,A2) err_map_int_bool_equal((A1),(A2))
#endif

#if ERR_ERRMAPINTBOOL_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTBOOL_P_EQUAL)
#define ERR_ERRMAPINTBOOL_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRMAPINTBOOL_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTBOOL_CONST_P_EQUAL)
#define ERR_ERRMAPINTBOOL_CONST_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRMAPINTBOOL_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTBOOL_P_EQUAL)
#define ERR_CONST_ERRMAPINTBOOL_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#ifndef ERR_ERRMAPINTBOOL_EQUAL
#define ERR_ERRMAPINTBOOL_EQUAL(A1,A2) ((A1).equal((A2)))
#endif

#if ERR_ERR_MAP_INT_BOOL_TP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_TP_ICOPY)
#define ERR_ERR_MAP_INT_BOOL_TP_ICOPY(A1,A2) err_map_int_bool_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_T_CONSTP_ICOPY)
#define ERR_ERR_MAP_INT_BOOL_T_CONSTP_ICOPY(A1,A2) err_map_int_bool_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_BOOL_TP_ICOPY)
#define ERR_CONST_ERR_MAP_INT_BOOL_TP_ICOPY(A1,A2) err_map_int_bool_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPINTBOOLP_DEEP_COPY && !defined(ERR_ERRMAPINTBOOLP_ICOPY)
#define ERR_ERRMAPINTBOOLP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPINTBOOL_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPINTBOOL_CONSTP_ICOPY)
#define ERR_ERRMAPINTBOOL_CONSTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPINTBOOLP_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTBOOLP_ICOPY)
#define ERR_CONST_ERRMAPINTBOOLP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_T_P_ICOPY)
#define ERR_ERR_MAP_INT_BOOL_T_P_ICOPY(A1,A2) err_map_int_bool_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_T_CONST_P_ICOPY)
#define ERR_ERR_MAP_INT_BOOL_T_CONST_P_ICOPY(A1,A2) err_map_int_bool_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_BOOL_T_P_ICOPY)
#define ERR_CONST_ERR_MAP_INT_BOOL_T_P_ICOPY(A1,A2) err_map_int_bool_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPINTBOOL_P_DEEP_COPY && !defined(ERR_ERRMAPINTBOOL_P_ICOPY)
#define ERR_ERRMAPINTBOOL_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPINTBOOL_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPINTBOOL_CONST_P_ICOPY)
#define ERR_ERRMAPINTBOOL_CONST_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPINTBOOL_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTBOOL_P_ICOPY)
#define ERR_CONST_ERRMAPINTBOOL_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_INT_BOOL_TP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_TP_OCOPY)
#define ERR_ERR_MAP_INT_BOOL_TP_OCOPY(A1,A2) err_map_int_bool_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_T_CONSTP_OCOPY)
#define ERR_ERR_MAP_INT_BOOL_T_CONSTP_OCOPY(A1,A2) err_map_int_bool_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_BOOL_TP_OCOPY)
#define ERR_CONST_ERR_MAP_INT_BOOL_TP_OCOPY(A1,A2) err_map_int_bool_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPINTBOOLP_DEEP_COPY && !defined(ERR_ERRMAPINTBOOLP_OCOPY)
#define ERR_ERRMAPINTBOOLP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPINTBOOL_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPINTBOOL_CONSTP_OCOPY)
#define ERR_ERRMAPINTBOOL_CONSTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPINTBOOLP_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTBOOLP_OCOPY)
#define ERR_CONST_ERRMAPINTBOOLP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_T_P_OCOPY)
#define ERR_ERR_MAP_INT_BOOL_T_P_OCOPY(A1,A2) err_map_int_bool_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_T_CONST_P_OCOPY)
#define ERR_ERR_MAP_INT_BOOL_T_CONST_P_OCOPY(A1,A2) err_map_int_bool_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_BOOL_T_P_OCOPY)
#define ERR_CONST_ERR_MAP_INT_BOOL_T_P_OCOPY(A1,A2) err_map_int_bool_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPINTBOOL_P_DEEP_COPY && !defined(ERR_ERRMAPINTBOOL_P_OCOPY)
#define ERR_ERRMAPINTBOOL_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPINTBOOL_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPINTBOOL_CONST_P_OCOPY)
#define ERR_ERRMAPINTBOOL_CONST_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPINTBOOL_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTBOOL_P_OCOPY)
#define ERR_CONST_ERRMAPINTBOOL_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_INT_BOOL_TP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_TP_IFREE)
#define ERR_ERR_MAP_INT_BOOL_TP_IFREE(A1) err_map_int_bool_delete((A1))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_T_CONSTP_IFREE)
#define ERR_ERR_MAP_INT_BOOL_T_CONSTP_IFREE(A1) err_map_int_bool_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_BOOL_TP_IFREE)
#define ERR_CONST_ERR_MAP_INT_BOOL_TP_IFREE(A1) err_map_int_bool_delete((A1))
#endif

#if ERR_ERRMAPINTBOOLP_DEEP_COPY && !defined(ERR_ERRMAPINTBOOLP_IFREE)
#define ERR_ERRMAPINTBOOLP_IFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPINTBOOL_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPINTBOOL_CONSTP_IFREE)
#define ERR_ERRMAPINTBOOL_CONSTP_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPINTBOOLP_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTBOOLP_IFREE)
#define ERR_CONST_ERRMAPINTBOOLP_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_T_P_IFREE)
#define ERR_ERR_MAP_INT_BOOL_T_P_IFREE(A1) err_map_int_bool_delete((A1))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_T_CONST_P_IFREE)
#define ERR_ERR_MAP_INT_BOOL_T_CONST_P_IFREE(A1) err_map_int_bool_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_BOOL_T_P_IFREE)
#define ERR_CONST_ERR_MAP_INT_BOOL_T_P_IFREE(A1) err_map_int_bool_delete((A1))
#endif

#if ERR_ERRMAPINTBOOL_P_DEEP_COPY && !defined(ERR_ERRMAPINTBOOL_P_IFREE)
#define ERR_ERRMAPINTBOOL_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPINTBOOL_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPINTBOOL_CONST_P_IFREE)
#define ERR_ERRMAPINTBOOL_CONST_P_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPINTBOOL_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTBOOL_P_IFREE)
#define ERR_CONST_ERRMAPINTBOOL_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_INT_BOOL_TP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_TP_OFREE)
#define ERR_ERR_MAP_INT_BOOL_TP_OFREE(A1) err_map_int_bool_delete((A1))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_T_CONSTP_OFREE)
#define ERR_ERR_MAP_INT_BOOL_T_CONSTP_OFREE(A1) err_map_int_bool_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_BOOL_TP_OFREE)
#define ERR_CONST_ERR_MAP_INT_BOOL_TP_OFREE(A1) err_map_int_bool_delete((A1))
#endif

#if ERR_ERRMAPINTBOOLP_DEEP_COPY && !defined(ERR_ERRMAPINTBOOLP_OFREE)
#define ERR_ERRMAPINTBOOLP_OFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPINTBOOL_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPINTBOOL_CONSTP_OFREE)
#define ERR_ERRMAPINTBOOL_CONSTP_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPINTBOOLP_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTBOOLP_OFREE)
#define ERR_CONST_ERRMAPINTBOOLP_OFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_T_P_OFREE)
#define ERR_ERR_MAP_INT_BOOL_T_P_OFREE(A1) err_map_int_bool_delete((A1))
#endif

#if ERR_ERR_MAP_INT_BOOL_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_BOOL_T_CONST_P_OFREE)
#define ERR_ERR_MAP_INT_BOOL_T_CONST_P_OFREE(A1) err_map_int_bool_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_BOOL_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_BOOL_T_P_OFREE)
#define ERR_CONST_ERR_MAP_INT_BOOL_T_P_OFREE(A1) err_map_int_bool_delete((A1))
#endif

#if ERR_ERRMAPINTBOOL_P_DEEP_COPY && !defined(ERR_ERRMAPINTBOOL_P_OFREE)
#define ERR_ERRMAPINTBOOL_P_OFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPINTBOOL_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPINTBOOL_CONST_P_OFREE)
#define ERR_ERRMAPINTBOOL_CONST_P_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPINTBOOL_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTBOOL_P_OFREE)
#define ERR_CONST_ERRMAPINTBOOL_P_OFREE(A1) delete((A1))
#endif

#ifndef ERR_ERRMAPINTBOOL_CONSTRUCTOR
#define ERR_ERRMAPINTBOOL_CONSTRUCTOR(A1) ((A1)._constructor())
#endif

#ifndef ERR_ERRMAPINTBOOL_DESTRUCTOR
#define ERR_ERRMAPINTBOOL_DESTRUCTOR(A1) ((A1)._destructor())
#endif


#endif /* defined ERWIN_ERR_MAP_INT_BOOL_f_h */

