
#if defined(ERR_ERR_MAP_INT_V_STREAM_TP_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_V_STREAM_TP_BEING_USED */

#if defined(ERR_ERR_MAP_INT_V_STREAM_T_CONSTP_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_V_STREAM_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_INT_V_STREAM_TP_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_INT_V_STREAM_TP_BEING_USED */

#if defined(ERR_ERRMAPINTVSTREAMP_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTVSTREAMP_BEING_USED */

#if defined(ERR_ERRMAPINTVSTREAM_CONSTP_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTVSTREAM_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRMAPINTVSTREAMP_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPINTVSTREAMP_BEING_USED */

#if defined(ERR_ERR_MAP_INT_V_STREAM_T_P_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_V_STREAM_T_P_BEING_USED */

#if defined(ERR_ERR_MAP_INT_V_STREAM_T_CONST_P_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_V_STREAM_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_INT_V_STREAM_T_P_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_INT_V_STREAM_T_P_BEING_USED */

#if defined(ERR_ERRMAPINTVSTREAM_P_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTVSTREAM_P_BEING_USED */

#if defined(ERR_ERRMAPINTVSTREAM_CONST_P_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTVSTREAM_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRMAPINTVSTREAM_P_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPINTVSTREAM_P_BEING_USED */

#if defined(ERR_ERRMAPINTVSTREAM_BEING_USED) && !defined(ERR_MAP_INT_V_STREAM_NEED_HEADER)
#define ERR_MAP_INT_V_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTVSTREAM_BEING_USED */



#ifdef ERR_MAP_INT_V_STREAM_NEED_HEADER
#include "error/err_map_int_v_stream.h"
#endif

