
#ifndef ERWIN_ERR_MAP_INT_CALLBACK_ti_h
#define ERWIN_ERR_MAP_INT_CALLBACK_ti_h

#define err_map_int_callback_hashlist_t_KIND STRUCT
#define err_map_int_callback_hashlist_t_TYPE_INFO  TYPE_INFO_NAME(err_map_int_callback_hashlist_t)
extern  TYPE_INFO_T(err_map_int_callback_hashlist_t);

#define err_map_int_callback_hashlist_t_p_KIND  POINTER
#define err_map_int_callback_hashlist_t_p_TYPE_INFO  TYPE_INFO_NAME(err_map_int_callback_hashlist_t_p)
extern  TYPE_INFO_T(err_map_int_callback_hashlist_t_p);

#define err_map_int_callback_hashlist_t_const_p_KIND POINTER
#define err_map_int_callback_hashlist_t_const_p_TYPE_INFO  TYPE_INFO_NAME(err_map_int_callback_hashlist_t_const_p)
extern  TYPE_INFO_T(err_map_int_callback_hashlist_t_const_p);

#define err_map_int_callback_internal_Iterator_KIND STRUCT
#define err_map_int_callback_internal_Iterator_TYPE_INFO  TYPE_INFO_NAME(err_map_int_callback_internal_Iterator)
extern  TYPE_INFO_T(err_map_int_callback_internal_Iterator);

#define err_map_int_callback_t_KIND STRUCT
#define err_map_int_callback_t_TYPE_INFO  TYPE_INFO_NAME(err_map_int_callback_t)
extern  TYPE_INFO_T(err_map_int_callback_t);

#define err_map_int_callback_t_p_KIND POINTER
#define err_map_int_callback_t_p_TYPE_INFO  TYPE_INFO_NAME(err_map_int_callback_t_p)
extern  TYPE_INFO_T(err_map_int_callback_t_p);

#define err_map_int_callback_t_const_p_KIND POINTER
#define err_map_int_callback_t_const_p_TYPE_INFO  TYPE_INFO_NAME(err_map_int_callback_t_const_p)
extern  TYPE_INFO_T(err_map_int_callback_t_const_p);

#define err_map_int_callback_content_KIND VECTOR
#define err_map_int_callback_content_TYPE_INFO  TYPE_INFO_NAME(err_map_int_callback_content)
extern  TYPE_INFO_T(err_map_int_callback_content);

#define err_map_int_callback_content_p_KIND POINTER
#define err_map_int_callback_content_p_TYPE_INFO  TYPE_INFO_NAME(err_map_int_callback_content_p)
extern  TYPE_INFO_T(err_map_int_callback_content_p);

#define ErrMapIntCallback_TYPE_INFO          err_map_int_callback_t_TYPE_INFO
#define ErrMapIntCallback_p_TYPE_INFO        err_map_int_callback_t_p_TYPE_INFO
#define ErrMapIntCallback_const_p_TYPE_INFO  err_map_int_callback_t_const_p_TYPE_INFO

#endif /* defined ERWIN_ERR_MAP_INT_CALLBACK_ti_h */

