
#if defined(ERR_ERR_MAP_SYMBOL_INT_TP_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_SYMBOL_INT_TP_BEING_USED */

#if defined(ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_SYMBOL_INT_TP_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_SYMBOL_INT_TP_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLINTP_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLINTP_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLINT_CONSTP_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLINT_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRMAPSYMBOLINTP_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPSYMBOLINTP_BEING_USED */

#if defined(ERR_ERR_MAP_SYMBOL_INT_T_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_SYMBOL_INT_T_P_BEING_USED */

#if defined(ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLINT_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLINT_P_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLINT_CONST_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLINT_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRMAPSYMBOLINT_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPSYMBOLINT_P_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLINT_BEING_USED) && !defined(ERR_MAP_SYMBOL_INT_NEED_HEADER)
#define ERR_MAP_SYMBOL_INT_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLINT_BEING_USED */



#ifdef ERR_MAP_SYMBOL_INT_NEED_HEADER
#include "error/err_map_symbol_int.h"
#endif

