
#ifndef ERWIN_ERR_MAP_SYMBOL_INT_f_h
#define ERWIN_ERR_MAP_SYMBOL_INT_f_h

struct err_map_symbol_int_t;
#ifndef __cplusplus
typedef struct err_map_symbol_int_t err_map_symbol_int_t;
#endif
typedef struct err_map_symbol_int_t ErrMapSymbolInt;

typedef err_map_symbol_int_t *err_map_symbol_int_t_p;

typedef err_map_symbol_int_t const *err_map_symbol_int_t_const_p;

#define ERR_MAP_SYMBOL_INT_SIG 404111167



#ifdef ERR_ERR_MAP_SYMBOL_INT_TP_DEEP
#  if ERR_ERR_MAP_SYMBOL_INT_TP_DEEP
#    ifndef ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY
#define ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY */

#ifndef ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE
#define ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP
#  if ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP
#    ifndef ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COPY
#define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COPY */

#ifndef ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COMPARE
#define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP
#  if ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY
#      define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY
#      define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY
#define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY */

#ifndef ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE
#define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE */

#ifdef ERR_ERRMAPSYMBOLINTP_DEEP
#  if ERR_ERRMAPSYMBOLINTP_DEEP
#    ifndef ERR_ERRMAPSYMBOLINTP_DEEP_COPY
#      define ERR_ERRMAPSYMBOLINTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPSYMBOLINTP_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLINTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPSYMBOLINTP_DEEP_COPY
#      define ERR_ERRMAPSYMBOLINTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPSYMBOLINTP_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLINTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPSYMBOLINTP_DEEP_COPY
#define ERR_ERRMAPSYMBOLINTP_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPSYMBOLINTP_DEEP_COPY */

#ifndef ERR_ERRMAPSYMBOLINTP_DEEP_COMPARE
#define ERR_ERRMAPSYMBOLINTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPSYMBOLINTP_DEEP_COMPARE */

#ifdef ERR_ERRMAPSYMBOLINT_CONSTP_DEEP
#  if ERR_ERRMAPSYMBOLINT_CONSTP_DEEP
#    ifndef ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COPY
#      define ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COPY
#      define ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COPY
#define ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COPY */

#ifndef ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COMPARE
#define ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERRMAPSYMBOLINTP_DEEP
#  if ERR_CONST_ERRMAPSYMBOLINTP_DEEP
#    ifndef ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COPY
#      define ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COMPARE
#      define ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COPY
#      define ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COMPARE
#      define ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COPY
#define ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COPY */

#ifndef ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COMPARE
#define ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP
#  if ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP
#    ifndef ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY
#define ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY */

#ifndef ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE
#define ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP
#  if ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP
#    ifndef ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COPY
#      define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COPY
#define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COPY */

#ifndef ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COMPARE
#define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP
#  if ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY
#      define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY
#      define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY
#define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY */

#ifndef ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE
#define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE */

#ifdef ERR_ERRMAPSYMBOLINT_P_DEEP
#  if ERR_ERRMAPSYMBOLINT_P_DEEP
#    ifndef ERR_ERRMAPSYMBOLINT_P_DEEP_COPY
#      define ERR_ERRMAPSYMBOLINT_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPSYMBOLINT_P_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLINT_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPSYMBOLINT_P_DEEP_COPY
#      define ERR_ERRMAPSYMBOLINT_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPSYMBOLINT_P_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLINT_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPSYMBOLINT_P_DEEP_COPY
#define ERR_ERRMAPSYMBOLINT_P_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPSYMBOLINT_P_DEEP_COPY */

#ifndef ERR_ERRMAPSYMBOLINT_P_DEEP_COMPARE
#define ERR_ERRMAPSYMBOLINT_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPSYMBOLINT_P_DEEP_COMPARE */

#ifdef ERR_ERRMAPSYMBOLINT_CONST_P_DEEP
#  if ERR_ERRMAPSYMBOLINT_CONST_P_DEEP
#    ifndef ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COPY
#      define ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COPY
#      define ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COMPARE
#      define ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COPY
#define ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COPY */

#ifndef ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COMPARE
#define ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERRMAPSYMBOLINT_P_DEEP
#  if ERR_CONST_ERRMAPSYMBOLINT_P_DEEP
#    ifndef ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COPY
#      define ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COMPARE
#      define ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COPY
#      define ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COMPARE
#      define ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COPY
#define ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COPY */

#ifndef ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COMPARE
#define ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COMPARE */

#if ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_INT_TP_HASH_RAW)
#define ERR_ERR_MAP_SYMBOL_INT_TP_HASH_RAW(A1) err_map_symbol_int_hash_raw((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_HASH_RAW)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_HASH_RAW(A1) err_map_symbol_int_hash_raw((A1))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_TP_HASH_RAW)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_HASH_RAW(A1) err_map_symbol_int_hash_raw((A1))
#endif

#if ERR_ERRMAPSYMBOLINTP_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLINTP_HASH_RAW)
#define ERR_ERRMAPSYMBOLINTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLINT_CONSTP_HASH_RAW)
#define ERR_ERRMAPSYMBOLINT_CONSTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPSYMBOLINTP_HASH_RAW)
#define ERR_CONST_ERRMAPSYMBOLINTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_INT_T_P_HASH_RAW)
#define ERR_ERR_MAP_SYMBOL_INT_T_P_HASH_RAW(A1) err_map_symbol_int_hash_raw((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_HASH_RAW)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_HASH_RAW(A1) err_map_symbol_int_hash_raw((A1))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_HASH_RAW)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_HASH_RAW(A1) err_map_symbol_int_hash_raw((A1))
#endif

#if ERR_ERRMAPSYMBOLINT_P_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLINT_P_HASH_RAW)
#define ERR_ERRMAPSYMBOLINT_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLINT_CONST_P_HASH_RAW)
#define ERR_ERRMAPSYMBOLINT_CONST_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPSYMBOLINT_P_HASH_RAW)
#define ERR_CONST_ERRMAPSYMBOLINT_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#ifndef ERR_ERRMAPSYMBOLINT_HASH_RAW
#define ERR_ERRMAPSYMBOLINT_HASH_RAW(A1) ((A1).hash_raw())
#endif

#if ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_INT_TP_CMP)
#define ERR_ERR_MAP_SYMBOL_INT_TP_CMP(A1,A2) err_map_symbol_int_cmp((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_CMP)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_CMP(A1,A2) err_map_symbol_int_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_TP_CMP)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_CMP(A1,A2) err_map_symbol_int_cmp((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLINTP_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLINTP_CMP)
#define ERR_ERRMAPSYMBOLINTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLINT_CONSTP_CMP)
#define ERR_ERRMAPSYMBOLINT_CONSTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPSYMBOLINTP_CMP)
#define ERR_CONST_ERRMAPSYMBOLINTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_INT_T_P_CMP)
#define ERR_ERR_MAP_SYMBOL_INT_T_P_CMP(A1,A2) err_map_symbol_int_cmp((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_CMP)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_CMP(A1,A2) err_map_symbol_int_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_CMP)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_CMP(A1,A2) err_map_symbol_int_cmp((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLINT_P_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLINT_P_CMP)
#define ERR_ERRMAPSYMBOLINT_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLINT_CONST_P_CMP)
#define ERR_ERRMAPSYMBOLINT_CONST_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPSYMBOLINT_P_CMP)
#define ERR_CONST_ERRMAPSYMBOLINT_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#ifndef ERR_ERRMAPSYMBOLINT_CMP
#define ERR_ERRMAPSYMBOLINT_CMP(A1,A2) ((A1).cmp((A2)))
#endif

#ifndef ERR_ERRMAPSYMBOLINT_ZERO
#define ERR_ERRMAPSYMBOLINT_ZERO (ErrMapSymbolInt::static_zero())
#endif

#if ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_INT_TP_EQUAL)
#define ERR_ERR_MAP_SYMBOL_INT_TP_EQUAL(A1,A2) err_map_symbol_int_equal((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_EQUAL)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_EQUAL(A1,A2) err_map_symbol_int_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_TP_EQUAL)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_EQUAL(A1,A2) err_map_symbol_int_equal((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLINTP_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLINTP_EQUAL)
#define ERR_ERRMAPSYMBOLINTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLINT_CONSTP_EQUAL)
#define ERR_ERRMAPSYMBOLINT_CONSTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPSYMBOLINTP_EQUAL)
#define ERR_CONST_ERRMAPSYMBOLINTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_INT_T_P_EQUAL)
#define ERR_ERR_MAP_SYMBOL_INT_T_P_EQUAL(A1,A2) err_map_symbol_int_equal((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_EQUAL)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_EQUAL(A1,A2) err_map_symbol_int_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_EQUAL)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_EQUAL(A1,A2) err_map_symbol_int_equal((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLINT_P_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLINT_P_EQUAL)
#define ERR_ERRMAPSYMBOLINT_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPSYMBOLINT_CONST_P_EQUAL)
#define ERR_ERRMAPSYMBOLINT_CONST_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPSYMBOLINT_P_EQUAL)
#define ERR_CONST_ERRMAPSYMBOLINT_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#ifndef ERR_ERRMAPSYMBOLINT_EQUAL
#define ERR_ERRMAPSYMBOLINT_EQUAL(A1,A2) ((A1).equal((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_TP_ICOPY)
#define ERR_ERR_MAP_SYMBOL_INT_TP_ICOPY(A1,A2) err_map_symbol_int_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_ICOPY)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_ICOPY(A1,A2) err_map_symbol_int_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_TP_ICOPY)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_ICOPY(A1,A2) err_map_symbol_int_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLINTP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINTP_ICOPY)
#define ERR_ERRMAPSYMBOLINTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINT_CONSTP_ICOPY)
#define ERR_ERRMAPSYMBOLINT_CONSTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLINTP_ICOPY)
#define ERR_CONST_ERRMAPSYMBOLINTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_T_P_ICOPY)
#define ERR_ERR_MAP_SYMBOL_INT_T_P_ICOPY(A1,A2) err_map_symbol_int_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_ICOPY)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_ICOPY(A1,A2) err_map_symbol_int_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_ICOPY)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_ICOPY(A1,A2) err_map_symbol_int_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLINT_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINT_P_ICOPY)
#define ERR_ERRMAPSYMBOLINT_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINT_CONST_P_ICOPY)
#define ERR_ERRMAPSYMBOLINT_CONST_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLINT_P_ICOPY)
#define ERR_CONST_ERRMAPSYMBOLINT_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_TP_OCOPY)
#define ERR_ERR_MAP_SYMBOL_INT_TP_OCOPY(A1,A2) err_map_symbol_int_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_OCOPY)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_OCOPY(A1,A2) err_map_symbol_int_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_TP_OCOPY)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_OCOPY(A1,A2) err_map_symbol_int_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLINTP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINTP_OCOPY)
#define ERR_ERRMAPSYMBOLINTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINT_CONSTP_OCOPY)
#define ERR_ERRMAPSYMBOLINT_CONSTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLINTP_OCOPY)
#define ERR_CONST_ERRMAPSYMBOLINTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_T_P_OCOPY)
#define ERR_ERR_MAP_SYMBOL_INT_T_P_OCOPY(A1,A2) err_map_symbol_int_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_OCOPY)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_OCOPY(A1,A2) err_map_symbol_int_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_OCOPY)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_OCOPY(A1,A2) err_map_symbol_int_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPSYMBOLINT_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINT_P_OCOPY)
#define ERR_ERRMAPSYMBOLINT_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINT_CONST_P_OCOPY)
#define ERR_ERRMAPSYMBOLINT_CONST_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLINT_P_OCOPY)
#define ERR_CONST_ERRMAPSYMBOLINT_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_TP_IFREE)
#define ERR_ERR_MAP_SYMBOL_INT_TP_IFREE(A1) err_map_symbol_int_delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_IFREE)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_IFREE(A1) err_map_symbol_int_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_TP_IFREE)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_IFREE(A1) err_map_symbol_int_delete((A1))
#endif

#if ERR_ERRMAPSYMBOLINTP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINTP_IFREE)
#define ERR_ERRMAPSYMBOLINTP_IFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINT_CONSTP_IFREE)
#define ERR_ERRMAPSYMBOLINT_CONSTP_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLINTP_IFREE)
#define ERR_CONST_ERRMAPSYMBOLINTP_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_T_P_IFREE)
#define ERR_ERR_MAP_SYMBOL_INT_T_P_IFREE(A1) err_map_symbol_int_delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_IFREE)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_IFREE(A1) err_map_symbol_int_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_IFREE)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_IFREE(A1) err_map_symbol_int_delete((A1))
#endif

#if ERR_ERRMAPSYMBOLINT_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINT_P_IFREE)
#define ERR_ERRMAPSYMBOLINT_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINT_CONST_P_IFREE)
#define ERR_ERRMAPSYMBOLINT_CONST_P_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLINT_P_IFREE)
#define ERR_CONST_ERRMAPSYMBOLINT_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_TP_OFREE)
#define ERR_ERR_MAP_SYMBOL_INT_TP_OFREE(A1) err_map_symbol_int_delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_OFREE)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONSTP_OFREE(A1) err_map_symbol_int_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_TP_OFREE)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_TP_OFREE(A1) err_map_symbol_int_delete((A1))
#endif

#if ERR_ERRMAPSYMBOLINTP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINTP_OFREE)
#define ERR_ERRMAPSYMBOLINTP_OFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPSYMBOLINT_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINT_CONSTP_OFREE)
#define ERR_ERRMAPSYMBOLINT_CONSTP_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPSYMBOLINTP_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLINTP_OFREE)
#define ERR_CONST_ERRMAPSYMBOLINTP_OFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_T_P_OFREE)
#define ERR_ERR_MAP_SYMBOL_INT_T_P_OFREE(A1) err_map_symbol_int_delete((A1))
#endif

#if ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_OFREE)
#define ERR_ERR_MAP_SYMBOL_INT_T_CONST_P_OFREE(A1) err_map_symbol_int_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_OFREE)
#define ERR_CONST_ERR_MAP_SYMBOL_INT_T_P_OFREE(A1) err_map_symbol_int_delete((A1))
#endif

#if ERR_ERRMAPSYMBOLINT_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINT_P_OFREE)
#define ERR_ERRMAPSYMBOLINT_P_OFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPSYMBOLINT_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPSYMBOLINT_CONST_P_OFREE)
#define ERR_ERRMAPSYMBOLINT_CONST_P_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPSYMBOLINT_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPSYMBOLINT_P_OFREE)
#define ERR_CONST_ERRMAPSYMBOLINT_P_OFREE(A1) delete((A1))
#endif

#ifndef ERR_ERRMAPSYMBOLINT_CONSTRUCTOR
#define ERR_ERRMAPSYMBOLINT_CONSTRUCTOR(A1) ((A1)._constructor())
#endif

#ifndef ERR_ERRMAPSYMBOLINT_DESTRUCTOR
#define ERR_ERRMAPSYMBOLINT_DESTRUCTOR(A1) ((A1)._destructor())
#endif


#endif /* defined ERWIN_ERR_MAP_SYMBOL_INT_f_h */

