
#ifndef ERWIN_ERR_MAP_INT_INT_f_h
#define ERWIN_ERR_MAP_INT_INT_f_h

struct err_map_int_int_t;
#ifndef __cplusplus
typedef struct err_map_int_int_t err_map_int_int_t;
#endif
typedef struct err_map_int_int_t ErrMapIntInt;

typedef err_map_int_int_t *err_map_int_int_t_p;

typedef err_map_int_int_t const *err_map_int_int_t_const_p;

#define ERR_MAP_INT_INT_SIG 1581805338



#ifdef ERR_ERR_MAP_INT_INT_TP_DEEP
#  if ERR_ERR_MAP_INT_INT_TP_DEEP
#    ifndef ERR_ERR_MAP_INT_INT_TP_DEEP_COPY
#      define ERR_ERR_MAP_INT_INT_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_INT_INT_TP_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_INT_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_INT_INT_TP_DEEP_COPY
#      define ERR_ERR_MAP_INT_INT_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_INT_INT_TP_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_INT_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_INT_INT_TP_DEEP_COPY
#define ERR_ERR_MAP_INT_INT_TP_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_INT_INT_TP_DEEP_COPY */

#ifndef ERR_ERR_MAP_INT_INT_TP_DEEP_COMPARE
#define ERR_ERR_MAP_INT_INT_TP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_INT_INT_TP_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP
#  if ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP
#    ifndef ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COPY
#      define ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COPY
#      define ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COPY
#define ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COPY */

#ifndef ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COMPARE
#define ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_MAP_INT_INT_TP_DEEP
#  if ERR_CONST_ERR_MAP_INT_INT_TP_DEEP
#    ifndef ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COPY
#      define ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COPY
#      define ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COPY
#define ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COPY */

#ifndef ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COMPARE
#define ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COMPARE */

#ifdef ERR_ERRMAPINTINTP_DEEP
#  if ERR_ERRMAPINTINTP_DEEP
#    ifndef ERR_ERRMAPINTINTP_DEEP_COPY
#      define ERR_ERRMAPINTINTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPINTINTP_DEEP_COMPARE
#      define ERR_ERRMAPINTINTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPINTINTP_DEEP_COPY
#      define ERR_ERRMAPINTINTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPINTINTP_DEEP_COMPARE
#      define ERR_ERRMAPINTINTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPINTINTP_DEEP_COPY
#define ERR_ERRMAPINTINTP_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPINTINTP_DEEP_COPY */

#ifndef ERR_ERRMAPINTINTP_DEEP_COMPARE
#define ERR_ERRMAPINTINTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPINTINTP_DEEP_COMPARE */

#ifdef ERR_ERRMAPINTINT_CONSTP_DEEP
#  if ERR_ERRMAPINTINT_CONSTP_DEEP
#    ifndef ERR_ERRMAPINTINT_CONSTP_DEEP_COPY
#      define ERR_ERRMAPINTINT_CONSTP_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPINTINT_CONSTP_DEEP_COMPARE
#      define ERR_ERRMAPINTINT_CONSTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPINTINT_CONSTP_DEEP_COPY
#      define ERR_ERRMAPINTINT_CONSTP_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPINTINT_CONSTP_DEEP_COMPARE
#      define ERR_ERRMAPINTINT_CONSTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPINTINT_CONSTP_DEEP_COPY
#define ERR_ERRMAPINTINT_CONSTP_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPINTINT_CONSTP_DEEP_COPY */

#ifndef ERR_ERRMAPINTINT_CONSTP_DEEP_COMPARE
#define ERR_ERRMAPINTINT_CONSTP_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPINTINT_CONSTP_DEEP_COMPARE */

#ifdef ERR_CONST_ERRMAPINTINTP_DEEP
#  if ERR_CONST_ERRMAPINTINTP_DEEP
#    ifndef ERR_CONST_ERRMAPINTINTP_DEEP_COPY
#      define ERR_CONST_ERRMAPINTINTP_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRMAPINTINTP_DEEP_COMPARE
#      define ERR_CONST_ERRMAPINTINTP_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRMAPINTINTP_DEEP_COPY
#      define ERR_CONST_ERRMAPINTINTP_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRMAPINTINTP_DEEP_COMPARE
#      define ERR_CONST_ERRMAPINTINTP_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRMAPINTINTP_DEEP_COPY
#define ERR_CONST_ERRMAPINTINTP_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRMAPINTINTP_DEEP_COPY */

#ifndef ERR_CONST_ERRMAPINTINTP_DEEP_COMPARE
#define ERR_CONST_ERRMAPINTINTP_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRMAPINTINTP_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_INT_INT_T_P_DEEP
#  if ERR_ERR_MAP_INT_INT_T_P_DEEP
#    ifndef ERR_ERR_MAP_INT_INT_T_P_DEEP_COPY
#      define ERR_ERR_MAP_INT_INT_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_INT_INT_T_P_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_INT_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_INT_INT_T_P_DEEP_COPY
#      define ERR_ERR_MAP_INT_INT_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_INT_INT_T_P_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_INT_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_INT_INT_T_P_DEEP_COPY
#define ERR_ERR_MAP_INT_INT_T_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_INT_INT_T_P_DEEP_COPY */

#ifndef ERR_ERR_MAP_INT_INT_T_P_DEEP_COMPARE
#define ERR_ERR_MAP_INT_INT_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_INT_INT_T_P_DEEP_COMPARE */

#ifdef ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP
#  if ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP
#    ifndef ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COPY
#      define ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COPY
#      define ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COMPARE
#      define ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COPY
#define ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COPY */

#ifndef ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COMPARE
#define ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP
#  if ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP
#    ifndef ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COPY
#      define ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COPY
#      define ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COMPARE
#      define ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COPY
#define ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COPY */

#ifndef ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COMPARE
#define ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COMPARE */

#ifdef ERR_ERRMAPINTINT_P_DEEP
#  if ERR_ERRMAPINTINT_P_DEEP
#    ifndef ERR_ERRMAPINTINT_P_DEEP_COPY
#      define ERR_ERRMAPINTINT_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPINTINT_P_DEEP_COMPARE
#      define ERR_ERRMAPINTINT_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPINTINT_P_DEEP_COPY
#      define ERR_ERRMAPINTINT_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPINTINT_P_DEEP_COMPARE
#      define ERR_ERRMAPINTINT_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPINTINT_P_DEEP_COPY
#define ERR_ERRMAPINTINT_P_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPINTINT_P_DEEP_COPY */

#ifndef ERR_ERRMAPINTINT_P_DEEP_COMPARE
#define ERR_ERRMAPINTINT_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPINTINT_P_DEEP_COMPARE */

#ifdef ERR_ERRMAPINTINT_CONST_P_DEEP
#  if ERR_ERRMAPINTINT_CONST_P_DEEP
#    ifndef ERR_ERRMAPINTINT_CONST_P_DEEP_COPY
#      define ERR_ERRMAPINTINT_CONST_P_DEEP_COPY 1
#    endif
#    ifndef ERR_ERRMAPINTINT_CONST_P_DEEP_COMPARE
#      define ERR_ERRMAPINTINT_CONST_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_ERRMAPINTINT_CONST_P_DEEP_COPY
#      define ERR_ERRMAPINTINT_CONST_P_DEEP_COPY 0
#    endif
#    ifndef ERR_ERRMAPINTINT_CONST_P_DEEP_COMPARE
#      define ERR_ERRMAPINTINT_CONST_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_ERRMAPINTINT_CONST_P_DEEP_COPY
#define ERR_ERRMAPINTINT_CONST_P_DEEP_COPY 0
#endif /* !defined ERR_ERRMAPINTINT_CONST_P_DEEP_COPY */

#ifndef ERR_ERRMAPINTINT_CONST_P_DEEP_COMPARE
#define ERR_ERRMAPINTINT_CONST_P_DEEP_COMPARE 0
#endif /* !defined ERR_ERRMAPINTINT_CONST_P_DEEP_COMPARE */

#ifdef ERR_CONST_ERRMAPINTINT_P_DEEP
#  if ERR_CONST_ERRMAPINTINT_P_DEEP
#    ifndef ERR_CONST_ERRMAPINTINT_P_DEEP_COPY
#      define ERR_CONST_ERRMAPINTINT_P_DEEP_COPY 1
#    endif
#    ifndef ERR_CONST_ERRMAPINTINT_P_DEEP_COMPARE
#      define ERR_CONST_ERRMAPINTINT_P_DEEP_COMPARE 1
#    endif
#  else
#    ifndef ERR_CONST_ERRMAPINTINT_P_DEEP_COPY
#      define ERR_CONST_ERRMAPINTINT_P_DEEP_COPY 0
#    endif
#    ifndef ERR_CONST_ERRMAPINTINT_P_DEEP_COMPARE
#      define ERR_CONST_ERRMAPINTINT_P_DEEP_COMPARE 0
#    endif
#  endif
#endif
#ifndef ERR_CONST_ERRMAPINTINT_P_DEEP_COPY
#define ERR_CONST_ERRMAPINTINT_P_DEEP_COPY 0
#endif /* !defined ERR_CONST_ERRMAPINTINT_P_DEEP_COPY */

#ifndef ERR_CONST_ERRMAPINTINT_P_DEEP_COMPARE
#define ERR_CONST_ERRMAPINTINT_P_DEEP_COMPARE 0
#endif /* !defined ERR_CONST_ERRMAPINTINT_P_DEEP_COMPARE */

#if ERR_ERR_MAP_INT_INT_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_INT_TP_HASH_RAW)
#define ERR_ERR_MAP_INT_INT_TP_HASH_RAW(A1) err_map_int_int_hash_raw((A1))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_INT_T_CONSTP_HASH_RAW)
#define ERR_ERR_MAP_INT_INT_T_CONSTP_HASH_RAW(A1) err_map_int_int_hash_raw((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_INT_TP_HASH_RAW)
#define ERR_CONST_ERR_MAP_INT_INT_TP_HASH_RAW(A1) err_map_int_int_hash_raw((A1))
#endif

#if ERR_ERRMAPINTINTP_DEEP_COMPARE && !defined(ERR_ERRMAPINTINTP_HASH_RAW)
#define ERR_ERRMAPINTINTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRMAPINTINT_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPINTINT_CONSTP_HASH_RAW)
#define ERR_ERRMAPINTINT_CONSTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRMAPINTINTP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTINTP_HASH_RAW)
#define ERR_CONST_ERRMAPINTINTP_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERR_MAP_INT_INT_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_INT_T_P_HASH_RAW)
#define ERR_ERR_MAP_INT_INT_T_P_HASH_RAW(A1) err_map_int_int_hash_raw((A1))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_INT_T_CONST_P_HASH_RAW)
#define ERR_ERR_MAP_INT_INT_T_CONST_P_HASH_RAW(A1) err_map_int_int_hash_raw((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_INT_T_P_HASH_RAW)
#define ERR_CONST_ERR_MAP_INT_INT_T_P_HASH_RAW(A1) err_map_int_int_hash_raw((A1))
#endif

#if ERR_ERRMAPINTINT_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTINT_P_HASH_RAW)
#define ERR_ERRMAPINTINT_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_ERRMAPINTINT_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTINT_CONST_P_HASH_RAW)
#define ERR_ERRMAPINTINT_CONST_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#if ERR_CONST_ERRMAPINTINT_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTINT_P_HASH_RAW)
#define ERR_CONST_ERRMAPINTINT_P_HASH_RAW(A1) ((A1)->hash_raw())
#endif

#ifndef ERR_ERRMAPINTINT_HASH_RAW
#define ERR_ERRMAPINTINT_HASH_RAW(A1) ((A1).hash_raw())
#endif

#if ERR_ERR_MAP_INT_INT_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_INT_TP_CMP)
#define ERR_ERR_MAP_INT_INT_TP_CMP(A1,A2) err_map_int_int_cmp((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_INT_T_CONSTP_CMP)
#define ERR_ERR_MAP_INT_INT_T_CONSTP_CMP(A1,A2) err_map_int_int_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_INT_TP_CMP)
#define ERR_CONST_ERR_MAP_INT_INT_TP_CMP(A1,A2) err_map_int_int_cmp((A1),(A2))
#endif

#if ERR_ERRMAPINTINTP_DEEP_COMPARE && !defined(ERR_ERRMAPINTINTP_CMP)
#define ERR_ERRMAPINTINTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRMAPINTINT_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPINTINT_CONSTP_CMP)
#define ERR_ERRMAPINTINT_CONSTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRMAPINTINTP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTINTP_CMP)
#define ERR_CONST_ERRMAPINTINTP_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERR_MAP_INT_INT_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_INT_T_P_CMP)
#define ERR_ERR_MAP_INT_INT_T_P_CMP(A1,A2) err_map_int_int_cmp((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_INT_T_CONST_P_CMP)
#define ERR_ERR_MAP_INT_INT_T_CONST_P_CMP(A1,A2) err_map_int_int_cmp((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_INT_T_P_CMP)
#define ERR_CONST_ERR_MAP_INT_INT_T_P_CMP(A1,A2) err_map_int_int_cmp((A1),(A2))
#endif

#if ERR_ERRMAPINTINT_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTINT_P_CMP)
#define ERR_ERRMAPINTINT_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_ERRMAPINTINT_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTINT_CONST_P_CMP)
#define ERR_ERRMAPINTINT_CONST_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#if ERR_CONST_ERRMAPINTINT_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTINT_P_CMP)
#define ERR_CONST_ERRMAPINTINT_P_CMP(A1,A2) ((A1)->cmp((A2)))
#endif

#ifndef ERR_ERRMAPINTINT_CMP
#define ERR_ERRMAPINTINT_CMP(A1,A2) ((A1).cmp((A2)))
#endif

#ifndef ERR_ERRMAPINTINT_ZERO
#define ERR_ERRMAPINTINT_ZERO (ErrMapIntInt::static_zero())
#endif

#if ERR_ERR_MAP_INT_INT_TP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_INT_TP_EQUAL)
#define ERR_ERR_MAP_INT_INT_TP_EQUAL(A1,A2) err_map_int_int_equal((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_INT_T_CONSTP_EQUAL)
#define ERR_ERR_MAP_INT_INT_T_CONSTP_EQUAL(A1,A2) err_map_int_int_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_INT_TP_EQUAL)
#define ERR_CONST_ERR_MAP_INT_INT_TP_EQUAL(A1,A2) err_map_int_int_equal((A1),(A2))
#endif

#if ERR_ERRMAPINTINTP_DEEP_COMPARE && !defined(ERR_ERRMAPINTINTP_EQUAL)
#define ERR_ERRMAPINTINTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRMAPINTINT_CONSTP_DEEP_COMPARE && !defined(ERR_ERRMAPINTINT_CONSTP_EQUAL)
#define ERR_ERRMAPINTINT_CONSTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRMAPINTINTP_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTINTP_EQUAL)
#define ERR_CONST_ERRMAPINTINTP_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERR_MAP_INT_INT_T_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_INT_T_P_EQUAL)
#define ERR_ERR_MAP_INT_INT_T_P_EQUAL(A1,A2) err_map_int_int_equal((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COMPARE && !defined(ERR_ERR_MAP_INT_INT_T_CONST_P_EQUAL)
#define ERR_ERR_MAP_INT_INT_T_CONST_P_EQUAL(A1,A2) err_map_int_int_equal((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COMPARE && !defined(ERR_CONST_ERR_MAP_INT_INT_T_P_EQUAL)
#define ERR_CONST_ERR_MAP_INT_INT_T_P_EQUAL(A1,A2) err_map_int_int_equal((A1),(A2))
#endif

#if ERR_ERRMAPINTINT_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTINT_P_EQUAL)
#define ERR_ERRMAPINTINT_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_ERRMAPINTINT_CONST_P_DEEP_COMPARE && !defined(ERR_ERRMAPINTINT_CONST_P_EQUAL)
#define ERR_ERRMAPINTINT_CONST_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#if ERR_CONST_ERRMAPINTINT_P_DEEP_COMPARE && !defined(ERR_CONST_ERRMAPINTINT_P_EQUAL)
#define ERR_CONST_ERRMAPINTINT_P_EQUAL(A1,A2) ((A1)->equal((A2)))
#endif

#ifndef ERR_ERRMAPINTINT_EQUAL
#define ERR_ERRMAPINTINT_EQUAL(A1,A2) ((A1).equal((A2)))
#endif

#if ERR_ERR_MAP_INT_INT_TP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_TP_ICOPY)
#define ERR_ERR_MAP_INT_INT_TP_ICOPY(A1,A2) err_map_int_int_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_T_CONSTP_ICOPY)
#define ERR_ERR_MAP_INT_INT_T_CONSTP_ICOPY(A1,A2) err_map_int_int_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_INT_TP_ICOPY)
#define ERR_CONST_ERR_MAP_INT_INT_TP_ICOPY(A1,A2) err_map_int_int_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPINTINTP_DEEP_COPY && !defined(ERR_ERRMAPINTINTP_ICOPY)
#define ERR_ERRMAPINTINTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPINTINT_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPINTINT_CONSTP_ICOPY)
#define ERR_ERRMAPINTINT_CONSTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPINTINTP_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTINTP_ICOPY)
#define ERR_CONST_ERRMAPINTINTP_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_INT_INT_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_T_P_ICOPY)
#define ERR_ERR_MAP_INT_INT_T_P_ICOPY(A1,A2) err_map_int_int_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_T_CONST_P_ICOPY)
#define ERR_ERR_MAP_INT_INT_T_CONST_P_ICOPY(A1,A2) err_map_int_int_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_INT_T_P_ICOPY)
#define ERR_CONST_ERR_MAP_INT_INT_T_P_ICOPY(A1,A2) err_map_int_int_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPINTINT_P_DEEP_COPY && !defined(ERR_ERRMAPINTINT_P_ICOPY)
#define ERR_ERRMAPINTINT_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPINTINT_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPINTINT_CONST_P_ICOPY)
#define ERR_ERRMAPINTINT_CONST_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPINTINT_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTINT_P_ICOPY)
#define ERR_CONST_ERRMAPINTINT_P_ICOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_INT_INT_TP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_TP_OCOPY)
#define ERR_ERR_MAP_INT_INT_TP_OCOPY(A1,A2) err_map_int_int_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_T_CONSTP_OCOPY)
#define ERR_ERR_MAP_INT_INT_T_CONSTP_OCOPY(A1,A2) err_map_int_int_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_INT_TP_OCOPY)
#define ERR_CONST_ERR_MAP_INT_INT_TP_OCOPY(A1,A2) err_map_int_int_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPINTINTP_DEEP_COPY && !defined(ERR_ERRMAPINTINTP_OCOPY)
#define ERR_ERRMAPINTINTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPINTINT_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPINTINT_CONSTP_OCOPY)
#define ERR_ERRMAPINTINT_CONSTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPINTINTP_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTINTP_OCOPY)
#define ERR_CONST_ERRMAPINTINTP_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_INT_INT_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_T_P_OCOPY)
#define ERR_ERR_MAP_INT_INT_T_P_OCOPY(A1,A2) err_map_int_int_copy_err((A1),(A2))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_T_CONST_P_OCOPY)
#define ERR_ERR_MAP_INT_INT_T_CONST_P_OCOPY(A1,A2) err_map_int_int_copy_err((A1),(A2))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_INT_T_P_OCOPY)
#define ERR_CONST_ERR_MAP_INT_INT_T_P_OCOPY(A1,A2) err_map_int_int_copy_err((A1),(A2))
#endif

#if ERR_ERRMAPINTINT_P_DEEP_COPY && !defined(ERR_ERRMAPINTINT_P_OCOPY)
#define ERR_ERRMAPINTINT_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERRMAPINTINT_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPINTINT_CONST_P_OCOPY)
#define ERR_ERRMAPINTINT_CONST_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_CONST_ERRMAPINTINT_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTINT_P_OCOPY)
#define ERR_CONST_ERRMAPINTINT_P_OCOPY(A1,A2) ((A1)->copy_err((A2)))
#endif

#if ERR_ERR_MAP_INT_INT_TP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_TP_IFREE)
#define ERR_ERR_MAP_INT_INT_TP_IFREE(A1) err_map_int_int_delete((A1))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_T_CONSTP_IFREE)
#define ERR_ERR_MAP_INT_INT_T_CONSTP_IFREE(A1) err_map_int_int_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_INT_TP_IFREE)
#define ERR_CONST_ERR_MAP_INT_INT_TP_IFREE(A1) err_map_int_int_delete((A1))
#endif

#if ERR_ERRMAPINTINTP_DEEP_COPY && !defined(ERR_ERRMAPINTINTP_IFREE)
#define ERR_ERRMAPINTINTP_IFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPINTINT_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPINTINT_CONSTP_IFREE)
#define ERR_ERRMAPINTINT_CONSTP_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPINTINTP_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTINTP_IFREE)
#define ERR_CONST_ERRMAPINTINTP_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_INT_INT_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_T_P_IFREE)
#define ERR_ERR_MAP_INT_INT_T_P_IFREE(A1) err_map_int_int_delete((A1))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_T_CONST_P_IFREE)
#define ERR_ERR_MAP_INT_INT_T_CONST_P_IFREE(A1) err_map_int_int_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_INT_T_P_IFREE)
#define ERR_CONST_ERR_MAP_INT_INT_T_P_IFREE(A1) err_map_int_int_delete((A1))
#endif

#if ERR_ERRMAPINTINT_P_DEEP_COPY && !defined(ERR_ERRMAPINTINT_P_IFREE)
#define ERR_ERRMAPINTINT_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPINTINT_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPINTINT_CONST_P_IFREE)
#define ERR_ERRMAPINTINT_CONST_P_IFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPINTINT_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTINT_P_IFREE)
#define ERR_CONST_ERRMAPINTINT_P_IFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_INT_INT_TP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_TP_OFREE)
#define ERR_ERR_MAP_INT_INT_TP_OFREE(A1) err_map_int_int_delete((A1))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONSTP_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_T_CONSTP_OFREE)
#define ERR_ERR_MAP_INT_INT_T_CONSTP_OFREE(A1) err_map_int_int_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_TP_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_INT_TP_OFREE)
#define ERR_CONST_ERR_MAP_INT_INT_TP_OFREE(A1) err_map_int_int_delete((A1))
#endif

#if ERR_ERRMAPINTINTP_DEEP_COPY && !defined(ERR_ERRMAPINTINTP_OFREE)
#define ERR_ERRMAPINTINTP_OFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPINTINT_CONSTP_DEEP_COPY && !defined(ERR_ERRMAPINTINT_CONSTP_OFREE)
#define ERR_ERRMAPINTINT_CONSTP_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPINTINTP_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTINTP_OFREE)
#define ERR_CONST_ERRMAPINTINTP_OFREE(A1) delete((A1))
#endif

#if ERR_ERR_MAP_INT_INT_T_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_T_P_OFREE)
#define ERR_ERR_MAP_INT_INT_T_P_OFREE(A1) err_map_int_int_delete((A1))
#endif

#if ERR_ERR_MAP_INT_INT_T_CONST_P_DEEP_COPY && !defined(ERR_ERR_MAP_INT_INT_T_CONST_P_OFREE)
#define ERR_ERR_MAP_INT_INT_T_CONST_P_OFREE(A1) err_map_int_int_delete((A1))
#endif

#if ERR_CONST_ERR_MAP_INT_INT_T_P_DEEP_COPY && !defined(ERR_CONST_ERR_MAP_INT_INT_T_P_OFREE)
#define ERR_CONST_ERR_MAP_INT_INT_T_P_OFREE(A1) err_map_int_int_delete((A1))
#endif

#if ERR_ERRMAPINTINT_P_DEEP_COPY && !defined(ERR_ERRMAPINTINT_P_OFREE)
#define ERR_ERRMAPINTINT_P_OFREE(A1) delete((A1))
#endif

#if ERR_ERRMAPINTINT_CONST_P_DEEP_COPY && !defined(ERR_ERRMAPINTINT_CONST_P_OFREE)
#define ERR_ERRMAPINTINT_CONST_P_OFREE(A1) delete((A1))
#endif

#if ERR_CONST_ERRMAPINTINT_P_DEEP_COPY && !defined(ERR_CONST_ERRMAPINTINT_P_OFREE)
#define ERR_CONST_ERRMAPINTINT_P_OFREE(A1) delete((A1))
#endif

#ifndef ERR_ERRMAPINTINT_CONSTRUCTOR
#define ERR_ERRMAPINTINT_CONSTRUCTOR(A1) ((A1)._constructor())
#endif

#ifndef ERR_ERRMAPINTINT_DESTRUCTOR
#define ERR_ERRMAPINTINT_DESTRUCTOR(A1) ((A1)._destructor())
#endif


#endif /* defined ERWIN_ERR_MAP_INT_INT_f_h */

