
#if defined(ERR_ERR_V_MESSAGE_TP_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_ERR_V_MESSAGE_TP_BEING_USED */

#if defined(ERR_ERR_V_MESSAGE_T_CONSTP_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_ERR_V_MESSAGE_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_V_MESSAGE_TP_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_V_MESSAGE_TP_BEING_USED */

#if defined(ERR_ERRVMESSAGEP_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_ERRVMESSAGEP_BEING_USED */

#if defined(ERR_ERRVMESSAGE_CONSTP_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_ERRVMESSAGE_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRVMESSAGEP_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRVMESSAGEP_BEING_USED */

#if defined(ERR_ERR_V_MESSAGE_T_P_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_ERR_V_MESSAGE_T_P_BEING_USED */

#if defined(ERR_ERR_V_MESSAGE_T_CONST_P_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_ERR_V_MESSAGE_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_V_MESSAGE_T_P_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_V_MESSAGE_T_P_BEING_USED */

#if defined(ERR_ERRVMESSAGE_P_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_ERRVMESSAGE_P_BEING_USED */

#if defined(ERR_ERRVMESSAGE_CONST_P_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_ERRVMESSAGE_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRVMESSAGE_P_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRVMESSAGE_P_BEING_USED */

#if defined(ERR_ERRVMESSAGE_BEING_USED) && !defined(ERR_V_MESSAGE_NEED_HEADER)
#define ERR_V_MESSAGE_NEED_HEADER 1
#endif /* defined ERR_ERRVMESSAGE_BEING_USED */



#ifdef ERR_V_MESSAGE_NEED_HEADER
#include "error/err_v_message.h"
#endif

