
#if defined(ERR_ERR_MAP_SYMBOL_STREAM_TP_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_SYMBOL_STREAM_TP_BEING_USED */

#if defined(ERR_ERR_MAP_SYMBOL_STREAM_T_CONSTP_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_SYMBOL_STREAM_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_SYMBOL_STREAM_TP_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_SYMBOL_STREAM_TP_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLSTREAMP_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLSTREAMP_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLSTREAM_CONSTP_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLSTREAM_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRMAPSYMBOLSTREAMP_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPSYMBOLSTREAMP_BEING_USED */

#if defined(ERR_ERR_MAP_SYMBOL_STREAM_T_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_SYMBOL_STREAM_T_P_BEING_USED */

#if defined(ERR_ERR_MAP_SYMBOL_STREAM_T_CONST_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_SYMBOL_STREAM_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_SYMBOL_STREAM_T_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_SYMBOL_STREAM_T_P_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLSTREAM_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLSTREAM_P_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLSTREAM_CONST_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLSTREAM_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRMAPSYMBOLSTREAM_P_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPSYMBOLSTREAM_P_BEING_USED */

#if defined(ERR_ERRMAPSYMBOLSTREAM_BEING_USED) && !defined(ERR_MAP_SYMBOL_STREAM_NEED_HEADER)
#define ERR_MAP_SYMBOL_STREAM_NEED_HEADER 1
#endif /* defined ERR_ERRMAPSYMBOLSTREAM_BEING_USED */



#ifdef ERR_MAP_SYMBOL_STREAM_NEED_HEADER
#include "error/err_map_symbol_stream.h"
#endif

