
#if defined(ERR_ERR_V_CHAR_CONST_P_TP_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_ERR_V_CHAR_CONST_P_TP_BEING_USED */

#if defined(ERR_ERR_V_CHAR_CONST_P_T_CONSTP_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_ERR_V_CHAR_CONST_P_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_V_CHAR_CONST_P_TP_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_V_CHAR_CONST_P_TP_BEING_USED */

#if defined(ERR_ERRVCHARCONSTPP_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_ERRVCHARCONSTPP_BEING_USED */

#if defined(ERR_ERRVCHARCONSTP_CONSTP_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_ERRVCHARCONSTP_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRVCHARCONSTPP_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRVCHARCONSTPP_BEING_USED */

#if defined(ERR_ERR_V_CHAR_CONST_P_T_P_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_ERR_V_CHAR_CONST_P_T_P_BEING_USED */

#if defined(ERR_ERR_V_CHAR_CONST_P_T_CONST_P_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_ERR_V_CHAR_CONST_P_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_V_CHAR_CONST_P_T_P_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_V_CHAR_CONST_P_T_P_BEING_USED */

#if defined(ERR_ERRVCHARCONSTP_P_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_ERRVCHARCONSTP_P_BEING_USED */

#if defined(ERR_ERRVCHARCONSTP_CONST_P_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_ERRVCHARCONSTP_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRVCHARCONSTP_P_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRVCHARCONSTP_P_BEING_USED */

#if defined(ERR_ERRVCHARCONSTP_BEING_USED) && !defined(ERR_V_CHAR_CONST_P_NEED_HEADER)
#define ERR_V_CHAR_CONST_P_NEED_HEADER 1
#endif /* defined ERR_ERRVCHARCONSTP_BEING_USED */



#ifdef ERR_V_CHAR_CONST_P_NEED_HEADER
#include "error/err_v_char_const_p.h"
#endif

