
#if defined(ERR_ERR_MAP_INT_BOOL_TP_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_BOOL_TP_BEING_USED */

#if defined(ERR_ERR_MAP_INT_BOOL_T_CONSTP_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_BOOL_T_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_INT_BOOL_TP_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_INT_BOOL_TP_BEING_USED */

#if defined(ERR_ERRMAPINTBOOLP_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTBOOLP_BEING_USED */

#if defined(ERR_ERRMAPINTBOOL_CONSTP_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTBOOL_CONSTP_BEING_USED */

#if defined(ERR_CONST_ERRMAPINTBOOLP_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPINTBOOLP_BEING_USED */

#if defined(ERR_ERR_MAP_INT_BOOL_T_P_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_BOOL_T_P_BEING_USED */

#if defined(ERR_ERR_MAP_INT_BOOL_T_CONST_P_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_ERR_MAP_INT_BOOL_T_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERR_MAP_INT_BOOL_T_P_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_CONST_ERR_MAP_INT_BOOL_T_P_BEING_USED */

#if defined(ERR_ERRMAPINTBOOL_P_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTBOOL_P_BEING_USED */

#if defined(ERR_ERRMAPINTBOOL_CONST_P_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTBOOL_CONST_P_BEING_USED */

#if defined(ERR_CONST_ERRMAPINTBOOL_P_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_CONST_ERRMAPINTBOOL_P_BEING_USED */

#if defined(ERR_ERRMAPINTBOOL_BEING_USED) && !defined(ERR_MAP_INT_BOOL_NEED_HEADER)
#define ERR_MAP_INT_BOOL_NEED_HEADER 1
#endif /* defined ERR_ERRMAPINTBOOL_BEING_USED */



#ifdef ERR_MAP_INT_BOOL_NEED_HEADER
#include "error/err_map_int_bool.h"
#endif

