/* -*- Mode: C -*- */
/* Generated Wed Sep 17 00:48:03 GMT 2008
 */

#ifdef ERWIN_DEBUG_INCLUDE
#warning "Including err_v_stream_d.h"
#endif

#ifndef ERWIN_ERR_V_STREAM_D_h
#define ERWIN_ERR_V_STREAM_D_h

#ifdef ERWIN_DEBUG_INCLUDE
#warning "First inclusion of err_v_stream_d.h"
#endif

#include "error/err_vector_u.h"
#include "error/err_v_stream_u.h"



/* Preface */
#  define ERR_V_STREAM_INDEX_IS_VOID 0
#  define ERR_V_STREAM_INDEX_IS_INT 0
#  define ERR_V_STREAM_INDEX_IS_CHAR 0

/* CONSTANT_ZERO */
#if ERR_V_STREAM_INDEX_IS_VOID
#  undef ERR_V_STREAM_CONSTANT_ZERO
#  define ERR_V_STREAM_CONSTANT_ZERO 1
#  undef ERR_V_STREAM_DYN_ZERO
#elif defined(ERR_V_STREAM_CONSTANT_ZERO)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_CONSTANT_ZERO)
#    undef ERR_V_STREAM_CONSTANT_ZERO
#    define ERR_V_STREAM_CONSTANT_ZERO 1
#  else
#    undef ERR_V_STREAM_CONSTANT_ZERO
#    define ERR_V_STREAM_CONSTANT_ZERO 0
#  endif
#elif defined(ERR_V_STREAM_DYN_ZERO)
#  if !ERWIN_BOOL_VALUE(ERR_V_STREAM_DYN_ZERO)
#    define ERR_V_STREAM_CONSTANT_ZERO 1
#  else
#    define ERR_V_STREAM_CONSTANT_ZERO 0
#  endif
#elif defined(ERR_ERR_FORMATTED_STREAM_T_P_HAS_CONSTANT_ZERO)
#  if ERWIN_BOOL_VALUE(ERR_ERR_FORMATTED_STREAM_T_P_HAS_CONSTANT_ZERO)
#    define ERR_V_STREAM_CONSTANT_ZERO 1
#  else
#    define ERR_V_STREAM_CONSTANT_ZERO 0
#  endif
#elif defined(ERR_VECTOR_CONSTANT_ZERO)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_CONSTANT_ZERO)
#    define ERR_V_STREAM_CONSTANT_ZERO 1
#  else
#    define ERR_V_STREAM_CONSTANT_ZERO 0
#  endif
#elif defined(ERR_VECTOR_DYN_ZERO)
#  if !ERWIN_BOOL_VALUE(ERR_VECTOR_DYN_ZERO)
#    define ERR_V_STREAM_CONSTANT_ZERO 1
#  else
#    define ERR_V_STREAM_CONSTANT_ZERO 0
#  endif
#elif defined(ERR_ERWIN_CONSTANT_ZERO)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_CONSTANT_ZERO)
#    define ERR_V_STREAM_CONSTANT_ZERO 1
#  else
#    define ERR_V_STREAM_CONSTANT_ZERO 0
#  endif
#elif defined(ERR_ERWIN_DYN_ZERO)
#  if !ERWIN_BOOL_VALUE(ERR_ERWIN_DYN_ZERO)
#    define ERR_V_STREAM_CONSTANT_ZERO 1
#  else
#    define ERR_V_STREAM_CONSTANT_ZERO 0
#  endif
#elif defined(ALL_ERWIN_CONSTANT_ZERO)
#  if ERWIN_BOOL_VALUE(ALL_ERWIN_CONSTANT_ZERO)
#    define ERR_V_STREAM_CONSTANT_ZERO 1
#  else
#    define ERR_V_STREAM_CONSTANT_ZERO 0
#  endif
#elif !defined(ALL_ERWIN_DYN_ZERO)
#  define ERR_V_STREAM_CONSTANT_ZERO 0
#elif !ERWIN_BOOL_VALUE(ALL_ERWIN_DYN_ZERO)
#  define ERR_V_STREAM_CONSTANT_ZERO 1
#else
#  define ERR_V_STREAM_CONSTANT_ZERO 0
#endif
#if !defined(ERR_V_STREAM_DYN_ZERO)
#elif ERR_V_STREAM_CONSTANT_ZERO == ERWIN_BOOL_VALUE(ERR_V_STREAM_DYN_ZERO)
#  error "Inconsistency: ERR_V_STREAM_CONSTANT_ZERO == ERR_V_STREAM_DYN_ZERO"
#endif
#if ERWIN_BOOL_VALUE(ERR_V_STREAM_CONSTANT_ZERO)
#  define ERR_V_STREAM_DYN_ZERO 0
#else
#  define ERR_V_STREAM_DYN_ZERO 1
#endif

/* USE_DEFAULT_ARGS */
#if !defined(__cplusplus)
#  undef ERR_V_STREAM_USE_DEFAULT_ARGS
#  define ERR_V_STREAM_USE_DEFAULT_ARGS 0
#  undef ERR_V_STREAM_NO_DEFAULT_ARGS
#elif defined(ERR_V_STREAM_USE_DEFAULT_ARGS)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_USE_DEFAULT_ARGS)
#    undef ERR_V_STREAM_USE_DEFAULT_ARGS
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 1
#  else
#    undef ERR_V_STREAM_USE_DEFAULT_ARGS
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 0
#  endif
#elif defined(ERR_V_STREAM_NO_DEFAULT_ARGS)
#  if !ERWIN_BOOL_VALUE(ERR_V_STREAM_NO_DEFAULT_ARGS)
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 1
#  else
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 0
#  endif
#elif defined(ERR_VECTOR_USE_DEFAULT_ARGS)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_USE_DEFAULT_ARGS)
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 1
#  else
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 0
#  endif
#elif defined(ERR_VECTOR_NO_DEFAULT_ARGS)
#  if !ERWIN_BOOL_VALUE(ERR_VECTOR_NO_DEFAULT_ARGS)
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 1
#  else
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 0
#  endif
#elif defined(ERR_ERWIN_USE_DEFAULT_ARGS)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_USE_DEFAULT_ARGS)
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 1
#  else
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 0
#  endif
#elif defined(ERR_ERWIN_NO_DEFAULT_ARGS)
#  if !ERWIN_BOOL_VALUE(ERR_ERWIN_NO_DEFAULT_ARGS)
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 1
#  else
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 0
#  endif
#elif defined(ALL_ERWIN_USE_DEFAULT_ARGS)
#  if ERWIN_BOOL_VALUE(ALL_ERWIN_USE_DEFAULT_ARGS)
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 1
#  else
#    define ERR_V_STREAM_USE_DEFAULT_ARGS 0
#  endif
#elif !defined(ALL_ERWIN_NO_DEFAULT_ARGS)
#  define ERR_V_STREAM_USE_DEFAULT_ARGS 1
#elif !ERWIN_BOOL_VALUE(ALL_ERWIN_NO_DEFAULT_ARGS)
#  define ERR_V_STREAM_USE_DEFAULT_ARGS 1
#else
#  define ERR_V_STREAM_USE_DEFAULT_ARGS 0
#endif
#if !defined(ERR_V_STREAM_NO_DEFAULT_ARGS)
#elif ERR_V_STREAM_USE_DEFAULT_ARGS == ERWIN_BOOL_VALUE(ERR_V_STREAM_NO_DEFAULT_ARGS)
#  error "Inconsistency: ERR_V_STREAM_USE_DEFAULT_ARGS == ERR_V_STREAM_NO_DEFAULT_ARGS"
#endif
#if ERWIN_BOOL_VALUE(ERR_V_STREAM_USE_DEFAULT_ARGS)
#  define ERR_V_STREAM_NO_DEFAULT_ARGS 0
#else
#  define ERR_V_STREAM_NO_DEFAULT_ARGS 1
#endif
#if defined(ERR_V_STREAM_USE_DEFAULT_ARGS) && ERR_V_STREAM_USE_DEFAULT_ARGS
#  define ERR_V_STREAM_DEFAULT_ARG(X) = X
#else
#  define ERR_V_STREAM_DEFAULT_ARG(X)
#endif

/* SUPER_CLASS */
#if !defined(__cplusplus)
#elif defined(ERR_V_STREAM_SUPER_CLASS)
#elif defined(ERR_VECTOR_SUPER_CLASS)
#  define ERR_V_STREAM_SUPER_CLASS ERR_VECTOR_SUPER_CLASS
#elif defined(ERR_ERWIN_SUPER_CLASS)
#  define ERR_V_STREAM_SUPER_CLASS ERR_ERWIN_SUPER_CLASS
#elif defined(ALL_ERWIN_SUPER_CLASS)
#  define ERR_V_STREAM_SUPER_CLASS ALL_ERWIN_SUPER_CLASS
#endif

/* SUPER_CLASS_ACCESS */
#if !defined(__cplusplus)
#elif defined(ERR_V_STREAM_SUPER_CLASS_ACCESS)
#elif defined(ERR_VECTOR_SUPER_CLASS_ACCESS)
#  define ERR_V_STREAM_SUPER_CLASS_ACCESS ERR_VECTOR_SUPER_CLASS_ACCESS
#elif defined(ERR_ERWIN_SUPER_CLASS_ACCESS)
#  define ERR_V_STREAM_SUPER_CLASS_ACCESS ERR_ERWIN_SUPER_CLASS_ACCESS
#elif defined(ALL_ERWIN_SUPER_CLASS_ACCESS)
#  define ERR_V_STREAM_SUPER_CLASS_ACCESS ALL_ERWIN_SUPER_CLASS_ACCESS
#else
#  define ERR_V_STREAM_SUPER_CLASS_ACCESS private
#endif

/* STD_MEMBERS */
#if defined(ERR_V_STREAM_TYPE_INFO_STD_MEMBERS)
#elif defined(err_v_stream_t_TYPE_INFO_STD_MEMBERS)
#  define ERR_V_STREAM_TYPE_INFO_STD_MEMBERS err_v_stream_t_TYPE_INFO_STD_MEMBERS
#endif
#if defined(ERR_V_STREAM_STD_MEMBERS)
#elif defined(ERR_VECTOR_STD_MEMBERS)
#  define ERR_V_STREAM_STD_MEMBERS(CLASS_NAME) ERR_VECTOR_STD_MEMBERS(CLASS_NAME)
#  define ERR_V_STREAM_TYPE_INFO_STD_MEMBERS ERR_VECTOR_TYPE_INFO_STD_MEMBERS
#elif defined(ERR_ERWIN_STD_MEMBERS)
#  define ERR_V_STREAM_STD_MEMBERS(CLASS_NAME) ERR_ERWIN_STD_MEMBERS(CLASS_NAME)
#  define ERR_V_STREAM_TYPE_INFO_STD_MEMBERS ERR_ERWIN_TYPE_INFO_STD_MEMBERS
#elif defined(ALL_ERWIN_STD_MEMBERS)
#  define ERR_V_STREAM_STD_MEMBERS(CLASS_NAME) ALL_ERWIN_STD_MEMBERS(CLASS_NAME)
#  define ERR_V_STREAM_TYPE_INFO_STD_MEMBERS ALL_ERWIN_TYPE_INFO_STD_MEMBERS
#else
#  define ERR_V_STREAM_STD_MEMBERS(CLASS_NAME)
#  define ERR_V_STREAM_TYPE_INFO_STD_MEMBERS
#endif

/* HAVE_SIG */
#if defined(ERR_V_STREAM_HAVE_SIG)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_HAVE_SIG)
#    undef ERR_V_STREAM_HAVE_SIG
#    define ERR_V_STREAM_HAVE_SIG 1
#  else
#    undef ERR_V_STREAM_HAVE_SIG
#    define ERR_V_STREAM_HAVE_SIG 0
#  endif
#elif defined(ERR_V_STREAM_NO_SIG)
#  if !ERWIN_BOOL_VALUE(ERR_V_STREAM_NO_SIG)
#    define ERR_V_STREAM_HAVE_SIG 1
#  else
#    define ERR_V_STREAM_HAVE_SIG 0
#  endif
#elif defined(ERR_V_STREAM_FORCE_SIG)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_FORCE_SIG)
#    define ERR_V_STREAM_HAVE_SIG 1
#  else
#    define ERR_V_STREAM_HAVE_SIG 0
#  endif
#elif defined(ERR_VECTOR_HAVE_SIG)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_HAVE_SIG)
#    define ERR_V_STREAM_HAVE_SIG 1
#  else
#    define ERR_V_STREAM_HAVE_SIG 0
#  endif
#elif defined(ERR_VECTOR_NO_SIG)
#  if !ERWIN_BOOL_VALUE(ERR_VECTOR_NO_SIG)
#    define ERR_V_STREAM_HAVE_SIG 1
#  else
#    define ERR_V_STREAM_HAVE_SIG 0
#  endif
#elif defined(ERR_VECTOR_FORCE_SIG)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_FORCE_SIG)
#    define ERR_V_STREAM_HAVE_SIG 1
#  else
#    define ERR_V_STREAM_HAVE_SIG 0
#  endif
#elif defined(ERR_ERWIN_HAVE_SIG)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_HAVE_SIG)
#    define ERR_V_STREAM_HAVE_SIG 1
#  else
#    define ERR_V_STREAM_HAVE_SIG 0
#  endif
#elif defined(ERR_ERWIN_NO_SIG)
#  if !ERWIN_BOOL_VALUE(ERR_ERWIN_NO_SIG)
#    define ERR_V_STREAM_HAVE_SIG 1
#  else
#    define ERR_V_STREAM_HAVE_SIG 0
#  endif
#elif defined(ERR_ERWIN_FORCE_SIG)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_FORCE_SIG)
#    define ERR_V_STREAM_HAVE_SIG 1
#  else
#    define ERR_V_STREAM_HAVE_SIG 0
#  endif
#elif defined(ALL_ERWIN_HAVE_SIG)
#  if ERWIN_BOOL_VALUE(ALL_ERWIN_HAVE_SIG)
#    define ERR_V_STREAM_HAVE_SIG 1
#  else
#    define ERR_V_STREAM_HAVE_SIG 0
#  endif
#elif defined(ALL_ERWIN_NO_SIG)
#  if !ERWIN_BOOL_VALUE(ALL_ERWIN_NO_SIG)
#    define ERR_V_STREAM_HAVE_SIG 1
#  else
#    define ERR_V_STREAM_HAVE_SIG 0
#  endif
#elif defined(ALL_ERWIN_FORCE_SIG)
#  if ERWIN_BOOL_VALUE(ALL_ERWIN_FORCE_SIG)
#    define ERR_V_STREAM_HAVE_SIG 1
#  else
#    define ERR_V_STREAM_HAVE_SIG 0
#  endif
#elif defined(DEVEL)
#  define ERR_V_STREAM_HAVE_SIG 1
#else
#  define ERR_V_STREAM_HAVE_SIG 0
#endif
#if !defined(ERR_V_STREAM_NO_SIG)
#elif ERR_V_STREAM_HAVE_SIG == ERWIN_BOOL_VALUE(ERR_V_STREAM_NO_SIG)
#  error "Inconsistency: ERR_V_STREAM_HAVE_SIG == ERR_V_STREAM_NO_SIG"
#endif
#if !defined(ERR_V_STREAM_FORCE_SIG)
#elif ERR_V_STREAM_HAVE_SIG != ERWIN_BOOL_VALUE(ERR_V_STREAM_FORCE_SIG)
#  error "Inconsistency: ERR_V_STREAM_HAVE_SIG != ERR_V_STREAM_FORCE_SIG"
#endif
#if ERWIN_BOOL_VALUE(ERR_V_STREAM_HAVE_SIG)
#  define ERR_V_STREAM_NO_SIG 0
#else
#  define ERR_V_STREAM_NO_SIG 1
#endif

/* ALLOW_OUTOFRANGE */
#if defined(ERR_V_STREAM_ALLOW_OUTOFRANGE)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_ALLOW_OUTOFRANGE)
#    undef ERR_V_STREAM_ALLOW_OUTOFRANGE
#    define ERR_V_STREAM_ALLOW_OUTOFRANGE 1
#  else
#    undef ERR_V_STREAM_ALLOW_OUTOFRANGE
#    define ERR_V_STREAM_ALLOW_OUTOFRANGE 0
#  endif
#elif defined(ERR_VECTOR_ALLOW_OUTOFRANGE)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_ALLOW_OUTOFRANGE)
#    define ERR_V_STREAM_ALLOW_OUTOFRANGE 1
#  else
#    define ERR_V_STREAM_ALLOW_OUTOFRANGE 0
#  endif
#elif defined(ERR_ERWIN_ALLOW_OUTOFRANGE)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_ALLOW_OUTOFRANGE)
#    define ERR_V_STREAM_ALLOW_OUTOFRANGE 1
#  else
#    define ERR_V_STREAM_ALLOW_OUTOFRANGE 0
#  endif
#elif !defined(ALL_ERWIN_ALLOW_OUTOFRANGE)
#  define ERR_V_STREAM_ALLOW_OUTOFRANGE 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_ALLOW_OUTOFRANGE)
#  define ERR_V_STREAM_ALLOW_OUTOFRANGE 1
#else
#  define ERR_V_STREAM_ALLOW_OUTOFRANGE 0
#endif

/* INLINE_STORE */
#if defined(ERR_V_STREAM_INLINE_STORE)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_INLINE_STORE)
#    undef ERR_V_STREAM_INLINE_STORE
#    define ERR_V_STREAM_INLINE_STORE 1
#  else
#    undef ERR_V_STREAM_INLINE_STORE
#    define ERR_V_STREAM_INLINE_STORE 0
#  endif
#elif defined(ERR_VECTOR_INLINE_STORE)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_INLINE_STORE)
#    define ERR_V_STREAM_INLINE_STORE 1
#  else
#    define ERR_V_STREAM_INLINE_STORE 0
#  endif
#elif defined(ERR_ERWIN_INLINE_STORE)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_INLINE_STORE)
#    define ERR_V_STREAM_INLINE_STORE 1
#  else
#    define ERR_V_STREAM_INLINE_STORE 0
#  endif
#elif !defined(ALL_ERWIN_INLINE_STORE)
#  define ERR_V_STREAM_INLINE_STORE 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_INLINE_STORE)
#  define ERR_V_STREAM_INLINE_STORE 1
#else
#  define ERR_V_STREAM_INLINE_STORE 0
#endif

/* RANGE_CHECK */
#if defined(ERR_V_STREAM_RANGE_CHECK)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_RANGE_CHECK)
#    undef ERR_V_STREAM_RANGE_CHECK
#    define ERR_V_STREAM_RANGE_CHECK 1
#  else
#    undef ERR_V_STREAM_RANGE_CHECK
#    define ERR_V_STREAM_RANGE_CHECK 0
#  endif
#elif defined(ERR_V_STREAM_NO_RANGE_CHECK)
#  if !ERWIN_BOOL_VALUE(ERR_V_STREAM_NO_RANGE_CHECK)
#    define ERR_V_STREAM_RANGE_CHECK 1
#  else
#    define ERR_V_STREAM_RANGE_CHECK 0
#  endif
#elif defined(ERR_VECTOR_RANGE_CHECK)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_RANGE_CHECK)
#    define ERR_V_STREAM_RANGE_CHECK 1
#  else
#    define ERR_V_STREAM_RANGE_CHECK 0
#  endif
#elif defined(ERR_VECTOR_NO_RANGE_CHECK)
#  if !ERWIN_BOOL_VALUE(ERR_VECTOR_NO_RANGE_CHECK)
#    define ERR_V_STREAM_RANGE_CHECK 1
#  else
#    define ERR_V_STREAM_RANGE_CHECK 0
#  endif
#elif defined(ERR_ERWIN_RANGE_CHECK)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_RANGE_CHECK)
#    define ERR_V_STREAM_RANGE_CHECK 1
#  else
#    define ERR_V_STREAM_RANGE_CHECK 0
#  endif
#elif defined(ERR_ERWIN_NO_RANGE_CHECK)
#  if !ERWIN_BOOL_VALUE(ERR_ERWIN_NO_RANGE_CHECK)
#    define ERR_V_STREAM_RANGE_CHECK 1
#  else
#    define ERR_V_STREAM_RANGE_CHECK 0
#  endif
#elif defined(ALL_ERWIN_RANGE_CHECK)
#  if ERWIN_BOOL_VALUE(ALL_ERWIN_RANGE_CHECK)
#    define ERR_V_STREAM_RANGE_CHECK 1
#  else
#    define ERR_V_STREAM_RANGE_CHECK 0
#  endif
#elif !defined(ALL_ERWIN_NO_RANGE_CHECK)
#  define ERR_V_STREAM_RANGE_CHECK 1
#elif !ERWIN_BOOL_VALUE(ALL_ERWIN_NO_RANGE_CHECK)
#  define ERR_V_STREAM_RANGE_CHECK 1
#else
#  define ERR_V_STREAM_RANGE_CHECK 0
#endif
#if !defined(ERR_V_STREAM_NO_RANGE_CHECK)
#elif ERR_V_STREAM_RANGE_CHECK == ERWIN_BOOL_VALUE(ERR_V_STREAM_NO_RANGE_CHECK)
#  error "Inconsistency: ERR_V_STREAM_RANGE_CHECK == ERR_V_STREAM_NO_RANGE_CHECK"
#endif
#if ERWIN_BOOL_VALUE(ERR_V_STREAM_RANGE_CHECK)
#  define ERR_V_STREAM_NO_RANGE_CHECK 0
#else
#  define ERR_V_STREAM_NO_RANGE_CHECK 1
#endif

/* MANY_CASTS */
#if !defined(__cplusplus)
#  undef ERR_V_STREAM_MANY_CASTS
#  define ERR_V_STREAM_MANY_CASTS 0
#elif defined(ERR_V_STREAM_MANY_CASTS)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_MANY_CASTS)
#    undef ERR_V_STREAM_MANY_CASTS
#    define ERR_V_STREAM_MANY_CASTS 1
#  else
#    undef ERR_V_STREAM_MANY_CASTS
#    define ERR_V_STREAM_MANY_CASTS 0
#  endif
#elif defined(ERR_VECTOR_MANY_CASTS)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_MANY_CASTS)
#    define ERR_V_STREAM_MANY_CASTS 1
#  else
#    define ERR_V_STREAM_MANY_CASTS 0
#  endif
#elif defined(ERR_ERWIN_MANY_CASTS)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_MANY_CASTS)
#    define ERR_V_STREAM_MANY_CASTS 1
#  else
#    define ERR_V_STREAM_MANY_CASTS 0
#  endif
#elif !defined(ALL_ERWIN_MANY_CASTS)
#  define ERR_V_STREAM_MANY_CASTS 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_MANY_CASTS)
#  define ERR_V_STREAM_MANY_CASTS 1
#else
#  define ERR_V_STREAM_MANY_CASTS 0
#endif
#if defined(ERR_V_STREAM_MANY_CASTS) && ERR_V_STREAM_MANY_CASTS
#  define ERR_V_STREAM_DEFAULT_ARG_MANY(X) ERR_V_STREAM_DEFAULT_ARG(X)
#else
#  define ERR_V_STREAM_DEFAULT_ARG_MANY(X)
#endif

/* LOW_MEM */
#if defined(ERR_V_STREAM_LOW_MEM)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_LOW_MEM)
#    undef ERR_V_STREAM_LOW_MEM
#    define ERR_V_STREAM_LOW_MEM 1
#  else
#    undef ERR_V_STREAM_LOW_MEM
#    define ERR_V_STREAM_LOW_MEM 0
#  endif
#elif defined(ERR_VECTOR_LOW_MEM)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_LOW_MEM)
#    define ERR_V_STREAM_LOW_MEM 1
#  else
#    define ERR_V_STREAM_LOW_MEM 0
#  endif
#elif defined(ERR_ERWIN_LOW_MEM)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_LOW_MEM)
#    define ERR_V_STREAM_LOW_MEM 1
#  else
#    define ERR_V_STREAM_LOW_MEM 0
#  endif
#elif !defined(ALL_ERWIN_LOW_MEM)
#  define ERR_V_STREAM_LOW_MEM 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_LOW_MEM)
#  define ERR_V_STREAM_LOW_MEM 1
#else
#  define ERR_V_STREAM_LOW_MEM 0
#endif

/* SMALL_SIZE */
#if defined(ERR_V_STREAM_SMALL_SIZE)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_SMALL_SIZE)
#    undef ERR_V_STREAM_SMALL_SIZE
#    define ERR_V_STREAM_SMALL_SIZE 1
#  else
#    undef ERR_V_STREAM_SMALL_SIZE
#    define ERR_V_STREAM_SMALL_SIZE 0
#  endif
#elif defined(ERR_VECTOR_SMALL_SIZE)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_SMALL_SIZE)
#    define ERR_V_STREAM_SMALL_SIZE 1
#  else
#    define ERR_V_STREAM_SMALL_SIZE 0
#  endif
#elif defined(ERR_ERWIN_SMALL_SIZE)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_SMALL_SIZE)
#    define ERR_V_STREAM_SMALL_SIZE 1
#  else
#    define ERR_V_STREAM_SMALL_SIZE 0
#  endif
#elif !defined(ALL_ERWIN_SMALL_SIZE)
#  define ERR_V_STREAM_SMALL_SIZE 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_SMALL_SIZE)
#  define ERR_V_STREAM_SMALL_SIZE 1
#else
#  define ERR_V_STREAM_SMALL_SIZE 0
#endif

/* MEDIUM_SIZE */
#if defined(ERR_V_STREAM_MEDIUM_SIZE)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_MEDIUM_SIZE)
#    undef ERR_V_STREAM_MEDIUM_SIZE
#    define ERR_V_STREAM_MEDIUM_SIZE 1
#  else
#    undef ERR_V_STREAM_MEDIUM_SIZE
#    define ERR_V_STREAM_MEDIUM_SIZE 0
#  endif
#elif defined(ERR_VECTOR_MEDIUM_SIZE)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_MEDIUM_SIZE)
#    define ERR_V_STREAM_MEDIUM_SIZE 1
#  else
#    define ERR_V_STREAM_MEDIUM_SIZE 0
#  endif
#elif defined(ERR_ERWIN_MEDIUM_SIZE)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_MEDIUM_SIZE)
#    define ERR_V_STREAM_MEDIUM_SIZE 1
#  else
#    define ERR_V_STREAM_MEDIUM_SIZE 0
#  endif
#elif !defined(ALL_ERWIN_MEDIUM_SIZE)
#  define ERR_V_STREAM_MEDIUM_SIZE 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_MEDIUM_SIZE)
#  define ERR_V_STREAM_MEDIUM_SIZE 1
#else
#  define ERR_V_STREAM_MEDIUM_SIZE 0
#endif

/* LARGE_INDEX */
#if defined(ERR_V_STREAM_LARGE_INDEX)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_LARGE_INDEX)
#    undef ERR_V_STREAM_LARGE_INDEX
#    define ERR_V_STREAM_LARGE_INDEX 1
#  else
#    undef ERR_V_STREAM_LARGE_INDEX
#    define ERR_V_STREAM_LARGE_INDEX 0
#  endif
#elif defined(ERR_VECTOR_LARGE_INDEX)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_LARGE_INDEX)
#    define ERR_V_STREAM_LARGE_INDEX 1
#  else
#    define ERR_V_STREAM_LARGE_INDEX 0
#  endif
#elif defined(ERR_ERWIN_LARGE_INDEX)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_LARGE_INDEX)
#    define ERR_V_STREAM_LARGE_INDEX 1
#  else
#    define ERR_V_STREAM_LARGE_INDEX 0
#  endif
#elif !defined(ALL_ERWIN_LARGE_INDEX)
#  define ERR_V_STREAM_LARGE_INDEX 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_LARGE_INDEX)
#  define ERR_V_STREAM_LARGE_INDEX 1
#else
#  define ERR_V_STREAM_LARGE_INDEX 0
#endif

/* PREALLOC_SIZE */
#if defined(ERR_V_STREAM_PREALLOC_SIZE)
#elif defined(ERR_VECTOR_PREALLOC_SIZE)
#  define ERR_V_STREAM_PREALLOC_SIZE ERR_VECTOR_PREALLOC_SIZE
#elif defined(ERR_ERWIN_PREALLOC_SIZE)
#  define ERR_V_STREAM_PREALLOC_SIZE ERR_ERWIN_PREALLOC_SIZE
#elif defined(ALL_ERWIN_PREALLOC_SIZE)
#  define ERR_V_STREAM_PREALLOC_SIZE ALL_ERWIN_PREALLOC_SIZE
#endif

/* CHUNK_SIZE */
#if defined(ERR_V_STREAM_CHUNK_SIZE)
#elif defined(ERR_VECTOR_CHUNK_SIZE)
#  define ERR_V_STREAM_CHUNK_SIZE ERR_VECTOR_CHUNK_SIZE
#elif defined(ERR_ERWIN_CHUNK_SIZE)
#  define ERR_V_STREAM_CHUNK_SIZE ERR_ERWIN_CHUNK_SIZE
#elif defined(ALL_ERWIN_CHUNK_SIZE)
#  define ERR_V_STREAM_CHUNK_SIZE ALL_ERWIN_CHUNK_SIZE
#endif

/* ALLOW_NULL */
#if defined(ERR_V_STREAM_ALLOW_NULL)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_ALLOW_NULL)
#    undef ERR_V_STREAM_ALLOW_NULL
#    define ERR_V_STREAM_ALLOW_NULL 1
#  else
#    undef ERR_V_STREAM_ALLOW_NULL
#    define ERR_V_STREAM_ALLOW_NULL 0
#  endif
#elif defined(ERR_VECTOR_ALLOW_NULL)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_ALLOW_NULL)
#    define ERR_V_STREAM_ALLOW_NULL 1
#  else
#    define ERR_V_STREAM_ALLOW_NULL 0
#  endif
#elif defined(ERR_ERWIN_ALLOW_NULL)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_ALLOW_NULL)
#    define ERR_V_STREAM_ALLOW_NULL 1
#  else
#    define ERR_V_STREAM_ALLOW_NULL 0
#  endif
#elif !defined(ALL_ERWIN_ALLOW_NULL)
#  define ERR_V_STREAM_ALLOW_NULL 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_ALLOW_NULL)
#  define ERR_V_STREAM_ALLOW_NULL 1
#else
#  define ERR_V_STREAM_ALLOW_NULL 0
#endif

/* DIRECT_RECURSION */
#if !defined(__cplusplus)
#elif defined(ERR_V_STREAM_DIRECT_RECURSION)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_DIRECT_RECURSION)
#    undef ERR_V_STREAM_DIRECT_RECURSION
#    define ERR_V_STREAM_DIRECT_RECURSION 1
#  else
#    undef ERR_V_STREAM_DIRECT_RECURSION
#    define ERR_V_STREAM_DIRECT_RECURSION 0
#  endif
#elif defined(ERR_VECTOR_DIRECT_RECURSION)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_DIRECT_RECURSION)
#    define ERR_V_STREAM_DIRECT_RECURSION 1
#  else
#    define ERR_V_STREAM_DIRECT_RECURSION 0
#  endif
#elif defined(ERR_ERWIN_DIRECT_RECURSION)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_DIRECT_RECURSION)
#    define ERR_V_STREAM_DIRECT_RECURSION 1
#  else
#    define ERR_V_STREAM_DIRECT_RECURSION 0
#  endif
#elif !defined(ALL_ERWIN_DIRECT_RECURSION)
#  define ERR_V_STREAM_DIRECT_RECURSION 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_DIRECT_RECURSION)
#  define ERR_V_STREAM_DIRECT_RECURSION 1
#else
#  define ERR_V_STREAM_DIRECT_RECURSION 0
#endif

/* HAVE_INT_CONSTRUCTOR */
#if defined(__cplusplus)
#  if ERR_V_STREAM_DYN_ZERO && ERR_V_STREAM_INDEX_IS_INT
#    undef ERR_V_STREAM_HAVE_INT_CONSTRUCTOR
#    define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 0
#    undef ERR_V_STREAM_NO_INT_CONSTRUCTOR
#  elif defined(ERR_V_STREAM_HAVE_INT_CONSTRUCTOR)
#    if ERWIN_BOOL_VALUE(ERR_V_STREAM_HAVE_INT_CONSTRUCTOR)
#      undef ERR_V_STREAM_HAVE_INT_CONSTRUCTOR
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 1
#    else
#      undef ERR_V_STREAM_HAVE_INT_CONSTRUCTOR
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif defined(ERR_V_STREAM_NO_INT_CONSTRUCTOR)
#    if !ERWIN_BOOL_VALUE(ERR_V_STREAM_NO_INT_CONSTRUCTOR)
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 1
#    else
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif defined(ERR_VECTOR_HAVE_INT_CONSTRUCTOR)
#    if ERWIN_BOOL_VALUE(ERR_VECTOR_HAVE_INT_CONSTRUCTOR)
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 1
#    else
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif defined(ERR_VECTOR_NO_INT_CONSTRUCTOR)
#    if !ERWIN_BOOL_VALUE(ERR_VECTOR_NO_INT_CONSTRUCTOR)
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 1
#    else
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif defined(ERR_ERWIN_HAVE_INT_CONSTRUCTOR)
#    if ERWIN_BOOL_VALUE(ERR_ERWIN_HAVE_INT_CONSTRUCTOR)
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 1
#    else
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif defined(ERR_ERWIN_NO_INT_CONSTRUCTOR)
#    if !ERWIN_BOOL_VALUE(ERR_ERWIN_NO_INT_CONSTRUCTOR)
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 1
#    else
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif defined(ALL_ERWIN_HAVE_INT_CONSTRUCTOR)
#    if ERWIN_BOOL_VALUE(ALL_ERWIN_HAVE_INT_CONSTRUCTOR)
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 1
#    else
#      define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 0
#    endif
#  elif !defined(ALL_ERWIN_NO_INT_CONSTRUCTOR)
#    define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 1
#  elif !ERWIN_BOOL_VALUE(ALL_ERWIN_NO_INT_CONSTRUCTOR)
#    define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 1
#  else
#    define ERR_V_STREAM_HAVE_INT_CONSTRUCTOR 0
#  endif
#  if !defined(ERR_V_STREAM_NO_INT_CONSTRUCTOR)
#  elif ERR_V_STREAM_HAVE_INT_CONSTRUCTOR == ERWIN_BOOL_VALUE(ERR_V_STREAM_NO_INT_CONSTRUCTOR)
#    error "Inconsistency: ERR_V_STREAM_HAVE_INT_CONSTRUCTOR == ERR_V_STREAM_NO_INT_CONSTRUCTOR"
#  endif
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_HAVE_INT_CONSTRUCTOR)
#    define ERR_V_STREAM_NO_INT_CONSTRUCTOR 0
#  else
#    define ERR_V_STREAM_NO_INT_CONSTRUCTOR 1
#  endif
#endif

/* IMPLEMENT_FORMAT */
#if ERR_V_STREAM_INDEX_IS_CHAR
#  if defined(ERR_V_STREAM_IMPLEMENT_FORMAT)
#    if ERWIN_BOOL_VALUE(ERR_V_STREAM_IMPLEMENT_FORMAT)
#      undef ERR_V_STREAM_IMPLEMENT_FORMAT
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 1
#    else
#      undef ERR_V_STREAM_IMPLEMENT_FORMAT
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 0
#    endif
#  elif defined(ERR_V_STREAM_NO_FORMAT)
#    if !ERWIN_BOOL_VALUE(ERR_V_STREAM_NO_FORMAT)
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 1
#    else
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 0
#    endif
#  elif defined(ERR_VECTOR_IMPLEMENT_FORMAT)
#    if ERWIN_BOOL_VALUE(ERR_VECTOR_IMPLEMENT_FORMAT)
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 1
#    else
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 0
#    endif
#  elif defined(ERR_VECTOR_NO_FORMAT)
#    if !ERWIN_BOOL_VALUE(ERR_VECTOR_NO_FORMAT)
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 1
#    else
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 0
#    endif
#  elif defined(ERR_ERWIN_IMPLEMENT_FORMAT)
#    if ERWIN_BOOL_VALUE(ERR_ERWIN_IMPLEMENT_FORMAT)
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 1
#    else
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 0
#    endif
#  elif defined(ERR_ERWIN_NO_FORMAT)
#    if !ERWIN_BOOL_VALUE(ERR_ERWIN_NO_FORMAT)
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 1
#    else
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 0
#    endif
#  elif defined(ALL_ERWIN_IMPLEMENT_FORMAT)
#    if ERWIN_BOOL_VALUE(ALL_ERWIN_IMPLEMENT_FORMAT)
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 1
#    else
#      define ERR_V_STREAM_IMPLEMENT_FORMAT 0
#    endif
#  elif !defined(ALL_ERWIN_NO_FORMAT)
#    define ERR_V_STREAM_IMPLEMENT_FORMAT 1
#  elif !ERWIN_BOOL_VALUE(ALL_ERWIN_NO_FORMAT)
#    define ERR_V_STREAM_IMPLEMENT_FORMAT 1
#  else
#    define ERR_V_STREAM_IMPLEMENT_FORMAT 0
#  endif
#  if !defined(ERR_V_STREAM_NO_FORMAT)
#  elif ERR_V_STREAM_IMPLEMENT_FORMAT == ERWIN_BOOL_VALUE(ERR_V_STREAM_NO_FORMAT)
#    error "Inconsistency: ERR_V_STREAM_IMPLEMENT_FORMAT == ERR_V_STREAM_NO_FORMAT"
#  endif
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_IMPLEMENT_FORMAT)
#    define ERR_V_STREAM_NO_FORMAT 0
#  else
#    define ERR_V_STREAM_NO_FORMAT 1
#  endif
#endif

/* POSITION_POINTER */
#if defined(ERR_V_STREAM_POSITION_POINTER)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_POSITION_POINTER)
#    undef ERR_V_STREAM_POSITION_POINTER
#    define ERR_V_STREAM_POSITION_POINTER 1
#  else
#    undef ERR_V_STREAM_POSITION_POINTER
#    define ERR_V_STREAM_POSITION_POINTER 0
#  endif
#elif defined(ERR_VECTOR_POSITION_POINTER)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_POSITION_POINTER)
#    define ERR_V_STREAM_POSITION_POINTER 1
#  else
#    define ERR_V_STREAM_POSITION_POINTER 0
#  endif
#elif defined(ERR_ERWIN_POSITION_POINTER)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_POSITION_POINTER)
#    define ERR_V_STREAM_POSITION_POINTER 1
#  else
#    define ERR_V_STREAM_POSITION_POINTER 0
#  endif
#elif !defined(ALL_ERWIN_POSITION_POINTER)
#  define ERR_V_STREAM_POSITION_POINTER 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_POSITION_POINTER)
#  define ERR_V_STREAM_POSITION_POINTER 1
#else
#  define ERR_V_STREAM_POSITION_POINTER 0
#endif

/* # */
#ifdef ERR_V_STREAM_IMPLEMENTATION



#ifdef ERR_ERWIN_COMPILING
#  include "error/erwin/defaults.h"
#  include "error/erwin/forwards.h"
#else
#  include <error/erwin/defaults.h>
#  include <error/erwin/forwards.h>
#endif

/* NOMEM_IS_FATAL */
#if defined(ERR_V_STREAM_NOMEM_IS_FATAL)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_NOMEM_IS_FATAL)
#    undef ERR_V_STREAM_NOMEM_IS_FATAL
#    define ERR_V_STREAM_NOMEM_IS_FATAL 1
#  else
#    undef ERR_V_STREAM_NOMEM_IS_FATAL
#    define ERR_V_STREAM_NOMEM_IS_FATAL 0
#  endif
#elif defined(ERR_VECTOR_NOMEM_IS_FATAL)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_NOMEM_IS_FATAL)
#    define ERR_V_STREAM_NOMEM_IS_FATAL 1
#  else
#    define ERR_V_STREAM_NOMEM_IS_FATAL 0
#  endif
#elif defined(ERR_ERWIN_NOMEM_IS_FATAL)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_NOMEM_IS_FATAL)
#    define ERR_V_STREAM_NOMEM_IS_FATAL 1
#  else
#    define ERR_V_STREAM_NOMEM_IS_FATAL 0
#  endif
#elif !defined(ALL_ERWIN_NOMEM_IS_FATAL)
#  define ERR_V_STREAM_NOMEM_IS_FATAL 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_NOMEM_IS_FATAL)
#  define ERR_V_STREAM_NOMEM_IS_FATAL 1
#else
#  define ERR_V_STREAM_NOMEM_IS_FATAL 0
#endif

/* ASSERTION_FAILED_HANDLER */
#if defined(ERR_V_STREAM_ASSERTION_FAILED_HANDLER)
#elif defined(ERR_VECTOR_ASSERTION_FAILED_HANDLER)
#  define ERR_V_STREAM_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK) ERR_VECTOR_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK)
#elif defined(ERR_ERWIN_ASSERTION_FAILED_HANDLER)
#  define ERR_V_STREAM_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK) ERR_ERWIN_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK)
#elif defined(ALL_ERWIN_ASSERTION_FAILED_HANDLER)
#  define ERR_V_STREAM_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK) ALL_ERWIN_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK)
#else
#  define ERR_V_STREAM_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK) ERR_ERWIN_DEFAULT_ASSERTION_FAILED_HANDLER(FILE,LINE,FUNC,CHECK)
#endif

/* OPTIMISE_SIZE */
#if defined(ERR_V_STREAM_OPTIMISE_SIZE)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_OPTIMISE_SIZE)
#    undef ERR_V_STREAM_OPTIMISE_SIZE
#    define ERR_V_STREAM_OPTIMISE_SIZE 1
#  else
#    undef ERR_V_STREAM_OPTIMISE_SIZE
#    define ERR_V_STREAM_OPTIMISE_SIZE 0
#  endif
#elif defined(ERR_VECTOR_OPTIMISE_SIZE)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_OPTIMISE_SIZE)
#    define ERR_V_STREAM_OPTIMISE_SIZE 1
#  else
#    define ERR_V_STREAM_OPTIMISE_SIZE 0
#  endif
#elif defined(ERR_ERWIN_OPTIMISE_SIZE)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_OPTIMISE_SIZE)
#    define ERR_V_STREAM_OPTIMISE_SIZE 1
#  else
#    define ERR_V_STREAM_OPTIMISE_SIZE 0
#  endif
#elif !defined(ALL_ERWIN_OPTIMISE_SIZE)
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_OPTIMISE_SIZE)
#  define ERR_V_STREAM_OPTIMISE_SIZE 1
#else
#  define ERR_V_STREAM_OPTIMISE_SIZE 0
#endif

/* SPLIT */
#if defined(ERR_V_STREAM_SPLIT)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_SPLIT)
#    undef ERR_V_STREAM_SPLIT
#    define ERR_V_STREAM_SPLIT 1
#  else
#    undef ERR_V_STREAM_SPLIT
#    define ERR_V_STREAM_SPLIT 0
#  endif
#elif defined(ERR_VECTOR_SPLIT)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_SPLIT)
#    define ERR_V_STREAM_SPLIT 1
#  else
#    define ERR_V_STREAM_SPLIT 0
#  endif
#elif defined(ERR_ERWIN_SPLIT)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_SPLIT)
#    define ERR_V_STREAM_SPLIT 1
#  else
#    define ERR_V_STREAM_SPLIT 0
#  endif
#elif !defined(ALL_ERWIN_SPLIT)
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_SPLIT)
#  define ERR_V_STREAM_SPLIT 1
#else
#  define ERR_V_STREAM_SPLIT 0
#endif

/* AUTO_SHRINK */
#if defined(ERR_V_STREAM_AUTO_SHRINK)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_AUTO_SHRINK)
#    undef ERR_V_STREAM_AUTO_SHRINK
#    define ERR_V_STREAM_AUTO_SHRINK 1
#  else
#    undef ERR_V_STREAM_AUTO_SHRINK
#    define ERR_V_STREAM_AUTO_SHRINK 0
#  endif
#elif defined(ERR_V_STREAM_NO_AUTO_SHRINK)
#  if !ERWIN_BOOL_VALUE(ERR_V_STREAM_NO_AUTO_SHRINK)
#    define ERR_V_STREAM_AUTO_SHRINK 1
#  else
#    define ERR_V_STREAM_AUTO_SHRINK 0
#  endif
#elif defined(ERR_VECTOR_AUTO_SHRINK)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_AUTO_SHRINK)
#    define ERR_V_STREAM_AUTO_SHRINK 1
#  else
#    define ERR_V_STREAM_AUTO_SHRINK 0
#  endif
#elif defined(ERR_VECTOR_NO_AUTO_SHRINK)
#  if !ERWIN_BOOL_VALUE(ERR_VECTOR_NO_AUTO_SHRINK)
#    define ERR_V_STREAM_AUTO_SHRINK 1
#  else
#    define ERR_V_STREAM_AUTO_SHRINK 0
#  endif
#elif defined(ERR_ERWIN_AUTO_SHRINK)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_AUTO_SHRINK)
#    define ERR_V_STREAM_AUTO_SHRINK 1
#  else
#    define ERR_V_STREAM_AUTO_SHRINK 0
#  endif
#elif defined(ERR_ERWIN_NO_AUTO_SHRINK)
#  if !ERWIN_BOOL_VALUE(ERR_ERWIN_NO_AUTO_SHRINK)
#    define ERR_V_STREAM_AUTO_SHRINK 1
#  else
#    define ERR_V_STREAM_AUTO_SHRINK 0
#  endif
#elif defined(ALL_ERWIN_AUTO_SHRINK)
#  if ERWIN_BOOL_VALUE(ALL_ERWIN_AUTO_SHRINK)
#    define ERR_V_STREAM_AUTO_SHRINK 1
#  else
#    define ERR_V_STREAM_AUTO_SHRINK 0
#  endif
#elif !defined(ALL_ERWIN_NO_AUTO_SHRINK)
#  define ERR_V_STREAM_AUTO_SHRINK 1
#elif !ERWIN_BOOL_VALUE(ALL_ERWIN_NO_AUTO_SHRINK)
#  define ERR_V_STREAM_AUTO_SHRINK 1
#else
#  define ERR_V_STREAM_AUTO_SHRINK 0
#endif
#if !defined(ERR_V_STREAM_NO_AUTO_SHRINK)
#elif ERR_V_STREAM_AUTO_SHRINK == ERWIN_BOOL_VALUE(ERR_V_STREAM_NO_AUTO_SHRINK)
#  error "Inconsistency: ERR_V_STREAM_AUTO_SHRINK == ERR_V_STREAM_NO_AUTO_SHRINK"
#endif
#if ERWIN_BOOL_VALUE(ERR_V_STREAM_AUTO_SHRINK)
#  define ERR_V_STREAM_NO_AUTO_SHRINK 0
#else
#  define ERR_V_STREAM_NO_AUTO_SHRINK 1
#endif

/* C_MM */
#if !defined(__cplusplus)
#  undef ERR_V_STREAM_C_MM
#  define ERR_V_STREAM_C_MM 1
#elif defined(ERR_V_STREAM_C_MM)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_C_MM)
#    undef ERR_V_STREAM_C_MM
#    define ERR_V_STREAM_C_MM 1
#  else
#    undef ERR_V_STREAM_C_MM
#    define ERR_V_STREAM_C_MM 0
#  endif
#elif defined(ERR_VECTOR_C_MM)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_C_MM)
#    define ERR_V_STREAM_C_MM 1
#  else
#    define ERR_V_STREAM_C_MM 0
#  endif
#elif defined(ERR_ERWIN_C_MM)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_C_MM)
#    define ERR_V_STREAM_C_MM 1
#  else
#    define ERR_V_STREAM_C_MM 0
#  endif
#elif !defined(ALL_ERWIN_C_MM)
#  define ERR_V_STREAM_C_MM 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_C_MM)
#  define ERR_V_STREAM_C_MM 1
#else
#  define ERR_V_STREAM_C_MM 0
#endif

/* COMPARE_LEXICOGRAPHICALLY */
#if defined(ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY)
#    undef ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY
#    define ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY 1
#  else
#    undef ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY
#    define ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY 0
#  endif
#elif defined(ERR_VECTOR_COMPARE_LEXICOGRAPHICALLY)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_COMPARE_LEXICOGRAPHICALLY)
#    define ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY 1
#  else
#    define ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY 0
#  endif
#elif defined(ERR_ERWIN_COMPARE_LEXICOGRAPHICALLY)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_COMPARE_LEXICOGRAPHICALLY)
#    define ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY 1
#  else
#    define ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY 0
#  endif
#elif defined(ALL_ERWIN_COMPARE_LEXICOGRAPHICALLY)
#  if ERWIN_BOOL_VALUE(ALL_ERWIN_COMPARE_LEXICOGRAPHICALLY)
#    define ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY 1
#  else
#    define ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY 0
#  endif
#elif ERR_V_STREAM_INDEX_IS_CHAR
#  define ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY 1
#else
#  define ERR_V_STREAM_COMPARE_LEXICOGRAPHICALLY 0
#endif

/* PRIORITY_COMPARE_LEXICOGRAPHICALLY */
#if defined(ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY)
#    undef ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY
#    define ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY 1
#  else
#    undef ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY
#    define ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY 0
#  endif
#elif defined(ERR_VECTOR_PRIORITY_COMPARE_LEXICOGRAPHICALLY)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_PRIORITY_COMPARE_LEXICOGRAPHICALLY)
#    define ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY 1
#  else
#    define ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY 0
#  endif
#elif defined(ERR_ERWIN_PRIORITY_COMPARE_LEXICOGRAPHICALLY)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_PRIORITY_COMPARE_LEXICOGRAPHICALLY)
#    define ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY 1
#  else
#    define ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY 0
#  endif
#elif !defined(ALL_ERWIN_PRIORITY_COMPARE_LEXICOGRAPHICALLY)
#  define ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_PRIORITY_COMPARE_LEXICOGRAPHICALLY)
#  define ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY 1
#else
#  define ERR_V_STREAM_PRIORITY_COMPARE_LEXICOGRAPHICALLY 0
#endif

/* DEBUG_EXPENSIVE_CHECKS */
#if defined(NDEBUG)
#  undef ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS
#  define ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS 0
#elif defined(ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS)
#    undef ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS
#    define ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS 1
#  else
#    undef ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS
#    define ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS 0
#  endif
#elif defined(ERR_VECTOR_DEBUG_EXPENSIVE_CHECKS)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_DEBUG_EXPENSIVE_CHECKS)
#    define ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS 1
#  else
#    define ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS 0
#  endif
#elif defined(ERR_ERWIN_DEBUG_EXPENSIVE_CHECKS)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_DEBUG_EXPENSIVE_CHECKS)
#    define ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS 1
#  else
#    define ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS 0
#  endif
#elif !defined(ALL_ERWIN_DEBUG_EXPENSIVE_CHECKS)
#  define ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_DEBUG_EXPENSIVE_CHECKS)
#  define ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS 1
#else
#  define ERR_V_STREAM_DEBUG_EXPENSIVE_CHECKS 0
#endif

/* INITIAL_SIZE */
#if defined(ERR_V_STREAM_INITIAL_SIZE)
#elif defined(ERR_VECTOR_INITIAL_SIZE)
#  define ERR_V_STREAM_INITIAL_SIZE ERR_VECTOR_INITIAL_SIZE
#elif defined(ERR_ERWIN_INITIAL_SIZE)
#  define ERR_V_STREAM_INITIAL_SIZE ERR_ERWIN_INITIAL_SIZE
#elif defined(ALL_ERWIN_INITIAL_SIZE)
#  define ERR_V_STREAM_INITIAL_SIZE ALL_ERWIN_INITIAL_SIZE
#else
#  define ERR_V_STREAM_INITIAL_SIZE 8
#endif

/* MINIMAL_SIZE */
#if defined(ERR_V_STREAM_MINIMAL_SIZE)
#elif defined(ERR_VECTOR_MINIMAL_SIZE)
#  define ERR_V_STREAM_MINIMAL_SIZE ERR_VECTOR_MINIMAL_SIZE
#elif defined(ERR_ERWIN_MINIMAL_SIZE)
#  define ERR_V_STREAM_MINIMAL_SIZE ERR_ERWIN_MINIMAL_SIZE
#elif defined(ALL_ERWIN_MINIMAL_SIZE)
#  define ERR_V_STREAM_MINIMAL_SIZE ALL_ERWIN_MINIMAL_SIZE
#else
#  define ERR_V_STREAM_MINIMAL_SIZE 8
#endif

/* OUTOFRANGE_IS_FATAL */
#if defined(ERR_V_STREAM_OUTOFRANGE_IS_FATAL)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_OUTOFRANGE_IS_FATAL)
#    undef ERR_V_STREAM_OUTOFRANGE_IS_FATAL
#    define ERR_V_STREAM_OUTOFRANGE_IS_FATAL 1
#  else
#    undef ERR_V_STREAM_OUTOFRANGE_IS_FATAL
#    define ERR_V_STREAM_OUTOFRANGE_IS_FATAL 0
#  endif
#elif defined(ERR_VECTOR_OUTOFRANGE_IS_FATAL)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_OUTOFRANGE_IS_FATAL)
#    define ERR_V_STREAM_OUTOFRANGE_IS_FATAL 1
#  else
#    define ERR_V_STREAM_OUTOFRANGE_IS_FATAL 0
#  endif
#elif defined(ERR_ERWIN_OUTOFRANGE_IS_FATAL)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_OUTOFRANGE_IS_FATAL)
#    define ERR_V_STREAM_OUTOFRANGE_IS_FATAL 1
#  else
#    define ERR_V_STREAM_OUTOFRANGE_IS_FATAL 0
#  endif
#elif !defined(ALL_ERWIN_OUTOFRANGE_IS_FATAL)
#  define ERR_V_STREAM_OUTOFRANGE_IS_FATAL 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_OUTOFRANGE_IS_FATAL)
#  define ERR_V_STREAM_OUTOFRANGE_IS_FATAL 1
#else
#  define ERR_V_STREAM_OUTOFRANGE_IS_FATAL 0
#endif

/* OCOPY */
#if defined(ERR_ERR_FORMATTED_STREAM_T_P_OCOPY_PROVIDED)
#elif defined(ERR_ERR_FORMATTED_STREAM_T_P_OCOPY)
#  define ERR_ERR_FORMATTED_STREAM_T_P_OCOPY_PROVIDED 1
#elif defined(ERR_ERR_FORMATTED_STREAM_T_P_COPY)
#  define ERR_ERR_FORMATTED_STREAM_T_P_OCOPY_PROVIDED 1
#  define ERR_ERR_FORMATTED_STREAM_T_P_OCOPY(TO_BE_COPIED,ERR_P) ERR_ERR_FORMATTED_STREAM_T_P_COPY(TO_BE_COPIED,ERR_P)
#else
#  define ERR_ERR_FORMATTED_STREAM_T_P_OCOPY(TO_BE_COPIED,ERR_P) TO_BE_COPIED
#  define ERR_ERR_FORMATTED_STREAM_T_P_OCOPY_PROVIDED 0
#endif
#if defined(ERR_ERR_FORMATTED_STREAM_T_P_OCOPY)
#elif ERR_ERR_FORMATTED_STREAM_T_P_OCOPY_PROVIDED
#  error "Inconsistency: ERR_ERR_FORMATTED_STREAM_T_P_OCOPY_PROVIDED is true but ERR_ERR_FORMATTED_STREAM_T_P_OCOPY is undefined."
#endif

/* OFREE */
#if defined(ERR_ERR_FORMATTED_STREAM_T_P_OFREE_PROVIDED)
#elif defined(ERR_ERR_FORMATTED_STREAM_T_P_OFREE)
#  define ERR_ERR_FORMATTED_STREAM_T_P_OFREE_PROVIDED 1
#elif defined(ERR_ERR_FORMATTED_STREAM_T_P_FREE)
#  define ERR_ERR_FORMATTED_STREAM_T_P_OFREE_PROVIDED 1
#  define ERR_ERR_FORMATTED_STREAM_T_P_OFREE(TO_BE_DESTROYED) ERR_ERR_FORMATTED_STREAM_T_P_FREE(TO_BE_DESTROYED)
#else
#  define ERR_ERR_FORMATTED_STREAM_T_P_OFREE(TO_BE_DESTROYED)
#  define ERR_ERR_FORMATTED_STREAM_T_P_OFREE_PROVIDED 0
#endif
#if defined(ERR_ERR_FORMATTED_STREAM_T_P_OFREE)
#elif ERR_ERR_FORMATTED_STREAM_T_P_OFREE_PROVIDED
#  error "Inconsistency: ERR_ERR_FORMATTED_STREAM_T_P_OFREE_PROVIDED is true but ERR_ERR_FORMATTED_STREAM_T_P_OFREE is undefined."
#endif

/* ZERO */
#if !defined(ERR_ERR_FORMATTED_STREAM_T_P_ZERO)
#  define ERR_ERR_FORMATTED_STREAM_T_P_ZERO (err_formatted_stream_t * )0
#endif

/* HASH_RAW */
#if defined(ERR_ERR_FORMATTED_STREAM_T_P_HASH_RAW)
#elif defined(ERR_ERR_FORMATTED_STREAM_T_P_HASHVAL)
#  define ERR_ERR_FORMATTED_STREAM_T_P_HASH_RAW(X) ERR_ERR_FORMATTED_STREAM_T_P_HASHVAL(X)
#endif

/* HASH */
#if defined(ERR_ERR_FORMATTED_STREAM_T_P_HASH)
#elif defined(ERR_ERR_FORMATTED_STREAM_T_P_HASH_RAW)
#  define ERR_ERR_FORMATTED_STREAM_T_P_HASH(X) err_hashval_t_hash((ERR_ERR_FORMATTED_STREAM_T_P_HASH_RAW(X)))
#endif

/* CMP */
#if defined(ERR_ERR_FORMATTED_STREAM_T_P_CMP_PROVIDED)
#elif defined(ERR_ERR_FORMATTED_STREAM_T_P_CMP)
#  define ERR_ERR_FORMATTED_STREAM_T_P_CMP_PROVIDED 1
#else
#  define ERR_ERR_FORMATTED_STREAM_T_P_CMP_PROVIDED 0
#endif
#if defined(ERR_ERR_FORMATTED_STREAM_T_P_CMP)
#elif ERR_ERR_FORMATTED_STREAM_T_P_CMP_PROVIDED
#  error "Inconsistency: ERR_ERR_FORMATTED_STREAM_T_P_CMP_PROVIDED is true but ERR_ERR_FORMATTED_STREAM_T_P_CMP is undefined."
#endif

/* PRIORITY_CMP */
#if defined(ERR_ERR_FORMATTED_STREAM_T_P_PRIORITY_CMP_PROVIDED)
#elif defined(ERR_ERR_FORMATTED_STREAM_T_P_PRIORITY_CMP)
#  define ERR_ERR_FORMATTED_STREAM_T_P_PRIORITY_CMP_PROVIDED 1
#else
#  if defined(ERR_ERR_FORMATTED_STREAM_T_P_CMP)
#    define ERR_ERR_FORMATTED_STREAM_T_P_PRIORITY_CMP(A,B) ERR_ERR_FORMATTED_STREAM_T_P_CMP(A,B)
#  endif
#  define ERR_ERR_FORMATTED_STREAM_T_P_PRIORITY_CMP_PROVIDED 0
#endif
#if defined(ERR_ERR_FORMATTED_STREAM_T_P_PRIORITY_CMP)
#elif ERR_ERR_FORMATTED_STREAM_T_P_PRIORITY_CMP_PROVIDED
#  error "Inconsistency: ERR_ERR_FORMATTED_STREAM_T_P_PRIORITY_CMP_PROVIDED is true but ERR_ERR_FORMATTED_STREAM_T_P_PRIORITY_CMP is undefined."
#endif

/* EQUAL */
#if defined(ERR_ERR_FORMATTED_STREAM_T_P_EQUAL)
#elif !ERR_ERR_FORMATTED_STREAM_T_P_CMP_PROVIDED
#  define ERR_ERR_FORMATTED_STREAM_T_P_EQUAL(A,B) (A) == (B)
#elif defined(ERR_ERR_FORMATTED_STREAM_T_P_CMP)
#  define ERR_ERR_FORMATTED_STREAM_T_P_EQUAL(A,B) (ERR_ERR_FORMATTED_STREAM_T_P_CMP(A,B)) == 0
#endif

/* UPDATE_POS */
#if defined(ERR_V_STREAM_UPDATE_POS)
#elif defined(ERR_VECTOR_UPDATE_POS)
#  define ERR_V_STREAM_UPDATE_POS(SELF,ELEMENT,INDEX) ERR_VECTOR_UPDATE_POS(SELF,ELEMENT,INDEX)
#elif defined(ERR_ERWIN_UPDATE_POS)
#  define ERR_V_STREAM_UPDATE_POS(SELF,ELEMENT,INDEX) ERR_ERWIN_UPDATE_POS(SELF,ELEMENT,INDEX)
#elif defined(ALL_ERWIN_UPDATE_POS)
#  define ERR_V_STREAM_UPDATE_POS(SELF,ELEMENT,INDEX) ALL_ERWIN_UPDATE_POS(SELF,ELEMENT,INDEX)
#endif

/* UPDATE_POS2 */
#if defined(ERR_V_STREAM_UPDATE_POS2)
#elif defined(ERR_VECTOR_UPDATE_POS2)
#  define ERR_V_STREAM_UPDATE_POS2(SELF,ELEMENT1,INDEX1,ELEMENT2,INDEX2) ERR_VECTOR_UPDATE_POS2(SELF,ELEMENT1,INDEX1,ELEMENT2,INDEX2)
#elif defined(ERR_ERWIN_UPDATE_POS2)
#  define ERR_V_STREAM_UPDATE_POS2(SELF,ELEMENT1,INDEX1,ELEMENT2,INDEX2) ERR_ERWIN_UPDATE_POS2(SELF,ELEMENT1,INDEX1,ELEMENT2,INDEX2)
#elif defined(ALL_ERWIN_UPDATE_POS2)
#  define ERR_V_STREAM_UPDATE_POS2(SELF,ELEMENT1,INDEX1,ELEMENT2,INDEX2) ALL_ERWIN_UPDATE_POS2(SELF,ELEMENT1,INDEX1,ELEMENT2,INDEX2)
#endif

/* MANUAL_POSITION */
#if defined(ERR_V_STREAM_MANUAL_POSITION)
#  if ERWIN_BOOL_VALUE(ERR_V_STREAM_MANUAL_POSITION)
#    undef ERR_V_STREAM_MANUAL_POSITION
#    define ERR_V_STREAM_MANUAL_POSITION 1
#  else
#    undef ERR_V_STREAM_MANUAL_POSITION
#    define ERR_V_STREAM_MANUAL_POSITION 0
#  endif
#elif defined(ERR_VECTOR_MANUAL_POSITION)
#  if ERWIN_BOOL_VALUE(ERR_VECTOR_MANUAL_POSITION)
#    define ERR_V_STREAM_MANUAL_POSITION 1
#  else
#    define ERR_V_STREAM_MANUAL_POSITION 0
#  endif
#elif defined(ERR_ERWIN_MANUAL_POSITION)
#  if ERWIN_BOOL_VALUE(ERR_ERWIN_MANUAL_POSITION)
#    define ERR_V_STREAM_MANUAL_POSITION 1
#  else
#    define ERR_V_STREAM_MANUAL_POSITION 0
#  endif
#elif !defined(ALL_ERWIN_MANUAL_POSITION)
#  define ERR_V_STREAM_MANUAL_POSITION 0
#elif ERWIN_BOOL_VALUE(ALL_ERWIN_MANUAL_POSITION)
#  define ERR_V_STREAM_MANUAL_POSITION 1
#else
#  define ERR_V_STREAM_MANUAL_POSITION 0
#endif

#endif /* ERR_V_STREAM_IMPLEMENTATION */
#endif /* !defined(ERWIN_ERR_V_STREAM_D_h) */
