#include "init.cpp"
#include "error.cpp"
#include "count.cpp"
#include "location.cpp"
#include "buffer.cpp"
#include "filter.cpp"
#include "callback.cpp"
#include "printf.cpp"
#include "style.cpp"
#include "style-plain.cpp"
#include "style-colon.cpp"
#include "style-quotes.cpp"
#include "style-qt.cpp"

