/* Generated automatically by makesymbol.pl (part of Erwin library) */
#ifdef DEFINE_NUMERIC_SYMBOLS
/* In case your symbols are ints, this is the list of pre-defined symbols. */
#  define err_sym_assertion 0
#  define err_sym_banner 1
#  define err_sym_debug 2
#  define err_sym_error 3
#  define err_sym_fatal 4
#  define err_sym_general 5
#  define err_sym_info 6
#  define err_sym_internal 7
#  define err_sym_note 8
#  define err_sym_progress 9
#  define err_sym_prompt 10
#  define err_sym_unclassified 11
#  define err_sym_untagged 12
#  define err_sym_warning 13
#  define FIRST_DYNAMIC_SYMBOL 14
#endif /* defined(SYMBOL_HEADER) */

DEF_SYMBOL(err_sym_assertion,"assertion")
DEF_SYMBOL(err_sym_banner,"banner")
DEF_SYMBOL(err_sym_debug,"debug")
DEF_SYMBOL(err_sym_error,"error")
DEF_SYMBOL(err_sym_fatal,"fatal")
DEF_SYMBOL(err_sym_general,"general")
DEF_SYMBOL(err_sym_info,"info")
DEF_SYMBOL(err_sym_internal,"internal")
DEF_SYMBOL(err_sym_note,"note")
DEF_SYMBOL(err_sym_progress,"progress")
DEF_SYMBOL(err_sym_prompt,"prompt")
DEF_SYMBOL(err_sym_unclassified,"unclassified")
DEF_SYMBOL(err_sym_untagged,"untagged")
DEF_SYMBOL(err_sym_warning,"warning")

#ifdef IN_LIBERROR_COMPILE
#  ifndef sym_assertion
#    define sym_assertion err_sym_assertion
#  endif
#  ifndef sym_banner
#    define sym_banner err_sym_banner
#  endif
#  ifndef sym_debug
#    define sym_debug err_sym_debug
#  endif
#  ifndef sym_error
#    define sym_error err_sym_error
#  endif
#  ifndef sym_fatal
#    define sym_fatal err_sym_fatal
#  endif
#  ifndef sym_general
#    define sym_general err_sym_general
#  endif
#  ifndef sym_info
#    define sym_info err_sym_info
#  endif
#  ifndef sym_internal
#    define sym_internal err_sym_internal
#  endif
#  ifndef sym_note
#    define sym_note err_sym_note
#  endif
#  ifndef sym_progress
#    define sym_progress err_sym_progress
#  endif
#  ifndef sym_prompt
#    define sym_prompt err_sym_prompt
#  endif
#  ifndef sym_unclassified
#    define sym_unclassified err_sym_unclassified
#  endif
#  ifndef sym_untagged
#    define sym_untagged err_sym_untagged
#  endif
#  ifndef sym_warning
#    define sym_warning err_sym_warning
#  endif
#endif
