/* -*- Mode: C -*- */
/*
 * Author: Henrik Theiling
 * Description:
 *     Implementation of library wide thingies.
 *
 * @@Begin: Licencing and Copying@@
 * 
 * Copyright (c) Henrik Theiling
 * Licence Version 2, Special Version for Erwin.
 * 
 * The term 'this software' used in the following, additional to its
 * usual usage, also includes the instantiated source files generated by
 * tools of this package.
 * 
 * This software is provided 'as-is', without warranty of any kind,
 * express or implied.  In no event will the authors or copyright holders
 * be held liable for any damages arising from the use of this software.
 * 
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 * 
 * 1. The origin of this software must not be misrepresented; you must
 * not claim that you wrote the original software. If you use this
 * software in a product, an acknowledgment in the product documentation
 * would be appreciated.
 * 
 * 2. Altered source versions must be plainly marked as such, and must
 * not be misrepresented as being the original software.
 * 
 * 3. You must not use any of the names of the authors or copyright
 * holders of the original software for advertising or publicity
 * pertaining to distribution without specific, written prior permission.
 * 
 * 4. If you change this software and redistribute parts or all of it in
 * any form, you must make the source code of the altered version of this
 * software available.  As an exception, files that were generated by
 * tools of this package may be used freely, including modification.
 * 
 * 5. This notice must not be removed or altered from any source
 * distribution.
 * 
 * This licence is governed by the Laws of Germany.  Disputes shall be
 * settled by Saarbruecken City Court.
 * 
 * @@End: Licencing and Copying@@
 *
 */

#define ERR_ERWIN_COMPILING 1

#include "error/erwin/base_i.h"
#include "error/erwin/stdinc.h"

#ifdef HAVE_TIME_H
#include "time.h"
#endif

#define initialised err_erwin_initialised

#ifdef __cplusplus
extern "C" {
#endif
/* BEGIN INITIALISATION DECLARATION */
/* END INITIALISATION DECLARATION */
#ifdef __cplusplus
}
#endif

/* ////////////////////////////////////////////////////////////////////// */

#ifdef HAVE_GETPID
#define erwin_getpid (getpid())
#else
#define erwin_getpid 0
#endif

static ERR_ERWIN_BOOL is_prefix (char const *haystack, char const *needle, int *len)
{
    *len= strlen (needle);
    return strncmp (haystack, needle, *len) == 0;
}

static void handle_param (char const *param)
{
    if (strcmp (param, "assertion_failure=abort") == 0)
        err_erwin_assertion_is_fatal= ERR_ERWIN_TRUE;
    else
    if (strcmp (param, "assertion_failure=continue") == 0)
        err_erwin_assertion_is_fatal= ERR_ERWIN_FALSE;
    else {
#ifdef HAVE_LIBERROR
        fleprintf (C_TAG_ERROR, 0, __FILE__, __LINE__,
                 "Unrecognised option: --err_erwin:%s\n",
                 param);
#else
        ERR_ERWIN_ERROR_PRINT (ERR_ERWIN_ERROR_STREAM,
                 "%s:%d: (Erwin:base.c) Error: Unrecognised option: --err_erwin:%s\n",
                 __FILE__,
                 __LINE__,
                 param);
#endif
    }
}

/* Search parameters for --err_erwin: prefix. */
static void parse_params (int *argc, char ***argv)
{
    int i;
    int o;

    o= 1;
    for (i=1; i < *argc; i++) {
         int len;
         if (is_prefix ((*argv)[i], "--err_erwin:", &len))
             handle_param ((*argv)[i] + len);
         else
            (*argv)[o++]= (*argv)[i];
    }
    (*argc)= o;
}

/* Initialisation of erwin and all its modules */
void err_erwin_init (int *argc, char ***argv)
{
    if (argc != NULL && argv != NULL) 
        parse_params (argc, argv);    /* reparse for each invocation, even if we're initialised */

    if (initialised)
        return;
    initialised= ERR_ERWIN_TRUE;

    /* Now the stuff that must not be initialised twice: */
#if defined(HAVE_SRAND) && defined(HAVE_TIME) && !defined(ERR_ERWIN_REQUIRE_DETERMINISM)
    srand ((unsigned)time (NULL) + 7931 * erwin_getpid);
#endif

    err_erwin_init_map ();

/* BEGIN INITIALISATION CALLS */
/* END INITIALISATION CALLS */
}
